### ISSUE TITLE
Custom request?

### ISSUE THREAD

**Issue by Aigai0s** [onevcat/Kingfisher#10]
Will passing custom requests ever be possible? I want to add an option for basic authentication and it isn't very comfortable to manage this.

**Comment by onevcat** [comment]
It is a lack of Kingfisher currently, and there is a plan to add it later.

**Comment by onevcat** [comment]
Added in #23 
Wait for merging.

**Comment by onevcat** [comment]
Merged.

You can now customize the request like this:

```swift
KingfisherManager.sharedManager.downloader.requestModifier = {
        (request: NSMutableURLRequest) in
        // Do what you need to modify the download request.
}
```

**Comment by Aigai0s** [comment]
Thanks for your quick solution. I really appreciate your work and motivation.

**Comment by NBoymanns** [comment]
@onevcat I used you're solution for basic Auth:

`KingfisherManager.sharedManager.downloader.requestModifier = {
        (request: NSMutableURLRequest) in
        // Do what you need to modify the download request.
}`

Can you tell me how to do this with the new Kingfisher 3.0 :)?

**Comment by onevcat** [comment]
@NBoymanns 
Take a look at [this](https://github.com/onevcat/Kingfisher/wiki/Kingfisher-3.0-Migration-Guide#imagedownloader) and [this](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending)
