### ISSUE TITLE
Show changeable image from same URL

### ISSUE THREAD

**Issue by reenaphilip** [onevcat/Kingfisher#1000]
I am using Kingfisher to load imageView with images from URL. Sometimes the image may be changed at the same url. 
Using below code, I am trying to load the imageView
sideVC.profileImage.kf.setImage(with: profileUrl, placeholder: #imageLiteral(resourceName: "profile_1"), options: [.fromMemoryCacheOrRefresh], progressBlock: nil, completionHandler: nil)

But the image is not getting updated. Only the old image is showing. Why this happens ? In Kingfisher documentation, it is stated that, " fromMemoryCacheOrRefresh can be used to display changeable image behind same url, while avoiding download it again and again "

**Comment by MariaKulkova** [comment]
@reenaphilip "If set, Kingfisher will try to retrieve the image from memory cache first. If the image is not in memory cache, then it will ignore the disk cache but download the image again from network"
It seems to me that your image is in memory when the data behind the URL changes. 
If image refreshing is critical I use [.forceRefresh, .keepCurrentImageWhileLoading]. This combination keeps the current image visible and updates the image data ignoring cache.

**Comment by reenaphilip** [comment]
@MariaKulkova Thank you for the solution. I tried with that and its working fine. But when I used it to load images, in tableview, there is problem in reusing the same images in different cells. 
I am loading cells from an object array. Each object will have image url and the imageview has to be loaded from the corresponding imageURL. When I use [.forceRefresh, .keepCurrentImageWhileLoading], tableview reuses the images. Why this happens? Is it because of the wrong handling of tableview ?

**Comment by onevcat** [comment]
@reenaphilip I suggest you could also add this code to your cell's reuse methods:

```swift
// In your customized cell
class MyCell: UICollectionViewCell {
    
    @IBOutlet weak var cellImageView: UIImageView!

    override func prepareForReuse() {
        super.prepareForReuse()
        cellImageView.kf.cancelDownloadTask()
        cellImageView.image = nil
    }
}
```

**Comment by aeberbach** [comment]
Does Kingfisher support detection changed network resource by examining Etag responses or by using conditional GET requests and taking note of the 304 status response?

**Comment by onevcat** [comment]
No, Kingfisher is using its own cache and does not use ETag or modified date (URL cache). If you need to update the resource, the easiest way would be appending a query (like a timestamp, `https://domain.com/image.png?t=123456`) to your URL.
