### ISSUE TITLE
Some resources are missing

### ISSUE THREAD

**Issue by alexanderkhitev** [onevcat/Kingfisher#1008]
Hi @onevcat! I did fork and downloaded the project, ran the tests and they did not start from me because some resources are missing.

Please have a look https://monosnap.com/file/hLLmGc14amS21BMSRFIqr5Lgj2Fb8o

**Comment by onevcat** [comment]
Check https://github.com/onevcat/Kingfisher#developments-and-tests

Just run `setup.sh` to fix it!
