### ISSUE TITLE
collectionview Terminated due to memory issue

### ISSUE THREAD

**Issue by applepeopletsai** [onevcat/Kingfisher#1011]
您好，喵大
有個問題困擾我好幾天了
找了很多資訊都還沒有個頭緒

問題是這樣的
我在一個controller A上放了一個scrollview
scrollview中放了兩個controllerB與C
所以在controller A可以左右滑看controllerB與C
而在controller B與C中各放置了一個collectionview，用來呈現照片
controller B與C 均為call API取得照片網址並使用kf.setimage來設置照片
而我的做法是，當畫面在controller B時，call API讀取應該要呈現在controller B的資料並呈現照片
當往右滑，畫面在controller C時，才call API讀取應該要呈現在controller C的資料並呈現照片
此時會發生崩潰，原因是Terminated due to memory issue

我的猜測是因為download task太多而導致的
我也嘗試過在左右滑切換畫面時先呼叫KingfisherManager.shared.downloader.cancelAll()取消所有尚未下載完的task，在call API取得資料
但結果還是一樣會崩潰

不知道這樣的做法是不是錯了?

還煩請喵大題點一下該如何解決這個問題
感激不盡 😅

**Comment by onevcat** [comment]
Not quite sure the pixel size of your images. However, loading lots of large images may cause this problem sometimes, especially you are still keeping strong references to them when you scroll between controllers.

I suggest you try to unload the images (by setting imageView.image to `nil`), when you do not display them.

Cancelling the download tasks might have nothing to do with it.

**Comment by applepeopletsai** [comment]
Thank you for your suggestion!
I will try it.
