### ISSUE TITLE
Kingfisher Pod Build Setting: change Swift 4 to Swift 4.2

### ISSUE THREAD

**Issue by joebenton** [onevcat/Kingfisher#1014]
I have grabbed the latest commit from the master branch in my pod file (to get the latest commits since the 4.9.0 release) for Swift 4.2. The code has updated to Swift 4.2, however the Kingfisher target in the Pods workspace still has the build setting 'Swift Language Version' set to Swift 4 which means I am still seeing the "Conversion to Swift 4.2 is available" issue and is giving build errors with code that has changed for Swift 4.2 syntax. If I switch that build setting to 4.2 in the dropdown then that fixes all the issues. Not sure if something needs updating in the pod specs or settings for kingfisher pod?

I have done `pod repo update` to make sure I have the latest commits and tried to reintegrate and re-install the pod. Is there something I am doing wrong?

` pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher.git', :branch => 'master'`

![swiftlanguageversion](https://user-images.githubusercontent.com/6377840/45698402-d1be5880-bb5f-11e8-8a94-fecbe7806f05.png)

![swiftconversion](https://user-images.githubusercontent.com/6377840/45698396-ce2ad180-bb5f-11e8-8e51-77c9be8686ce.png)

**Comment by Adrift001** [comment]
.swift-version里面的版本号是不是应该改成4.2?

**Comment by onevcat** [comment]
Master is already in Swift 4.2 (which is not tagged yet), while the version 4.9.0 is still 4.0. I will release it later today.

**Comment by joebenton** [comment]
Yeah I have got the commits after the 4.9 release which has the Swift 4.2 changes, but the build setting is still Swift 4 and needs changing with it. Let me know when you release it with that change :)

**Comment by MrBoog** [comment]
Found this today https://github.com/onevcat/Kingfisher/releases/tag/4.10.0. Feel free to try the new release now,

**Comment by joebenton** [comment]
Yeah thanks spotted 4.10.0 got released :)
