### ISSUE TITLE
version 4.10 showing compilation errors

### ISSUE THREAD

**Issue by Tahia50** [onevcat/Kingfisher#1018]
tried installing  pod 'Kingfisher'. Version 4.10.0 is showing six compilation errors in AnimatedImageView.swift, Image.swift and ImageTransition.swift files

**Comment by onevcat** [comment]
4.10 is using Swift 4.2 so you need Xcode 10 for it. If you are still using Xcode 9, please do not upgrade it now.

**Comment by onevcat** [comment]
It depends on how did you integrate Kingfisher. If you are using CocoaPods, just specify the version 4.9.0 and do a pod install as long as you are using Xcode 9:

```
pod 'AFNetworking', '= 4.9.0'
```

**Comment by wjling** [comment]
I happened to finding that `ContentMode` in Kingfisher conflicts with `ContentMode` in UIView. My code 
```
let processor = ResizingImageProcessor.init(referenceSize: CGSize.init(width: _width, height: _height), mode: ContentMode.aspectFill)
```
occurs an error said `Type 'UIView.ContentMode' has no member 'aspectFill'`.
I'm using XCode 10 but my project Swift version is Swift 4.0. I think this UIView's new feature should only appear in Swift 4.2. Maybe this is a bug of XCode

**Comment by sejolopab** [comment]
what about Carthage? I'm trying to do Carthage update on the version 4.9.0 but it's not compiling correctly ( github "onevcat/Kingfisher" ~> 4.9.0 )

**Comment by onevcat** [comment]
@sejolopab You need to do the similar, as long as you still using Xcode 9, you need `github "onevcat/Kingfisher" == 4.9.0`
