### ISSUE TITLE
Images are swapped in CollectionViewCell

### ISSUE THREAD

**Issue by emmasuzuki** [onevcat/Kingfisher#102]
I started using Kingfisher with Swift in CollecitonViewCell and realized some weird behavior. 
When ~8 or more cells are shown on screen at a time, same images are shown in multiple cells where no cells are configured with same image url.  Also when I scroll, the images are swapped.
Do you see the same behavior ?

Here is my code:
```swift
imageView.kf_setImageWithURL(thumbnailUrl,
    placeholderImage: UIImage(named: "loading_image"),
    optionsInfo: nil,
    completionHandler: { [weak imageView] (image, error, cacheType, imageURL) -> () in
        if error == nil {
            imageView?.image = image
        } else {
            imageView?.image = UIImage(named: "no_image")
        }
})
```

**Comment by onevcat** [comment]
Your code seems good to me except reseting the image once again when downloading successfully. The  `kf_setImageWithURL` will set the image for you when everything goes OK.

May I know some more detail and context on how do you configure your cell? And you could check and the demo project in the repo as well, in which a collection view is used to show some images.

**Comment by emmasuzuki** [comment]
Thanks, you gave me a hint.  The issue was the resetting.  I guess my function did not maintain the imageView's references since it is a reused cell from collection view.  

Here is a revised code:
```swift
imageView.kf_setImageWithURL(thumbnailUrl,
    placeholderImage: UIImage(named: "loading_image"),
    optionsInfo: nil,
    completionHandler: { [weak imageView] (image, error, cacheType, imageURL) -> () in
        if error != nil {
            imageView?.image = UIImage(named: "no_image")
        }
})
```

**Comment by onevcat** [comment]
:)

**Comment by Ankish** [comment]
@onevcat 
imageView.kf_setImageWithURL(thumbnailUrl,
    placeholderImage: UIImage(named: "loading_image"),
    optionsInfo: nil,
    completionHandler: { [weak imageView] (image, error, cacheType, imageURL) -> () in
        if error != nil {
            imageView?.image = UIImage(named: "no_image")
        }
        // for fast scrolling when the cell is reused and you might have 2 request for same cell on queue .should we also check if previous url is same as current one. To avoid showing wrong image on the cell till the correct one invokes and reloads the cell or is this handled. In the demo this is not handled. 
Note I am using prepareForReuse() to set imageview.image = nil // does this take of it.
Just curious before I put KF code in all over my project.
   something like
    if thumbnailUrl != imageURL{ // a completion for previous cell
                 imageView?.image = nil
       }
})

**Comment by onevcat** [comment]
There should be no concern for it. Kingfisher will remember the last set image url and ignore previous image loading, even if it is not yet finished.

**Comment by HariNarayanan777** [comment]
Here what  is the name of the image "no_image" means which is downloaded from the server image or your placeholder image.
?????

**Comment by HariNarayanan777** [comment]
And also i am getting error "Value of type 'UIImage?' has no member 'kf_setImageWithURL'"  what the extension for the method.?
Please help me.

**Comment by emmasuzuki** [comment]
@HariNarayanan777 `UIImage(named: "no_image")` is local image. When an error occurs fetching the image from the url, I will replace the placeholder image ("loading_image") to "no_image" image.

And `kf_setImageWithURL` is an old API and also Kingfisher's API is on `UIImageView`. Not on `UIImage`.  

I think you can try 
```swift
imageView.kf.setImage(
    with: imageUrl,
    placeholder: UIImage(named:"some_placeholder_image"),
    options: nil,
    progressBlock: nil,
    completionHandler: { (image: Image?, error: NSError?, cache: CacheType, url: URL?) in
    })
```
