### ISSUE TITLE
Gif does not start animating when prefetched.

### ISSUE THREAD

**Issue by proxpero** [onevcat/Kingfisher#1022]
### Issue Description

A gif does not automatically animate when I first load it using the prefetcher.

#### What

I cannot get a gif to start animating when loading it using `ImagePrefetcher` and using a `UIImageView`
The animation *does* start as expected when *not* using the prefetcher.

This is true for me on a device and on the simulator. I'm on iOS 12. I tried older versions of KF going back to 4.8.0 as well as 4.10.0.

#### Reproduce

Set `shouldPrefetch` to `true`.

	import UIKit
	import Kingfisher

	class ViewController: UIViewController {

		@IBOutlet weak var imageView: UIImageView!
		let url = URL(string: "https://media.giphy.com/media/omHPYZttAVAAw/giphy.gif")!

		override func viewDidLoad() {
			super.viewDidLoad()

			let shouldPrefetch = true

			if shouldPrefetch {
				ImageCache.default.clearMemoryCache()
				ImageCache.default.clearDiskCache {
					self.prefetchUrl()
				}
			} else {
				imageView.kf.setImage(with: url)
			}
		}

		func prefetchUrl() {
			let prefetcher = ImagePrefetcher(resources: [url]) { (_, _, _) in
				self.imageView.kf.setImage(with: self.url)
			}
			prefetcher.start()
		}
	}

#### Other Comment

🙏🏼

**Comment by xspyhack** [comment]
If you use `ImagePrefetcher` to preload gif and use `UIImageView` to display, you need to set `options.preloadAllAnimationData = true`.
In other words, `let prefetcher = ImagePrefetcher(resources: [url], options: [.preloadAllAnimationData])`

**Comment by proxpero** [comment]
Thanks. I’m using `AnimatedImageView`s instead and everything is working well. 🎉
