### ISSUE TITLE
This gif will crash in Kingfisher in a UIImageView

### ISSUE THREAD

**Issue by proxpero** [onevcat/Kingfisher#1023]
### Issue Description

👋🏼

`https://media1.giphy.com/media/UxjCqclGSRtMQ/giphy.gif`
This gif will crash Kingfisher using a `UIImageView` in iOS 12, but an `AnimatedImageView` is ok.

#### Reproduce

	import UIKit
	import Kingfisher

	class ViewController: UIViewController {

		@IBOutlet weak var imageView: UIImageView!
		let url = URL(string: "https://media1.giphy.com/media/UxjCqclGSRtMQ/giphy.gif")!

		override func viewDidLoad() {
			super.viewDidLoad()
			imageView.kf.setImage(with: url)
		}
	}

**Comment by onevcat** [comment]
It's crashing due to memory. This gif is too large (1600 × 900) and system `UIImageView` requires all frames to be decoded before it can create a serial of images.

So please use `AnimatedImageView` to only decode several frames to display this image, which is just for this case.

**Comment by mountainKingG** [comment]
@onevcat JXPhotoBrowser use your kingfisher for JXKingfisherLoader, if gif image larger than 10 mb, memory will go to big soon and app will crash. 
 Now I change the image loader tool to YYKit, app do not crash. So just suggest whether have optimize place. Best wishes.
