### ISSUE TITLE
Feature Request: Load low-resolution image from URL as placeholder, then load high-resolution

### ISSUE THREAD

**Issue by frankrausch** [onevcat/Kingfisher#1028]
Hi,

I make a reader app for Wikipedia and I often want to **load and display a low-resolution version** of an image **before loading and displaying the high-resolution variant.**

Adding the possibility to add a second `URL` as the placeholder parameter when configuring a UIImageView seems like an elegant way to do this.

```swift
// Small 220 × 147px  version:
let lowResolutionImageURL = URL(string: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Alcedo_azurea_-_Julatten.jpg/220px-Alcedo_azurea_-_Julatten.jpg")

// Large 1800 × 1200px version
let highResolutionImageURL = URL(string: "https://upload.wikimedia.org/wikipedia/commons/7/72/Alcedo_azurea_-_Julatten.jpg")

imageView.kf.setImage(with: highResolutionImageURL, placeholder: lowResolutionImageURL, options: [], progressBlock: nil, completionHandler: nil)
```

What do you think?

**Comment by onevcat** [comment]
`Placeholder` is a protocol and you could make any view as a placeholder. So you could just extend an image view as `Placeholder` and load image there.

**Comment by frankrausch** [comment]
Ah, I didn’t think of that. Thank you very much for the quick reply! I will give it a try and come back to this thread if I see any issues with the approach you suggested.
