### ISSUE TITLE
WatchKit disable

### ISSUE THREAD

**Issue by sondangpangaribuan** [onevcat/Kingfisher#103]
How to use Kingfisher without WatchKit because i got problem when do compiling ( error: opening import file for module 'WatchKit': Permission denied )

**Comment by onevcat** [comment]
May I know how did you install Kingfisher into your project?

You should have permission to load WatchKit from your Mac if things goes correctly.

However, you could just remove the `WKInterfaceImage+Kingfisher.swift` file and the WatchKit framework from "Link Binary With Libraries" of Build Phase to opt out the WatchKit support.

**Comment by sondangpangaribuan** [comment]
I install using Carthage, 
can you explain how to load permission for WatchKit ?

Anyway Thank for Kingfisher

**Comment by onevcat** [comment]
@sondangpangaribuan  I am not quite sure about your issue. However, maybe it is something related to your project settings, such as Framework search path pointing to a strange place or there is something wrong with the file/folder permission. 

There are some similar issues [here](http://stackoverflow.com/questions/30196440/opening-import-file-for-module-swift-permission-denied) and [here](http://stackoverflow.com/questions/26258264/opening-import-file-for-module-swift-permission-denied) for you to refer.

**Comment by onevcat** [comment]
And if your project has a plan to update to Swift 2.0 soon, I guess you could just ignore this. Since Kingfisher for Swift 2.0 version removed WatchKit support temporarily. And it will be released soon with iOS 9.

**Comment by onevcat** [comment]
Kingfisher 1.5.0 for Swift 2 released.
