### ISSUE TITLE
双向验证的https请求

### ISSUE THREAD

**Issue by ethancheung1990** [onevcat/Kingfisher#1034]
是否支持双向验证的https请求？
若支持，请问怎么实现?
若不支持，可否将func downloader(_ downloader: ImageDownloader, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void)方法的实现开放出来

**Comment by onevcat** [comment]
This is already open. See https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#authentication-with-nsurlcredential

**Comment by ethancheung1990** [comment]
> This is already open. See https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#authentication-with-nsurlcredential

thanks!
