### ISSUE TITLE
关于ImageDownloader中的barrierQueue

### ISSUE THREAD

**Issue by FengWuFei** [onevcat/Kingfisher#1039]
采用concurrent的barrierQueue是为了提高fetchLoads的访问效率，使用.barrier去限制更改操作防止竞争，但是读取的操作fetchLoad(for url: URL)为什么也要使用.barrier，如果全都使用.barrier操作的话，与serial队列不久没区别了吗？

**Comment by onevcat** [comment]
Bad code. These will be refactored in version 5.0.
