### ISSUE TITLE
Why did I change "Allow for Loads" not work, does it only support HTTPS?

### ISSUE THREAD

**Issue by Benzoudeliuxing** [onevcat/Kingfisher#1049]
I use  the simple  imageView.kf.setImage(with: url)    But HTTP not work and I set "Allow for Loads" to YES.   does it only support HTTPS?

**Comment by onevcat** [comment]
No, it supports both HTTP and HTTPS, as long as you set up everything correctly.

The option reads as "Allow Arbitrary Loads", please check your Info.plist setting.

BTW, maybe you can get some information by checking the console log or printing out the error in the completion block.
