### ISSUE TITLE
Kingfisher是否存在内存泄露问题

### ISSUE THREAD

**Issue by zhangshuqing** [onevcat/Kingfisher#1059]
我在项目中引用了Kingfisher用来替代SDWebImage。但是今天今天发现一个问题，当我退出一个页面的时候清除内存缓存，发现内存并没有回复到最初的内存大小。反复进入页面发现有一定的内存残留，没有被完全清除。确定我的这个页面没有循环引用问题。
然后我运行了一次Kingfisher的官方demo， 发现反复清除缓存并重新加载，也会造成内存的一直增长，所以怀疑Kingfisher存在内存泄露问题

**Comment by ZSMHup** [comment]
我也是的，我在tableview上加载图片时内存一直往上飙，用SDWebImage就没有这个问题

**Comment by MarcSteven** [comment]
@zhangshuqing  I think you should use instruments to check the memory leaks  and then report the issue ,no pic ,just words ......

**Comment by onelcat** [comment]
看看Demo这些问题都可以解决
