### ISSUE TITLE
更新到2.0有好多错误

### ISSUE THREAD

**Issue by zhouzizi** [onevcat/Kingfisher#106]
今天下载了Xcode7_GM,然后在pod文件中改成 
pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher.git', :branch => 'swift-2.0'
但是更新了好多错误？

**Comment by onevcat** [comment]
请检查一下你的 command line 版本。另外现在 master 也是 Swift 2.0 版本了。

**Comment by zhouzizi** [comment]
command line 版本？请问如何更新？

**Comment by onevcat** [comment]
请确认下在 Xcode 里设置的 Locations 里 Command Line Tools 版本是 7.0

**Comment by zhouzizi** [comment]
可以了。谢谢您 ！顺便请问一下，别的第三方库也更新到了2.0还是有好多issues，不知道还需要改什么地方，能麻烦您指教一下吗？

**Comment by zhouzizi** [comment]
import Kingfisher 发现  Could not build Objective-C module 'Kingfisher'

**Comment by onevcat** [comment]
已经不属于本 repo 的内容，请自行查阅资料和解决。

I am closing this.
