### ISSUE TITLE
Is the 'cache' turned on or not if i'm using it like this?

### ISSUE THREAD

**Issue by alexliubj** [onevcat/Kingfisher#107]
Just a quick question,

Is the 'cache' turned on or not if i'm using it like this?

`imageView.kf_setImageWithURL(NSURL(string: "http://your_image_url.png")!, placeholderImage: nil)`

**Comment by onevcat** [comment]
It will be cached in Kingfisher's cache.

**Comment by alexliubj** [comment]
So by default 'cache' works???

**Comment by onevcat** [comment]
Sure. It is a feature of Kingfisher.
