### ISSUE TITLE
setting indicatorType inside an extension is no longer possible

### ISSUE THREAD

**Issue by murad1981** [onevcat/Kingfisher#1071]
The latest version of Kingfisher (5.0.0) won't let me set the indicatorType property from inside an extension (previously with versions 4.10.1 and below this was possible):

```
extension UIImageView {
    func test() {
        self.kf.indicatorType = .activity 
//the above line gives the error: Cannot assign to property: 'self' is immutable
    }
}
```

there was a [closed issue](https://github.com/onevcat/Kingfisher/issues/469) about this and it has been marked as resolved, but now the issue rose up again.

**Comment by onevcat** [comment]
Duplicated to #1064
