### ISSUE TITLE
struct vs class

### ISSUE THREAD

**Issue by iFallen** [onevcat/Kingfisher#1080]
### Issue Description

```
public struc KingfisherWrapper<Base> {
    public let base: Base
    public init(_ base: Base) {
        self.base = base
    }
}
```

>
你好~想问一下，这个地方 struct 可否替换为class,对整个架构会不会有啥影响。谢谢！

**Comment by onevcat** [comment]
This is a performance consideration. `struct` would be much faster than `class`.

Kingfisher does not consider the usage in Objective-C. If you want to use it in Objective-C, I suggest you could write your own wrapper. Can you give me some example of your use case and information? So maybe I can give some more suggestion.

**Comment by iFallen** [comment]
extension Test where Base: Timer {
    static func scheduledTimer (timeInterval: TimeInterval,
                                   repeats: Bool,
                                   completion:@escaping ((_ timer:Timer)->())) -> Timer{
        return Timer.scheduledTimer(timeInterval: timeInterval,
                                    target: self,
                                    selector: #selector(Timer.zx.completionLoop(timer:)),//
                                    userInfo: completion, repeats: repeats)
    }
    
    @objc static func completionLoop(timer:Timer) {//Members of constrained extensions cannot be declared @objc
        guard let completion = timer.userInfo as? ((Timer) -> ()) else {
            return
        }
        completion(timer)
    }
}

extension Timer {
    class func zx_scheduledTimer (timeInterval: TimeInterval,
                                   repeats: Bool,
                                   completion:@escaping ((_ timer:Timer)->())) -> Timer{
        return Timer.scheduledTimer(timeInterval: timeInterval,
                                    target: self,
                                    selector: #selector(zx_completionLoop(timer:)),
                                    userInfo: completion, repeats: repeats)
    }
    
    @objc class func zx_completionLoop(timer:Timer) {
        guard let completion = timer.userInfo as? ((Timer) -> ()) else {
            return
        }
        completion(timer)
    }
}

**Comment by iFallen** [comment]
谢谢，那问一下。
举个例子，
我是这么子写好：
```
extension Test where Base: Timer {
    static func scheduledTimer (timeInterval: TimeInterval,
                                   repeats: Bool,
                                   completion:@escaping ((_ timer:Timer)->())) -> Timer{
        return Timer.scheduledTimer(timeInterval: timeInterval,
                                    target: self,
                                    selector: #selector(Timer.zx.completionLoop(timer:)),//这个地方没法处理
                                    userInfo: completion, repeats: repeats)
    }
    
    @objc static func completionLoop(timer:Timer) {//Members of constrained extensions cannot be declared @objc
        guard let completion = timer.userInfo as? ((Timer) -> ()) else {
            return
        }
        completion(timer)
    }
}
```

还是直接这么子些好：
```
extension Timer {
    class func zx_scheduledTimer (timeInterval: TimeInterval,
                                   repeats: Bool,
                                   completion:@escaping ((_ timer:Timer)->())) -> Timer{
        return Timer.scheduledTimer(timeInterval: timeInterval,
                                    target: self,
                                    selector: #selector(zx_completionLoop(timer:)),
                                    userInfo: completion, repeats: repeats)
    }
    
    @objc class func zx_completionLoop(timer:Timer) {
        guard let completion = timer.userInfo as? ((Timer) -> ()) else {
            return
        }
        completion(timer)
    }
}
```

**Comment by onevcat** [comment]
If you are developing an app, you could just choose the latter. 

The main reason Kingfisher chose a `kf` compatible wrapper, is that as a library (instead of the final app), there might be name conflicting when extending a class from Foundation or UIKit.

In your particular example, you can define the `completionLoop` in an internal `Timer` extension, instead of defining it to `Test`. Then you should be able to use `@objc` and target-action pattern. I didn't try myself, but something like this:

```swift
extension Test where Base: Timer {
    static func scheduledTimer (timeInterval: TimeInterval,
                                   repeats: Bool,
                                   completion:@escaping ((_ timer:Timer)->())) -> Timer{
        return Timer.scheduledTimer(timeInterval: timeInterval,
                                    target: base, // Use `base` instead of `self`
                                    selector: #selector(completionLoop(timer:)),
                                    userInfo: completion, repeats: repeats)
    }
}

extension Timer {    
    @objc static func completionLoop(timer:Timer) {
        guard let completion = timer.userInfo as? ((Timer) -> ()) else {
            return
        }
        completion(timer)
    }
}
```
