### ISSUE TITLE
第一次安装  backgroundDecode 模式导致内存爆炸

### ISSUE THREAD

**Issue by xiaohuochai** [onevcat/Kingfisher#1082]
第一次运行 app  加载图片会导致内存爆炸 直到 app 被杀
iphone6  系统版本12.0

imageView.kf.setImage(with: ImageResource(downloadURL: downloadURL),
                                             placeholder: nil,
                                             options: [.backgroundDecode])

**Comment by onevcat** [comment]
Not sure what the Kingfisher version you are using. I suggest you use the latest version 5 if possible. In the new version, we improved a lot on performance on both memory usage and loading speed.

For some more advanced performance tips, please read [our wiki](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#performance-tips) to know some best practice when using Kingfisher.
