### ISSUE TITLE
喵大，请问未来可以支持异步获取网络视频首祯图片的逻辑么？

### ISSUE THREAD

**Issue by DreamParagon** [onevcat/Kingfisher#1088]
类似如下逻辑
<img width="1190" alt="2019-01-09 11 16 18" src="https://user-images.githubusercontent.com/5466178/50874919-ed948580-1400-11e9-97eb-ab12b129f568.png">

**Comment by onevcat** [comment]
This needs to import AVFoundation and be only used in a very limited case. In Kingfisher 5, it can be implemented with a customize `ImageDataProvider` very easily. Check this [wiki page](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#imagedataprovider) to know how to add your own data provider. Basically, you just need to add the logic above and call the `data(handler:)` with the image data.
