### ISSUE TITLE
Why does indicatortype need var?

### ISSUE THREAD

**Issue by ntvhouston** [onevcat/Kingfisher#1090]
Greetings.
I have been trying to use some libraries which I use to use earlier and what I found is that before I use to add the indicator type and it use to simply work but now if I do the way as it is addressed in kingfisher docs, it doesn't work. For example:-

```
let imageView = UIImageView()
imageView.indicatorType = .activity // This doesn't work as it says the imageView should be a var not a let but it use to work before
```

**Now the problem** is not all the repos are updated so therefore as Kingfisher is updated therefore this method isn't working in many libraries which have a imageView as a predefined constant in their code.

_**Is there any work around or a proper way to handle this case.**_

Thanks really appreciate your time and help.
**And thanks for such a great repo.**

**Comment by onevcat** [comment]
There is no `indicatorType` on image view, it is on the `kf` extension of image view. So this would not work now:

```swift
let imageView = UIImageView()
imageView.kf.indicatorType = .activity
```

You can just either make the image view mutable or the `kf` mutable:

```swift
var i = imageView
i.kf.indicatorType = .activity

var kf = imageView.kf
kf.indicatorType = .activity
```

**Comment by ntvhouston** [comment]
Wonderful. Thanks a lot. It was a typo for imageView.kf.indicatorType but thanks a lot. It worked simply awesome. Thanks again.
