### ISSUE TITLE
Can't load local image by path in 5.x version 

### ISSUE THREAD

**Issue by iFallen** [onevcat/Kingfisher#1092]
### Issue Description

Can't load local image by path in 5.x version 

#### What

``` ruby
imageView.kf.setImage(with: URL(fileURLWithPath: path))
```
- 5.x version: can't load ❌
- 4.x version: load success ✅

**Comment by onevcat** [comment]
I even didn't know this could work in version 4.x. The `setImage` with a URL was designed for networking, which uses a `URLSession` to make an HTTP request. This behavior is not changed in version 5, so I am not sure about the situation.

However, in version 5, you can use the `ImageDataProvider` for loading an image from disk. See this wiki for more: https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#image-from-local-file
