### ISSUE TITLE
Module file's minimum deployment target is ios10.0 v10.0 in Swift 4.2

### ISSUE THREAD

**Issue by HebaAtallah** [onevcat/Kingfisher#1093]
I've updated to Swift 4.2 but there's a Swift Compiler Error 

`Module file's minimum deployment target is ios10.0 v10.0: /Users/heba/Library/Developer/Xcode/DerivedData/------gnbsunckknydeadcdgwcmagycrxy/Build/Products/StagingDebug-iphonesimulator/Kingfisher/Kingfisher.framework/Modules/Kingfisher.swiftmodule/x86_64.swiftmodule`

![screen-shot-2019-01-16-at-3 02 36-pm](https://user-images.githubusercontent.com/6685615/51251550-42587300-19a2-11e9-8d38-fd0053deafe3.png)

Knowing that the Kingfisher is `5.1.0` 

![screen-shot-2019-01-16-at-3 04 21-pm](https://user-images.githubusercontent.com/6685615/51251746-a713cd80-19a2-11e9-9005-9dccb6bef899.png)

**Comment by onevcat** [comment]
I don't know how can it be related to Swift version.

Kingfisher 5 supports from iOS 10 as the deploy target, so please make sure that your app also uses iOS 10 or later as the iOS Deployment Target. If you are integrating Kingfisher through CocoaPods, it also worth to check the "platform :ios" setting in your Podfile.

**Comment by HebaAtallah** [comment]
the platform :ios in Podfile is 10.0 indeed.

**Comment by aleene** [comment]
With Xcode 10.1 and build setting to Swift 4, I get this error as well. Revert to KingFisher 4.0?

**Comment by onevcat** [comment]
@aleene 

Kingfisher 5 should support both Swift 4 and 4.2. How did you integrate Kingfisher to your project (CocoaPods or Carthage? And its version?)

Is there any chance to give me a reproducible sample on this error? 
Or does it also happen in a new project?

**Comment by HebaAtallah** [comment]
I figured it out, the iOS deployment target in `Project` and `Target` was below 10.

**Comment by teolemon** [comment]
@HebaAtallah could you reopen this issue to make it visible again ?

**Comment by onevcat** [comment]
@aleene @teolemon Kingfisher 5 now requires iOS 10 or later. So please try to confirm that your deploy target is above iOS 10. If you still need to support iOS 9 for a while, you can choose to use Kingfisher 4.x instead.

**Comment by onevcat** [comment]
Now there is an "ios9" branch fo iOS 9 supporting temporarily before we migrate to image renderer. Please consider to use that branch when you need to use Kingfisher 5 on iOS 9.

**Comment by FritzHsiao** [comment]
i'm having this issue too. iOS Deployment Target in Project and Target are both iOS 11, still getting this error. How to fix this?

**Comment by AmrKafina** [comment]
Changing the minimum deployment target of the Pods project fixed the issue for me.

**Comment by nalna** [comment]
> 我已经更新到Swift 4.2，但是有一个Swift编译器错误
> 
> `Module file's minimum deployment target is ios10.0 v10.0: /Users/heba/Library/Developer/Xcode/DerivedData/------gnbsunckknydeadcdgwcmagycrxy/Build/Products/StagingDebug-iphonesimulator/Kingfisher/Kingfisher.framework/Modules/Kingfisher.swiftmodule/x86_64.swiftmodule`
> 
> ![屏幕截图-2019-01-16-at-3 02 36-pm](https://user-images.githubusercontent.com/6685615/51251550-42587300-19a2-11e9-8d38-fd0053deafe3.png)
> 
> 知道翠鸟是 `5.1.0`
> 
> ![screen-shot-2019-01-16-at-3 04 21-pm](https://user-images.githubusercontent.com/6685615/51251746-a713cd80-19a2-11e9-9005-9dccb6bef899.png)

Hello, may I ask if you have solved this problem? I have encountered the same mistake as you. My swift is also 4.2 version, not upgraded to 5.0 version

**Comment by Dalein** [comment]
Maybe you have more than 1 target in project, and in one of them min iOS version is below than 10.0?
