### ISSUE TITLE
AnimatedImageView 加载gif 图片模糊

### ISSUE THREAD

**Issue by dlxxl06** [onevcat/Kingfisher#1095]
AnimatedImageView 加载gif 图片模糊 
[https://github.com/onevcat/Kingfisher/blob/master/Sources/Views/AnimatedImageView.swift](https://github.com/onevcat/Kingfisher/blob/master/Sources/Views/AnimatedImageView.swift)
在496行
`if needsPrescaling, size != .zero {
                scaledImage = image.kf.resize(to: size, for: contentMode)
            } else {
                scaledImage = image
            }`
 问题原因是 控件大小是40x40 默认开启了needsPrescaling。导致图片被压缩成了40x40 但是手机是retain屏，图片很模糊。
其实图片压缩是很有必要的，但这里压缩的太狠了。导致显示不清楚。目前使用时已经关闭了这个属性。希望作者能优化掉这个问题。

**Comment by onevcat** [comment]
Kingfisher is using pixel instead of point by default, since the images from Internet does not contain any information of scale. You can use [scaleFactor](https://github.com/onevcat/Kingfisher/blob/master/Sources/General/KingfisherOptionsInfo.swift#L118) in the option to specified a scale you need.

**Comment by onevcat** [comment]
Oh, it seems that this option is not applied for the animated image view. I guess it worths to consider screen factor here.

**Comment by dlxxl06** [comment]
是的。最开始我也是加了 `scaleFactor `option 但是没有生效，查看源码才发现的。这个很好修复的

**Comment by onevcat** [comment]
There is no response for a while. It seems to be working well for now,  so I decided to merge it.
