### ISSUE TITLE
Img not downloaded

### ISSUE THREAD

**Issue by stefanosisto** [onevcat/Kingfisher#1099]
Hello!
I'm using kf to download imgs in a tableView, but the image is not downloaded if the url ends with anything different to the extension
Ex: 
www.pippo.it/photo.jpg ---> is shown
www.pippo.it/photo.jpg?version=1 ---> is not shown.

Any help?

**Comment by IvanovDeveloper** [comment]
the same

**Comment by IvanovDeveloper** [comment]
> > the same
> 
> I think u didn't solved it, right?

I've solved it. For get ability download the image by url, I need add "Authorization" header.

It is my code:

```
let modifier = AnyModifier { request in
    var r = request
    r.setValue("TOKEN", forHTTPHeaderField: "Authorization")
    return r
}
KingfisherManager.shared.defaultOptions.append(contentsOf: [KingfisherOptionsInfoItem.requestModifier(modifier)])
```

Kingfisher documentation [https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#downloader](url)

**Comment by stefanosisto** [comment]
Thanks man! Let me try :)
