### ISSUE TITLE
pod 1.6 is not available now?

### ISSUE THREAD

**Issue by alexliubj** [onevcat/Kingfisher#111]
-> Kingfisher (1.5.0)
   A lightweight and pure Swift implemented library for downloading and cacheing
   image from the web.
   pod 'Kingfisher', '~> 1.5.0'
   - Homepage: https://github.com/onevcat/Kingfisher
   - Source:   https://github.com/onevcat/Kingfisher.git

**Comment by alexliubj** [comment]
[!] Unable to satisfy the following requirements:

- `Kingfisher (~> 1.6)` required by `Podfile`

**Comment by onevcat** [comment]
Some error on `pod trunk push` now. Please use `~> 1.5` instead. It should be updated soon.

**Comment by alexliubj** [comment]
Is 1.5 supporting swift 2.0? Coz I found you deleted that branch.

**Comment by onevcat** [comment]
Yes, it is.

**Comment by alexliubj** [comment]
Thank, Awesome!

**Comment by onevcat** [comment]
I guess we could leave it open until CocoaPods trunk restored.

**Comment by alexliubj** [comment]
lol

**Comment by onevcat** [comment]
Should be fixed now.
