### ISSUE TITLE
Xcode´s autocomplete does not work when I include Kingfisher.

### ISSUE THREAD

**Issue by agustr** [onevcat/Kingfisher#112]
Hi,
I installed/added Kingfisher to my project by using 'pod install'. 
Then in one of my view controllers I imported Kingfisher.
At first it worked fine but after a short while autocomplete stopped working. And it just stopped working in the files where Kingfisher is imported. I doubt that there is a direct problem with Kingfisher itself but suspect some combination of cocoapods install and Kingfisher so I just wonder if anyone has any idea what might be causing the autocomplete mechanism to stop working.

**Comment by agustr** [comment]
Hi,

I am sorry to have bothered you but I fixed the problem it seems. I have tried many thing in different order and now I am unable to reproduce the problem so I dont really know what fixed it but the last few things I tried was to do the following:
1. Remove the 'include Kingfisher' in my swift file.
2. Comment out all calls to Kingfisher functions.
3. Close xcode.
4. Delete everything in the following folder: /Users/<username>/Library/Developer/Xcode/DerivedData
5. Start xcode and open my project.
6. Run the 'Clean' command. At this point the autocompletion started working again.
7. Re-include Kingfisher and un-comment out all the references to Kingfisher functions.
everything workes as expected.

**Comment by agustr** [comment]
Okay after a few compiles the autocomplete stopped working again.

**Comment by onevcat** [comment]
:(  Maybe you encountered some annoying SourceKit bugs of Apple. Did you try to update to the latest Xcode? And another thing you could try is removing third party plugins, sometimes they also may cause these kind of problems.

Since it works well for me for my three own projects, I cannot tell why yet. I guess there is little I could do to help it, expect for waiting Apple to improve the IDE.

**Comment by spidergears** [comment]
I have been using this for some time now, never had a problem.

**Comment by onevcat** [comment]
Since there is no further clue on it, I am closing it for now. If anyone facing the same problem, please give a report by reopening it.

**Comment by jasperblues** [comment]
Strange, I have the same issue in AppCode. (Seems to work in Xcode).
