### ISSUE TITLE
KingFisher can't download image from google book api

### ISSUE THREAD

**Issue by gharary** [onevcat/Kingfisher#1120]
#### What

kf is not working with some links ended without image extension.

for example when I try to download an image from google book API, it do nothing.

here is an example of a link which kf couldn't load.
http://books.google.com/books/content?id=zzbtf3OJZJ8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api

**Comment by onevcat** [comment]
Can you try to print and check what error is it in the setting completion handler?

You link is a non-HTTPS one and I guess you need to change you ATS (app transport security) settings to load it.

**Comment by gharary** [comment]
Problem Solved with ATS.
Thanks a lot.
