### ISSUE TITLE
Possible Deadlock on SessionDelegate?

### ISSUE THREAD

**Issue by zwang** [onevcat/Kingfisher#1121]
### Check List

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [x] I want to report a problem instead of asking a question. 

### Issue Description
The app stuck after fetching multiple images, debugging find there are two threads stopping at the same place fighting for a lock

#### What
Stack trace for main thread: 

```
com.apple.main-thread
0  libsystem_kernel.dylib         0x19bd7af54 __psynch_mutexwait + 8
1  libsystem_pthread.dylib        0x19bdfe0b4 _pthread_mutex_firstfit_lock_wait + 92
2  libsystem_pthread.dylib        0x19bdfe024 _pthread_mutex_firstfit_lock_slow$VARIANT$armv81 + 256
3  Kingfisher                     0x1069c10fc closure #1 in SessionDelegate.add(_:url:callback:) (SessionDelegate.swift:96)
4  Kingfisher                     0x1069a7694 partial apply for thunk for @escaping @callee_guaranteed (@guaranteed SessionDelegate, @unowned Int, @in_guaranteed SessionDataTask.TaskCallback) -> () (<compiler-generated>)
5  Kingfisher                     0x1069a7710 partial apply for specialized  (<compiler-generated>)
6  Kingfisher                     0x1069cb3d0 SessionDataTask.cancel(token:) (<compiler-generated>)
7  Kingfisher                     0x1069b9064 KingfisherWrapper<A>.cancelDownloadTask() (<compiler-generated>)
8  Plato                          0x10500bc10 GamePlayersCollectionViewCell.prepareForReuse() (<compiler-generated>)
9  Plato                          0x10500bc60 @objc GamePlayersCollectionViewCell.prepareForReuse() (<compiler-generated>)
10 UIKitCore                      0x1c8c9f83c -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:] + 588
11 UIKitCore                      0x1c8ca01b0 -[UICollectionView dequeueReusableCellWithReuseIdentifier:forIndexPath:] + 180
12 Plato                          0x10500af68 GamePlayersCollectionView.collectionView(_:cellForItemAt:) (GamePlayersCollectionView.swift:86)
13 Plato                          0x10500b3c0 @objc GamePlayersCollectionView.collectionView(_:cellForItemAt:) (<compiler-generated>)
14 UIKitCore                      0x1c8c8c39c -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 356
15 UIKitCore                      0x1c8c906dc -[UICollectionView _updateVisibleCellsNow:] + 4036
16 UIKitCore                      0x1c8c9577c -[UICollectionView layoutSubviews] + 324
17 UIKitCore                      0x1c986977c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1380
18 QuartzCore                     0x1a07e1b7c -[CALayer layoutSublayers] + 184
19 QuartzCore                     0x1a07e6b34 CA::Layer::layout_if_needed(CA::Transaction*) + 324
20 UIKitCore                      0x1c9854c68 -[UIView(Hierarchy) layoutBelowIfNeeded] + 548
21 Plato                          0x104fcb188 RoomActiveGameTableViewCell.updateViews() (<compiler-generated>)
22 Plato                          0x105056c78 RoomActiveGamesViewController.tableView(_:cellForRowAt:) (RoomActiveGameTableViewCell.swift:54)
23 Plato                          0x10505730c @objc RoomActiveGamesViewController.tableView(_:cellForRowAt:) (<compiler-generated>)
24 UIKitCore                      0x1c95ead84 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 684
25 UIKitCore                      0x1c95eb2cc -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 80
26 UIKitCore                      0x1c95b69a4 -[UITableView _updateVisibleCellsNow:isRecursive:] + 2256
27 UIKitCore                      0x1c95d4890 -[UITableView layoutSubviews] + 140
28 UIKitCore                      0x1c986977c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1380
29 QuartzCore                     0x1a07e1b7c -[CALayer layoutSublayers] + 184
30 QuartzCore                     0x1a07e6b34 CA::Layer::layout_if_needed(CA::Transaction*) + 324
31 QuartzCore                     0x1a0745598 CA::Context::commit_transaction(CA::Transaction*) + 340
32 QuartzCore                     0x1a0773ec8 CA::Transaction::commit() + 608
33 QuartzCore                     0x1a0774d30 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
34 CoreFoundation                 0x19c1756bc __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
35 CoreFoundation                 0x19c170350 __CFRunLoopDoObservers + 412
36 CoreFoundation                 0x19c1708f0 __CFRunLoopRun + 1264
37 CoreFoundation                 0x19c1700e0 CFRunLoopRunSpecific + 436
38 GraphicsServices               0x19e3e9584 GSEventRunModal + 100
39 UIKitCore                      0x1c93c0c00 UIApplicationMain + 212
40 Plato                          0x104e3f300 main (AppDelegate.swift:26)
41 libdyld.dylib                  0x19bc2ebb4 start + 4
```

Stack trace for crashing thread:
```
Crashed: NSOperationQueue 0x2833f5e40 (QOS: UNSPECIFIED)
0  Kingfisher                     0x1069c3d14 specialized Array.init<A>(_:) (SessionDelegate.swift)
1  Kingfisher                     0x1069c1ecc SessionDelegate.onCompleted(task:result:) (<compiler-generated>)
2  Kingfisher                     0x1069c4970 specialized SessionDelegate.urlSession(_:task:didCompleteWithError:) (SessionDelegate.swift:207)
3  Kingfisher                     0x1069c22d4 @objc SessionDelegate.urlSession(_:task:didCompleteWithError:) (<compiler-generated>)
4  CFNetwork                      0x19c980f98 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.241 + 276
5  Foundation                     0x19cc758bc __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
6  Foundation                     0x19cb7dab8 -[NSBlockOperation main] + 72
7  Foundation                     0x19cb7cf8c -[__NSOperationInternal _start:] + 740
8  Foundation                     0x19cc77790 __NSOQSchedule_f + 272
9  libdispatch.dylib              0x19bc1d6c8 _dispatch_call_block_and_release + 24
10 libdispatch.dylib              0x19bc1e484 _dispatch_client_callout + 16
11 libdispatch.dylib              0x19bbf4e04 _dispatch_continuation_pop$VARIANT$armv81 + 404
12 libdispatch.dylib              0x19bbf44e8 _dispatch_async_redirect_invoke + 592
13 libdispatch.dylib              0x19bc00aec _dispatch_root_queue_drain + 344
14 libdispatch.dylib              0x19bc0134c _dispatch_worker_thread2 + 116
15 libsystem_pthread.dylib        0x19be0117c _pthread_wqthread + 472
16 libsystem_pthread.dylib        0x19be03cec start_wqthread + 4
```

Debugging Screenshots when I pressed pause in Xcode debugger while app is stuck.

![screen shot 2019-02-24 at 8 58 03 am](https://user-images.githubusercontent.com/1171212/53308106-58840980-3853-11e9-80cb-a01208111455.png)

![screen shot 2019-02-24 at 8 57 32 am](https://user-images.githubusercontent.com/1171212/53308107-58840980-3853-11e9-9fa3-b79007a975bd.png)

Looks like they are both stuck at 

```
func task(for url: URL) -> SessionDataTask? {
```

#### Reproduce

Our app is a chat and casual game app, in an active chat room view, when I scroll the messages up and down fast enough (which will trigger either download images from server or fetch image from cache), it trigger this crash.  However, the code shown in the main thread stacktrace is actually for another VC (Active game List) which is loaded but not visible, this  game list VC and the chat VC are both sub view controllers of the chatroom VC. Game list VC are actively being updated when people create and updating games, and in the game list VC, there are players list for each active game, the one in main thread one is to set the player profile image via Kingfisher image view extension method:

```
cell.avatarImageView.kf.setImage(with: url)
```

#### Other Comment

I can provide more information if needed. Thanks.

**Comment by onevcat** [comment]
Hi,

May I know what's your version? There are some fixes on the thread recently in the latest release. Could you try the latest version to see whether it is still there? Thanks!

**Comment by zwang** [comment]
Thanks @onevcat . That's super fast reply.  👍  I was going to add the version but interrupted. Thought I could add later before you reply. Sorry. :)

I have the latest version of 5.1.1 because I manually merged everything from latest master to my fork in this branch https://github.com/zwang/Kingfisher/tree/ios9 . The revision we were using is https://github.com/zwang/Kingfisher/commit/df7c452d351b292b43bbdf741e574794e38b5bde, in which you can see there are the changes of 5.1.1. 

The difference is I still need to support iOS 9 so I have manually applied this patch: https://github.com/zwang/Kingfisher/commit/71b6dcb85dd828e0df91e905a89f9544b49dda77 

To make sure I am using the exact latest version of 5.1.1, I am going to make a build of our app based on Kingfisher 5.1.1 release in this repo and test again. I will report back in about 4-5 hours. 

Thank you for jumping on this fast. 👍 🙏

**Comment by zwang** [comment]
I updated the minimal target to 10.0 for our app and then use Kingfisher 5.1.1 from this repository. Still get the same error as below:

<img width="1680" alt="screen shot 2019-02-24 at 8 25 03 pm" src="https://user-images.githubusercontent.com/1171212/53314403-ffc46900-3872-11e9-81db-cfde456d1f81.png">

<img width="1680" alt="screen shot 2019-02-24 at 8 25 49 pm" src="https://user-images.githubusercontent.com/1171212/53314410-04891d00-3873-11e9-9187-39cd0087235f.png">

I am using Xcode 10.1 (10B61), debugging on iPhone X with iOS 12.1.4.

**Comment by onevcat** [comment]
Do you have a chance to try this branch [fix/locks](https://github.com/onevcat/Kingfisher/tree/fix/locks)?

**Comment by zwang** [comment]
> Do you have a chance to try this branch [fix/locks](https://github.com/onevcat/Kingfisher/tree/fix/locks)?

@onevcat thanks a lot. You beat me again. I was going to try the same thing you just did since I just caught up with the code after reading some documents for NSLock. 

I am trying that now.  Thank you very much!

**Comment by zwang** [comment]
@onevcat After trying the fix for 25 minutes without a crash, I think it is safe to say this commit https://github.com/onevcat/Kingfisher/commit/7742aff5ffafb530f98e11058c6a814b9bb77373 fixed the issue. Usually I can get a crash without the fix in like 1 minute of scrolling. 

Thanks a lot for the fix. I really appreciate it. 👍 🙏
