### ISSUE TITLE
KF only loads 1px (maybe a few more?) of the image, somehow displays as gradient, instead of the whole image

### ISSUE THREAD

**Issue by LinusGeffarth** [onevcat/Kingfisher#1129]
Hey there,  
I have a `UICollectionView` with image views in which I load images asynchronously. The first time I open the view controller, it sometimes shows me this:

<img width="120" alt="image bug" src="https://user-images.githubusercontent.com/9455439/53815058-2cf2d480-3f61-11e9-82af-4b7afceb248a.png">

When I dismiss the vc and reopen it, the images are shown properly:

<img width="120" alt="screen shot 2019-03-05 at 16 11 14" src="https://user-images.githubusercontent.com/9455439/53815137-56136500-3f61-11e9-8805-d39fe2c19005.png">

I'm guessing that they're now showing like they should because they're cached.  
What makes it weirder than just not showing anything is that there's a gradient there. I'm unsure as to whether that gradient is part of the image - just highly zoomed in - or it's primary colors from the image (not sure where these would come from).

From our API, the images are fetched for double the view size (double for retina) so it can't really be a wrong content mode, such as top left.  
Also, for the **upper image** view in the screenshot below, I changed the content mode from `.scaleAspectFill` to `.center` which should draw the image in it's real size and it turns into this:

<img width="116" alt="screen shot 2019-03-05 at 16 20 55" src="https://user-images.githubusercontent.com/9455439/53815809-ab9c4180-3f62-11e9-8633-5a1df0c92435.png">

...which leads me to believe that the image is only 1x1px?

Any idea what's wrong?

**Comment by onevcat** [comment]
Are you using any `ImageProcessor`? May I know some code snippet when you setting your image views?

**Comment by LinusGeffarth** [comment]
@onevcat was an issue on my end, sorry!

**Comment by onevcat** [comment]
Good to hear that you found it! Never mind. :]
