### ISSUE TITLE
Kingfisher with POST request

### ISSUE THREAD

**Issue by tarsVEVO** [onevcat/Kingfisher#1133]
My Image URLs requires a httpBody. So I'm using `AnyModifier` to modify request:
`        var request = networkUtl.request(getPhoto: photoDownloader.email, pass: photoDownloader.pass, uuid: photoDownloader.uuid, projectId: photoDownloader.projectId, p_id: "\(id)", type: type)
        `
`
let modifier = AnyModifier { req in
            return request
        }`

but when I call `setImage` method it returns me error log like so : 
`Job failed: Retrieving resource failed, and this resource is not the one currently expected. Error: processorError(reason: Kingfisher.KingfisherError.ProcessorErrorReason.processingFailed(processor: Kingfisher.DefaultImageProcessor(identifier: ""), item: Kingfisher.ImageProcessItem.data(39 bytes))). Resource: network(https://asc.com/api/ios/get_photo/123/123/1).`

I wonder this issue cause `Kingfisher` does not support `POST` request ?

**Comment by onevcat** [comment]
Kingfisher should support response from either GET or POST, as long as you are returning the correct image data.

The error indicates that the result is discarded because you are trying to load another image for the image view. So Kingfisher will respect the latter setting and ignore the result from the first setImage. Is that your case, of any idea on this?

**Comment by tarsVEVO** [comment]
I'm put the code inside func `collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath)`
Is it right or not ?

**Comment by onevcat** [comment]
That means your request is not correct and your server returns you an error. : (

I suggest you try to observe the request with a proxy or on your server, to make sure it is what you expected. Kingfisher would just send the request you give, regardless it is a GET or a POST, and parse the response data to the image.

**Comment by tarsVEVO** [comment]
Omg, can't believe that I forgot to pass header. 
Solved ! thanks for the replies
