### ISSUE TITLE
loading indicator

### ISSUE THREAD

**Issue by adelbios** [onevcat/Kingfisher#1136]
can i replace loading indicator by this lib [https://github.com/Juanpe/SkeletonView](url) ?!

**Comment by onevcat** [comment]
I don't any experience on the `SkeletonView`. But if you can get the `UIView` object from it, you can make it conform to Kingfisher's `Indicator`.

Basically, you need to specify a `view` to add to and remove from the target image view. And also implement the `startAnimatingView` and `stopAnimatingView` to make it animatable if you need.

See more on this topic [here](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#using-a-customized-view).
