### ISSUE TITLE
Disk caching completion callback?

### ISSUE THREAD

**Issue by muratyasarr** [onevcat/Kingfisher#1138]
Hello,

We're using Kingfisher for caching operation of thousands of images. It takes ~a minute for caching to disk operation to finish. We need a callback to know if caching to disk has finished. Is there way to achieve this with the current Kingfisher version?

Thank you.

**Comment by onevcat** [comment]
Not sure how did you send the images to cache. If you are using the image view extension method (`kf.setImage`), maybe you can try to use the [.waitForCache](https://github.com/onevcat/Kingfisher/blob/master/Sources/General/KingfisherOptionsInfo.swift#L90-L91) option.

**Comment by muratyasarr** [comment]
Hello, thank you for the response. 

I use _retrieveImage_ and it seems waitForCache is not available for that method. How could I get to know if all caching has finished?

**Comment by onevcat** [comment]
Do you have any code snippet? How and what are you doing exactly?

Please do not just delete the issue template. Following it would make the communication smoother and you can get better support.

**Comment by muratyasarr** [comment]
I get my image URLs from a local db and iterate over them to download(hence cache) them so that once the app is opened when there is no internet connection, we make the images available to our users. Specifically, I want to catch the moment all disk caching operation finishes. With the below code I get the callbacks but when I monitor the memory I see that disk caching operations still continue although kingfisher completion callbacks trigger. 
```
    func getImageURLsAndCache(completion: @escaping(Bool) -> Void) {
        guard let db = db else { return }
        let imageTable = Table("image")
        do {
            var counter = 0
            var rows: [Row] = []
            for row in try db.prepare(imageTable) {
                rows.append(row)
            }
            
            for row in try db.prepare(imageTable) {
                var baseImageUrl = "{host.com}"
                if let imageUrl = try row.get(DatabaseColumnNames.url) {
                    baseImageUrl.append(imageUrl)
                    if let url = URL(string: baseImageUrl) {
                        KingfisherManager.shared.retrieveImage(with: url, options: nil, progressBlock: nil) { (image, error, type, url) in
                            if counter == rows.count - 1 {
                                completion(true)
                            }
                            counter += 1
                        }
                    }
                }
            }
        } catch {
            print(error)
        }
    }

```

**Comment by onevcat** [comment]
What's the version of Kingfisher you are using? `.waitForCache` was added from [version 4.9.0](https://github.com/onevcat/Kingfisher/releases/tag/4.9.0) and it should work for this `KingfisherManager.retrieveImage` method. Can you try to upgrade to a version supporting that option?

**Comment by muratyasarr** [comment]
Wow. I'll check the version and `.waitForCache`. Thank you for the quick responses! I'm closing the issue for now.
