### ISSUE TITLE
Kingfisher4 migrate to Kingfisher5 can't load local gif

### ISSUE THREAD

**Issue by Hstripe** [onevcat/Kingfisher#1144]
I use Kingfisher4 it worked, but when I migrate to Kingfisher5 it doesn't work.

Logs:

Path URL:Optional(file:///var/containers/Bundle/Application/90C361C7-653A-4934-9085-F8DD979CF024/*******.app/loading.gif)

responseError(
reason: Kingfisher.KingfisherError.ResponseErrorReason.invalidURLResponse(response: <NSURLResponse: 0x1c4203480> { URL: file:///var/containers/Bundle/Application/90C361C7-653A-4934-9085-F8DD979CF024/*******.app/loading.gif })
)

**Comment by onevcat** [comment]
Loading a local file now requires an `ImageDataProvider`. See [this wiki](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#image-from-local-file) for more.

**Comment by Hstripe** [comment]
Thank you, I solve it.😆
