### ISSUE TITLE
[Kingfisher 5.3] Prefetcher Fatal error: UnsafeMutablePointer.deinitialize with negative count

### ISSUE THREAD

**Issue by seanliu1** [onevcat/Kingfisher#1148]
This is a new issue for kingfisher 5.3 Prefetcher. I am not able to reproduce this issue on 5.2

<img width="823" alt="Screen Shot 2019-03-27 at 1 10 40 PM" src="https://user-images.githubusercontent.com/46942150/55108940-e68d2300-5091-11e9-90fa-98d1ad6b1222.png">
<img width="434" alt="Screen Shot 2019-03-27 at 1 10 47 PM" src="https://user-images.githubusercontent.com/46942150/55108942-e856e680-5091-11e9-9f0f-b5591a06abea.png">

**Comment by onevcat** [comment]
Should be fixed in version 5.3.1.
