### ISSUE TITLE
ProcessorError on setting image in UITableViewCell subclass

### ISSUE THREAD

**Issue by RAITERN** [onevcat/Kingfisher#1155]
Hi,
I'm using kingfisher in UITableviewCell subclass to fetch fav icons of websites. When I scroll the tableview list its working for limited cells & for the remaining cell I'm getting the following error 

`processorError(reason: Kingfisher.KingfisherError.ProcessorErrorReason.processingFailed(processor: Kingfisher.DefaultImageProcessor(identifier: ""), item: Kingfisher.ImageProcessItem.data(132 bytes)))`

Once I got this error, there is no fetching of images after that even though there is image.
This is my code in cellForRowAt:

```
let modifier = AnyModifier { request in
                    var req = request
                    req.setValue(headerToken, forHTTPHeaderField: "Authorization")
                    req.httpMethod = "GET"
                    return req
                }
                
                let logoUrl = URL(string: String(format: "https://myservice.com/logo?id=%@" logoId))
                iconImageView.kf.setImage(with: logoUrl, placeholder: UIImage(named: "placeholder"), options: [.requestModifier(modifier)]) { result in
                    switch result {
                    case .success(let value):
                        // The source object which contains information like `url`.
                        print(value.source)
                    case .failure(let error):
                        print(error) // The error happens
                    }
                }
```

**Comment by onevcat** [comment]
It means your downloading is correctly finished with some data, but it is not an image and cannot be converted to a valid `UIImage` object. I suggest you check what the downloaded content exactly is (the length of that data is 132 bytes). The size is not likely to be a valid image, but some text or error message from your server.

**Comment by RAITERN** [comment]
The downloaded data is image only, because its working sometimes. After I cleared the cache and start fetching the image, the error happening again. Will there be any problem if the tableview datasource count is over 150 & scrolling the list fast might cause the problem?

**Comment by RAITERN** [comment]
My bad. I am getting error text in that case due to limit reached. That why it was working sometimes. Thank you.
