### ISSUE TITLE
KingFisher won't care get parameters of image to load

### ISSUE THREAD

**Issue by SalihBalkan** [onevcat/Kingfisher#1156]
If you load this URL as image:
https://i.f5haber.com/img/2/660/320/files/haber/1085070.jpg?v=542019111948

You see this image instead:
https://i.f5haber.com/img/2/660/320/files/haber/1085070.jpg

It doesn't care get parameters at all.

**Comment by onevcat** [comment]
I tried both of your links and it works well for me.

Can you prepare a sample project which this issue can be reproduced?

**Comment by SalihBalkan** [comment]
Oh sorry maybe it's because I am using Kingfisher 4.0. I will try this out when I have time for this.

**Comment by tarsVEVO** [comment]
Can Kingfisher distinguish the same URL but different http-body?

**Comment by onevcat** [comment]
No. If you use the same URL, and that URL is cached, Kingfisher will not try to start any network anymore but load the cached image.
