### ISSUE TITLE
How to set image for UITabBarItem

### ISSUE THREAD

**Issue by aliunco** [onevcat/Kingfisher#1157]
I know that to set the image for tabbar item I can use the code below, but is it possible to set image with url using kingfisher?
```swift
    self.tabBarItem.image = UIImage(named: "item")
    self.tabBarItem.selectedImage = UIImage(named: "item_selected")
```

**Comment by onevcat** [comment]
Kingfisher does not provide the extension methods for setting images for a bar item. You need to use `KingfisherManager` to get the image and set it manually yourself.

See [this section](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#getting-an-image-without-ui) in our wiki for more.
