### ISSUE TITLE
Setting the kf.indicatorType breaks the zoom functionality of the UIScrollView embedding the UIImageView

### ISSUE THREAD

**Issue by rowanmulder** [onevcat/Kingfisher#1158]
### Issue Description
Setting the kf.indicatorType breaks the zoom functionality of the UIScrollView embedding the UIImageView

#### What
Recently we've updated from Kingfisher 4.10.0 to 5.3.1, after upgrading we've encountered a problem where zooming on an UIImageView results in zooming in the top left corner, instead of the coordinates indicated by the user.

Our code consists of a UIScrollView that contains a large UIView that has placed multiple images as UIImageView horizontally. The UIScrollView is configured with with "isPagingEnabled" to give allow a user to swipe from left to right between various images. The content size of the UIScrollView is using hard coded height and width and is used to calculate the scroll needed for a pageable swipe navigation. The UIScrollView has a minimum zoom scale of 1.0 and a maximum of 2.0. We've implemented the viewForZooming delegate method, as well as some convenience code while zoomed in an scroll to the next "page".

So far this all worked until we upgraded. After debugging it seems that the zoom function, that normally zooms in on the coordinates the user uses multi-touch around (or double taps) is broken. Instead it always returns to the top left corner, regardless fo where in the UIScrollView is zoomed. Disabling the line with "self?.kf.indicatorType = .activity" fixes this problem.

#### Reproduce
1) Create a UIScrollView on a UIView (on a UIViewController)
2) Set a static dimension for the content of the scroll view
3) Enable zoom (min: 1.0, max 2.0, default 1.0)
4) Create a UIView and add (one or more) UIImageViews to it
5) Return the correct view for viewForZooming (the entire container view)
6) Use Kingfisher to load a remote image on the UIImageView and make of the activity indicator by setting the indicatorType
7) Run and try to zoom the image (disable the previous line and try again)

**Comment by onevcat** [comment]
@rowanmulder 

Thanks for the report and detail information. The indicator type `.activity` only adds a `UIActivityIndicatorView` to the image view, with its intrinsic size and center anchor to the image view. I cannot imagine how it could affect a parent scroll view.

I need first reproduce this issue before I can dig deeper. But since the UI structure is not trivial and I am not 100% sure about on your description. I guess it would be faster if you can prepare a simple sample project in which I can check this issue. Can you build a sample for it when you have time?

Thank you!

**Comment by rowanmulder** [comment]
@onevcat 

Attached a quick and dirty example of where it goes wrong (just pinch to zoom to see the effect). Disable "self?.kf.indicatorType = .activity" in "Image+Download.swift" to see it behave differently.
[KingfisherTestApp.zip](https://github.com/onevcat/Kingfisher/files/3072275/KingfisherTestApp.zip)

**Comment by onevcat** [comment]
In your sample, you are not specifying correct layout constraints for the `containerView`. Kingfisher's built-in activity indicator relies on a set of correct constraints. In your case, once `.activity` is added, it will ask upon to the container view, which lacks a layout strategy and causes the issue.

So I guess you can try to remove the line below to make it work:

```swift
containerView.translatesAutoresizingMaskIntoConstraints = false
```

**Comment by rowanmulder** [comment]
@onevcat Tried it and it seems to resolve the problem. Thanks for your time!
