### ISSUE TITLE
Warning: 'public' modifier is redundant for property declared in a public extension

### ISSUE THREAD

**Issue by phlippieb** [onevcat/Kingfisher#1169]
When building a project that uses Kingfisher, there are several instances of the warning "'public' modifier is redundant for property declared in a public extension".

**Comment by phlippieb** [comment]
Ah, seems like this was on a very old version, my bad. Updated our minimum deployment target to be able to update to the latest version of this pod.

**Comment by originpulses** [comment]
Seems like I am having this issue as well and upgrading isn't an option for me. Is there a way to silence this warning? I have to specifically use Swift 4 and my pod version is 4 as well.

**Comment by onevcat** [comment]
The current version of Kingfisher is still supporting Swift 4 so I guess it is an option to upgrade for you.

**Comment by originpulses** [comment]
I initially tried 5.0 but the build fails with different issues than this one. I decided to downgrade to 4.0 which gives me no problems in the build but brings me to these warnings.

**Comment by originpulses** [comment]
Seems weird but I uninstalled Xcode's latest version and now these warnings disappear. I had 2 Xcode installed and I was running this on 10 and getting those warnings. I uninstalled the latest one and now it works on 10 without those warnings.
