### ISSUE TITLE
Problem with callback version of kf_setImagewithURL

### ISSUE THREAD

**Issue by camill-a** [onevcat/Kingfisher#117]
Hello,

first I canna thanks you for this easy to use and ligthweigth framework!

My problem is the following: 

- I am using `kf_setImageWithURL()` inside of `tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath)`
The code is the following 
```
override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell: ProductCell = tableView.dequeueReusableCellWithIdentifier(CCELL.PRODUCT, forIndexPath: indexPath) as! ProductCell
        let row = indexPath.row
        let product = products.elements[row]
        
        cell.configure(product)
        
        if let imgView = cell.imageView {
            imgView.kf_showIndicatorWhenLoading = true
            imgView.kf_setImageWithURL(NSURL(string: product.pictureUrl)!, placeholderImage: nil, options: KingfisherOptions.None, progressBlock: nil, completionHandler: { (image, error, CacheType, imageURL) -> () in
                self.ProductTable.reloadRowsAtIndexPaths([indexPath], withRowAnimation: UITableViewRowAnimation.Automatic)
                })
        return cell
}
```

This implémentation is a bit weird, at first I used 

```
imgView.kf_setImageWithURL(NSURL(string: product.pictureUrl)!, placeholderImage: nil)
```

but i couldn't have the callback to refresh my UITableViewCell.

Problem is that Xcode tell me that the fonction I use now is deprecated, and that I should use another one but whenI use it it's the same, or my paremeters (even rigth after long check) never match the asked parameters. I think something is vronw, maybe in my way of doing my stuff or with the api :/

Hope you can help

Have a good day,

Alexandre Camilleri from France!

**Comment by onevcat** [comment]
Hi,

The `options` version of API is deprecated. You should use the `optionsInfo` version instead. You can just pass a `nil` for it, like this:

imgView.kf_setImageWithURL(NSURL(string: product.pictureUrl)!, placeholderImage: nil, optionsInfo: nil, progressBlock: nil, completionHandler: { (image, error, CacheType, imageURL) -> () in
                self.ProductTable.reloadRowsAtIndexPaths([indexPath], withRowAnimation: UITableViewRowAnimation.Automatic)
                })

**Comment by camill-a** [comment]
Wow thank you very much sir, it fixes my problem!

Have a good day
