### ISSUE TITLE
总是会崩溃到这里是什么原因呢

### ISSUE THREAD

**Issue by simpleLiYu** [onevcat/Kingfisher#1175]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/20043672/57287914-109f1f80-70eb-11e9-93dd-adcca7fa1f30.png">

**Comment by onevcat** [comment]
It seems that you are trying to call `get()` on the result but it is an error that you are not handling. Maybe you need to add `do...try` block and handle the error correctly. (Or use the `switch` statement on the result to make it gracefully.)

**Comment by simpleLiYu** [comment]
好的十分感谢。应该是对Result的处理不正确，单纯的break掉就会崩溃
