### ISSUE TITLE
Infinite image loading with memory leak?

### ISSUE THREAD

**Issue by camill-a** [onevcat/Kingfisher#118]
When I lord my pictures in UITableView everything goes smooth. In my whole datables, one link is broken.
When the api try to get the image from the broken link, the cell flickers and the memory usage increase until I reboot the app.

Here is the piece of code, I don't think I do anything wrong, but maybe I miss to do something?
```
    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell: ProductCell = tableView.dequeueReusableCellWithIdentifier(CCELL.PRODUCT, forIndexPath: indexPath) as! ProductCell
        let row = indexPath.row
        let product = products.elements[row]
        
        cell.configure(product)

        if let imgView = cell.imageView {
            imgView.kf_setImageWithURL(
                NSURL(string: product.pictureUrl)!,
                placeholderImage: nil,
                optionsInfo: nil,
                progressBlock: nil,
                completionHandler: { (image, error, CacheType, imageURL) -> () in
                self.ProductTable.reloadRowsAtIndexPaths([indexPath], withRowAnimation: UITableViewRowAnimation.Automatic) }
            )
        }
        return cell
    }
```

**Comment by onevcat** [comment]
Why do you need to reload the cell after setting image finished? Kingfisher will set the image to the image view for you. If you reload the same cell, your `tableView: cellForRowAtIndexPath:` will be called again and again. Is that what you really need?

**Comment by camill-a** [comment]
Well, if I don't do this then the image never appear until I scroll the cells because the views are not refreshed? Maybe this is not a good pactice?

**Comment by camill-a** [comment]
Ok i fixes the problem, is because I used the default Image set by apple in the UITableViewCell, and not mind...

**Comment by KimiChiu** [comment]
I have the same problem.
Kingfisher didn't show image after downloading. How did you fix this issue?
I don't have any default image in my ImageView.
