### ISSUE TITLE
Images when cached its URL doesn't have extension (.png, .jpg) etc.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [onevcat/Kingfisher#1180]
Images when cached its local URL doesn't have an extension (.png, .jpg) etc.
So, we I am trying to retrieve local path for particular image it returns like following.

`Devices/25B1CAB6-1D71-492B-845C-31985FC0AD4E/data/Containers/Data/Application/76CFF941-5968-41A9-B17B-7828CC9D58F7/Library/Caches/com.onevcat.Kingfisher.ImageCache.default/adb48eb6fb8703a3d3a00ab386a9f5fb` 

I am using `ImageCache.default` object to retrieve cached image path.
`ImageCache.default.cachePath(forKey: "some identifier")`

When I manually goto the path, images doesn't contain extension. following is screenshot for the same.

![Screen Shot 2019-05-10 at 6 51 29 PM](https://user-images.githubusercontent.com/19154948/57530431-d6d15180-7354-11e9-96f7-65528995ca58.png)

_Actually, I am using_ **UIDocumentInteractionController** _to open image in full screen. So, it requires local path of an image._ 
_Since, image doesn't contains extension, I am getting error during present_ `UIDocumentInteractionController`_._

**Comment by onevcat** [comment]
It is how Kingfisher designed. The image names are hashed to prevent conflicting and reusing. Normally you should never care about the extension.

If you can make sure that all the images belong to a certain type, you can set [this property](https://onevcat.github.io/Kingfisher/Enums/DiskStorage/Config.html#/s:10Kingfisher11DiskStorageO6ConfigV13pathExtensionSSSgvp).

**Comment by Rashesh-Bosamiya** [comment]
I tried `pathExtension` property as well. But doesn't seems to be worked.

**Comment by onevcat** [comment]
I believe it should work since [this test](https://github.com/onevcat/Kingfisher/blob/master/Tests/KingfisherTests/ImageCacheTests.swift#L221-L235) is passing without problem.

**Comment by Rashesh-Bosamiya** [comment]
Okay, Thanks for you prompt reply. I will deep dive into this to figure out.
For now, I am closing this issue. If I wouldn't succeeded, will re-open.
