### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found

### ISSUE THREAD

**Issue by thejogsa** [onevcat/Kingfisher#1185]
dyld: lazy symbol binding failed: Symbol not found: 

_$s10Kingfisher0A7WrapperVAASo11UIImageViewCRbzlE8setImage4with11placeholder7options13progressBlock17completionHandlerAA12DownloadTaskVSgAA8Resource_pSg_AA11Placeholder_pSgSayAA0A15OptionsInfoItemOGSgys5Int64V_AXtcSgyAA6ResultOyAA08RetrievefV0VAA0A5ErrorOGcSgtF

  Referenced from: /Users/xyz/Library/Developer/CoreSimulator/Devices/0AE1C996-FDAD-4CB5-9936-F2387C5A1C9F/data/Containers/Bundle/Application/72A4B378-39B4-4337-BAB9-D4D6458281DC/PodTest.app/Frameworks/MyOwn.framework/MyOwn
  Expected in: /Users/xyz/Library/Developer/CoreSimulator/Devices/0AE1C996-FDAD-4CB5-9936-F2387C5A1C9F/data/Containers/Bundle/Application/72A4B378-39B4-4337-BAB9-D4D6458281DC/PodTest.app/Frameworks/Kingfisher.framework/Kingfisher

![Screenshot 2019-05-17 at 12 19 37 PM](https://user-images.githubusercontent.com/8350797/57908756-71261d80-789e-11e9-8aa7-cb7c37650941.png)

**Comment by necatievrenyasar** [comment]
@thejogsa  Did you solve problem?

**Comment by GabzTodaro** [comment]
I've been facing this issue. Did you find the fix?

**Comment by onevcat** [comment]
Basically this is due to you didn't add Kingfisher.framework to the embed/copy framework to your project. Your `MyOwn.framework` links and expects Kingfisher to be there, but in fact it is not in your bundle.

**Comment by winterdl** [comment]
I've been facing this issue. Did you find the fix?

`dyld[1348]: Symbol not found: _$s10Kingfisher0A15OptionsInfoItemO10transitionyAcA15ImageTransitionOcACmFWC`

**Comment by winterdl** [comment]
Add this to the app that using framework

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
```
