### ISSUE TITLE
I have some problems when Creating a ImageProcessor

### ISSUE THREAD

**Issue by whereiswhere** [onevcat/Kingfisher#1186]
I want to create a ImageProcessor for add some drop shadows to the image.

So first when I put the sample code of "Creating your own processor" at Cheat Sheet in to my code: 
`struct WebpProcessor: ImageProcessor {

    // `identifier` should be the same for processors with the same properties/functionality
    // It will be used when storing and retrieving the image to/from cache.
    let identifier = "com.yourdomain.webpprocessor"
    
    // Convert input data/image to target image and return it.
    func process(item: ImageProcessItem, options: KingfisherParsedOptionsInfo) -> Image? {
        switch item {
        case .image(let image):
            print("already an image")
            return image
        case .data(let data):
            return WebpFramework.createImage(from: webpData)
        }
    }
    }

I got the error said 

> Type 'WebpProcessor' does not conform to protocol 'ImageProcessor'

But the process(item:options:) function is alway there, and if click the fix button of the 'Do you want to add protocol stubs?' and it add another process(item:options:) function to the Struct. 

Anybody knows the problem?

**Comment by onevcat** [comment]
I tried the sample code and everything goes fine.

The wiki is for the latest version (Kingfisher 5), are you using a previous version? The signature was changed a bit for this method, so it is possible that the sample is not working in a Kingfisher 4 integration.
