### ISSUE TITLE
Branch iOS 9 has issue in podspec

### ISSUE THREAD

**Issue by gianfilippocisternino** [onevcat/Kingfisher#1191]
The branch iOS 9 doesn't work.
Cocoapods returns an error in the podspec.
Please fix it.

Thank you in advance.

**Comment by dstranz** [comment]
@gianfilippocisternino:

What is your Cocoa Pods version?
`pod --version`

**Comment by idrougge** [comment]
Looks like Cocoapods 1.7.0 is required.

**Comment by onevcat** [comment]
The ios9 branch will never be updated anymore. So I am closing this issue.
