### ISSUE TITLE
AnimatedImageView.Animator.animatedFrames 线程安全的疑惑

### ISSUE THREAD

**Issue by luochaojing** [onevcat/Kingfisher#1195]
您好！
非常感谢Kingfisher这个强大的库，不过最近在使用的时候遇到了个线程安全的问题。

1. 主线程：在AnimatedImageView.display方法里调用了animator.currentFrameImage，获取animatedFrames[safe: index]?.image，这里是在主线程获取animatedFrames数组

2. 子线程 DispatchQueue(label: "com.onevcat.Kingfisher.Animator.preloadQueue") 的updatePreloadedFrames 等方法也设置了animatedFrames数组

这里的线程安全是如何保证的呢？目前我用的过程中挺高概率出现悬垂指针的问题，crash在 return animatedFrames[safe: index]?.image 这里。堆栈信息主要是
![屏幕快照 2019-05-27 11 29 14](https://user-images.githubusercontent.com/13879378/58393761-b6063d00-8072-11e9-8dd0-86449e95f912.png)

或者 [NSTaggedPointerString CGImage]: unrecognized selector sent to instance

**Comment by onevcat** [comment]
@luochaojing Thanks for pointing it out. I guess there might be some issues here. I will check to see how can we solve it. (Maybe applying some locks I guess...)

**Comment by zhixingxi** [comment]
我使用的 5.6.0 版本，也是挺高概率的会出现这个问题。

**Comment by luochaojing** [comment]
> 我使用的 5.6.0 版本，也是挺高概率的会出现这个问题。
我这边的解决方案是给animatedFrames的读写操作加锁，经线上验证这方法对于性能和安全都是可行的

**Comment by onevcat** [comment]
@luochaojing 

感谢指出。如果有验证过的话，能不能发一个 PR 过来？感谢！

**Comment by onevcat** [comment]
Should be fixed in #1257
