### ISSUE TITLE
Bug with caching rounded image 

### ISSUE THREAD

**Issue by aleksiosdev** [onevcat/Kingfisher#1197]
Hi!

I have a strange bug, probably with cache image. I made test project to reproduce it.
https://github.com/aleksiosdev/KingfisherBug
1. Just install app. Using kingfisher we will download image, apply round circle processor and show it to user
2. Select cell - cell background become gray and you'll see that image is true circled.
3. Just stop app.
4. And open it one more time. Now image will be taken from cache.
5. Select cell - cell background become gray and you will see that image is no circle - it have ugly white borders of square.
Here is the picture: https://imgur.com/a/nFvX841
6. To see again normal picture - delete app and install again, invalidate cache or add options not to use cache

It see really problem for me cause I have same ui logic
s in the app. I can't use cornerRadius cause it affect frame rate. 
Any suggestions?

**Comment by onevcat** [comment]
@aleksiosdev I guess you are trying to make a JPG image round cornered. Maybe it is worth to read [this topic](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#serializer-to-force-a-format).

**Comment by aleksiosdev** [comment]
@onevcat Thank you! It is. Didn't thought it not converting by default>
