### ISSUE TITLE
Swift 5.1 compatibility

### ISSUE THREAD

**Issue by gadirajp** [onevcat/Kingfisher#1202]
### Issue Description
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1
#### What
As Apple released the Xcode 11 beta, kingfisher does not compile as the swift version is incompatible.
#### Reproduce
Build the app with kingfisher latest version on Xcode11 beta

**Comment by onevcat** [comment]
There is no module compatible yet so you need to also rebuild Kingfisher from source in Xcode 11, instead of using a binary from Xcode 10.
