### ISSUE TITLE
File url problem in latest version

### ISSUE THREAD

**Issue by Insfgg99x** [onevcat/Kingfisher#1204]
### Issue Description

file url problem with latest version

#### What
```
imv.kf.setImage(with: URL.init(fileURLWithPath: filePath))
```
[Tell us about the issue]

file url problem

**Comment by nayooti** [comment]
Read in:
`https://github.com/onevcat/Kingfisher/wiki/New-In-Kingfisher-5`
Section:
**Loading From Arbitrary Source**

**Comment by onevcat** [comment]
It was an "accident" that Kingfisher 4.x could load a local file through URL, it is not intended and in Kingfisher 5, you need to specify it explicitly: https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#image-from-local-file
