### ISSUE TITLE
Get original Image while using kf.setImage method

### ISSUE THREAD

**Issue by ghazi256** [onevcat/Kingfisher#1219]
The result while using setImage method

`
let processor = DownsamplingImageProcessor(size: CGSize(width: 450, height: 450))
        imgView?.kf.setImage(
            with: url,
            placeholder: nil,
            options: [
                .processor(processor),
                .transition(.fade(0.5)),
                .cacheMemoryOnly]){ result in
                    switch result {
                    case .success(let value):
                        print(value.image)
                        print("Task done for: \(value.source.url?.absoluteString ?? "")")
                    case .failure(let error):
                        print("Job failed: \(error.localizedDescription)")
                    }
        }`

do not have original image if I have applied processor I am not able to get original image but when I use **downloader.downloadImage** its result have original image value. I would rather use setImage as it handles most things itself like cache etc. Is there any way I can get original image using setImage method?

**Comment by onevcat** [comment]
Setting images just respect your input options and transform/process the images for you.

I guess you can add a `.cacheOriginalImage` option when you set the image, and then retrieve it by 

```swift
KingfisherManager.shared.cache.retrieveImage(forKey: url.cacheKey) { result in
    switch result {
    case .success(let fetched):
        let original: UIImage? = fetched.image
    case .failure(let e):
        print(e)
    }
}
```

However, maybe it is not exactly you want, since there is a side effect: the original images are also cached.

**Comment by onevcat** [comment]
For more about this topic, check [the wiki here](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#cache-original-image-when-using-a-processor).

**Comment by ghazi256** [comment]
I am not storing original images in cache I was storing them in memory. So if it is not possible currently I will be moving toward disk storage. Thanks
