### ISSUE TITLE
crash in ImageProgressiveSerialQueue

### ISSUE THREAD

**Issue by jitesh-sharma** [onevcat/Kingfisher#1226]
I am fetching images from server with fast scroll of uitableview containing uiimageview in every cell and am getting crash lots of time in **ImageProgressiveSerialQueue** class.

Fabric crash report;-
Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x1cdcdac5c _swift_release_dealloc + 16
1  Kingfisher                     0x102e2e398 $s10Kingfisher27ImageProgressiveSerialQueue33_72482AE8B575BA147A8975AD699D4BEFLLC3add7minimum7closureySd_yyycctFyycfU_yycfU_ + 340
2  Kingfisher                     0x102e2e398 $s10Kingfisher27ImageProgressiveSerialQueue33_72482AE8B575BA147A8975AD699D4BEFLLC3add7minimum7closureySd_yyycctFyycfU_yycfU_ + 340
3  Kingfisher                     0x102dd76c4 $sIeg_IeyB_TR + 28
4  libdispatch.dylib              0x19fa0ca38 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x19fa0d7d4 _dispatch_client_callout + 16
6  libdispatch.dylib              0x19f9ed9e4 _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 1008
7  CoreFoundation                 0x19ff5dec0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
8  CoreFoundation                 0x19ff58df8 __CFRunLoopRun + 1924
9  CoreFoundation                 0x19ff58354 CFRunLoopRunSpecific + 436
10 GraphicsServices               0x1a215879c GSEventRunModal + 104
11 UIKitCore                      0x1cc543b68 UIApplicationMain + 212
12 Limeroad                       0x102242568 main + 16 (main.m:16)
13 libdyld.dylib                  0x19fa1e8e0 start + 4

**Comment by onevcat** [comment]
Maybe it is related to #1220 

I will release a new version today and you could try the new version.
