### ISSUE TITLE
Can swift5 version supports iOS 9.0

### ISSUE THREAD

**Issue by Hstripe** [onevcat/Kingfisher#1228]
These days I update my project to swift5.0, but my project minimum deployment target is iOS 9.2. So I couldn't update Kingfhisher to swift 5 version. 
     Can swift5 version supports iOS9?
     Thanks~!

**Comment by onevcat** [comment]
Maybe you can try the ios9 branch (https://github.com/onevcat/Kingfisher/tree/ios9) but the iOS 9 support was already dropped and it will not get updates anymore.
