### ISSUE TITLE
How to make KingFisher understand I have the image I need at a higher resolution and make it resize it and use it?

### ISSUE THREAD

**Issue by GilbertAndreiFloarea** [onevcat/Kingfisher#1229]
I have in my app images at 3 different resolutions: 100x100 441x441 1200x1200. Let's presume I have a UITabBarController.

First tab a UICollectionView with images at 441x441. When I tap one item it adds the id into an array. With this array I populate tab no.2 (where I have a UICollectionView with items at 1200x1200). In tab no.3 same as tab no.2 but images at 100x100. Before navigating to tab no.2 or no.3, I stop the internet connection.

I now have in ImageCache.default all the images in tab no.1 (from the cells that got loaded) with the ids: "https://somethingAndTheID/441".

When I go to tab no.2 I ask KingFisher to give me images from "https://somethingAndTheID/1200" and *"https://somethingAndTheID/100" for tab no.3 and I get a no internet error.

I want to tell KingFisher when I tap lets say image with id 17 the following:

Download from "https://something17/1200"
Cache this on disk
Delete "https://something17/441" or "https://something17/100"
When asked for "https://something17/441" use "https://something17/1200" and scale it down.
What I have now:

I can download the image at 1200, but when I ask for it at 441 it tries to download another image.

Also if you have any other ideas please feel free to share it. Appreciate all the help in advance.

**Comment by onevcat** [comment]
I guess in either tab you can use the code below:

```swift
imageView.kf.setImage(
            with: URL(string: "https://something17/1200")!,
            options: [
                .cacheOriginalImage,
                .processor(DownsamplingImageProcessor(size: sizeInTab))])
```

This will always try to download the 1200x1200 image and downsampling it to the `sizeInTab` which you need. At the same time, `.cacheOriginalImage` is applied, so once downloaded, the high-resolution image can be reused to generate a smaller image without downloading again.

**Comment by GilbertAndreiFloarea** [comment]
This won't help me.
I have hundreds of images in tab 1 at 441x441, with the solution you suggested I would have to download all those images at 1200x1200, and store them all in cache, I would like to just download it at 1200x1200 when necessary and drop the lower resolutions then.
I think I can manually write this, but would be interested if there is another solution for this

**Comment by onevcat** [comment]
This is not a common task so I guess you need to write the logic yourself by combining [image cache existing check](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#check-whether-an-image-in-the-cache) before you decide whether to download or downsampling. And [image manager retrieving](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#getting-an-image-without-ui) to get and cache the highest resolution image before you stopping the Internet connection.

**Comment by GilbertAndreiFloarea** [comment]
Thank you. Will go on this path then.
