### ISSUE TITLE
怎么获取图像格式

### ISSUE THREAD

**Issue by wsl2ls** [onevcat/Kingfisher#1236]
怎么获取图像格式？下载图片完成之后，通过那个API 获取图像格式？

**Comment by MarcSteven** [comment]
`

// Creates an image from a given data and options. `.JPEG`, `.PNG` or `.GIF` is supported. For other
    /// image format, image initializer from system will be used. If no image object could be created from
    /// the given `data`, `nil` will be returned.
    ///
    /// - Parameters:
    ///   - data: The image data representation.
    ///   - options: Options to use when creating the image.
    /// - Returns: An `Image` object represents the image if created. If the `data` is invalid or not supported, `nil`
    ///            will be returned.
    public static func image(data: Data, options: ImageCreatingOptions) -> Image? {
        var image: Image?
        switch data.kf.imageFormat {
        case .JPEG:
            image = Image(data: data, scale: options.scale)
        case .PNG:
            image = Image(data: data, scale: options.scale)
        case .GIF:
            image = KingfisherWrapper.animatedImage(data: data, options: options)
        case .unknown:
            image = Image(data: data, scale: options.scale)
        }
        return image
    }
  
  `
Please read the source code about ImageFormat, you will understand

**Comment by wsl2ls** [comment]
> `
> 
> // Creates an image from a given data and options. `.JPEG`, `.PNG` or `.GIF` is supported. For other
> /// image format, image initializer from system will be used. If no image object could be created from
> /// the given `data`, `nil` will be returned.
> ///
> /// - Parameters:
> /// - data: The image data representation.
> /// - options: Options to use when creating the image.
> /// - Returns: An `Image` object represents the image if created. If the `data` is invalid or not supported, `nil`
> /// will be returned.
> public static func image(data: Data, options: ImageCreatingOptions) -> Image? {
> var image: Image?
> switch data.kf.imageFormat {
> case .JPEG:
> image = Image(data: data, scale: options.scale)
> case .PNG:
> image = Image(data: data, scale: options.scale)
> case .GIF:
> image = KingfisherWrapper.animatedImage(data: data, options: options)
> case .unknown:
> image = Image(data: data, scale: options.scale)
> }
> return image
> }
> 
> `
> Please read the source code about ImageFormat, you will understand

这个类我看了，我主要是想问在图片下载完成后的回调里，怎么获取图片的ImageFormat，比如说以下代码 ：
 imageView.kf.setImage(with: imageUrl!, placeholder: nil, options: [.processor(processor), .scaleFactor(UIScreen.main.scale), .cacheOriginalImage, .onlyLoadFirstFrame] , progressBlock: { (receivedSize, totalSize) in
                    //下载进度
                }) { (result) in
                   //下载完成
                    switch result {
                    case .success(let value):
                        let image: Image = value.image
                       //图片格式 ？
                      var imageType = ????????  怎么获得
                    }   
                    case .failure(let error):
                        print(error)
                    }
                }
        }
    }

**Comment by onevcat** [comment]
@wsl2ls May I know why you want to get the image format? Depending on your purpose, there might be different best practices.

In general, Kingfisher handles the data -> image converting for you and hides the format information from you. But you can basically use the delegate methods in `ImageDownloaderDelegate` to get the data and check image format there.

**Comment by wsl2ls** [comment]
> @wsl2ls May I know why you want to get the image format? Depending on your purpose, there might be different best practices.
> 
> In general, Kingfisher handles the data -> image converting for you and hides the format information from you. But you can basically use the delegate methods in `ImageDownloaderDelegate` to get the data and check image format there.

**Comment by wsl2ls** [comment]
> @wsl2ls May I know why you want to get the image format? Depending on your purpose, there might be different best practices.
> 
> In general, Kingfisher handles the data -> image converting for you and hides the format information from you. But you can basically use the delegate methods in `ImageDownloaderDelegate` to get the data and check image format there.

类似于微博列表下载并显示图片完成后，想把GIF图标签显示出来，然后逐个GIF播放?

**Comment by wsl2ls** [comment]
@onevcat  类似于微博列表下载并显示图片完成后，想把GIF图标签显示出来，然后逐个GIF播放?

**Comment by wsl2ls** [comment]
@onevcat 类似于微博列表下载并显示图片完成后，想把GIF图标签显示出来，然后逐个GIF播放?

**Comment by onevcat** [comment]
It is not that possible to provide it for every image setting in the current implementation. The `Source` is not only containing images from the Internet or disk, but also some image provider which provide a CG context to draw an image from scratch. For the Internet or disk cases, the image data is encoded and we can determine in which format they are. But for the latter case (image drawing), there is no such "image format" concept there.

To me, the closest solution is implementing some methods in `ImageDownloaderDelegate`, like [this one](https://onevcat.github.io/Kingfisher/Protocols/ImageDownloaderDelegate.html#/s:10Kingfisher23ImageDownloaderDelegateP05imageC0_11didDownload3for4withyAA0bC0C_So7NSImageC10Foundation3URLVSo13NSURLResponseCSgtF), then check the request URL and response body data to determine the image format for a certain URL.
