### ISSUE TITLE
Outdated DefaultCacheSerializer documentation

### ISSUE THREAD

**Issue by markst** [onevcat/Kingfisher#1238]
#### What

`DefaultCacheSerializer` documentation mentions:
```
    /// Only when `original` contains valid PNG, JPEG and GIF format data, the `image` will be
    /// converted to the corresponding data type. Otherwise, if the `original` is provided but it is not
    /// a valid format, the `original` data will be used for cache.
```

But it appears that this is no longer the case & `original` data is not used as fallback as indicated. 
It appears that the commit: https://github.com/onevcat/Kingfisher/commit/77e70a3ff8acb3df6a620e1459c1ed338216a92c removes this feature:
```swift
case .unknown: data = original ?? image.kf.normalized.kf.pngRepresentation()
```

Personally we need the original image data be stored for security hash calculation. Which could be achieved by using our own `CacheSerializer`. However it might be worth updating the code or documentation for consistency sake?

**Comment by onevcat** [comment]
Thanks for it. It should be updated now in #1256
