### ISSUE TITLE
Annoying warning about broken Objective-C bridge

### ISSUE THREAD

**Issue by yurijmi** [onevcat/Kingfisher#124]
![2015-10-21 13 13 32](https://cloud.githubusercontent.com/assets/785492/10633757/8f477488-77f5-11e5-8550-a89d9b8b2206.png)

```Umbrella header for module 'Kingfisher' does not include header 'Kingfisher.h'```

This only occurs if using code from master branch. Version in CocoaPods doesn't have that warning.

**Comment by onevcat** [comment]
May I know how did you build the framework? What do you mean by using code from master branch? Did you try to install it by specifying the master in CocoaPods or anything else? If so, would please tell me the CocoaPods version you are using?
It could be great help if you could describe it more detail, including a reproducing step would be better.

Thank you. :)

**Comment by onevcat** [comment]
And I found something might be related to it. It seems no solution there although. Just link it here for future refer. https://github.com/CocoaPods/CocoaPods/issues/3200

**Comment by yurijmi** [comment]
Warning occurs while using this pod
```pod 'Kingfisher', git: 'https://github.com/onevcat/Kingfisher.git'```

Everything's okay (gif does not work ;()
```pod 'Kingfisher'```

**Comment by yurijmi** [comment]
I looked at CocoaPods/CocoaPods#3200 it doesn't solved anything. The most interesting fact is that I use 3 different pods from GitHub and the warning only occurs on Kingfisher

**Comment by yurijmi** [comment]
Also look at this:

Umbrella for the APNGKit:
![2015-10-21 19 12 15](https://cloud.githubusercontent.com/assets/785492/10642702/b7fd2ca6-7827-11e5-8e51-a9854387c89b.png)

Umbrella for the Kingfisher:
![2015-10-21 19 12 30](https://cloud.githubusercontent.com/assets/785492/10642713/c7ee098c-7827-11e5-9958-e2e821243be8.png)

**Comment by yurijmi** [comment]
Fixed it. CocoaPods wants a Objective-C bridging header even if you don't use Objective-C in your project. Making a pull request...
