### ISSUE TITLE
图片加载慢的问题。

### ISSUE THREAD

**Issue by Jacket12** [onevcat/Kingfisher#1250]
如图所示，当网络不是很快的情况下，图片加载非常的慢，甚至网络恢复正常速度之后，图片仍然加载不出来
![F221D287FB6CF8D3D19CBB80E776927A](https://user-images.githubusercontent.com/16936767/62590574-6c9e5d80-b8ff-11e9-8f1c-34e73af75820.png)

**Comment by onevcat** [comment]
Kingfisher 默认的 timeout 是 15 秒，可以试试看打印一下 completion handler 的结果，是不是已经超时失败了？这部分的话基本是系统的网络调度优先级的问题，Kingfisher 里可能没什么特别好的处理方式。

**Comment by Jacket12** [comment]
目前主要是提交苹果审核的问题了，因为苹果那边在弱网差的情况下，图片就会这样，网络正常的时候就不会有这样的问题！就是这个框架，在弱网的情况下，有没有更好的处理方法，因为这样一直被苹果打回，我目前对这个问题没有更好的解决方案了，如果有的话，解答一下！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wei Wang <notifications@github.com>
发送时间: 2019年8月9日 22:49
收件人: onevcat/Kingfisher <Kingfisher@noreply.github.com>
抄送: Jacket12 <393012983@qq.com>, Author <author@noreply.github.com>
主题: 回复：[onevcat/Kingfisher] 图片加载慢的问题。 (#1250)




Kingfisher 默认的 timeout 是 15 秒，可以试试看打印一下 completion handler 的结果，是不是已经超时失败了？这部分的话基本是系统的网络调度优先级的问题，Kingfisher 里可能没什么特别好的处理方式。

**Comment by Jacket12** [comment]
这是苹果审核的截图




发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wei Wang <notifications@github.com>
发送时间: 2019年8月9日 22:49
收件人: onevcat/Kingfisher <Kingfisher@noreply.github.com>
抄送: Jacket12 <393012983@qq.com>, Author <author@noreply.github.com>
主题: 回复：[onevcat/Kingfisher] 图片加载慢的问题。 (#1250)




Kingfisher 默认的 timeout 是 15 秒，可以试试看打印一下 completion handler 的结果，是不是已经超时失败了？这部分的话基本是系统的网络调度优先级的问题，Kingfisher 里可能没什么特别好的处理方式。

**Comment by Jacket12** [comment]
还想补充一点，就是在弱网情况下，我其他数据都能正常加载出来的，就是图片在弱网加载不出来，一旦加载不出来，就会变成上述图片那样，不会再加载了！目前就是这个图片问题！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wei Wang <notifications@github.com>
发送时间: 2019年8月9日 22:49
收件人: onevcat/Kingfisher <Kingfisher@noreply.github.com>
抄送: Jacket12 <393012983@qq.com>, Author <author@noreply.github.com>
主题: 回复：[onevcat/Kingfisher] 图片加载慢的问题。 (#1250)




Kingfisher 默认的 timeout 是 15 秒，可以试试看打印一下 completion handler 的结果，是不是已经超时失败了？这部分的话基本是系统的网络调度优先级的问题，Kingfisher 里可能没什么特别好的处理方式。
