### ISSUE TITLE
RoundProcess background color is white instead of transparent 

### ISSUE THREAD

**Issue by seanliu1** [onevcat/Kingfisher#1264]
Version I use is 5.7.0

Based on documentation 

`    /// Background color of the output image. If `nil`, it will use a transparent background.
`

However when I tested it out it looks like sometime it will return clear background,  sometime it will return white background. Then I specially set background to clear, same thing happens. 
This is option identifier 
`com.onevcat.Kingfisher.DownsamplingImageProcessor((51.0, 72.0))|>com.onevcat.Kingfisher.RoundCornerImageProcessor(10.0)_UIExtendedGrayColorSpace 0 0"
`

I set it the breakpoint for both processor, none of them are called. Here is how I used kf

Then it turns out because images are all cached, and processor are indeed called before store to the disk
```
 kf.setImage(
            with: url,
            placeholder: nil,
            options: baseOptions(withExtraProcessors: [RoundCornerImageProcessor(cornerRadius: cornerRadius, backgroundColor: .clear)] as [ImageProcessor]))

    fileprivate func baseOptions(withExtraProcessors extraProcessors: [ImageProcessor]? = nil) -> [KingfisherOptionsInfoItem] {

        var processors: ImageProcessor = DownsamplingImageProcessor(size: bounds.size)

        if let extras = extraProcessors {
            for extraProcessor in extras {
                processors = processors >> extraProcessor
            }
        }

        return [
            .processor(processors),
            .scaleFactor(UIScreen.main.scale),
            TransitionConstants.defaultFadeIn
        ]
    }

```

**Comment by onevcat** [comment]
Please check this: https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#serializer-to-force-a-format

Duplicated: #1197 #968 #693 and maybe more.
