### ISSUE TITLE
Too much memory consumed by Kingfisher

### ISSUE THREAD

**Issue by ShivamPokhriyal** [onevcat/Kingfisher#1268]
Using kingfisher increases memory consumption of my app too much. 
The problem I am facing is, in my tableview, every cell has a imageview which I populate using Kingfisher. But the memory consumption increases to more than 100mbs just by using Kingfisher. 

I have created a sample [here](https://github.com/ShivamPokhriyal/MemoryIssue), you can clone it and check there. To keep it simple I created just a single imageview and loaded the image using kingfisher and the memory consumption went up by around 40mbs.
Following is the code I used:
`imageView.kf.setImage(with: url, placeholder: placeholder)`
You can imagine what would happen if I use multiple imageviews inside a tableview.
The sample will also have SDWebImage integrated which seems to work fine.

Is it something that I'm doing wrong while using kingfisher? Maybe there is some API that needs to be called before showing the image and I'm missing it or maybe some caching options. Please let me know your thoughts on this.

**Comment by riazhazan** [comment]
Same issue happened for me also. Is there is any quick fix?

**Comment by onevcat** [comment]
There is no magic. SDWebImage is using ImageIO as the default decoder, and the image pixel memory is not counted as a part of your process. However, this is not the case in Kingfisher. If you are checking the memory usage, instead of focusing the memory of your process, I suggest you check the free memory as well. For example, in your sample:

### SDWebImage Before

<img width="688" alt="截屏2019-08-2722 16 54" src="https://user-images.githubusercontent.com/1019875/63775898-49256c00-c91b-11e9-9e0b-9a138b6934dd.png">

### SDWebImage After

<img width="688" alt="截屏2019-08-2722 17 10" src="https://user-images.githubusercontent.com/1019875/63775919-517da700-c91b-11e9-87e3-366b841d8e3a.png">

### Taken memory = "before" - "after"

832.3MB - 809.5MB = 22.8MB

### Kingfisher Before

<img width="688" alt="截屏2019-08-2722 17 55" src="https://user-images.githubusercontent.com/1019875/63776058-96094280-c91b-11e9-80d4-7ae2631692c6.png">

### Kingfisher After

<img width="688" alt="截屏2019-08-2722 18 07" src="https://user-images.githubusercontent.com/1019875/63776067-9bff2380-c91b-11e9-93df-1a703c9884e2.png">

### Taken memory = "before" - "after"

843MB - 823.4MB = 19.6MB

---

There are some other factors, but I believe both are using the same level of memory, just in different places.

As you are showing a very big image, it takes a lot of memory. If these images are for a table view cell, I suggest you use the built-in downsampling processor to make a smaller version of the image before it gets into memory. You can read and follow [this tip](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#using-downsamplingimageprocessor-for-high-resolution-images) to know more on this topic.

**Comment by ShivamPokhriyal** [comment]
@onevcat 
Thanks for your response. Few concerns that I still have are:
1. About the screenshots you shared, for Kingfisher the highest memory usage is 31Mb whereas for SDWebImage it is 16mb. This is just for 1 image, you can image what will happen in a tableview full of images.
2. Apart from that, another major concern **even when you press back button the memory usage won't go down for Kingfisher**, it would still be the same but thats not the case with SDWebImage. 
I read through the cheat seat which mentions that I can restrict the cache limit, explicitly clear all the contents of the cache and change the expiration time. These might help me but I don't know about the sideeffects I will face after changing those parameters. Maybe if I clear cache too soon, it would re-download the images too often which again is a issue.  

That sample is really simple. In my app, I have a tableViewController which contains atleast 1 imageview per cell. And whenever I open that controller the memory usage jumps to 100mbs and it even increases on scroll, but the worst part is the memory doesn't come down even after pressing the back button. And if I open another instance of the same controller with different data the memory goes to the point where the app crashes. And that is really a problem.

I can't understand why the memory usage won't go down even when the imageview is not in the view hierarchy.

About the heavy image part, I just used a sample image from internet to demonstrate the issue. In my app the images are the ones that are captured via iPhone and it can be HD or UHD anything and we already have a compression algorithm in place.

**Comment by onevcat** [comment]
> 1. About the screenshots you shared, for Kingfisher the highest memory usage is 31Mb whereas for SDWebImage it is 16mb.

As I indicates, SDWebImage is using ImageIO to decode the downloaded data, but Kingfisher is using Core Graphics. ImageIO will hold the pixel data in its own process, that's the reason it is not counted as your process, but it actually exists and takes memory. So you should not only check the memory shown under your process but also check the free memory. You will find either Kingfisher or SDWebImage is using almost the same memory on your device.

> you can image what will happen in a tableview full of images

Please take a look at my last sentence:

> As you are showing a very big image, it takes a lot of memory. If these images are for a table view cell, I suggest you use the built-in downsampling processor to make a smaller version of the image before it gets into memory. You can read and follow [this tip](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#using-downsamplingimageprocessor-for-high-resolution-images) to know more on this topic.

There is also [a demo scene](https://github.com/onevcat/Kingfisher/blob/master/Demo/Demo/Kingfisher-Demo/ViewControllers/HighResolutionCollectionViewController.swift) in this repo, which shows how to download and display thousands of high-resolution images in a table view. Please remember to check that.

> 2. even when you press back button the memory usage won't go down for Kingfisher

The images are cached to memory as well by default. If you did not change anything, it takes [at most 25%](https://github.com/onevcat/Kingfisher/blob/master/Sources/Cache/ImageCache.swift#L242-L245) memory of your device. When you click the back button, the memory would still be in memory if the purge condition is not met.

You can also try to [set the limit of memory cache yourself](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#set-limit-for-cache). Maybe you can make it a smaller number and check the result. If the memory still keeps going up unbound, then there must be either an issue in Kingfisher or a memory retain in your code.

**Comment by robmontesinos** [comment]
I have a similar problem - great insight on ImageIO vs. Core Graphics - using SwiftUI. I have one List with 100 items and another with about 400 items. The product images are large but I'm just using the the smaller images - to see the larger image I am kicking the user out to their internet browser so I don't need to cache the large images, I'd like to cache the thumbnails. When I add DownsamplingImageProcessor I get "Use of unresolved identifier 'DownsamplingImageProcessor'" error. Pertinent code below:

`
import KingfisherSwiftUI

KFImage(URL(string: profileImageLink), options: [
                    .processor(DownsamplingImageProcessor(size: CGSize(width: 70, height: 70)))
                    .scaleFactor(NSScreen.main.scale),
                    .cacheOriginalImage
`

Am I missing something here? I'd appreciate your help

**Comment by onevcat** [comment]
@robmontesinos The `DownsamplingImageProcessor` is defined in module "Kingfisher" instead of "KingfisherSwiftUI", so you also need to `import Kingfisher`.

**Comment by robmontesinos** [comment]
@onevcat Thank you for the quick response. I added "import Kingfisher" as well as you suggested and now I get "'View' is ambiguous for type lookup in this context."

I had this error earlier before making the above comment so I took import Kingfisher line out. 

Is there something I am doing wrong?

**Comment by onevcat** [comment]
You can either:

1. Only import the `DownsamplingImageProcessor` struct by: `import struct Kingfisher.DownsamplingImageProcessor`

or 

2. Rename your `View` to `SwiftUI.View`.

I suggest 1.

**Comment by onevcat** [comment]
It is not your bad, but a Kingfisher back-compatible problem before SwiftUI introduced.

SwiftUI is using types name like `View`, `Image`. Unfortunately, it is also what Kingfisher named them from long before to simplify the cross-platform code: `typealias View = UIView` or `typealias View = NSView`. The name will be conflicting when you import the whole Kingfisher and SwiftUI at the same time.

**Comment by robmontesinos** [comment]
@onevcat Thank you for your prompt response. You are correct: item one above worked but introduced a new issue.

`
KFImage(URL(string: profileImageLink), options: [
                    .processor(DownsamplingImageProcessor(size: CGSize(width: 70, height: 70)))
                        .scaleFactor(NSScreen.main?.backingScaleFactor),
                    .cacheOriginalImage
                ])
`

The above gives error: "Expression type '[KingfisherOptionsInfoItem].Type' is ambiguous without more context"

I tried "import enum Kingfisher.KingfisherOptionsInfoItem" but that didn't work. I'm sorry to bother you again but would you mind taking a look? Thanks again

**Comment by onevcat** [comment]
Maybe you just need another `,` to make it work. Instead of 

```
KFImage(
  URL(string: profileImageLink), 
  options: [
    .processor(DownsamplingImageProcessor(size: CGSize(width: 70, height: 70)))
    .scaleFactor(NSScreen.main?.backingScaleFactor),
    .cacheOriginalImage
  ]
)
```

You need this:

```diff
KFImage(
  URL(string: profileImageLink), 
  options: [
-    .processor(DownsamplingImageProcessor(size: CGSize(width: 70, height: 70)))
+    .processor(DownsamplingImageProcessor(size: CGSize(width: 70, height: 70))),
    .scaleFactor(NSScreen.main?.backingScaleFactor),
    .cacheOriginalImage
  ]
)
```

**Comment by robmontesinos** [comment]
@onevcat Thank you so much - that did the trick. I wish SwiftUI had more accurate error messages. I should have caught that. Sorry to bother you - this library is a great piece of work. All the best.

**Comment by Klaudas** [comment]
Hey guys, this problem still exists. 

I was trying to load 1MB+ images in `UICollectionView`, used downsampling, but no luck. In the end switched to a different library
