### ISSUE TITLE
Image loading from cache too slow

### ISSUE THREAD

**Issue by gerryats** [onevcat/Kingfisher#1271]
I have a UITableview each cell loads an image when images are loading from cache tableview freezes for less than a second.

**Comment by onevcat** [comment]
It should not happen and we didn't receive any similar report of it.

Can you attach a sample project for it?

**Comment by Yamyee** [comment]
in tableviewCell,the same row ,if the first image loaded from disk ,the second image loaded from network,the network image will show first,then the image show from disk. cause the disk image loaded too slow, it should be cancel or Intercept
