### ISSUE TITLE
DefaultProcessor Fail when downloading a gif

### ISSUE THREAD

**Issue by choxxy** [onevcat/Kingfisher#1273]
Whenever I try to download a gif image it fails with the error below, the gif is 578kb only. What could be the cause and how do I fix it?

`processorError(reason: Kingfisher.KingfisherError.ProcessorErrorReason.processingFailed(processor: Kingfisher.DefaultImageProcessor(identifier: ""), item: Kingfisher.ImageProcessItem.data(67418 bytes)))`

**Comment by onevcat** [comment]
This error happens when the downloaded data cannot be processed with the given default image processor. It seems that the format is not supported or the image is broken. Can you paste the failing image here or give me the URL? So I can have a try with it maybe.

**Comment by kodsanati** [comment]
Hi, I have the same problem. The image is here: https://storage.googleapis.com/ninastale_assets/IMG_5969-icon.png

**Comment by tiendaik** [comment]
@onevcat Hi, currently I'm having same issue, but it's not gif image, just a simple jpg image, and it's only fail on some device (from my testing it's fail on iPhone 6 & 6s device, but success on iPhone 6+ & 6s+).
Here is image link, please check it
http://img1.xgaming.vn/xgame/images/avatar/20200706/4NxEiWftEf2Rz2hy.jpg
(on Android it's load normal too)

**Comment by onevcat** [comment]
@tiendaik This is not a JPEG image, but a WebP image. It is not supported internally in Kingfisher on iOS 13 or earlier. 

From iOS 14, Apple adds the system-level support of WebP image in `UIImage`, that is why your image can be loaded on some devices (with iOS 14), but failed on others.

To add support for WebP images on all iOS versions, please check [this wiki page](https://github.com/onevcat/Kingfisher/wiki/FAQ#can-i-load-some-special-image-format-like-webp).

**Comment by tiendaik** [comment]
> @tiendaik This is not a JPEG image, but a WebP image. It is not supported internally in Kingfisher on iOS 13 or earlier.
> 
> From iOS 14, Apple adds the system-level support of WebP image in `UIImage`, that is why your image can be loaded on some devices (with iOS 14), but failed on others.
> 
> To add support for WebP images on all iOS versions, please check [this wiki page](https://github.com/onevcat/Kingfisher/wiki/FAQ#can-i-load-some-special-image-format-like-webp).

Thanks so much it worked!

**Comment by Deepjunctiontech** [comment]
@onevcat I am facing the same issue at both UItableviewcell as well as a single UIImage . The error is following 
---
ob failed: Processing image failed. Processor: DefaultImageProcessor(identifier: ""). Processing item: data(82154 bytes)
---
The Image link is https://mediafree1.zeroerp.com/ImportantMedia/DEMOSCHOOL/homework/images/dbf77385bafc43a94a0cea6c8ccf9681360f1f2a16114044076.jpeg

This problem is visible in iphone 6 at ios 12.4.9 and iphone 6s 14.3 ,
In the simulator this works properly . 

Regards, Deep

**Comment by onevcat** [comment]
@Deepjunctiontech 

Accessing this link gives me this result:

```
{"code":"417","message":"ORGKEY Is Missing"}
```

I guess it is either something is lack or the link itself is expired. So I cannot say what's going on now.

**Comment by GuruprasannaRao94** [comment]
@onevcat I am facing same issue with WebP image on WatchOS(7.1). Is WebP images are supported in WatchOS?

**Comment by onevcat** [comment]
No. It seems that the WebP is only default supported by system in iOS 14 and macOS 11. Loading it on watchOS 7 results in a failure so you still need a third party processor.

**Comment by YamunaChebolu** [comment]
@onevcat I am facing same issue with WebP image on tvOS(14.x). Is WebP images are supported in tvOS?
I am using Kingfisher 7.2.2 and I am able to download the images properly in iOS devices but the images are not downloading in tvOS 14.x. I am getting this error when I am trying to download it in tvOS 14.x 
Error: processorError(reason: Kingfisher.KingfisherError.ProcessorErrorReason.processingFailed(processor: Kingfisher.DefaultImageProcessor(identifier: ""), item: Kingfisher.ImageProcessItem.data(32644 bytes)))

Please respond me back ASAP.

**Comment by onevcat** [comment]
Seems tvOS does not contain native support for WebP, so it won't work there.

For this, I would still suggest [read this](https://github.com/onevcat/Kingfisher/wiki/FAQ#can-i-load-some-special-image-format-like-webp) and use things like [Kingfisher-WebP](https://github.com/yeatse/KingfisherWebP).

**Comment by fedorinovdmitry** [comment]
@onevcat Can you explain why i got this error: 
"processorError(reason: Kingfisher.KingfisherError.ProcessorErrorReason.processingFailed(processor: Kingfisher.DefaultImageProcessor(identifier: ""), item: Kingfisher.ImageProcessItem.data(25268 bytes)))" 
for image by https://my.licard.com/i/new_1920px%20-%201106px%20+1%25.png , please?

**Comment by onevcat** [comment]
![截屏2023-12-19 22 41 47](https://github.com/onevcat/Kingfisher/assets/1019875/b1cdd8a3-479e-42c3-bd64-738addfc1997)

@fedorinovdmitry I can load this image without any issue. Do you have some code snippet or reproducible steps? Are you using some customized image processors?

**Comment by fedorinovdmitry** [comment]
> ![截屏2023-12-19 22 41 47](https://private-user-images.githubusercontent.com/1019875/291603716-b1cdd8a3-479e-42c3-bd64-738addfc1997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTM3MzEsIm5iZiI6MTcwMjk5MzQzMSwicGF0aCI6Ii8xMDE5ODc1LzI5MTYwMzcxNi1iMWNkZDhhMy00NzllLTQyYzMtYmQ2NC03MzhhZGRmYzE5OTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTM0MzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFkZDg3MzQxMWVmYWZiMTBjN2Q0MzU5ZjIzMDI3ZmQ1MDAxZGE1YTZjYTAzYWM0Mzg4NGQzNDMxZDdhYTI2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7Vy9CWtak7TXUOUX2ZvlSstXtuOWk3MP0iDfQ25_fAs)
> 
> @fedorinovdmitry I can load this image without any issue. Do you have some code snippet or reproducible steps? Are you using some customized image processors?

Sorry to bother you, we just figured it out. We received a captcha instead of an image from this link from the app.
