### ISSUE TITLE
Adding Aspect Fit/Fill to DownsamplingImageProcessor

### ISSUE THREAD

**Issue by kevinvanmierlo** [onevcat/Kingfisher#1278]
I have a UICollectionView where cells load image from local storage. These images are taken by the camera, so I wanted to make them smaller so the UICollectionView will be faster. However it seems the DownsamplingImageProcessor always downsamples using Aspect Fit. If I add logs I see I pass the size of 182.5 with scale 2.0 to the DownsamplingImageProcessor. And I added a completion listener to see how big the image was (which was taken in portrait). The images are 102.5 x 182.5 with scale 2.0. The code is below:

```
self.imageView.kf.setImage(
                with: LocalFileImageDataProvider(fileURL: url),
                options: [
                    KingfisherOptionsInfoItem.processor(DownsamplingImageProcessor(size: boundsSize)),
                    KingfisherOptionsInfoItem.scaleFactor(UIScreen.main.scale),
                    KingfisherOptionsInfoItem.cacheOriginalImage
                ]
        ) { (result: Kingfisher.Result<RetrieveImageResult, KingfisherError>) -> Void in
            switch result {
                case .success(let value):
                    dLog("result image size: \(value.image.size) and scale: \(value.image.scale)")
                default:
                    break
            }
        }
```

But every UIImageView has Aspect Fill as content mode, so now every image is blurry because it is resized too small.

I saw that the ResizingImageProcessor does provide a mode for Aspect Fit/Fill. However if I use that it rotates my images. I'm not sure if I should open another issue for this?

**Comment by onevcat** [comment]
I believe it is not possible to implement the downsampling in an aspect fill way without introducing a performance issue. The `DownsamplingImageProcessor` uses `CGImageSourceCreateThumbnailAtIndex` underhood and it specifies the target size by setting [`kCGImageSourceThumbnailMaxPixelSize`](https://developer.apple.com/documentation/imageio/kcgimagesourcethumbnailmaxpixelsize?language=swift). It defines the larger side of the target size of downsampled images. It by default to behave as "aspect fit" to contain every pixel of the downsampled image. 

If we want to provide an aspect fill way, we have to read the data first to get its ratio, which is conflicting the purpose of the `DownsamplingImageProcessor`. To get an "aspect fill" behavior, maybe you can try to give a larger `boundsSize`.
