### ISSUE TITLE
Please add support for Swift Package Manager (Dependencies)

### ISSUE THREAD

**Issue by ethanwa** [onevcat/Kingfisher#1280]
Many people will be moving away from CocoaPods and Carthage and using Swift Package Manager (Dependencies). Can you please add support? Thank you!

**Comment by MarcSteven** [comment]
@ethanwa  It support SPM. I think you should read it here([swift package manager usage](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#creating-a-library-package)

**Comment by RobertEmoji** [comment]
It's possible to import Kingfisher into Xcode project with Xcode 11 and Swift package manager, but it produces an error: 

```
AppKit is not available when building for iOS. 
Consider using `#if targetEnvironment(macCatalyst)` to conditionally import this framework when building for Mac Catalyst.
```
Kingfisher -> Sources -> Extensions -> NSButton + Kingfisher.swift -> Line 28 "import AppKit"

**Comment by onevcat** [comment]
SPM support is added in "xcode11" branch. We will make a merge and new release for it after the new Xcode releasing. Before that, please specify that branch to add Kingfisher to your project.

**Comment by ethanwa** [comment]
Xcode 11 is now out.

**Comment by ralfebert** [comment]
When I fetch the package via Swift Package Manager in Xcode 11 final with the default settings I get version 5.7.1 which still fails with the error:

```
AppKit is not available when building for iOS Simulator. Consider using `#if targetEnvironment(macCatalyst)` to conditionally import this framework when building for Mac Catalyst.
```

Using the `xcode11` branch works as a workaround.

**Comment by onevcat** [comment]
@ralfebert 
I am releasing the new version now. Please wait for a while.
