### ISSUE TITLE
Indicator should support new UIActivityIndicatorView styles for dark mode

### ISSUE THREAD

**Issue by uncleho** [onevcat/Kingfisher#1283]
UIActivityIndicatorView has new .medium and .large properties, rather than .gray and .white. This is to deal with dark mode in iOS 13 -- so Indicator.swift should be updated to support this on iOS 13.

**Comment by onevcat** [comment]
This should be already added in the xcode11 branch. I will merge and release it eventually, but more tests are still needed so please use that branch for a while (and any feedback is welcome!)

**Comment by onevcat** [comment]
Oh, wait... I think it is not yet updated. I will try to give it a fix now.
