### ISSUE TITLE
Is there an option for a fallback url if loading failed?

### ISSUE THREAD

**Issue by tfonfara** [onevcat/Kingfisher#1284]
I checked the wiki but didn't find a solution for that flow:
1. Display local placeholder image ✅
2. Load image from url ✅
3. If url loading failed, try to download from an alternative url ❓

I found the `.onFailureImage()` option but this only takes an image as value. How would you implement this behavior? With the following code I think I can't be sure that `imageView` is still the "same" as for the initial `setImage()` call if e.g. this image view is inside a cell and this cell is being reused during the loading 🤔 

```
imageView.kf.setImage(with: url1, placeholder: placeholder, options: options) { result in
    switch result {
    case .success(let value):
        break
    case .failure(let error):
        if error.isInvalidResponseStatusCode {
            imageView.kf.setImage(with: url2, placeholder: placeholder, options: options)
        }
    }
}
```

**Comment by onevcat** [comment]
I think `.onFailureImage` is just for your purpose. The image view is bound to a task identifier internally, so you do not have to worry about it. If you find something is wrong, please reopen this and I can have a deeper look.

**Comment by onevcat** [comment]
Duplicated with #1245 

Now there is no way to do that directly.

For your case in reusing cells, maybe you can check with `error.notCurrentSourceTask`. It will be thrown before any other error now, which indicates that the image task is not that one issued by the current image view. So you can safely skip the completion callbacks with that error.

I think adding a fallback URL is something we can add as a new feature later.

**Comment by tfonfara** [comment]
All right, thanks! Tested this and it seems to be working with a little teak (need to keep the url replacement in memory otherwise it causes flickering). By checking the status code I implicit check also for not current source, so that should be fine then. Code for reference if anyone else comes across this case:

```
let urlToLoad = Blacklist.shared.isBlacklisted(url1) ? url2 : url1
imageView.kf.setImage(with: urlToLoad, placeholder: placeholder, options: options) { result in
    switch result {
    case .success(let value):
        break
    case .failure(let error):
        if error.isInvalidResponseStatusCode, urlToLoad != url2 {
            Blacklist.shared.markAsBlacklisted(url1, replacement: url2)
            imageView.kf.setImage(with: url2, placeholder: placeholder, options: options)
        }
    }
}
```

**Comment by denizaydemir** [comment]
How can we use exactly this approach in SwiftUI?

**Comment by denizaydemir** [comment]
Just solved my own question. in `onFailure`, I mutated the state used by `KFImage(URL(string: self.imageUrl)!)`. New urls can be fetched from network and passed to `onFailure` block by callbacks.
