### ISSUE TITLE
Add option to disable Disk cache TTL extending

### ISSUE THREAD

**Issue by makesource** [onevcat/Kingfisher#1286]
#### What

Maybe related with https://github.com/onevcat/Kingfisher/pull/1196.
But I wonder why not support this option in DiskCache.
I use both MemoryCache and DiskCache to optimize image load and works well in most of cases.
But when the image corresponds to static URL changed, Kingfisher never refresh cached image until extended expired date (which  updated every cache hit).
If the image frequently accessed, this expire date extends without limitation.
So that's why I need to control cache extend option in DiskCache.

If there's not similiar discussion on this topic, could I write a new PR on this?

**Comment by onevcat** [comment]
Yes, I agree that we can add the same feature for the disk cache. Can you please create a PR for that? Thanks!

**Comment by makesource** [comment]
resolve in PR https://github.com/onevcat/Kingfisher/pull/1287.
Thanks!
