### ISSUE TITLE
How to add  cornerRadius to placeholder image 

### ISSUE THREAD

**Issue by JiBaoBao** [onevcat/Kingfisher#1297]
When I use `RoundCornerImageProcessor(cornerRadius: cornerRadius)` to add cornerRadius，the placeholder image still has no cornerRadius。

**Comment by onevcat** [comment]
The image processor only works for the downloaded images. Kingfisher processes the image and store the final version to cache by default. So it does not work for the placeholder images.

You can choose either:

1. Apply the same `RoundCornerImageProcessor` to the placeholder image before you set your image view: 

`let roundCorneredImage = RoundCornerImageProcessor(cornerRadius: 10).process(item: .image(image)`

or

2. Set the `cornerRadius` of the image view layer to make all things inside it round-cornered [like this](https://stackoverflow.com/questions/25476139/how-do-i-make-an-uiimage-view-with-rounded-corners-cgrect-swift).
