### ISSUE TITLE
5.8.0 semantic versioning seems wrong?

### ISSUE THREAD

**Issue by Nooba** [onevcat/Kingfisher#1299]
Hello,

This is more of a heads up than an actual issue as the deed is done, but regarding the following changes in 5.8.0:

> Rename too generic typealias names in Kingfisher, to avoid conflicting with SwiftUI types. Original Kingfisher.Image is now Kingfisher.KFCrossPlatformImage. The similar rules are applied to other cross-platform typealias too, such as Kingfisher.View, Kingfisher.Color and more.

 I believe that this should have warranted an actual major bump as this could break some build, since these aliases were public. (Matter of fact, it did break mine). Even if it is a quick fix, if you want to properly apply semantic versioning, breaking things should only be done in major releases.

Thank you for your work.
Regards

**Comment by onevcat** [comment]
Hi, @Nooba 

Thanks for opening this! You are definitely right on this. It was really a trade-off between following semantic version strictly and giving fixes/new features to more users. I tried to follow the semantic version as much as possible, but I thought these typealiases change is so small and trivial. Based on these reasons, I just wanted to leave the next major version release to something bigger.

I am so sorry for the inconvenience it brought to you (and others affected). I should consider it more carefully and draw some experience from it. But now it is not easy to take the release back.

Thank you for your understanding.

**Comment by Nooba** [comment]
Yeah I wouldn't try to re-release it or change the version number or anything. This will totally do.
I just wanted to make sure this was in your mind for the next releases!

No worries.
Cheers

**Comment by onevcat** [comment]
Backward compatibility is brought back in 5.8.2. So you could just use your original code once you resolve your version to 5.8.2.

Ref: https://github.com/onevcat/Kingfisher/issues/1303
