### ISSUE TITLE
Feature: Is it possible to get somehow the cache size?

### ISSUE THREAD

**Issue by szuniverse** [onevcat/Kingfisher#13]
Hi

I think it would be great if somehow get the cache size in Mb?
Is it possible now or do you plan to implement it in the future?

**Comment by onevcat** [comment]
It is a feature in plan and will be added later.

**Comment by onevcat** [comment]
Added in #15

**Comment by onevcat** [comment]
Waiting for merge.

**Comment by szuniverse** [comment]
Nice! thanks!

**Comment by onevcat** [comment]
Merged.

Please use this to get cache files size in disk:

```swift
KingfisherManager.sharedManager.cache.calculateDiskCacheSizeWithCompletionHandler { (size) -> () in
    println("disk size in bytes: \(size)")
}
```

**Comment by szuniverse** [comment]
Thanks! its very useful! thanks again
