### ISSUE TITLE
Carthage binary not downloaded for 5.8.1

### ISSUE THREAD

**Issue by gotev** [onevcat/Kingfisher#1302]
When using Carthage and updating the library to 5.8.1, the binary release does not get downloaded and compilation from source is triggered every time. I think it's because the name of the zip in the release is `Kingfisher-5.8.1.zip` and Carthage expects `Kingfisher.framework.zip` and so fails to resolve it.

**Comment by onevcat** [comment]
From 5.8, Kingfisher does not provide the original .framework built by Carthage, but instead, providing it as `.xcframework` format. This is a generic and Apple supported way to distribute Swift package as binary. The new `Kingfisher-5.8.1.zip` contains xcframeworks now.

Carthage is trying to implement the support for xcframework (https://github.com/Carthage/Carthage/pull/2801), and after this feature done, you can use the xcframework.

**Comment by onevcat** [comment]
And there is also a related topic for CocoaPods, so the new format can be benefit for both package managers. https://github.com/CocoaPods/CocoaPods/issues/9148

**Comment by gotev** [comment]
Thanks fior the detailed explanation!

**Comment by onevcat** [comment]
Some more information. Currently, it seems that Carthage 0.33.0 fails to create the `.version` file for Kingfisher 5.8. It causes `--cache-builds` not recognizing the built cache and keeping building Kingfisher even it is already there.

There is an issue that tracks it https://github.com/Carthage/Carthage/issues/2882. I tried to build Carthage from the master branch and there Kingfisher can be cached without problem. So I guess a new Carthage release would fix that issue.
