### ISSUE TITLE
Kingfisher crashes when rendering a KFImage in SwiftUI

### ISSUE THREAD

**Issue by keyboard-clacker** [onevcat/Kingfisher#1306]
### Issue Description

I'm rendering a pretty basic KFImage with:
```swift
KFImage(URL(string: 'https://blah.com/some-image.jpg'))
```
and when I'm compiling the app, I'm getting this error:
<img width="747" alt="Screen Shot 2019-10-05 at 10 10 44 PM" src="https://user-images.githubusercontent.com/2652762/66263281-f3679d80-e7bd-11e9-9351-eb4090d80fae.png">

I'm a bit new to swift development, so pardon any ignorance on my end, but I have no idea how to solve this problem and I think it could possibly be an issue with this library? I'm using it correctly as far as I can tell

#### Reproduce

I think this should happen on any SwiftUI app. I installed KingfisherSwiftUI with the swift package manager and have tried 5.8.1 and 5.8.2. I had everything working fine on 5.8.1 and with ios 13.1.1, but I upgraded to ios 13.2 and I think that may be the cause of the crash.

#### Other Comment

Thanks for the great library! As someone that hasn't done much iOS dev yet, this has made it way easier with downloading images + displaying them.

**Comment by onevcat** [comment]
I believe it is a bug of current Xcode 11.2 beta. There is no clue why this happens and I suggest wait for another beta version. Until then, you can use Xcode 11.0 or 11.1 GM, in which it should work fine.

**Comment by keyboard-clacker** [comment]
Sounds good, thank you! Yeah I downgraded to 11.1 and it's working again

**Comment by yonaskolb** [comment]
Anyone know any workarounds for this? If I downgrade to 11.1 I get a compiler error somewhere else in SwiftUI 😄

**Comment by onevcat** [comment]
There is no workaround, the only thing would report this to Apple and wait for another beta.

>  I downgrade to 11.1 I get a compiler error somewhere else in SwiftUI

It should not happen. Maybe it is related to some ambiguous. I suggest you check #1305 to see whether it could help.

**Comment by onevcat** [comment]
The same issue still happens in Xcode 11.2 beta 2. I created an issue in Swift bug tracking system: https://bugs.swift.org/browse/SR-11604

I am reopenning it for a better tracking of this issue. Please comment there if there is any new information.

**Comment by pedrommcarrasco** [comment]
Any word on this?

**Comment by ismyhc** [comment]
I've just ran across the same issue with Xcode 11.2 beta.

**Comment by onevcat** [comment]
#1330 contains more detail on this issue, so it is tracked there instead.
