### ISSUE TITLE
使用Xcode11，短时间内调大量用kf.setImage，可能会出现progressBlock和completionHandler再也不会回调的问题

### ISSUE THREAD

**Issue by SoalHuang** [onevcat/Kingfisher#1309]
使用Xcode11, swift5.1。UICollectionViewCell内的UIImageView短时间大量内调用kf.setImage，可能会出现progressBlock和completionHandler再也不会回调的问题，除非完全退出App重新打开，也可能需要完全退出再打开多次尝试才能正常使用。

**Comment by SoalHuang** [comment]
public private(set) var taskIdentifier: Source.Identifier.Value? {
        get {
            let box: Box<Source.Identifier.Value>? = getAssociatedObject(base, &taskIdentifierKey)
            defer { objc_sync_exit(self) }
            objc_sync_enter(self)
            return box?.value
        }
        set {
        }


调试发现这里的objc_sync会严重拖慢加载速度，可能造成卡顿甚至崩溃，特别是在复用的cell上快速加载大量可能重复的图片的时候特别容易复现。
最后，AssociatedObject使用了spinlock_t，是不是没必要再使用objc_sync了。

**Comment by onevcat** [comment]
感谢反馈。这边需要再考虑一下怎么能把线程的问题解决掉..

**Comment by onevcat** [comment]
@SoalHuang Can you try #1310 to see whether your issue can be solved or not? Thanks!

**Comment by SoalHuang** [comment]
@onevcat Yes, #1310  fixed my issue. Thanks!

**Comment by onevcat** [comment]
Released in 5.9.0.
