### ISSUE TITLE
设置淡出效果后，此时在tableCell中刷新，淡出效果会再次出现

### ISSUE THREAD

**Issue by xiaoli-style** [onevcat/Kingfisher#1313]
设置淡出效果后，此时在tableCell中刷新，淡出效果会再次出现。有什么方法可以设置不再显示淡入淡出效果？

**Comment by SaveFree** [comment]
你可以 model 中 添加一个变量 来 控制

**Comment by onevcat** [comment]
By default, the transition should not happen again if the image is read from the cache. I also tried it in the demo app in this repo, but cannot reproduce this issue.

 @xiaoli-style Can you paste some code snippet, or are you trying to clean the cache before reloading the table view cells? I also suggest printing the `cacheType` of the result, to check where is it from (cache or network):

```swift
imageView.kf.setImage(url) { result in 
    switch result {
    case .success(let value): print(value.cacheType)
    case .failure(_): break
    }
}
```
