### ISSUE TITLE
downloader image 时， URLRequest 是否可以暴露给开发者，做http请求验签

### ISSUE THREAD

**Issue by leery** [onevcat/Kingfisher#1315]
protocol ImageDownloaderDelegate

func imageDownloader(_ downloader: ImageDownloader, willDownloadImageForURL url: URL, with request: URLRequest?)

上述方法，在imageview+kingfilsher  setimageWithUrl 方法拿不到当前request

**Comment by onevcat** [comment]
Maybe this would help? https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending
