### ISSUE TITLE
Multiprocessors - more than two? 

### ISSUE THREAD

**Issue by hugovanderlei** [onevcat/Kingfisher#1319]
Is there a way to use more than two processors?  I couldn't get this done. It would be better if we can pass an array of processors.

**Comment by onevcat** [comment]
Check this: https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#multiple-processors

**Comment by onevcat** [comment]
You should be able to concat as many as you want.

**Comment by onevcat** [comment]
Ah, maybe you still need some `()` now. We can improve it later.

```swift
let a = BlurImageProcessor(blurRadius: 12)
let b = RoundCornerImageProcessor(cornerRadius: 12)
let c = TintImageProcessor(tint: .black)
        
let processor = (a >> b) >> c
```

**Comment by hugovanderlei** [comment]
thanks!
