### ISSUE TITLE
VIew Reused Clean Image

### ISSUE THREAD

**Issue by jienice** [onevcat/Kingfisher#1323]
use this code to set image

`cell.imageView.kf.setImage(with: URL.init(string: icon))`

but imageView show image just before setted  when i set image like below:

` cell.imageView.image = uiimage(named: string)`

` cell.imageView.image = nil`

by the way, this happened a few times.

what should i do to clean image when the cell reused?

**Comment by affbedran** [comment]
This is described in detail on the Cheat Sheet wiki page.

Inside your reusable cell's code, you should override prepareForReuse() and call the following method: `cell.imageView.kf.cancelDownloadTask()`

That will prevent your images from being reused all over the place.

**Comment by onevcat** [comment]
@jienice I am not quite sure what did you do?

Do you mean you called `kf.setImage` from a URL and then tried to set the `image` of the same `UIImageView` with its plain setter (`cell.imageView.image = uiimage(named: string)`) ? If so, I guess it will show your named image for a while, then the downloaded image will be used to replace it.

As @affbedran said, if you want to stop the current downloading, you can just call the `cancelDownloadTask` on the image view. But in a more general case, Kingfisher will manage and handle the downloaded image by comparing whether it is the one expected by the image view. So in normal cases, you do not have to worry about the cleaning when reusing image view, but just set another new one with `kf.setImage` method.

Until I can know what exactly you want to do, there is no further suggestion I can give.

**Comment by sanjeetchand** [comment]
Hi how would this be implemented if my images are inside a uicollectionview which is inside a uitableview when cells are reused?

Do we somehow get a reference to the cells that have started the download task and cancel them from the tableviewcontroller?

Any help is greatly appreciated!

Thank you :)

**Comment by onevcat** [comment]
@sanjeetchand 

You can ignore this reuse problem and just call `kf.setImage` method for the image views inside a reused cell. Kingfisher will check the desired image URL and ensure only the image from last setting method be used and displayed. In this case, the previous `setImage` and all the tasks will continue and the images are downloaded and cached. For the same time, the completion handler will be called with a `notCurrentSourceTask` error for these "dropped" images.

If you want some optimization, a typical way is canceling the current downloading task when the cell is about to disappear. This is already covered in the [wiki page here](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#cancelling-unnecessary-downloading-tasks).

**Comment by onevcat** [comment]
I am closing this issue since no more information.
