### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by CheaterHu** [onevcat/Kingfisher#1325]
为什么不管是Image还是KFImage放到NavigationLink里面就只有一个蓝色色块，而不是显示图片？
```
NavigationLink(destination: DetailView()) {
     Image("test.jpg")
 }

NavigationLink(destination: DetailView()) {
               KFImage(URL(string: "https://github.com/onevcat/Flower-Data-Set/raw/master/rose/rose-1.jpg")!)
}
``` 
好像只要不是png的图片都会有问题

**Comment by onevcat** [comment]
Maybe you need to check the renderingMode modifier. https://developer.apple.com/documentation/swiftui/image/3269728-renderingmode
