### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-1002

### ISSUE THREAD

**Issue by samzhiwei** [onevcat/Kingfisher#1334]
出现error 
Error Domain=NSURLErrorDomain Code=-1002 "不支持的URL" UserInfo={NSLocalizedDescription=不支持的URL, NSErrorFailingURLStringKey=//img.alicdn.com/imgextra/i1/822280525/O1CN01bMfNLH1FkUUsFwICT_!!822280525.jpg_210x210.jpg

图片url是 img.alicdn.com/imgextra/i1/822280525/O1CN01bMfNLH1FkUUsFwICT_!!822280525.jpg_210x210.jpg
Chrome和Safair都能打开，是URL的问题么？求问有没什么办法能处理。

**Comment by onevcat** [comment]
It is not a valid URL without a protocol component. Please prefix it by `https:`.
