### ISSUE TITLE
Why is the highest version of pod import 4.10.0, I specify import the latest version number, pod prompt can not be found

### ISSUE THREAD

**Issue by nalna** [onevcat/Kingfisher#1347]

**Comment by onevcat** [comment]
Try `pod repo update` if you are still using old CocoaPods. And also check what did you specify for Kingfisher's version. To use version 5, you need `~> 5.0` eg.

**Comment by nalna** [comment]
Hello, I am sure that my local pod is the latest, and then I also searched. The version number returned by pod clearly has the latest version number, but when I specified the import version of 5.9.0, pod indicated that the current version could not be found

**Comment by onevcat** [comment]
The podspec of Kingfisher should be already submitted to CocoaPods [without problem](https://github.com/CocoaPods/Specs/blob/master/Specs/a/a/6/Kingfisher/5.9.0/Kingfisher.podspec.json). Personally, I am not an expert of CocoaPods and not quite sure about the steps what extract to check. So I believe you can get more help to ask it in the CocoaPods repo or Stackoverflow with a "cocoapods" tag...

**Comment by onevcat** [comment]
Could it be the required ios platform version? Kingfisher 5 supports from iOS version 10. So if your Podfile still wants iOS 9, there would be an error.

BTW, can you paste the detail of your error?

**Comment by nalna** [comment]
I see, I know where I made a mistake. Thanks for reminding me. IOS supported locally started from 9, but Kingfisher supported from 10, so I need to change my local version library
