### ISSUE TITLE
Same mistake

### ISSUE THREAD

**Issue by nalna** [onevcat/Kingfisher#1348]
/Users/dzx/Desktop/project_km/Pods/JXPhotoBrowser/Source/Kingfisher/JXKingfisherLoader.swift:10:8: Compiling for iOS 9.0, but module 'Kingfisher' has a minimum deployment target of iOS 10.0: /Users/dzx/Library/Developer/Xcode/DerivedData/YSJ_Project-gxhdtsjyrhshuwcfqtjmtxnjmkzy/Build/Products/Debug-iphoneos/Kingfisher/Kingfisher.swiftmodule/arm64-apple-ios.swiftmodule
I also reproduced this error after setting the version number to 10.0, including podFile and project version number

**Comment by affbedran** [comment]
Could you show us your podfile?

**Comment by onevcat** [comment]
Kingfisher requires iOS 10.0, so please check your project deployment target setting.
