### ISSUE TITLE
Could not load the "EXIF JPEG"

### ISSUE THREAD

**Issue by hazytint** [onevcat/Kingfisher#135]
After update to 0.17.0, some image could not load. 
Those image have the same magic bytes, is FF D8 FF E1, not the standard FF D8 FF E0. 
Like this [http://7xlw0s.com2.z0.glb.qiniucdn.com/FsNyIiOyfkYBKWBGuTTyAnXE9n7w]()

**Comment by onevcat** [comment]
Fixed in #136

**Comment by hazytint** [comment]
简单粗暴😂
