### ISSUE TITLE
ImageDownloader sessionDelegate crash

### ISSUE THREAD

**Issue by xuhongfei** [onevcat/Kingfisher#1357]
![image](https://user-images.githubusercontent.com/3990919/69779288-73b8e680-11e2-11ea-94d5-fa3ac5c20dee.png)

**Comment by ArchieGoodwin** [comment]
The same thing for me

**Comment by xuhongfei** [comment]
@onevcat, could you help to resolve this issue? Thanks a lot!

**Comment by onevcat** [comment]
I guess it is duplicated to #1330

**Comment by onevcat** [comment]
You can either 

1. Set `DEAD_CODE_STRIPPING = NO`, or
2. Use Xcode 11.3 (although still in beta), or 
3. Change to use CocoaPods/Carthage instead of SPM

to solve it.
