### ISSUE TITLE
Kingfigher SwiftUI

### ISSUE THREAD

**Issue by lehelmedves** [onevcat/Kingfisher#1360]
Hey guys,

- I've added the following to my pod file: pod 'Kingfisher/SwiftUI'
- I've run pod install
- I've added "import KingfisherSwiftUI" to my source file
- The module is not recognised in XCode

What am I doing wrong?

**Comment by onevcat** [comment]
When build against CocoaPods, it is a part of Kingisher instead, so you can just use `import struct KFImage` to get started and use `KFImage` to load from web.

**Comment by lehelmedves** [comment]
Thank you so much, this works perfectly!

**Comment by Jooc** [comment]
This issue perfectly helps helps me! Thanks!
