### ISSUE TITLE
Storing image to disk cache fails but return success when file name is not hashed

### ISSUE THREAD

**Issue by denisPoifol** [onevcat/Kingfisher#1361]
When storing image to diskStorage we end up calling :
```
func store(
            value: T,
            forKey key: String,
            expiration: StorageExpiration? = nil) throws
        {
```
which fails when trying to store with a key containing a '/' character, but still returns success.
the issue is due to the fact we are using 
`createFile(atPath path: String, contents data: Data?, attributes attr: [FileAttributeKey : Any]? = nil) -> Bool`
And when we take a look at foundation we can see this function is a compatibility function that returns true or false if the file created with success
```
    /* These methods are provided here for compatibility. The corresponding methods on NSData which return NSErrors should be regarded as the primary method of creating a file from an NSData or retrieving the contents of a file as an NSData.
     */
```
Unfortunately I cannot find which method creating a file returns a NSError as mentioned in the above commentary.
It would be best to call this function but in the case we cant checking the boolean resulting from the `createFile(atPath path: String, contents data: Data?, attributes attr: [FileAttributeKey : Any]? = nil) -> Bool` function before returning success would be a good step forward.

**Comment by onevcat** [comment]
I guess Apple means [this method](https://developer.apple.com/documentation/foundation/data/1779858-write), which can give you an error when it encounters an error. I will check whether it is good or not to use this instead.

**Comment by onevcat** [comment]
Seems we cannot migrate to the `Data.write` method without loosing some features. Now the file manager also takes responsibility for setting the file attributes, which are later used to verify the disk cache.

We cannot change the current implementation before we can find a better one.

**Comment by denisPoifol** [comment]
If we cannot move to `Data.write` method maybe we could check the return boolean of the `createFile`method and raise a generic error if it not true.
The error will not be explicit but at least we will not be returning a success when in fact the file creation failed.

**Comment by onevcat** [comment]
@denisPoifol Yes, you are right.

**Comment by onevcat** [comment]
@denisPoifol Can you review the PR #1364, in which an error should be thrown when this happens.
