### ISSUE TITLE
JPEG compression quality fixed at 1.0

### ISSUE THREAD

**Issue by marco-palumbo** [onevcat/Kingfisher#1362]
https://github.com/onevcat/Kingfisher/blob/15fc36194a3b31ffbfe3e02322175d2af23e9da5/Sources/Image/Image.swift#L243

It would be nice if the JPEG compression quality could be parametric.

I'd be happy to fix this issue, but I'm not sure where's the best place to add the parameter.

**Comment by onevcat** [comment]
Thanks for it. I don't think it is a bad idea to add it.

But before that, may I know some context? Are you trying to use this API directly or use it from somewhere else?

**Comment by marco-palumbo** [comment]
Sorry, you're right: I've been too concise.
In the meanwhile, I've taken a deeper look into the code and realized that the issue is broader than what I was initially thinking.

### Context
I'm using Kingfisher in a collection view to display unprocessed thumbnail images. For the full-size images, I don't use Kingfisher. I do cache on disk all the images: Kingfisher's cache for thumbnail and my cache for full images. All images are JPEG.

### Issue
Looking at the file size of the cached images, I've noticed that the size of thumbnails was often bigger than that of the full images.
Digging into the code, I found out that unprocessed images are never saved using their original _data_.

https://github.com/onevcat/Kingfisher/blob/15fc36194a3b31ffbfe3e02322175d2af23e9da5/Sources/General/KingfisherManager.swift#L335-L336

They are always re-compressed with a compression quality of 1.0. That is what made me think that the compression quality should be parametrized. But, even if my initial proposal is still a valid enhancement, the real issue here is that there should be a way to cache the image original data even if it hasn't been processed.

**Comment by onevcat** [comment]
@marco-palumbo 

Umm. Yes, you are right, that could be a size problem. The current implementation follows a unified workflow, regardless of whether the image is processed or not. Maybe we can improve this by the combination of:

1. By default, if no processor is applied, we should prefer to cache the original data. This helps to prevent multiple compression of the image.
2. Providing an option to specify image quality when saving images as JPEG.

And before these can be applied, if it is urgent to you, I suggest you can create your own `CacheSerializer` and use it as an option to override current behavior. Could be something like this:

```swift
public struct OriginalDataCacheSerializer: CacheSerializer {
    public func data(with image: KFCrossPlatformImage, original: Data?) -> Data? {
        return original
    }
    
    public func image(with data: Data, options: KingfisherParsedOptionsInfo) -> KFCrossPlatformImage? {
        return KingfisherWrapper.image(data: data, options: options.imageCreatingOptions)
    }
}

imageView.kf.setImage(with: url, options: [.cacheSerializer(OriginalDataCacheSerializer())])
```

**Comment by marco-palumbo** [comment]
Thank you @onevcat for adding the feature!
