### ISSUE TITLE
Are there any plans for supporting full fledged videos in the future?

### ISSUE THREAD

**Issue by AlanCPSC** [onevcat/Kingfisher#1369]
Hello there, and thank you for maintaining this great library.

I know that the library already currently supports animated `.gif` files to a certain extent. I was wondering if there are currently any plans for supporting the singular/looping playback of full fledged video files such as (`.mp4` and `.webm`) in the future.

**Comment by onevcat** [comment]
The video totally belongs to another domain and I guess a streaming behavior might make sense for that. So I cannot see a possibility to add that to Kingfisher currently. 

Sorry for that!
