### ISSUE TITLE
使用RoundCornerImageProcessor画出圆角图片后，缓存到磁盘的image有白色背景

### ISSUE THREAD

**Issue by zyvv** [onevcat/Kingfisher#1370]
`RoundCornerImageProcessor(cornerRadius: width, targetSize: CGSize(width: w, height: h),  backgroundColor: nil)` 生成的图片在内存中是透明圆角，但是程序退出后再次进来，从磁盘读取的缓存图片，圆角背景变成了白色。

**Comment by onevcat** [comment]
#1279 #968

**Comment by zyvv** [comment]
谢谢！
