### ISSUE TITLE
All images flicker when tableview reloadData

### ISSUE THREAD

**Issue by LeaderBoy** [onevcat/Kingfisher#1377]
How to reproduce this problem?

1. All `UITableViewCell` finishes loading images normally

```swift
newsImageView.kf.setImage(with: url,placeholder: #imageLiteral(resourceName: "placeholder_small"),options: [.transition(.fade(1)),.cacheOriginalImage])
```

2. push to a new `ViewController` 

```swift
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    /// 1.push to a new controller
    
    /// 2.
    tableView.reloadData()
}
```

3. pop 
4. lock the iPhone (this is the most critical step)
5. reopen the iPhone and click the cell,all images will flicker

**Comment by onevcat** [comment]
When you lock your phone, the app will go background and Kingfisher will try to purge the memory cache it is using (to release as much memory as possible so your app will not likely to be killed in background). After that, when you load these images again, it will be fetched from disk by default, which is an async behavior to prevent UI thread lag. It causes this flicker.

I believe adding the [`loadDiskFileSynchronously`](https://onevcat.github.io/Kingfisher/Enums/KingfisherOptionsInfoItem.html#/s:10Kingfisher0A15OptionsInfoItemO25loadDiskFileSynchronouslyyA2CmF) would prevent this flicker with some trade-off of UI thread lagging (if you are not loading a lot of images at the same time, it can be ignored.).

**Comment by LeaderBoy** [comment]
It works, thank you

**Comment by oStarlyChen** [comment]
Thank you, this is really workable to me !

**Comment by JeremyHuang37** [comment]
Thanks a lot, it's works to me
