### ISSUE TITLE
Can not load some JPGs with using "kf_setImageWithURL"

### ISSUE THREAD

**Issue by britzlieg** [onevcat/Kingfisher#138]
Hey , 
I try to the use function "kf_setImageWithURL" to load a jpg from the network，but it can not show the jpg correctly. So I check the of Kingfisher source code and find out that Kingfisher use the magic code to define jpg file type. And I check the wiki  (https://en.wikipedia.org/wiki/List_of_file_signatures) and another article (https://billatnapier.wordpress.com/2013/04/22/magic-numbers-in-files) about jpg magic code .The two articles show the different about the standard of the JPG file magic number defining.The Wiki standard use FF D8 FF E0 and the article use FF D8 .So I doubt that which standard is the real standard of JPG magic number. If I use the magic number standard of Kingfisher , the function "kf_setImageWithURL" wil not load the jpg from "http://a.hiphotos.baidu.com/image/pic/item/9c16fdfaaf51f3de649a327897eef01f3a297986.jpg".  If I change Kingfisher source to fit the standard of the article, it work well.

**Comment by onevcat** [comment]
Please update to 1.7.1 and have a try.

**Comment by britzlieg** [comment]
1.7.1 fixed the bug.
