### ISSUE TITLE
failed to implement Kingfisher by carthage

### ISSUE THREAD

**Issue by sariminapp** [onevcat/Kingfisher#1387]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x ] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x ] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.

### Issue Description

I followed Kingfisher installation guide on https://github.com/onevcat/Kingfisher/wiki/Installation-Guide, but after On your application targets’ “General” settings tab, in the “Linked Frameworks and Libraries” section, drag and drop each framework you want to use from the Carthage/Build folder on disk. Error appear : 
"ld: /Users/myusername/Desktop/myprojectname/Carthage/Build/iOS/Kingfisher.framework/Kingfisher compiled with newer version of Swift language (unknown ABI version 0x07) than previous files (unknown ABI version 0x06) file '/Users/myusername/Desktop/myprojectname/Carthage/Build/iOS/Kingfisher.framework/Kingfisher' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

How to fix it so that error did not appear again?

#### What
Error ->
"ld: /Users/myusername/Desktop/myprojectname/Carthage/Build/iOS/Kingfisher.framework/Kingfisher compiled with newer version of Swift language (unknown ABI version 0x07) than previous files (unknown ABI version 0x06) file '/Users/myusername/Desktop/myprojectname/Carthage/Build/iOS/Kingfisher.framework/Kingfisher' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

#### Reproduce

After last step -> $(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Kingfisher.framework
, error appear, so I try to know from where error started. so, it started after this step -> On your application targets’ “General” settings tab, in the “Linked Frameworks and Libraries” section, drag and drop each framework you want to use from the Carthage/Build folder on disk. and before this step -> /usr/local/bin/carthage copy-frameworks

**Comment by onevcat** [comment]
Do you have multiple Xcode versions installed? Are you using the same version of Xcode command line tool as the Xcode you are opening to add Kingfisher?

**Comment by sariminapp** [comment]
> Do you have multiple Xcode versions installed? Are you using the same version of Xcode command line tool as the Xcode you are opening to add Kingfisher?

I only have one xcode versions. I am using same version of Xcode command line tool as the Xcode I am opening to add Kingfisher

**Comment by onevcat** [comment]
Any chance to try how it can work in a new project with the same steps? BTW, may I know the Xcode version and carthage version you are using?

Thanks!

**Comment by sariminapp** [comment]
> Any chance to try how it can work in a new project with the same steps? BTW, may I know the Xcode version and carthage version you are using?
> 
> Thanks!

xCode version 10.1, carthage version 0.34.0. I tried but no chance to make it work.

**Comment by onevcat** [comment]
Ummm, I guess it might be something related to the SwiftUI support of Kingfisher. Xcode 10 does not have an idea of how to build the lastest version of Kingfisher. Can you try to restrict the version of Kingfisher like this in your Cartfile, before you have a chance to upgrade to Xcode 11?

```
github "onevcat/Kingfisher" == 5.7.0
```

**Comment by sariminapp** [comment]
<img width="642" alt="Screen Shot 2020-01-31 at 16 51 35" src="https://user-images.githubusercontent.com/31340076/73529855-fc097100-4449-11ea-8ab9-133000119c59.png">

I use version 5.7.1

**Comment by sariminapp** [comment]
> Ummm, I guess it might be something related to the SwiftUI support of Kingfisher. Xcode 10 does not have an idea of how to build the lastest version of Kingfisher. Can you try to restrict the version of Kingfisher like this in your Cartfile, before you have a chance to upgrade to Xcode 11?
> 
> ```
> github "onevcat/Kingfisher" == 5.7.0
> ```

after I change to version 5.7.0 and update carthage, the error still exist

**Comment by sariminapp** [comment]
<img width="573" alt="Screen Shot 2020-01-31 at 17 02 33" src="https://user-images.githubusercontent.com/31340076/73530660-80a8bf00-444b-11ea-94aa-f7d3a3285bad.png">

I found this when switch back to version 5.7.1

**Comment by onevcat** [comment]
It is normal to skip the prebuilt framework and fallback to a source build. Does the build finishes without problem? Are you still getting the same ABI error when linking?

I am afraid it is not probably a problem in Kingfisher, but the environment of your machine and tool chain issue...

**Comment by sariminapp** [comment]
> still getting the same ABI error when linking

I am still getting the same ABI error when linking when change to version 5.7.0

**Comment by onevcat** [comment]
![50B56DF3-3270-4359-A11B-DEA7534CF6D1](https://user-images.githubusercontent.com/1019875/73531573-13eaf000-445e-11ea-86a0-ea11ba56cfd1.png)

According to this, Xcode 10.1 ships with Swift 4.2.4. But your Carthage is using Swift 5.0.1 when building Kingfisher. I suggest you check and make sure you are using the same Xcode version and command line tool version.

**Comment by sariminapp** [comment]
I ever use Kingfisher with my another project with xCode 10.1 and set swift version of the target to swift 3, and it works. but that time I use cocoapods, not carthage.
