### ISSUE TITLE
load from image and not imageview

### ISSUE THREAD

**Issue by MauMaxxa** [onevcat/Kingfisher#139]
Hi, is there a way to make Kingfisher download a remote image and put it in mi UIImage, insted of UIImageView? 

Thank you

**Comment by onevcat** [comment]
You can always use the components in Kingfisher separately. Maybe you could have a look at the `ImageDownloader` type.

**Comment by MauMaxxa** [comment]
Sorry i dont know how to do it, could you please help me? 
Thank you

**Comment by onevcat** [comment]
You could find some example in the test files: https://github.com/onevcat/Kingfisher/blob/master/KingfisherTests/ImageDownloaderTests.swift

**Comment by MauMaxxa** [comment]
Thank you, work done!

Have a nice day!
