### ISSUE TITLE
aws s3 image processing swift

### ISSUE THREAD

**Issue by Anil-093** [onevcat/Kingfisher#1391]
how to use kingfisher to load images in colliectionview. Currently i have my image files in S3 bucket protected folders. I can download the images using aws identitiy id and file name key. But i want to use kingfisher to handle the caching. Done adding custom headers in request but nothing downloads

**Comment by onevcat** [comment]
I am not quite familiar with AWS S3 bucket myself. But according to [this doc](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html) it seems that you may need an `Authorization` header in the request to get a protected resource.

What are you doing now? Are you using any other SDK or how did you download the images now?
