### ISSUE TITLE
Bug: Download from https 

### ISSUE THREAD

**Issue by szuniverse** [onevcat/Kingfisher#14]
Hi 

I try to download an image:
https://i.scdn.co/image/15b2aeb2ffbe7e279b438d47f6a21d5768f3da9d
This is an image url from spotify api request.

I get this error:
NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813

I know the solution if you use NSURLConnection:

   func connection(connection: NSURLConnection, canAuthenticateAgainstProtectionSpace protectionSpace: NSURLProtectionSpace) -> Bool {
        return protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust
    }
    

    func connection(connection: NSURLConnection, didReceiveAuthenticationChallenge challenge: NSURLAuthenticationChallenge) {
        if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
            let credentials = NSURLCredential(forTrust: challenge.protectionSpace.serverTrust)
            challenge.sender.useCredential(credentials, forAuthenticationChallenge: challenge)
        }
        challenge.sender.continueWithoutCredentialForAuthenticationChallenge(challenge)
    }

**Comment by onevcat** [comment]
Thanks for reporting. Challenge is not implemented now. I will add it later.

**Comment by onevcat** [comment]
Hi, @szuniverse 
I just tested your url and it seems work for me well. The site is well certificated and I believe the problem would be the date and time setting of your test devices/simulators. If you set them correctly, Kingfisher should work well for it.

And I also plan to add an interface for the certification challenge in case of someone needs self-signed certification support later. But it would be at a lower priority.

**Comment by szuniverse** [comment]
Okey, it would be great the self-signed cerf support! I am waiting...
I dont know whats wrong with my environment because everything looks good..

**Comment by onevcat** [comment]
Added in #21. Wait for merging.

**Comment by onevcat** [comment]
Merged. You can now use `trustedHosts` of `ImageDownloader` to skip the self-signed host.

```
KingfisherManager.sharedManager.downloader.trustedHosts = Set(["i.scdn.co"])
```

for example.

But it is not recommended unless you know what this means. It would be better to get a certification from a CA.

@szuniverse And I believe you have no need to use this for i.scdn.co, there should be something else wrong with your environment.

**Comment by szuniverse** [comment]
you are awesome! thanks!
