### ISSUE TITLE
Add a just round corner processor?

### ISSUE THREAD

**Issue by longjianjiang** [onevcat/Kingfisher#1404]
Right now, we have `RoundCornerImageProcessor` to set image round corner. 

But sometimes, some image like avatar just need round effect, and we don't know network image original size, `cornerRadius` param set is not correct, we also need set `targetSize`.

So, is it necessary to add a new processor to handle above condition?

**Comment by rogerfanfan** [comment]
like this?  
Set cornerRadius on view.
https://stackoverflow.com/questions/44675108/kingfisher-3-0-ios-swift-roundcornerimageprocessor-white-background

**Comment by onevcat** [comment]
Sorry for the late reply but it is now implemented in #1443. I will find a time to merge and release this feature.
