### ISSUE TITLE
AnimatedImageView CPU usage

### ISSUE THREAD

**Issue by Elshad** [onevcat/Kingfisher#1407]
When using AnimatedImageView CPU usage always shows at least 1-2%, but when using UIImageView there is 0% CPU usage

**Comment by onevcat** [comment]
The `AnimatedImageView` is trying to not decoding all frames to memory at once. Instead, it only decodes and keeps the next several frames. So it needs to decode new frames while playing current ones. By doing that, `AnimatedImageView` is using much less memory than a plain `UIImageView`.

So basically it is a trade-off between memory and CPU.
