### ISSUE TITLE
Can't save round Corner image?

### ISSUE THREAD

**Issue by zzzzzyijie** [onevcat/Kingfisher#1414]
version : 5.12.0

here is my code : 
          .....
      
        let info = [.processor(RoundCornerImageProcessor(cornerRadius: 10),.transition(.fade(1))]
        self.kf.setImage(with: URL(string: imgUrl)!,options: info)
       
         .....

but i check sandbox , the image is like this  (the corner is white ? ): 

![e6b383787c93b0fc4cbbc251a6dc5cb9](https://user-images.githubusercontent.com/17098514/77194535-1e02a400-6b1b-11ea-8d83-20421a8f050d.png)

Am i missed some setting?

**Comment by zzzzzyijie** [comment]
![WX20200321-022816](https://user-images.githubusercontent.com/17098514/77194847-a1bc9080-6b1b-11ea-95dd-8e58b7e307e7.png)

**Comment by zzzzzyijie** [comment]
when the  backgroudColor is white , it looks ok.
but in dark mode , it's very obviously~

**Comment by onevcat** [comment]
Please check this: https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#serializer-to-force-a-format

**Comment by zzzzzyijie** [comment]
thanks a lot!
