### ISSUE TITLE
Store image to disk do not work after update from v1.6.x to v1.7.x

### ISSUE THREAD

**Issue by little2s** [onevcat/Kingfisher#142]
Hi, onevcat(miao da da ^ ^):
I found that the API  `storeImage(image: UIImage, originalData: NSData? = nil, forKey key: String)` of `ImageCache` class did't work if the caller do not set `originalData` parameter.
The reason why is the block below:

... ...
        if toDisk {
            dispatch_async(ioQueue, { () -> Void in
                let imageFormat: ImageFormat
                if let originalData = originalData {
                    imageFormat = originalData.kf_imageFormat
                } else {
                    imageFormat = .Unknown
                }
                
                let data: NSData?
                switch imageFormat {
                case .PNG: data = UIImagePNGRepresentation(image)
                case .JPEG: data = UIImageJPEGRepresentation(image, 1.0)
                case .GIF: data = UIImageGIFRepresentation(image)
                case .Unknown: data = originalData
                }
                
                if let data = data {
                    if !self.fileManager.fileExistsAtPath(self.diskCachePath) {
                        do {
                            try self.fileManager.createDirectoryAtPath(self.diskCachePath, withIntermediateDirectories: true, attributes: nil)
                        } catch _ {}
                    }
               ... ...

The `originalData` is nil, so the `data` is always `nil`, the save block will never be called.

So if Kingfisher want to keep the API, it may be implemented like this:

  ... ... 
   public func storeImage(image: UIImage, originalData: NSData? = nil, forKey key: String) {
        let data = originalData ?? UIImagePNGRepresentation(image)
        storeImage(image, originalData: data, forKey: key, toDisk: true, completionHandler: nil)
    }
   ... ...

What do you think? Looking forward to your reply.

Thank you very much,
little2s.

**Comment by onevcat** [comment]
Oh, sure. You are correct. I will handle it later.

**Comment by onevcat** [comment]
Fixed in #148
