### ISSUE TITLE
Use Kingfisher as a dependency inside  dynamic package

### ISSUE THREAD

**Issue by iTarek** [onevcat/Kingfisher#1427]
### Issue Description

I include Kingfisher as a dependency for my local package, My  package is dynamic to avoid Xcode 11.4 problems when include the KingFisher last release 5.13.3 - Dynamic SPM, The application crash with error can not find framework

products: [
        .library(
            name: "MyPack",
            type: .dynamic,
            targets: ["MyPack"]
        )
    ],
    dependencies: [
        .package(url: "git@github.com:onevcat/other.git", .exact("1.1.4"))
        .package(url: "git@github.com:onevcat/Kingfisher.git", .exact("5.13.3"))
    ]

#### What

Everything works good if I used Kingfisher 5.13.2

#### Reproduce

Just include Kingfisher 5.13.3 inside dynamic package

#### Other Comment

We need a version of Kingfisher still not using Dynamic or a solution for dev who need to include as dependency inside a dynamic package

**Comment by onevcat** [comment]
See #1426

**Comment by iTarek** [comment]
> Create a wrapper dynamic framework, then add the plain Kingfisher to it, expose necessary methods from Kingfisher there, then import the framework into other targets like your main app or extensions. (In other words, wrap the SPM Kingfisher library in your own dynamic framework, and import the dynamic framework everywhere else).

I am using this solution but this works if Kingfisher was static but now you changed it to dynamic, it works but app crash when run because It can not find Kingfisher

What is the solution for that after you changed the Kingfisher to dynamic?

**Comment by onevcat** [comment]
It now (in the master branch) exposes all kinds of build configurations, including the static variant. Can you check and use the `KingfisherStatic` target instead?

**Comment by onevcat** [comment]
(Or just the original `Kingfisher`, which is reverted back to an `.automatic` build, if you trust SPM's choice of linking method.)

**Comment by iTarek** [comment]
> It now (in the master branch) exposes all kinds of build configurations, including the static variant. Can you check and use the `KingfisherStatic` target instead?

I am sorry I do not know how to include variant

Can you show me how to change this?
.package(url: "git@github.com:onevcat/Kingfisher.git", .exact("5.13.2"))

**Comment by onevcat** [comment]
1. Update the `.exact("5.13.2")` to something like `.branch("master")` (until I have time to tag a release for the latest changes).
2. Update your `MyPack` target, mark the dependency to KingfisherStatic (or just keep Kingfisher as long as you did step 1)

```
.target(
  name: "MyPack",
  dependencies: ["KingfisherStatic"],
  // ...
)
```

I didn't try it myself.

**Comment by basememara** [comment]
I ended up having to specify the exact commit to grab that change until master is tagged (can you please tag it when you get a chance?):

```
    dependencies: [
        .package(url: "git@github.com:onevcat/Kingfisher.git", .revision("16e6ec9b42263adf6bdaa6ddb7716bd5236d7b63"))
    ]
```

I also posted about this in the Swift forums:
https://forums.swift.org/t/specify-dependencies-should-be-built-as-dynamic-or-static/35257

**Comment by basememara** [comment]
Actually this may not be the correct way to handle this: https://forums.swift.org/t/specify-dependencies-should-be-built-as-dynamic-or-static/35257

> The duplicate entries in your example cannot co‐exist at runtime, and hence invite trouble by letting the package graph decide what to do... The right thing to do here is to declare only the automatic one. Any client that specifically cares should create their own package which links however many dependencies they want into an explicitly .dynamic or .static library of their own.

**Comment by onevcat** [comment]
I have tagged the current master with a 5.13.4 version.

I really wish I could only provide the automatic version for the library in Package.swift. But actually SPM (or Xcode) is not doing well as they declared when picking up the correct/desired linking style. It would be always a static linking and cause a diagnostic error. Sometimes the diagnostic error is telling the truth (but without providing a direct solution), and sometimes even worse, it is a false positive.

I hope we can revert back to the `.automatic` way soon if Xcode can solve this issue.

See #1426 for more detail.
