### ISSUE TITLE
Thumbnails tend to be resized after downloaded

### ISSUE THREAD

**Issue by imadeit** [onevcat/Kingfisher#143]
Hi, recently I start to use the library to fetch thumbnail of customized UITableViewCell.
I set the contentMode of  UIImageView of the thumbnail to .ScaleAspectFit in storyboard and give it a fixed size, but after following call:
```
        cell.imageView?.kf_showIndicatorWhenLoading = false
        cell.imageView?.kf_setImageWithURL(cellObj.thumbnailUrl!, placeholderImage: UIImage(named: "thumb120x120"))
```
( the image size indicated by cellObj.thumbnailUrl may be bigger than the placeholder image size)
the UIImageView extended over the original size, much wider than the thumbnail UIImageView, making the layout of UITableViewCell ugly.

Is there any option to refrain such kind of behavior? 

Thanks!

**Comment by eclipsegst** [comment]
In case anyone else has this problem, there's a default image with name "imageView" in UITableViewCell. You can try to use a different name for your custom UIImageView. Make sure to set your customImageView.layer.masksToBounds = true.
