### ISSUE TITLE
Add the ability to parse response data when errors happen

### ISSUE THREAD

**Issue by tony-hoang999** [onevcat/Kingfisher#1441]
### Issue Description
With the current ImageDownloaderDelegate methods, it is not possible to parse the response data in case an error happens, says 404.
In my case, I'd want to parse the data (in HTML format) to extract the error.

It'd be nice if this is make possible.

Cheers,
Tony Hoang

**Comment by onevcat** [comment]
Hi,

By default, Kingfisher expects the response has the correct status code (200..<400) to continue to download the data. So, if the initially received response contains an invalid HTTP status code (such as 404), Kingfisher will just cancel the request.

To change this and receive all data, you need to first make the status code as valid by implementing [the `isValidStatusCode` delegate method](https://github.com/onevcat/Kingfisher/blob/master/Sources/Networking/ImageDownloaderDelegate.swift#L99).

Then, you can try [this delegate method](https://github.com/onevcat/Kingfisher/blob/master/Sources/Networking/ImageDownloaderDelegate.swift#L72)? It should contain the actual data of the response. Maybe you can verify the data here to see if it is a valid image or some other data (such as an HTML).

---

Or,

If you have control for your own server, maybe it would be a much better idea to contain some error information (such as a sub error code, etc) in the response header, then inspect [this method](https://github.com/onevcat/Kingfisher/blob/master/Sources/Networking/ImageDownloaderDelegate.swift#L50-L54), where you can get the response object in the error like this:

```swift
func imageDownloader(
    _ downloader: ImageDownloader,
    didFinishDownloadingImageForURL url: URL,
    with response: URLResponse?,
    error: Error?) {

    if let kfError = error as? KingfisherError, case KingfisherError.responseError(.invalidHTTPStatusCode(let response)) = kfError {
        response.allHeaderFields["sub-error-code"]
    }
}
```
