### ISSUE TITLE
BlurImageProcessor(blurRadius: 4)

### ISSUE THREAD

**Issue by pengzhiqiang110** [onevcat/Kingfisher#1442]
let processor = BlurImageProcessor(blurRadius: 4)
 cell.titleImageView.kf.setImage(with: URL(string:userphoto), placeholder: UIImage(named: "mouren"), options:[.processor(processor),.forceRefresh], progressBlock: nil, completionHandler: nil)
我这样设置模糊效果 但是在iPhone8plus 13.3.1 系统上  列表中有些图片加上模糊效果了 但是有的没有 这是为什么呢?

**Comment by tlb-xiongju** [comment]
@pengzhiqiang110 
嗨，你好！
问题解决了吗？

单看你给出的代码，是没有问题的。
如果还没有解决，你能把该`ViewController`中，用到`Kingfisher`的地方的代码都贴出来看下吗？

**Comment by onevcat** [comment]
Since there is no further feedback on this issue, I am closing it now. If the issue is still there unresolved, feel free to reopen it for more discuss.
