### ISSUE TITLE
FREE YouTube VIDEO TUTORIAL

### ISSUE THREAD

**Issue by rebeloper** [onevcat/Kingfisher#1445]
Hi,
Love Kingfiser. So I made a 36 minutes long YouTube tutorial explaining it: https://youtu.be/5_oiKPCplew

Feel free to add it to the README / Documentation / Cheat Sheet with this image [people tap on images more than on boring links :) ]
![kingfisher-swift-tutorial](https://user-images.githubusercontent.com/2488011/81195114-182b2a00-8fc6-11ea-9c3a-b6433858cba3.jpeg)

Hope you like it. I'm open to any feedback.

**Comment by onevcat** [comment]
Oh, thanks!

It is so nice to see this and I really like the tutorial and it looks great at the first look. I will check it in detail to make sure everything is fine, then I can find a good place for the image and link! 

(Maybe I also need to resize the image a bit to make it fit other content in the documentation)

**Comment by onevcat** [comment]
@rebeloper I added the image and link to the getting started wiki page here: https://github.com/onevcat/Kingfisher/wiki/Getting-Started-with-Kingfisher#tutorial

I hope it also helps you! Thank you!

**Comment by rebeloper** [comment]
Excellent! Thank you
