### ISSUE TITLE
can this project work with objective-c?

### ISSUE THREAD

**Issue by shams-ahmed** [onevcat/Kingfisher#145]

**Comment by onevcat** [comment]
I guess the answer is no. There are some types not subclass of `NSObject` so it might not be compatible with Objective-C. I suggest you use [SDWebImage](https://github.com/rs/SDWebImage) or [YYImage](https://github.com/ibireme/YYImage) instead if you need to target for Objective-C project.

**Comment by fraserscottmorrison** [comment]
While Objective C won't work directly with Kingfisher, its easy to create an intermediary swift class/extension so myclass.m -> myextension.swift -> Kingfisher
