### ISSUE TITLE
please update jQuery version to 3.5.0 in docs

### ISSUE THREAD

**Issue by adin283** [onevcat/Kingfisher#1453]
we scan code with white source.It seems docs use jQuery 3.4.1 which report  Security Vulnerability. So please update the jQuery versin to latest 3.5.1. Scan result below:

### Description:
In jQuery versions greater than or equal to 1.2 and before 3.5.0, passing HTML from untrusted sources - even after sanitizing it - to one of jQuery's DOM manipulation methods (i.e. .html(), .append(), and others) may execute untrusted code. This problem is patched in jQuery 3.5.0.

### Top Fix
Upgrade to version jQuery - 3.5.0
2 more fixes available
The reported vulnerability was not checked for vulnerability effectiveness and is suggested to be examined using Effective Usage Analysis.

**Comment by onevcat** [comment]
The doc is now generated by SwiftDocs and this should not be an issue any more.
