### ISSUE TITLE
Some url can't show image

### ISSUE THREAD

**Issue by applepeopletsai** [onevcat/Kingfisher#1454]
Hi, I face to a very strange issue
Most url to show image by this library is fine
But some url can't show image like this url:
"https://qn.feijing88.com/feijing-home/egame/image/20190914/9a201791ae004d5cb667e2b838adf5d3.jpg" 

I have no idea to how to solve this issue
Can anyone help?

**Comment by onevcat** [comment]
Although this is marked as a JPG in the file extension, it seems inside it is an SVG file, which is not built-in supported in Kingfisher. You may use another SVG library to parse this SVG data to image data, and then implement an [image data provider](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#creating-your-own-image-data-provider) to set the image with Kingfisher.

**Comment by applepeopletsai** [comment]
@onevcat 
 WOW!!!!
Thank you very much!

**Comment by applepeopletsai** [comment]
@onevcat 
Hi,
I found some other issue
When use the url "https://qn.feijing88.com/feijing-home/egame/image/20190121/584f7d5686124b9285f1f90f061ee1bb.png"
And use 'ImageProcessor' class to get image
In the 'process(item: ImageProcessItem, options: KingfisherParsedOptionsInfo)' function
The case goes to .data, not .image
My question is, why not go to .image case?

![截圖 2020-05-21 下午1 55 05](https://user-images.githubusercontent.com/19483534/82528134-aed11c80-9b6a-11ea-9ae4-4b3596d26d91.png)

**Comment by onevcat** [comment]
If you are implementing your own processor, the first processor will be called with `.data` item, which contains the original data downloaded from the source URL.

When implementing a processor, you need to consider both cases: one for receiving a data object and convert it to a target image, another for receiving an image object and process on it (do some transformation or effects, etc).
