### ISSUE TITLE
variable name ambiguous

### ISSUE THREAD

**Issue by silenceleewq** [onevcat/Kingfisher#1456]
version: 5.14.0
file: ImageView+Kingfisher.swift
`let noImageOrPlaceholderSet = base.image == nil && self.placeholder == nil`, there is `&&`, so, I think the variable name `noImageOrPlaceholderSet` should be `noImageAndPlaceholderSet`

**Comment by onevcat** [comment]
no (image or placeholder) set
== no (imageSet or placeholderSet)
== (no imageSet) and (no placeholderSet)

But yes, it is a bit confusing. Let's change its name.
