### ISSUE TITLE
outlined retain of RoundCornerImageProcessor ()

### ISSUE THREAD

**Issue by SuperY** [onevcat/Kingfisher#1462]
### Issue Description
这个版本 v15.14.0 编译期间crash，回退版本后回复正常。
是否是这个#1443 的问题，或许是编译器Bug？

相关信息：https://forums.developer.apple.com/thread/115715

**Comment by onevcat** [comment]
I cannot reproduce any compiling error with the latest Kingfisher version and Xcode version.

Can you give me some hint on how this issue can be reproduced? (Maybe some steps or a sample project, etc.)

Thanks!

**Comment by SuperY** [comment]
新建Demo没能复显，工程中又用v15.14.0也无法复显了～
