### ISSUE TITLE
Only iPhone11 Series simulator in iOS13 + load very high pixel image failure

### ISSUE THREAD

**Issue by JerryFans** [onevcat/Kingfisher#1463]
如题，但是即使能显示内存会暴增。只有iPhone11系列 iOS13+模拟器，Xcode11.5,加载超高分辨率图片无法显示

try:

self.button.kf.setImage(with: URL(string: "http://image.jerryfans.com/post.jpg"), for: .normal)

我的解决方式类似SDWebImage的提前位图解压且释放可以显示并且内存能明显降低。

如下：
 case .JPEG:
            image = KFCrossPlatformImage(data: data, scale: options.scale)

KFCrossPlatformImage(data: data, scale: options.scale) 使用 ->  getBitmapImage() 解析，可以解决无法显示和内存问题，不过想问下有否有更好的解决方案？还是我的用法不对？请指出谢谢🙏

static func getBitmapImage(data: Data , options: ImageCreatingOptions) -> KFCrossPlatformImage {
        var decompressedImageRef: CGImage?
        var orientation: UIImage.Orientation?
        autoreleasepool {
            let image = KFCrossPlatformImage(data: data as Data, scale: options.scale)
            let imageRef = image?.cgImage
            orientation = image?.imageOrientation ?? .up
            let colorSpace = CGColorSpaceCreateDeviceRGB()
            let bitmapInfo = CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue).rawValue
            let context = CGContext(data: nil, width: imageRef!.width, height: imageRef!.height, bitsPerComponent: 8, bytesPerRow: 0, space: colorSpace, bitmapInfo: bitmapInfo)
            let rect = CGRect(x: 0, y: 0, width: imageRef!.width, height: imageRef!.height)
            context?.draw(imageRef!, in: rect)
            decompressedImageRef = context?.makeImage()
        }
        return UIImage(cgImage: decompressedImageRef!, scale: options.scale, orientation: orientation!)
    }

**Comment by onevcat** [comment]
I guess this is basically identical to adding a `.backgroundDecode` (https://github.com/onevcat/Kingfisher/blob/master/Sources/General/KingfisherOptionsInfo.swift#L100) to the option when loading an image. Maybe you can try that too.

And if you do not need to have to display such a high-resolution image (say, you just want to set it as a thumbnail, or to a fixed (cannot be zoomed by pinch gesture) image view, I suggest using a `DownsamplingImageProcessor` to resize it before loading into memory, which gives you much better performance. [Check this.](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#using-downsamplingimageprocessor-for-high-resolution-images)

**Comment by JerryFans** [comment]
This photo is a 1125 x 11348 pixel jpg image .  It's a scene like photo browser, is sure that resize it in thumbnail cell is OK, but's when I click to the full screen (kingfisher is cache the origin image ),It's still not display. But when I convert to PNG as same pixel It's can display !  How do I solve this problem? Or it the system bug's in iOS13+ & iPhone11 Series Phone? because another system or iPhone it's can display origin Image.

**Comment by onevcat** [comment]
That is a pretty large image! I have no idea on whether it is a bug in iPhone 11 with iOS 13, but if it works fine in other platforms/systems combination, that should be some internal change or memory constraint issue for that specific device. 

For that size of an image, I personally suggest you try to implement a tiling strategy, to only load the necessary part of the image. It is worth to make your app live and perform well for any size of images. Maybe check [this article for more](https://medium.com/frame-io-engineering/huge-images-small-phone-15414b30d39e).

**Comment by JerryFans** [comment]
Thanks, that a good idea by have a high perform ! But now I solve this issue by use BitmapCreate to decompress and auto release right away . May be like you said that some system or devices auto decode bitmap have a max limit cost. 
| |
fanjiarong_haohao
邮箱：fanjiarong_haohao@163.com
|

Signature is customized by Netease Mail Master

On 06/03/2020 21:15, Wei Wang wrote:

That is a pretty large image! I have no idea on whether it is a bug in iPhone 11 with iOS 13, but if it works fine in other platforms/systems combination, that should be some internal change or memory constraint issue for that specific device.

For that size of an image, I personally suggest you try to implement a tiling strategy, to only load the necessary part of the image. It is worth to make your app live and perform well for any size of images. Maybe check this article for more.
