### ISSUE TITLE
Image not shown in emulator - Even onSuccess was triggered

### ISSUE THREAD

**Issue by rongchaua** [onevcat/Kingfisher#1466]
Hi,
I'm facing a problem which I have no point how to solve it. I use Kingfisher for loading Image by URL.

In the preview the image has been loaded and shown correctly. The onSuccess has been also triggered when running with the simulator

<img width="1080" alt="Screenshot 2020-06-08 at 13 28 09" src="https://user-images.githubusercontent.com/6661713/84025624-394bb580-a98c-11ea-9af7-4ee2de1a0ac3.png">

But in the simulator, the images doesn't show up at all. 

<img width="281" alt="Screenshot 2020-06-08 at 13 33 19" src="https://user-images.githubusercontent.com/6661713/84025925-a9f2d200-a98c-11ea-9001-747cf4b88c13.png">

I'm not sure if Kingfisher needs any permission for storage on the simulator? Or do I miss something?

**Comment by onevcat** [comment]
It seems that you rendered these images as a template. Maybe it is set somewhere in your outer view or it is the default render mode for the container view. I guess adding a `.renderingMode(.original)` after the `KFImage` would solve your issue.

**Comment by rongchaua** [comment]
Thank @onevcat , setting .renderingMode(.original) solves my problem. I'm trying to understand what exactly happened with the .renderingMode setting.
