### ISSUE TITLE
How to get Progress when using ImageDownloader.default.downloadImage ?

### ISSUE THREAD

**Issue by ghost** [onevcat/Kingfisher#1468]
How to get Progress when using ImageDownloader.default.downloadImage

**Comment by onevcat** [comment]
There should be a progress block in the download image method, maybe you can use it to getting callback when the progress changes.

https://onevcat.github.io/Kingfisher/Classes/ImageDownloader.html#/s:10Kingfisher15ImageDownloaderC08downloadB04with7options13progressBlock17completionHandlerAA12DownloadTaskVSg10Foundation3URLV_SayAA0A15OptionsInfoItemOGSgys5Int64V_ATtcSgyAA6ResultOyAA0b7LoadingS0VAA0A5ErrorOGcSgtF

**Comment by MrJohnDo** [comment]
The method seems deprecated.

**Comment by MrJohnDo** [comment]
But anyway thanks for such an amazing library.
