### ISSUE TITLE
How to get the image disk path

### ISSUE THREAD

**Issue by HMWDavid** [onevcat/Kingfisher#1469]

**Comment by tlb-xiongju** [comment]
hi, @HMWDavid 

By default, `Kingfisher` uses `ImageCache.default` to save image in default caches directory.
you can get the path as following:
```swift
let path = ImageCache.default.diskStorage.directoryURL
```

if you just want to cache some images, you can custom `ImageCache` by specifying disk cache path:
```swift
let path: URL = ... // your disk path
let cache = try? ImageCache(name: "custom name", cacheDirectoryURL: path)
```

**Comment by HMWDavid** [comment]
Thank you
