### ISSUE TITLE
crash in assertionFailure("The image (under key: \(key) should be existing in the original cache.")

### ISSUE THREAD

**Issue by KXZHANGL** [onevcat/Kingfisher#1471]
Hello development team, I have encountered some problems in the use process, I hope to get answers. Crash occurred while setting the picture, iPhone system is 13.5.1, Kingfisher 5.13.4, thank you very much for your efforts

**Comment by tlb-xiongju** [comment]
Hi, @KXZHANGL 
Could you please show me your code ?

**Comment by onevcat** [comment]
There is an optimization in Kingfisher. When you apply a processor to an image, the final image will be stored in the cache of course. At the same time, you can choose to store the original image in the cache as well. Then, later if you are going to apply another processor to the same image, the downloading of the original image can be skipped and all things will be executed locally.

This error means the original image should be found in the cache, but actually not. It should not happen normally. Can you share some of your code and how/what you did to use the processors or other options?
