### ISSUE TITLE
SwiftUI KFImage render blue screen instead of url photos

### ISSUE THREAD

**Issue by denizaydemir** [onevcat/Kingfisher#1478]
Using specific links such as following makes `KFImage` render a blue view instead of target photo.

`KFImage(URL(string: "https://instagram.fist13-1.fna.fbcdn.net/v/t51.12442-15/e15/105419559_1790070907800061_1462317894495949500_n.jpg?_nc_ht=instagram.fist13-1.fna.fbcdn.net&_nc_cat=101&_nc_ohc=AubO_qFMUUgAX-8hSBw&oh=ae9bad572475f1ab8e46ef0d420e67b4&oe=5EF53120&ig_cache_key=MjMzODQ4NjMwMzgzMjYwMzkxMQ%3D%3D.2")!)`

Logs:
`success: RetrieveImageResult(image: <UIImage:0x2836eae20 anonymous {640, 1138}>, cacheType: Kingfisher.CacheType.disk, source: Kingfisher.Source.network(https://instagram.fist13-1.fna.fbcdn.net/v/t51.12442-15/e15/105419559_1790070907800061_1462317894495949500_n.jpg?_nc_ht=instagram.fist13-1.fna.fbcdn.net&_nc_cat=101&_nc_ohc=AubO_qFMUUgAX-8hSBw&oh=ae9bad572475f1ab8e46ef0d420e67b4&oe=5EF53120&ig_cache_key=MjMzODQ4NjMwMzgzMjYwMzkxMQ%3D%3D.2), originalSource: Kingfisher.Source.network(https://instagram.fist13-1.fna.fbcdn.net/v/t51.12442-15/e15/105419559_1790070907800061_1462317894495949500_n.jpg?_nc_ht=instagram.fist13-1.fna.fbcdn.net&_nc_cat=101&_nc_ohc=AubO_qFMUUgAX-8hSBw&oh=ae9bad572475f1ab8e46ef0d420e67b4&oe=5EF53120&ig_cache_key=MjMzODQ4NjMwMzgzMjYwMzkxMQ%3D%3D.2))`

**Comment by denizaydemir** [comment]
Turns out, NavigationLink items foreground color is replaced with blue.

**Comment by muhrifqii** [comment]
adding `.buttonStyle(PlainButtonStyle())` resolve the NavigationLink issue for me
