### ISSUE TITLE
Crash in navigation link Xcode 12

### ISSUE THREAD

**Issue by leversol** [onevcat/Kingfisher#1479]
Fatal error: Attempted to read an unowned reference but object 0x6000003bc6c0 was already deallocated
.onAppear { [unowned binder] in
            if !binder.loadingOrSuccessed {
                binder.start()
            }
        }

**Comment by devolaw** [comment]
For me, it is not a crash, but all images are failed to load. Below is the `body` of my view:

```swift
var body: some View {
        NavigationView {
            ScrollView {
                LazyVStack {
                    ForEach(appStore.timelineArticleStates) { articleState in
                        NavigationLink(destination: Text("\(articleState.title)\n")) {
                            VStack(alignment: .leading, spacing: 0) {
                                KFImage(articleState.coverURL)
                                    .resizable()
                                    .aspectRatio(Metric.imageAspectRatio, contentMode: .fit)
                                Text("\(articleState.title)\n")
                            }
                        }
                    }
                }
            }
        }
    }
```

**Comment by Tlz-1994** [comment]
> For me, it is not a crash, but all images are failed to load. Below is the `body` of my view:
> 
> ```swift
> var body: some View {
>         NavigationView {
>             ScrollView {
>                 LazyVStack {
>                     ForEach(appStore.timelineArticleStates) { articleState in
>                         NavigationLink(destination: Text("\(articleState.title)\n")) {
>                             VStack(alignment: .leading, spacing: 0) {
>                                 KFImage(articleState.coverURL)
>                                     .resizable()
>                                     .aspectRatio(Metric.imageAspectRatio, contentMode: .fit)
>                                 Text("\(articleState.title)\n")
>                             }
>                         }
>                     }
>                 }
>             }
>         }
>     }
> ```

Looks a lot like js ...

**Comment by onevcat** [comment]
The `unowned` was not used anymore for quite a few times. Maybe try to upgrade to the latest Kingfisher and the current Xcode 12 beta 4 to see again?

I also tried the code snippet above, and it also works fine for me. I guess it would also be related to some beta version of Xcode and suggest a re-confirm.
