### ISSUE TITLE
使用URL加载图片是报'DefaultImageProcessor'错误

### ISSUE THREAD

**Issue by Treasure1** [onevcat/Kingfisher#1482]
let url = URL(string: "http://51farm-upload.oss-cn-hangzhou.aliyuncs.com/upload-android/2020-07-02/20200702162552263e0a942cac0bb.jpg?x-oss-process=image/resize,m_fill,w_268,h_248")!
imageView.kf.setImage(with: url)

**Comment by onevcat** [comment]
This is a WebP image and not supported by default in Kingfisher. To process a WebP image, maybe try to check this repo: https://github.com/Yeatse/KingfisherWebP

**Comment by SuperY** [comment]
iOS14 貌似默认支持webp，Kingfisher是否考虑，对webp相关做支持并向下兼容？😄

**Comment by onevcat** [comment]
iOS 14 的支持更多的是在 Safari 里，iOS SDK 中并没有提供对应的支持，所以还是需要额外的相关的解析工作。为了避免引入（对于大多数用户来说）不必要的依赖和代码，可能暂时还是不会直接在 Kingfisher 里添加 WebP 的支持。上面提到的 KingfisherWebP 已经为需要的同学提供了足够的支持，建议还是继续使用那边。

**Comment by SuperY** [comment]
虽然iOS SDK没有明确说明，不过根据现在iOS14中直接使用UIImage(named: "image.webp")，已经可以正常显示。

或许可以考虑iOS14以上在接入而外工作的情况下做支持。

**Comment by SuperY** [comment]
而且现在开发来看，webp使用Kingfisher 在iOS14下可以显示，但是低版本就不行。
这样的功能不一致问题是否需要在Readme中提示下😊

**Comment by onevcat** [comment]
啊...是这样么，我可能需要研究一下...感谢这些提示和信息。

**Comment by alouanemed** [comment]
@onevcat Any updates to this? are we going to expect WebP support soon?  Thanks!

**Comment by onevcat** [comment]
@alouanemed 

Hi,

I checked the system WebP support and now I guess no. It is not a good choice to add it at least for now. 

If we want to add WebP support built-in the Kingfisher, it would bring a heavy dependency on all iOS versions. Until we can upgrade the deployment target to iOS 14, I think it is not a good choice to contain it in this library. After all, it is still not a de facto standard yet when choosing to show an image on the network.

There are quite a few nice solutions to support WebP in Kingfisher and I really suggest you check them if you need to show a WebP image. Such as https://github.com/Yeatse/KingfisherWebP

I think it would be much easier (and also suitable) to have system-WebP support there. I will prepare a PR to KingfisherWebP and see if it can be contained there.

**Comment by SuperY** [comment]
I'm using  [WebPImageSerialization](https://github.com/mattt/WebPImageSerialization). 
Is KingfisherWebP better?

**Comment by onevcat** [comment]
@SuperY 

I personally do not use WebP or either library in my own project. So I do not have a stand to say which is better. But at first glance, I guess if implemented properly, both should be identical since they are using the same Google's encoding/decoding library.
