### ISSUE TITLE
Kingfisher can not work on "use_modular_headers!"

### ISSUE THREAD

**Issue by DeveloperJx** [onevcat/Kingfisher#1484]
#### What

Kingfisher can not work on "use_modular_headers!"

#### Reproduce

I was using Xcode 11.5 (11E608c) and cocoapods(1.9.3) and Kingfisher 4.10.1 to fish my work.When I set "use_modular_headers!" mark on my podfile then build workspace.An error comes out that shows on "Kingfisher-umbrella.h".

Can't  find "Kingfisher.h" on "Kingfisher-umbrella.h".

When I set "Kingfisher.h" on Build Phases Public Headers problem solved.

#### Other Comment

Can MiaoShen just delete this file "Kingfisher.h" or set it to public headers in podspec file?

Thinks.

**Comment by onevcat** [comment]
I guess we'd better put it to public headers. Any chance to make a PR for it? Thanks!

**Comment by DeveloperJx** [comment]
Sure

**Comment by DeveloperJx** [comment]
Hi,MiaoShen!I think I figure out why it doesn't work for my workspace when I try to fix this problem on my fork repositories.I try to add "Kingfisher.h" to public headers settings in podspec file but I failure again.I find the CocoaPod would never set the "Kingfisher.h" on Build Phases Public Headers even if I have already add "Kingfisher.h"to public headers settings in podspec file.
I was using "generate_multiple_pod_projects: true" at the same time.I have a self pod library which depends on "Kingfisher".So,I guess may be I set Kingfisher to different subproject cause the problem like this:

`pod 'NeedKingfisher',git: 'http://xxxx.git',:project_name => 'A'
  pod 'Kingfisher', :project_name => 'SwiftFoundations', :modular_headers => false`

Then I put it to the same project problem solved like this:

`pod 'SomeThingNeedKingfisher',git: 'http://xxxx.git',:project_name => 'A'
  pod 'Kingfisher', :project_name => 'A', :modular_headers => false`

Kingfisher is running pretty good now.So I share this with you.Maybe we can add this case to WiKi or readme to remind developer who like me don't separate Kingfisher and it dependent to different project.Kingfisher is very good to save my time by the way!! 

PS: This is the last time what do I do to solve this problem and someone was send it to stackoverflow and ask for help.
[stackoverflow](https://stackoverflow.com/questions/30355133/swift-framework-umbrella-header-h-not-found)

**Comment by onevcat** [comment]
Thanks for sharing this! I'll investigate.

**Comment by bluerainxty** [comment]
i met the problem too @DeveloperJx ,can we discuss ti?

**Comment by bluerainxty** [comment]
@onevcat i think we dont need Kingfisher.h ,  alamofire also support carthage and cocoapods , but it doesnt have Alamofire.h

**Comment by onevcat** [comment]
Yes, we do not need it. I will check and remove that also.

**Comment by DKIND1080** [comment]
who are u guys
