### ISSUE TITLE
Processor not work when kingfisher load image from disk

### ISSUE THREAD

**Issue by HuuLiang** [onevcat/Kingfisher#1487]
I load an image with url.

```
extension UIImageView {    
    final func loadImage(url:String,placeholdImage:UIImage? = nil,size:CGSize,cornerRadius:CGFloat = 0) {
        var options:[KingfisherOptionsInfoItem] = [.cacheOriginalImage,.cacheSerializer(FormatIndicatedCacheSerializer.jpeg)]
        if cornerRadius > 0 {
            options.append(.processor(DownsamplingImageProcessor.init(size: size) |> RoundCornerImageProcessor.init(cornerRadius: cornerRadius)))
        } else {
            options.append(.processor(DownsamplingImageProcessor.init(size: size)))
        }
        self.kf.setImage(with: URL(string: url),
                         placeholder: placeholdImage,
                         options: options)
    }
}
```

when this code first run ,kingfisher load image from network,it work well
but when i restart the app,kingfisher load image from disk and the image has no RoundCorner

**Comment by onevcat** [comment]
You are using a jpeg cache serializer, which means you tell Kingfisher to store the image as JPEG format in disk. However, the round corner requires the alpha channel to be transparent in the corner section.

Try to use a `FormatIndicatedCacheSerializer.png` and it should be fine.

**Comment by MuYuLi** [comment]
@onevcat  I cropping a image ，when this code first run ,kingfisher load image from network,it work well，
but when i restart the app, kingfisher load image from disk and the image is not the cropping one 

```
public static let `default` = MHYCroppingImageProcessor()

    public let identifier: String

    public let heightWidthRatio: CGFloat
    public let anchor: CGPoint
    
    public init(heightWidthRatio: CGFloat = 0.8, anchor: CGPoint = CGPoint(x: 0.5, y: 0.5)) {
        
        self.heightWidthRatio = heightWidthRatio
        self.anchor = anchor
        identifier = "com.mihoyo.Kingfisher.CroppingImageProcessor(\(heightWidthRatio)_\(anchor))"
        
    }
    
    public func process(item: ImageProcessItem, options: KingfisherParsedOptionsInfo) -> KFCrossPlatformImage? {
        switch item {
        case .image(let image):
            let imageWidth = image.size.width
            let imageHeight = image.size.height
            guard imageWidth > 0, imageHeight > 0 else { return DefaultImageProcessor.default.process(item: item, options: options) }
            if CGFloat(imageHeight / imageWidth) * anchor.y > heightWidthRatio * 0.5 {
                let y = imageHeight * anchor.y - imageWidth * heightWidthRatio * 0.5
                let rect = CGRect(x: 0, y: y, width: imageWidth, height: imageWidth * heightWidthRatio)
                if let cgImage = image.cgImage?.cropping(to: rect) {
                    return UIImage(cgImage: cgImage)
                }
                return image
            }
            return KingfisherManager.defaultImageProcessor.process(item: item, options: options)
        case .data: return (KingfisherManager.defaultImageProcessor |> self).process(item: item, options: options)
        }
    }

```

**Comment by onevcat** [comment]
Kingfisher is using `identifier` to determine whether to apply the same processor or not. 

Can you make sure you have the same `identifier` in your different sessions?

**Comment by MuYuLi** [comment]
Thank you for your reply
I have some processors:  
newOptions.append(customeCroppingImageProcessor)
newOptions.append(defaultProcessor)

you mean these processors` identifier should be the same?

**Comment by onevcat** [comment]
I am not sure what the `newOptions` is in your snippet. But Kingfisher relies on both the cache key and the processor identifier (from the processor you pass into Kingfisher's option like `options: [.processor(someProcessor)]`) to compute the final cache key which will be used to retrieve the image from cache.

If you have a processor identifier when storing the downloaded/processed images, and then try to another identifier to get them, Kingfisher will think those images are not stored in cache. Then it will try to download the original image and then use the (new) processor to process/store it again.

So, that means if you want to reuse the processor, you need to keep its identifier consistent. Check the [wiki page](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#creating-your-own-processor) to know how to create your own processor. And there are quite [a few built-in examples](https://github.com/onevcat/Kingfisher/blob/master/Sources/Image/ImageProcessor.swift) in the current implementation.

**Comment by MuYuLi** [comment]
I understand. Thank you very much
