### ISSUE TITLE
图片url加了 ?x-oss-process=style/app_forum_detail_userpic 参数以后，调试的时候总数断点定位到ImageDownloader.swift的 如下代码标记【breakpoint位置】

### ISSUE THREAD

**Issue by xiaopindev** [onevcat/Kingfisher#1490]
#### What

> Task <6F24D6B1-23A3-4AB2-987F-D25A2C6043C7>.<1> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "请求超时。" UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x28128b870 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <6F24D6B1-23A3-4AB2-987F-D25A2C6043C7>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <6F24D6B1-23A3-4AB2-987F-D25A2C6043C7>.<1>"
), NSLocalizedDescription=请求超时。, NSErrorFailingURLStringKey=https://***.qq.com/app/android/2020/08/03/f7sdh1zFSALorPBcPZaQOiEQz2XVtcFr.png?x-oss-process=style/app_forum_detail_userpic, NSErrorFailingURLKey=https://***.qq.com/app/android/2020/08/03/f7sdh1zFSALorPBcPZaQOiEQz2XVtcFr.png?x-oss-process=style/app_forum_detail_userpic, _kCFStreamErrorDomainKey=4}

图片url加了 ?x-oss-process=style/app_forum_detail_userpic 参数以后，调试的时候总数断点定位到ImageDownloader.swift的
如下代码标记【breakpoint位置】

```swift
// Before processing the downloaded data.
do {
    let value = try result.get()   【breakpoint位置】
    self.delegate?.imageDownloader(
        self,
        didFinishDownloadingImageForURL: url,
        with: value.1,
        error: nil
    )
} catch {
    self.delegate?.imageDownloader( 【breakpoint位置】
        self,
        didFinishDownloadingImageForURL: url,
        with: nil,
        error: error
    )
}
```

这样开发调试很麻烦，能不能优化一下？ 或者如何解决这个调试总是定位断点出错问题地方？

#### Reproduce

[The steps to reproduce this issue. What is the url you were trying to load, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by onevcat** [comment]
I am not sure what do you mean by this... The debugger and its whole environment are on your machine. It should be not related to the library. I suggest you check your breakpoints list in Xcode to see if any breakpoint you set might cause it. There should be nothing to do in Kingfisher for this.

**Comment by xiaopindev** [comment]
> I am not sure what do you mean by this... The debugger and its whole environment are on your machine. It should be not related to the library. I suggest you check your breakpoints list in Xcode to see if any breakpoint you set might cause it. There should be nothing to do in Kingfisher for this.

请求这个：https://.qq.com/app/android/2020/08/03/f7sdh1zFSALorPBcPZaQOiEQz2XVtcFr.png  地址的时候，正常，Kingfisher无错误断点

请求：https://.qq.com/app/android/2020/08/03/f7sdh1zFSALorPBcPZaQOiEQz2XVtcFr.png?x-oss-process=style/app_forum_detail_userpic，带?Query参数的时候，Kingfisher就会调试的时候出现异常断点
