### ISSUE TITLE
Display a preview image from a video swift

### ISSUE THREAD

**Issue by Adakhan** [onevcat/Kingfisher#1491]
Hi, what about setting an image from a video?  I know there exist `AVAssetImageGenerator` for AVPlayer. But, I found it not flexible for my situation. I think if you make it, it will a good feature.

**Comment by onevcat** [comment]
Implemented in #1500

**Comment by Adakhan** [comment]
@onevcat Use of unresolved identifier 'kUTTypeJPEG'

**Comment by onevcat** [comment]
What's your platform/build target? The `kUTTypeJPEG` should be either in `MobileCoreServices` (iOS) or `CoreServices` (macOS) and the CI builds are passing without problem.

**Comment by Adakhan** [comment]
@onevcat yeah, you are right. I forgot to import `CoreServices` or `MobileCoreServices`
