### ISSUE TITLE
ImageProcessor Unavailable in SwiftUI

### ISSUE THREAD

**Issue by TonyTang2001** [onevcat/Kingfisher#1493]
- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [x] I want to report a problem instead of asking a question.

### Issue Description

ImageProcessor protocol is inaccessible if only KingfisherSwiftUI is imported to current scope. 

#### What

When using Kingfisher in SwiftUI by importing KingfisherSwiftUI, the ImageProcessor and all the related protocols, including DownsamplingImageProcessor, are unavailable. Thus, the **exact code in [Kingfisher SwiftUI Support](https://github.com/onevcat/Kingfisher/wiki/SwiftUI-Support#Options) would not work**. 

However, a workaround would be creating a processor instance elsewhere. As follows: 
- Create a new file
- ```import Kingfisher```
- Instantiate a ```DownsamplingImageProcessor```
- Use the instance in previously unavailable scope.

#### Reproduce(Issue Code)
```
import SwiftUI
import KingfisherSwiftUI

struct ContentView: View {

    // Some Codes

    var body: some View {
       KFImage(
            url,
            options: [
                .transition(.fade(0.2)),
                .processor(
                    DownsamplingImageProcessor(size: CGSize(width: 50, height: 50))   // Error: Cannot find 'DownsamplingImageProcessor' in scope
                ),
                .cacheOriginalImage
            ])
    }
}
```

#### Workaround Code
```
import SwiftUI
import KingfisherSwiftUI

struct ContentView: View {

    // Some Codes

    var body: some View {
       KFImage(
            url,
            options: [
                .transition(.fade(0.2)),
                .processor(
                    processor
                ),
                .cacheOriginalImage
            ])
    }
}
```

In another file:
```
import SwiftUI
import Kingfisher

let processor = DownsamplingImageProcessor(size: CGSize(width: 50, height: 50))
```

#### Inquiry for Fix

Although a workaround does exist, it exists as an ugly patch that introduces chaos to the overall structure of a project. Therefore a fix of KingfisherSwiftUI is politely requested. 

Thank you for your time and work!

**Comment by onevcat** [comment]
The processors are in the Kingfisher module. So you have to `import Kingfisher` to add it to your source.

However, maybe you have already known, Kingfisher contains some typealias like `View` and `Button`, which may conflict with SwiftUI's `View` and `Button`. To solve it, you can instead only import the type you need from Kingfisher, like:

```swift
import struct Kingfisher.DownsamplingImageProcessor
```

**Comment by TonyTang2001** [comment]
I did fail to import Kingfisher as a whole package because of the conflicts, didn't think of importing types...😅

Anyway, thank you for solving my issue in response such quick!
