### ISSUE TITLE
placeholder with gif

### ISSUE THREAD

**Issue by JonathanChen123** [onevcat/Kingfisher#1497]
is it support gif for placeholder?

**Comment by onevcat** [comment]
It is not built-in supported, but it is easy enough to implement it yourself by using a GIF image view that conforms to `Placeholder`.

1. Create your own view containing an image view that can show GIF.
2. Make it conform to `Placeholder`.
3. Set an instance of your own view as a placeholder in Kingfisher's method.

https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#showing-a-placeholder
