### ISSUE TITLE
It can't be installed by cocoapods

### ISSUE THREAD

**Issue by lmcmz** [onevcat/Kingfisher#150]
Did anyone meet the same issues?
Pod works well with other projects.
<img width="437" alt="screen shot 2015-11-11 at 7 40 39 pm" src="https://cloud.githubusercontent.com/assets/9669733/11090349/1fcee786-88ac-11e5-9043-8326784c8459.png">

**Comment by lmcmz** [comment]
It seem that the version 1.8 is no available now.

<img width="1178" alt="screen shot 2015-11-11 at 8 19 52 pm" src="https://cloud.githubusercontent.com/assets/9669733/11091007/b6aa70b2-88b1-11e5-9c7f-262cfecfaa8f.png">

**Comment by onevcat** [comment]
I believe you are using some outdated mirror of the pods repo. Please update it. I attached the screenshot of current CocoaPods spec repo.

![snip20151111_1](https://cloud.githubusercontent.com/assets/1019875/11091072/9121fd3e-88ba-11e5-9631-e21ae23c0fba.png)

**Comment by lmcmz** [comment]
OK, I'm gonna figure it out.
Btw, thanks to reply me. XD
See you in Chinese Swift Developer Conference.
 :)
