### ISSUE TITLE
加载图片调试的时候总是断点定位到ImageDownloader

### ISSUE THREAD

**Issue by xiaopindev** [onevcat/Kingfisher#1503]
加载的图片地址：https://static.maoti.com/app/admin/2020/06/23/24707746fc08c629ebacfeb92e5f7be638cd74a2.jpeg?x-oss-process=style/app_forum_listpic

加了 ?x-oss-process=style/app_forum_listpic 这个带参数的时候，调用Kingfisher加载图片会断点定位到 Kingfisher/Core/ImageDownloader.swift 文件的第274行代码 let value = try result.get() 

我的应用图片都加了，所以用xcode调试的时候总是定位到这里，很影响正常开发，这个有没有现成的方法解决或者你们能不能修复一下这个问题？ 

结果如下图：
![1599131109316](https://user-images.githubusercontent.com/2084285/92108030-4ce6ab00-ee19-11ea-93b3-84363eebdae2.jpg)

**Comment by onevcat** [comment]
The breakpoint is totally a thing in your development environment. I don't think it can be related to the framework from any aspect.

**Comment by xiaopindev** [comment]
> The breakpoint is totally a thing in your development environment. I don't think it can be related to the framework from any aspect.

我删除?x-oss-process=style/app_forum_listpic 这个图片参数， Kingfisher就不会出现调试断点

还是说我的加载图片的代码有问题？ 代码如下：
`//加载普通图
            let progressive = ImageProgressive(
                isBlur: true,
                isFastestScan: true,
                scanInterval: 0.1
            )
            self.kf.setImage(
                with: url,
                placeholder: UIImage(named: placeholder.rawValue),
                options: [.loadDiskFileSynchronously,
                          .progressiveJPEG(progressive)],
                progressBlock: { receivedSize, totalSize in
                    //PPLog("图片下载中：\(receivedSize)/\(totalSize)， 地址：\(String(describing: webUrl))")
                },
                completionHandler: { result in
                    PPLog("Finished \(result)")
            })`

**Comment by onevcat** [comment]
I suggest you check your breakpoint tab in Xcode to see what are the breakpoints you have been setting.

**Comment by onevcat** [comment]
Or run `breakpoint list` in LLDB to check what is the "breakpoint 1.1" is in the list, which stops your code.
