### ISSUE TITLE
Error to Build KingfisherSwiftUI 5.15.1 with XCode 11.7

### ISSUE THREAD

**Issue by pjcau** [onevcat/Kingfisher#1516]
Hi Guys, 

I have this error to build KingfisherSwiftUI 5.15.1 with XCode 11.7.+
Can you check it?

J

**Comment by danieleforlani** [comment]
same here...

**Comment by recon2710** [comment]
Same Here. Reference to property 'binder'

**Comment by hanksudo** [comment]
Check here:

https://github.com/onevcat/Kingfisher/issues/1508#issuecomment-694074159

**Comment by pjcau** [comment]
I fixed but I use Carthage in CI but it failed the pipeline. So it's necessary the new release.

**Comment by onevcat** [comment]
Fixed and released as 5.15.2 for this issue.
