### ISSUE TITLE
Swift Compile Error with Xcode 12

### ISSUE THREAD

**Issue by vulgur** [onevcat/Kingfisher#1520]
#### 

When build or run the project, I got the error `Could not find module 'Kingfisher' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64`.

I found the issue is similar to #1514 .

Installed by SPM and Xcode 12 version is 12A7209(official one, not GM)

**Comment by NikKovIos** [comment]
Also error: `Building for iOS Simulator, but the linked framework 'Kingfisher.framework' was built for iOS.`

**Comment by onevcat** [comment]
@vulgur Cannot reproduce it when building with Kingfisher installed by SPM.

Are you trying to work on an ARM Mac (the Developer Transition Kit)?

**Comment by vulgur** [comment]
I resolved this error by setting VALID ARCHS to $(inherited).
谢谢喵大!

**Comment by MobileMon** [comment]
Vulgar can you please explain further what you did? I'm having this same issue. Can you post screenshots of your build settings?

**Comment by vulgur** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/3339536/93882124-59706c00-fd12-11ea-870a-0e2f4b0b6e32.png">
@MobileMon
