### ISSUE TITLE
SwiftUI Error reference to property 'binder' in closure requires explicit 'self.' to make capture semantics explicit

### ISSUE THREAD

**Issue by jscubida** [onevcat/Kingfisher#1521]
#### What

When trying to view a live preview of a SwiftUI file, Xcode failed to build the scheme and reports the error in the title

#### Reproduce

Open a SwiftUI file and attempt to view a live preview

#### Other Comment

Version 5.15.1

**Comment by onevcat** [comment]
It should be fixed by #1515 and I will tag a new release for it soon.
