### ISSUE TITLE
无法解析图片

### ISSUE THREAD

**Issue by coderZjc** [onevcat/Kingfisher#1555]
使用kingfisher加载图片：https://cdnimg.chinagoods.com/jpg/2020/10/13/c3708748607584a255c7238c66efce9d.jpg?imageMogr2/thumbnail/400x|watermark/1/image/aHR0cDovL3l3bWFsbC0xMzAxNTYzNTAxLmNvcy5hcC1zaGFuZ2hhaS5teXFjbG91ZC5jb20vcG5nLzIwMjAvMTAvMTUvODAxNDA3NWFkNWQyZmQ5ZDE4NjljZDljZjk5YTFhN2IucG5n/blogo/1
图片无法显示出来，其他地址的图片都是可以正常显示的，想请问下原因？

**Comment by onevcat** [comment]
This seems to be a JFIF format image (quite rarely used format). I am not sure if it is supported in Kingfisher (maybe not). I will have a look at it later.

**Comment by coderZjc** [comment]
Fine,thank you

**Comment by onevcat** [comment]
This image is loaded nicely in the sample app. So I guess it is supported. Can you try to print the error in the completion handler and paste it here?

![截屏2020-10-15 16 28 23](https://user-images.githubusercontent.com/1019875/96090661-8542d400-0f03-11eb-829a-32f1e27e09e3.png)

**Comment by onevcat** [comment]
```swift
imageView.kf.setImage(
  //...
 completionHandler: { result in
    print(result)
  } 
)
```

**Comment by coderZjc** [comment]
the error in the completion handler is that ：Error Domain=Kingfisher.KingfisherError Code=5001 "The input resource is empty."

**Comment by onevcat** [comment]
Please check the input URL, to make sure you are not passing a `nil` to Kingfisher.

**Comment by coderZjc** [comment]
Please see how to use it in my code，I follow the official usage to write the code
pod 'Kingfisher', '~> 5.14.1'

![image](https://user-images.githubusercontent.com/24477024/96094049-70644180-0eff-11eb-918e-92ddec07b761.png)

**Comment by onevcat** [comment]
`|` is not a valid character in the URL. You are getting a `nil` by using that string. You can append a `!` to the URL (`URL(string: )!`) to expect a crash.

Try to encode your URL string to get a valid URL. Say, replace `|` to `%7C` in your example.

**Comment by coderZjc** [comment]
OK,thank you very much
