### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by RobertEmoji** [onevcat/Kingfisher#1562]
I get 36 errors, when I try to compile my project (simulator or device). 
It worked fine in the past, but I cannot get it to run anymore. 

Xcode Version 12.1 (12A7403)
Kingfisher 5.15.7 (installed with SPM)
iOS Deployment Target: iOS 11.2

Undefined symbols for architecture arm64:
  "(extension in Kingfisher):Kingfisher.KingfisherWrapper<A where A: __C.UIImageView>.indicatorType.setter : Kingfisher.IndicatorType", referenced from:
      Keyboard.StickerCell.configure(data: Keyboard.Sticker?) -> () in StickerCell.o
  "(extension in Kingfisher):Kingfisher.KingfisherCompatible.kf.setter : Kingfisher.KingfisherWrapper<A>", referenced from:
      Keyboard.StickerCell.configure(data: Keyboard.Sticker?) -> () in StickerCell.o
  "(extension in Kingfisher):Kingfisher.KingfisherWrapper<A where A: __C.UIImageView>.indicator.getter : Kingfisher.Indicator?", referenced from:
      Keyboard.StickerCell.configure(data: Keyboard.Sticker?) -> () in StickerCell.o
  "Kingfisher.DelayRetryStrategy.init(maxRetryCount: Swift.Int, retryInterval: Kingfisher.DelayRetryStrategy.Interval) -> Kingfisher.DelayRetryStrategy", referenced from:
      Keyboard.StickerCell.configure(data: Keyboard.Sticker?) -> () in StickerCell.o
...

**Comment by onevcat** [comment]
It is not likely to be an issue in Kingfisher. Try to:

- Clean your project.
- Clean the derived data.
- Reset Swift package manager cache and resolve the dependency again.
- Delete and re-add Kingfisher to your project.
- Check if any other settings are changed.

**Comment by RobertEmoji** [comment]
Thanks for your quick answer!

> * Clean your project.
> * Clean the derived data.
> * Reset Swift package manager cache and resolve the dependency again.
> * Delete and re-add Kingfisher to your project.

These points didn't solve the problem. 

> * Check if any other settings are changed.

I think there is a problem with some settings. When I create a new empty project in Xcode and import Kingfisher, everything works fine. But my old projects don't compile. I will try to find the wrong setting and post the solution here.

**Comment by RobertEmoji** [comment]
Now I have solved the problem.

My App contains a keyboard extension. And the Kingfisher library was removed from the keyboard target. 
After adding it, everything works fine again. (General -> Keyboard Target -> Frameworks and Libraries -> add Kingfisher)

Sorry for the troubles, it was my mistake.
