### ISSUE TITLE
Gif 图片内存暴涨，只涨不降

### ISSUE THREAD

**Issue by tianya2416** [onevcat/Kingfisher#1566]
加载gif 图片列表的时候，内存暴涨，一直降不下来，不知道有没有合适的处理方案。

**Comment by onevcat** [comment]
默认情况下读取的所有帧都会被缓存在内存里。建议先试试看使用 `AnimatedImageView`，它默认会在渲染期间再进行解码 （用 CPU 换内存）。如果不理想的话，尽量在保证 cell reuse 的情况下，去调用 `KingfisherManager.shared.cache.clearMemoryCache()`，或者在设置图片的时候使用加上 `.memoryCacheExpiration(.expired)` 来跳过内存缓存。
