### ISSUE TITLE
AnimatedImageView内的Animator能开放出来吗？

### ISSUE THREAD

**Issue by CaiChenghan** [onevcat/Kingfisher#1572]
**AnimatedImageView**内的**Animator**能开放出来吗？以**readonly**的形式也可以，因为想要读取里面的数据，例如gif执行总时间。

**Comment by danielebogo** [comment]
@onevcat +1
Is it possible to have the Animator public and exposed (with its properties and methods too)?

**Comment by afterxleep** [comment]
I was looking into this.  Without publicly accessing the animator is there a way to grab a specific frame of a GIF file?

**Comment by onevcat** [comment]
Yes, it could be useful. I am working on it now. Stay tuned.
