### ISSUE TITLE
Multiple commands produce error when trying to archive project

### ISSUE THREAD

**Issue by matantech** [onevcat/Kingfisher#1573]
Hi,
after adding KingFisher to app target and KIngfisherSwiftUi to widget target I'm getting the following error when trying to archive the project:

Multiple commands produce '/Users/matan/Library/Developer/Xcode/DerivedData/IPTV_Free-chhmzqmvionaxvgpqvwwrkbufwtp/Build/Intermediates.noindex/ArchiveIntermediates/IPTV Free/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Kingfisher.framework':
1) Target 'Kingfisher' has create directory command with output '/Users/matan/Library/Developer/Xcode/DerivedData/IPTV_Free-chhmzqmvionaxvgpqvwwrkbufwtp/Build/Intermediates.noindex/ArchiveIntermediates/IPTV Free/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Kingfisher.framework'
2) Target 'Kingfisher.default-SwiftUI' has create directory command with output '/Users/matan/Library/Developer/Xcode/DerivedData/IPTV_Free-chhmzqmvionaxvgpqvwwrkbufwtp/Build/Intermediates.noindex/ArchiveIntermediates/IPTV Free/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Kingfisher.framework'

I searched for multiple files but didn't found nothing
thanks

**Comment by onevcat** [comment]
May I know how did you add Kingfisher to your project? Does this help?

https://github.com/onevcat/Kingfisher/issues/1522

**Comment by onevcat** [comment]
The root cause is both `pod 'Kinfisher'` and `pod 'Kingfisher/SwiftUI'` is producing a library with the same name. I will see if there is anything I can do in podspec side. :(

**Comment by matantech** [comment]
I commented in the issue you linked, I tried the solution suggested there but got another error.

**Comment by onevcat** [comment]
@macecchi You are having a typo there, instead of `Kingfishser/SwiftUI`, you need `Kingfisher/SwiftUI`.

However, I would also try to check if there is anything I can do when different sub pod is used.

**Comment by onevcat** [comment]
Here is some more discussion of this problem:

https://github.com/CocoaPods/CocoaPods/issues/8206
http://www.superarts.org/blog/2020/06/11/a-cocoapods-problem

An ideal solution is CocoaPods providing a syntax to specify a different product name for subspec target. However, I doubt whether it would be on their To-Do list.

Another obvious solution is just combining the SwiftUI support into the main target, making them a unified one. Since we are moving on to a new major release, it is a perfect time to do so and make less pain in the future. I am going to check how it can work.

**Comment by onevcat** [comment]
By the way, before that (Kingfisher v6), the workaround of using `Kingfisher/SwiftUI` in both your main app target and extension target should do the trick. @matantech

**Comment by onevcat** [comment]
> Another obvious solution is just combining the SwiftUI support into the main target, making them a unified one. Since we are moving on to a new major release, it is a perfect time to do so and make less pain in the future. I am going to check how it can work.

This will happen when the release of new Kingfisher major version 6.

**Comment by onevcat** [comment]
Version 6 was released and this should not be an issue anymore.
