### ISSUE TITLE
Is Kingfisher capable and supposed to persist image in the disk? 

### ISSUE THREAD

**Issue by jevonmao** [onevcat/Kingfisher#1578]
While reading the documentation and Github page of Kingfisher, it implied that Kingfisher cache to both memory and disk. But when I used the KFImage, it is downloading the image again every time the app process is ended. I just want a clarification on whether Kingfisher is capable of caching or persisting an image to disk, without having to redownload it.

**Comment by onevcat** [comment]
I am quite sure the cache (both memory and disk) are working well on `KFImage`. In fact, it is reusing the same cache policy and classes which are already in use in Kingfisher for UIKit for years.

Kingfisher is doing the cache based on the URL by default. So I suggest checking if you are having exact the same URL between each app session. And please also make sure you are not calling `ImageCache.clearCache` or `ImageCache.clearDiskCache` between your app start.

**Comment by jevonmao** [comment]
My bad, I tested it again with a static unchanging URL, and KFImage was able to cache to disk. Thank you!
