### ISSUE TITLE
可以把diskStorage方法public吗，或者能直接获得图片，不通过回调。

### ISSUE THREAD

**Issue by orange7yz** [onevcat/Kingfisher#1597]
主要使用skphoto 的协议方法需要直接返回图片

**Comment by onevcat** [comment]
`diskStorage` is [already public](https://github.com/onevcat/Kingfisher/blob/master/Sources/Cache/ImageCache.swift#L159) and you can get the cached file URL by just calling its [`cahceFileURL` method](https://github.com/onevcat/Kingfisher/blob/master/Sources/Cache/DiskStorage.swift#L248-L259).

The disk storage is just a cache manager object for raw data. You need to calculate the cache key and convert the result to the actual data yourself, which might not be a trivial work.

Instead, I suggest you can try [the `retrieveImageInDiskCache ` method](https://github.com/onevcat/Kingfisher/blob/master/Sources/Cache/ImageCache.swift#L570-L588) with a `[.loadDiskFileSynchronously]` option. With that option, the completion handler should be called in the same runloop so you can return the result image in a sync way.

**Comment by orange7yz** [comment]
Thanks, I have obtained the local image address through cahceFileURL
