### ISSUE TITLE
Loading and cacheing of generated UIImage instead of from NSURL

### ISSUE THREAD

**Issue by RyanRamchandar** [onevcat/Kingfisher#160]
Is it possible to load a UIImage directly with Kingfisher instead of from a NSURL?

For example, I have a UITableView with an UIImageView that generates a map snapshot using MKMapSnapshotter. This returns a UIImage which I load into the UIImageView, however, when the table is scrolled the map snapshot is regenerated again and again which can take some time. Ideally this would be retrieved from the cache.

If this is possible how can it be done?

**Comment by onevcat** [comment]
You could always use `ImageCache` type standalone. Maybe something like this.

```swift
if ImageCache.defaultCache.isImageCachedForKey("your_key") {
    ImageCache.defaultCache.retrieveImageForKey("your_key", options: KingfisherManager.OptionsNone) { (image, type) -> () in
        cell.imageView.image = image
    }
} else {
    let image = //Generate your image
    cell.imageView.image = image
    ImageCache.defaultCache.storeImage(image, forKey: "your_key")
}
```

Of course, you could do some wrapping affairs for it yourself to make it easier.

**Comment by RyanRamchandar** [comment]
Thanks this works pretty well. Do all the same default cache constraints apply to this defaultCache as well? (eg. expiration)

Also, theres a small typo in your snippet. `isImageCachedForKey` should have its `cached` property checked:
```
if ImageCache.defaultCache.isImageCachedForKey("your_key").cached {
    ImageCache.defaultCache.retrieveImageForKey("your_key", options: KingfisherManager.OptionsNone) { (image, type) -> () in
        cell.imageView.image = image
    }
} else {
    let image = //Generate your image
    cell.imageView.image = image
    ImageCache.defaultCache.storeImage(image, forKey: "your_key")
}
```

**Comment by Nautiyalsachin** [comment]
Can you provide updated version for this methods with swift 4 please? Thanks!

**Comment by onevcat** [comment]
@Nautiyalsachin 
The same code in Swift 4 now should be:

```swift
if ImageCache.default.imageCachedType(forKey: "your_key").cached {
    ImageCache.default.retrieveImage(forKey: "your_key", options: nil, completionHandler: { image, _ in
        cell.imageView.image = image
    })
} else {
    let image = //Generate your image
    cell.imageView.image = image
    ImageCache.default.store(image, forKey: "your_key")
}
```
