### ISSUE TITLE
Type of expression is ambiguous without more contex

### ISSUE THREAD

**Issue by mallikarjuna0308** [onevcat/Kingfisher#1606]
<img width="1047" alt="Screenshot 2021-01-27 at 5 53 19 PM" src="https://user-images.githubusercontent.com/50403836/105995070-7f49bb00-60ce-11eb-8438-77619bcbcd89.png">
After updating Kingfisherthrough pods: pod "Kingfisher" throwing an error as shown in the screenshot.

**Comment by onevcat** [comment]
What's the version you are using? There is no such symbol in the current codebase.

Every piece of the deprecated symbols should be already removed in Kingfisher 6, so please make sure you are on the latest version.

**Comment by mallikarjuna0308** [comment]
I am using Kingfisher 6.0.1

**Comment by onevcat** [comment]
Not sure how this can happen. This code was removed in version 6 and is not in the repo any more. Maybe try to run `pod update` or `pod install` to install Kingfisher again to see how it can change.

**Comment by onevcat** [comment]
There is no additional information and I believe it should not be a problem in Kingfisher. I am closing it.

If you find it is still an issue and have more to complain about, feel free to reopen it. :)

**Comment by mallikarjuna0308** [comment]
Ok @onevcat Thank you for your response.
