### ISSUE TITLE
Can't install this library with pod..

### ISSUE THREAD

**Issue by chenminhua** [onevcat/Kingfisher#161]
I just can't install this library with pod, please give me hint.
**[!] Unable to satisfy the following requirements:**
**- `Kingfisher (~> 1.8)` required by `Podfile`**

i guess it's a cocoapod's error

**Comment by onevcat** [comment]
What's your deploy target? Kingfisher requires iOS 8+ and be used as a framework in Swift.

**Comment by chenminhua** [comment]
I use swift and ios 9.0

**Comment by chenminhua** [comment]
<img width="857" alt="screen shot 2015-11-26 at 11 37 29 pm" src="https://cloud.githubusercontent.com/assets/10234400/11426380/b89cbede-9496-11e5-9544-8fc11db1cf1d.png">

**Comment by onevcat** [comment]
I guess it is some cocoa pods error instead of Kingfisher. Did you try some other pods?

And may I know the content of your Podfile?

**Comment by chenminhua** [comment]
of course, I just 

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'KingFisherIos' do
pod 'Kingfisher', '~> 1.8'
end

**I have try some other lib and didn't find that error**
thanks a lot

**Comment by onevcat** [comment]
I have tried it in my environment and it seems work well for me (with pod version 0.39.0).

Just did some search and it seems like you encountered this? https://github.com/CocoaPods/CocoaPods/issues/4373

I guess maybe you could just downgrade to 0.38.2 as a workaround and wait for the new version of CocoaPods. Or you could also try to modify the `pod 'Kingfisher', '~> 1.8'` to some more specified version like `pod 'Kingfisher', '~> 1.8.2'` (I am not sure it could work although).

**Comment by chenminhua** [comment]
I still can't figure it out
but I have get it done manually by "git submodule" way
anyway, thanks for your help.😊
