### ISSUE TITLE
Download Image with blur effect applied from a URL

### ISSUE THREAD

**Issue by ForceGT** [onevcat/Kingfisher#1611]
I'd like to apply a blur effect based on a Slider () value in SwiftUI 
I figured that can be done using ```setProcessor(BlurImageProcessor(blurRadius: CGFloat(blurRadius)))``` on the KFImage view and now I'd like to download this same image

I would also like to receive progress on download task 
I landed on [HackingWithSwift Solution](https://www.hackingwithswift.com/books/ios-swiftui/how-to-save-images-to-the-users-photo-library) to save the image but I'd like to know how it can exactly be done

**Comment by onevcat** [comment]
Maybe you can try the `onSuccess` to get the image:

```swift
KFImage(url)
    .onSuccess { r in
        let image = r.image
        // Do whatever you want to the image
    }
```

**Comment by ForceGT** [comment]
> Maybe you can try the `onSuccess` to get the image:
> 
> ```swift
> KFImage(url)
>     .onSuccess { r in
>         let image = r.image
>         // Do whatever you want to the image
>     }
> ```

Can you tell me what the ```ImageDownloader``` class is for?

**Comment by onevcat** [comment]
As its name, it is used to download an image.

For normal framework users, it is recommended to just use the `UIImageView` extension methods (`imageView.kf`) or `KFImage` to perform image downloading/caching. These types/methods wrap the detail and give you a high-level, easy to use APIs.

`ImageDownloader` and other types like `ImageCache` are what do the work underneath. They are prepared for advanced users to adjust the behavior in a fine grain size.

**Comment by ForceGT** [comment]
I finally did it using the following code
Keeping it here just in case someone needs it
```
let processor = BlurImageProcessor(blurRadius: CGFloat(blurRadius))
        let downloader = ImageDownloader.default
        downloader.downloadImage(with: URL(string: url)!, options: [.processor(processor)], progressBlock:  {
            (received, total) in
                self.downloadProgress = true
                self.downloadProgressValue = Float(received) / Float(total)
        }) { result in
            switch result {
            case .success(let result):
                    self.saveToAlbum(photo: result.image, albumTitle: "WallPixel")
            case .failure(_):
                self.downloadProgress = false
                self.downloadError = true
            }
```
