### ISSUE TITLE
When images are saved to disk after using image processor they lose alpha information

### ISSUE THREAD

**Issue by mcrakhman** [onevcat/Kingfisher#1613]
For example if we have some processor which tries to make round corners for the image like `let processor = RoundCornerImageProcessor(cornerRadius: 10)`, we see white pixels around the borders. I didn't check why this could happen.

**Comment by onevcat** [comment]
Please try a search in closed issues and there will be a lot of those.

**Comment by onevcat** [comment]
Some ref: https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#serializer-to-force-a-format
