### ISSUE TITLE
图片 cookie httpShouldHandleCookies 不生效

### ISSUE THREAD

**Issue by IT-ZhongPeng** [onevcat/Kingfisher#1616]
我通过  这种方式 进行 cookie 设置，但是完全没有反应。
let modifier = AnyModifier { request in
       var r = request
      r.httpShouldHandleCookies = true
      return r
}

self.imageView.kf.setImage(with: imageUrl, options: [.requestModifier(modifier)])

**Comment by onevcat** [comment]
从[文档](https://developer.apple.com/documentation/foundation/nsmutableurlrequest/1415485-httpshouldhandlecookies)来看这个值默认就是 `true`。建议查查看是不是其他地方的问题导致了没有按照您的预期工作。

**Comment by IT-ZhongPeng** [comment]
非常感谢
