### ISSUE TITLE
Url with kingfisher

### ISSUE THREAD

**Issue by tiego62** [onevcat/Kingfisher#162]
Hello, 

And thank you for your library Who is very useful
When I use kingfisher with a remote url I have no problem. However when I use it with a local url as assets-library://asset/asset.JPG?id=4545454-...... &ext=JPG the image is not displayed.

I get this url with this code ->
 var chosenImage = (info[UIImagePickerControllerReferenceUrl]?.absoluteString) as String
       
Do you have a solution ?

thanks
tiego

**Comment by onevcat** [comment]
assets library url is not supported yet.
