### ISSUE TITLE
calback error

### ISSUE THREAD

**Issue by kshysius** [onevcat/Kingfisher#163]
my code:

        profileImage.kf_setImageWithURL(NSURL(string: "your_image_url")!,
            placeholderImage: nil,
            optionsInfo: nil,
            progressBlock: { (receivedSize, totalSize) -> () in
                println("Download Progress: \(receivedSize)/\(totalSize)")
            },
            completionHandler: { (image, error, imageURL) -> () in
                println("Downloaded and set!")
            }
        )

and i have error: Cannot convert value of type '(_,_,_) -> ()' to expected argument type 'CompletionHandler?'

how to fix it?

**Comment by awind** [comment]
you could try this code instead:
```
   profileImage.kf_setImageWithURL(NSURL(string: "your_image_url")!,
        placeholderImage: nil,
        optionsInfo: nil,
        progressBlock: { receivedSize, totalSize in
            println("Download Progress: \(receivedSize)/\(totalSize)")
        },
        completionHandler: { image, error,cacheType, imageURL in
            println("Downloaded and set!")
        }
    )
```

**Comment by gregkerzhner** [comment]
small change for swift 2
```
   profileImage.kf_setImageWithURL(NSURL(string: "your_image_url")!,
        placeholderImage: nil,
        optionsInfo: nil,
        progressBlock: { receivedSize, totalSize in
            println("Download Progress: \(receivedSize)/\(totalSize)")
        },
        completionHandler: { image, error,cacheType, imageURL in
            print("Downloaded and set!")
        }
    )
```

**Comment by onevcat** [comment]
It should not be a Kingfisher problem and you could have a look at the [ViewController.swift](https://github.com/onevcat/Kingfisher/blob/master/Kingfisher-Demo/ViewController.swift) to know the correct syntax.

I am closing it.
