### ISSUE TITLE
Issue when testing for Swift 4.x

### ISSUE THREAD

**Issue by WillPromise** [onevcat/Kingfisher#1633]
I assume this project use fastlane to test different swift version, in `Fastfile`, we can see
https://github.com/onevcat/Kingfisher/blob/81dd1ce8401137637663046c7314e7c885bcc56d/fastlane/Fastfile#L38

however, to support swift 4.x, by setting the build setting `SWIFT_VERSION=#{options[:swift_version]}` is not enough.

To reproduce this issue, you can delete lines in `Sources/Utility/Result.swift` **from** line 29 **to** line 181,
https://github.com/onevcat/Kingfisher/blob/81dd1ce8401137637663046c7314e7c885bcc56d/Sources/Utility/Result.swift#L29
https://github.com/onevcat/Kingfisher/blob/81dd1ce8401137637663046c7314e7c885bcc56d/Sources/Utility/Result.swift#L181

then run `bundle exec fastlane tests`, the tests pass, which indicate lines in `Sources/Utility/Result.swift` from line 29 to line 181 are useless.
The tests **should** at least fail in swift 4.x since swift 4.x does not have `enum Result<Success, Failure>` built-in and we have deleted these lines.

so I believe the Tests needs update, either File `Sources/Utility/Result.swift` contains **useless** lines or the swift 4.x is **never** really tested.

Actually, the original issue is that I found this line `Kingfisher/Sources/General/KF.swift:124` won't compile in Swift < 5.2, because [SE-0253](https://github.com/apple/swift-evolution/blob/main/proposals/0253-callable.md) was implemented in Swift 5.2, so I ran tests and found this issue.
https://github.com/onevcat/Kingfisher/blob/81dd1ce8401137637663046c7314e7c885bcc56d/Sources/General/KF.swift#L124

**Comment by onevcat** [comment]
Thanks for reporting this.

We now have an integrated SwiftUI and other features built-in the framework, so I believe the latest version now can only support Swift 5.1 or 5.2.

If you still need to use it in Swift 4 or earlier, choose Kingfisher version 5.

I will also update and remove these unused things soon.
