### ISSUE TITLE
How to use KingFisher with UICollectionViewController

### ISSUE THREAD

**Issue by timothyerwin** [onevcat/Kingfisher#1648]
Hey,

Im trying to have an automatic sizing of height of cell based on the image with max width 200

```swift
        // IMPORTANT: this is the key to make your cells auto-sizing
        if let collectionViewLayout = collectionView.collectionViewLayout as? UICollectionViewFlowLayout {
            collectionViewLayout.estimatedItemSize = UICollectionViewFlowLayout.automaticSize
       }
```

```swift
 override init(frame: CGRect) {
        super.init(frame: frame)
        
        imageView.translatesAutoresizingMaskIntoConstraints = false
        imageView.kf.indicatorType = .activity
        imageView.contentMode = .scaleAspectFit
        imageView.clipsToBounds = true
        
        bubbleView.addSubview(imageView)
        
        imageView.leftAnchor.constraint(equalTo: bubbleView.leftAnchor).isActive = true
        imageView.rightAnchor.constraint(equalTo: bubbleView.rightAnchor).isActive = true
        // imageView.heightAnchor.constraint(equalTo: self.heightAnchor).isActive = true
        imageView.topAnchor.constraint(equalTo: self.topAnchor).isActive = true
    }
```

However, when I use it the height is like 5x as big as the image...how can I get it to correctly display images to a max width of 200 and dynamic height?

<img width="419" alt="Screen Shot 2021-03-04 at 2 03 33 PM" src="https://user-images.githubusercontent.com/2653209/110036842-7b730f00-7cf2-11eb-9fed-7f8fba1ea3d6.png">

**Comment by onevcat** [comment]
Not sure what the final layout you need or how did you set the cell and `bubbleView` layout. However, Kingfisher can work with auto sizing cell well. 

I just pushed a sample scene in the branch here (https://github.com/onevcat/Kingfisher/pull/1661), which maybe can help you get some ideas on how to make a self-sized cell. (Although the example is for table view, the same trick should apply to a collection view too.)

**Comment by onevcat** [comment]
There is already a sample scene in the demo app for using Kingfisher to display an auto-resizing cell. I am closing it for now.
