### ISSUE TITLE
KFImage.swift:164:25 missing return type

### ISSUE THREAD

**Issue by pawelkazmierczak** [onevcat/Kingfisher#1653]
Hi. I have this issue while building embed Kingfisher to my podspec with setting dependency swift version to 5.3. 
`Kingfisher/Sources/SwiftUI/KFImage.swift:164:25: error: function declares an opaque return type, but has no return statements in its body from which to infer an underlying type
`

**Comment by onevcat** [comment]
I cannot reproduce this (and I am not sure how did you set the Swift version to 5.3, I guess there is only an option for Swift 5?)

![截屏2021-03-09 20 43 27](https://user-images.githubusercontent.com/1019875/110465700-1cf5c880-8118-11eb-8318-385206642c36.png)


Do you have a reproducible sample that I can have a try? Thanks!

**Comment by ashusri16** [comment]
You don't need to set it to 5, you need to downgrade it from swift 5. Just use swift 4.2, it will work fine.

**Comment by pawelkazmierczak** [comment]
On xCode 12.4 works fine. The problem was xCode 11.
