### ISSUE TITLE
超大gifOOM

### ISSUE THREAD

**Issue by outer1** [onevcat/Kingfisher#1656]
在解码一张大小为7000*7000的GIF图时候，内存峰值达到了700M，在一些低端机器上很容易就OOM了，即使改源码做downsampling峰值还是降不下来，请问有合适的方案处理这种case吗
![image](https://user-images.githubusercontent.com/13569132/110614068-ecbc3180-81cc-11eb-99fa-8ddcd9a31e06.png)

**Comment by onevcat** [comment]
That is a way too huge image from any aspect. Downsampling only works for static images like JPEG or PNG.

Are you trying to use `UIImageView` or `AnimatedImageView`? If you are still in `UIImageView`, I suggest trying to switch to the `AnimatedImageView` to see if it can improve. Also try to set the `framePreloadCount` of the `AnimatedImageView` to a smaller number, such as `3` (I suggest) to make more trade-off from CPU to memory.

**Comment by outer1** [comment]
> That is a way too huge image from any aspect. Downsampling only works for static images like JPEG or PNG. It is not for a GIF image.
> 
> Are you trying to use `UIImageView` or `AnimatedImageView`? If you are still in `UIImageView`, I suggest trying to switch to the `AnimatedImageView` to see if it can improve. Also try to set the `framePreloadCount` of the `AnimatedImageView` to a smaller number, such as `3` (I suggest) to make more trade-off from CPU to memory.
> 
> If that does not work, I can only suggest you perform some resizing on your server side when storing this GIF.

这个gif是QA创建出来的，只有一帧，Gif展示是用的AnimatedImageView，看来只能让Server端处理下了，感谢！
