### ISSUE TITLE
Version 6.x won't compile using SPM

### ISSUE THREAD

**Issue by Red-Mak** [onevcat/Kingfisher#1659]
Hi,
im using KF in my SwiftUI project, i was using the v5.x and it works fine 👍 , now i want to use the new transition modifier to fade the placeHolder but the project won't build. i have this error:

<img width="590" alt="Capture d’écran 2021-03-11 à 16 02 42" src="https://user-images.githubusercontent.com/1404681/110809611-5861d580-8285-11eb-9190-381190b025ed.png">

can you help please, thanks :)

**Comment by onevcat** [comment]
This is not an error and I guess it should be totally safe to click the "Perform Changes" button to get rid of it? (I am not sure what is the unnecessary files are listed. Are they from Kingfisher or can you let me know what these files exact are?)

**Comment by Red-Mak** [comment]
Thank you for your quick answer.
i did "Perform Changes" but i have the same error after. I did use KF v6 in other project and it works fine, and as xcode doesn't give the list of "unnecessary build files" it hard to guess.

i'm going to close this issues as its specific to my project i think.

Thanks anyway.
