### ISSUE TITLE
为hash之后的文件名添加不同的后缀

### ISSUE THREAD

**Issue by tctony** [onevcat/Kingfisher#1670]
按照目前的代码，图片文件缓存的文件名在被hash之后，只能添加一个固定的后缀（`pathExtension`)。

无法为不同的图片添加不同后缀，用起来有些不方便。

考虑从图片的url中提取对应的后缀。

**Comment by onevcat** [comment]
Merged and I will tag it soon! @tctony  Thanks for the PR!
