### ISSUE TITLE
EXC_ARM_DA_ALIGN

### ISSUE THREAD

**Issue by outer1** [onevcat/Kingfisher#1674]
![image](https://user-images.githubusercontent.com/13569132/113241318-0854bc80-92e1-11eb-8a3b-d32738812582.png)

冷启动初始化Cache产生内存没对齐的crash

`let ioQueueName = "com.onevcat.Kingfisher.ImageCache.ioQueue.\(UUID().uuidString)"`

**Comment by onevcat** [comment]
I've never seen this crash before. It crashes inside Swift runtime so I do not have idea on what can cause it.

Is there any way to reproduce it?

**Comment by outer1** [comment]
> I've never seen this crash before. It crashes inside Swift runtime so I do not have idea on what can cause it.
> 
> Is there any way to reproduce it?
查了一些资料发现可能是UUID().string内部实现的问题，现在暂时是替换了UUID采用其他方式生成唯一的ioQueueName

**Comment by quocan2812** [comment]
The

**Comment by quocan2812** [comment]
Dad

**Comment by onevcat** [comment]
@outer1 Oh, that is quite surprising. Can I have a link of the resource you mentioned?
