### ISSUE TITLE
Image displays correctly on iOS 14 but processor error on iOS 13

### ISSUE THREAD

**Issue by daweido** [onevcat/Kingfisher#1677]
#### What

I'm trying to display on `KFImage` from an URL. It works perfectly fine on iOS 14. But it does not work on iOS 13. When printing the `.onFailure` it gives me this: 

`failure: processorError(reason: Kingfisher.KingfisherError.ProcessorErrorReason.processingFailed(processor: Kingfisher.DefaultImageProcessor(identifier: ""), item: Kingfisher.ImageProcessItem.data(18472 bytes)))`

#### Reproduce

Here is the code I use to display the image:

```swift
if (hasProfilePicture) {
				KFImage.url(URL(string: "https://bearwww-uploads-staging.s3.eu-west-3.amazonaws.com/pictures/53c07c05-146a-42fd-a509-0bb01aca65d4.jpeg"))
					.onSuccess { r in
						// r: RetrieveImageResult
						print("success: \(r)")
					}
					.onFailure { e in
						// e: KingfisherError
						print("failure: \(e)")
					}
					.resizable()
					.clipShape(Circle())
					.aspectRatio(contentMode: .fit)
					.frame(width: size, height: size)
			} else {
				Image("paw")
					.resizable()
					.clipShape(Circle())
					.aspectRatio(contentMode: .fit)
					.frame(width: size, height: size)
			}
```

**Comment by onevcat** [comment]
Although its extension is jpeg, the image in the link you posted is a WebP file.

Apple adds support for decoding a WebP image from iOS 14 (which is also what `DefaultImageProcessor` is using underline). But on earlier iOS versions, it is not supported.

There are some projects adding WebP processor to Kingfisher, which might solve it. For example this one: https://github.com/Yeatse/KingfisherWebP

You can also add one as dependency and pass the correct processor and cacheSerializer to make Kingfisher support WebP images:

```swift
KingfisherManager.shared.defaultOptions += [
  .processor(WebPProcessor.default),
  .cacheSerializer(WebPSerializer.default)
]
```

**Comment by noppefoxwolf** [comment]
Hi, I found this issue about webp.
I have created a webp extension for `Kingfisher`.
A feature of this extension is that it does not use libwebp.

https://github.com/noppefoxwolf/KingfisherWebP

**Comment by onevcat** [comment]
@noppefoxwolf Awesome! Do you mind if we contain your work in the [wiki page here](https://github.com/onevcat/Kingfisher/wiki/FAQ#can-i-load-some-special-image-format-like-webp)?

**Comment by noppefoxwolf** [comment]
@onevcat of course! I think it will be the best for projects with iOS 14.2+.

**Comment by onevcat** [comment]
Oh. I missed the fact that it is requiring iOS 14.2. On those platforms, I believe the `DefaultProcessor` also works well. Isn't it?

Anyway, I will take a deeper look into the implementation and see how can we contain it! Thanks!

**Comment by noppefoxwolf** [comment]
@onevcat One of the features is that it supports the animation webp.
