### ISSUE TITLE
[!] CDN: trunk Repo update failed - 4 error(s):

### ISSUE THREAD

**Issue by doyeon326** [onevcat/Kingfisher#1681]
Hi! i am a big fan of using Kingfisher. I used Kingfisher til yesterday and it was working fine, but when i try to work with my another laptop this morning and did pod install, got me an error of saying:

<img width="568" alt="스크린샷 2021-04-13 오후 3 04 55" src="https://user-images.githubusercontent.com/23535790/114504292-9d549f80-9c69-11eb-8288-d8bfc7ddbd47.png">

so i thought my project got some errors, and tried with different project which showed me the same errors. 

Have anyone seen this error?

**Comment by onevcat** [comment]
It seems to be an issue of CocoaPods or your network, instead of Kingfisher.

I do not have idea on what is this, maybe you can try to search or ask in CocoaPods. eg: https://github.com/CocoaPods/CocoaPods/issues/10580

**Comment by doyeon326** [comment]
Sorry it was CocoaPods issue. Thanks a lot!
