### ISSUE TITLE
Building Swift Compiler Error

### ISSUE THREAD

**Issue by JzwOnly** [onevcat/Kingfisher#1684]
use Cocoapods
version: Kingfisher 6.2.1
Xcode 11.5
![WechatIMG116](https://user-images.githubusercontent.com/21191349/114802029-88921c00-9dcf-11eb-9be0-759c03b380ab.png)

**Comment by onevcat** [comment]
:( To support SwiftUI inside the framework now it requires Xcode 12 at least. Please try Kingfisher 5.x to use in Xcode 11.x.
