### ISSUE TITLE
The picture can't be parsed,Error Domain Code=10000

### ISSUE THREAD

**Issue by ty82885279** [onevcat/Kingfisher#1689]
Hello,
I have a problem，The picture can't be parsed

this url can't be parsed: http://file-yrnd.17817.com/dev/54/1rMo716iTF3yFadhfsCmDnZVMFn/161879514868459870.jpg?size=400%3A352\u0026x-oss-process=style%2Ftest

error info : Error Domain Code=10000

but this url can be parsed :

http://file-yrnd.17817.com/dev/54/1rFDg2DcBqAqLHmb4ilTb9gd6ax/16185630508895122.jpg?size=900%3A1547\u0026x-oss-process=style%2Ftest

**Comment by onevcat** [comment]
Your first link points to a webp image in fact.

![截屏2021-04-20 21 57 47](https://user-images.githubusercontent.com/1019875/115399717-737c1980-a223-11eb-9181-f675803c4725.png)

It is not built-in supported on iOS until iOS 14. If you want to show it in any earlier versions, try to use a WebP plugin such as https://github.com/Yeatse/KingfisherWebP.

Check more in the [related FAQ page](https://github.com/onevcat/Kingfisher/wiki/FAQ#can-i-load-some-special-image-format-like-webp).
