### ISSUE TITLE
dyld: Symbol not found: _NSURLSessionTaskPriorityDefault

### ISSUE THREAD

**Issue by misuqian** [onevcat/Kingfisher#169]
When I install APP demo in iPhone6 ,iOS 8.3,I got this error and below is whole log

dyld: Symbol not found: _NSURLSessionTaskPriorityDefault
  Referenced from: /private/var/mobile/Containers/Bundle/Application/*******
  Expected in: /System/Library/Frameworks/Foundation.framework/Foundation
 in /private/var/mobile/Containers/Bundle/Application/**********
(lldb)

**Comment by onevcat** [comment]
I am not sure how did you try it, but you may need to link to `CFNetwork` manually.

**Comment by misuqian** [comment]
I install Kingfisher by pod and it perfect work
I find the reason is that I copy files directly to project and I got these errors

**Comment by onevcat** [comment]
Cool. In fact it seems to be a change in the linking system. Before the `CFNetwork` is auto linked if you refer to Foundation. But the behavior was changed in Xcode 7. See this https://github.com/onevcat/Kingfisher/pull/78 for more.
