### ISSUE TITLE
Kingfisher fails on checkout a certain locked version

### ISSUE THREAD

**Issue by onevcat** [onevcat/Kingfisher#1691]
Recently we did a git reflog to reduce the repo size (which caused by a wrongly committed doc archive binary). That rewrites some commit history so the original commit hash may not be available any more.

All the released versions (tags) are kept untouched. So if you have a problem while checking out with hash from dependency manager `lock` file, please try to resolve the version again to get a new commit hash. After that, fetching of Kingfisher should be much faster now.

Sorry for any inconvenience it might cause!

**Comment by gevartosky** [comment]
Hi :) 

Just for documentation sake. I'm having an issue that could be related to this.
My Xcode and Jenkins are on an endless fight for the package version 6.2.1 revision
```
-Removed:       "revision": "15d199e84677303a7004ed2c5ecaa1a90f3863f8",
+Added:          "revision": "bbc4bc4def7eb05a7ba8e1219f80ee9be327334e",
```
Open the project on Xcode and it resolves to **bbc4**, run in Jenkins and it resolves to **15d1**

I will probably update to 6.3.0 or pin the commit instead of version.

**Comment by onevcat** [comment]
Hi, @gevartosky 

Your Jenkins is correct and `15d1` is now the wrong hash.

Maybe it is an issue of Swift Package index cache. Please try to clean it by "File -> Swift Packages -> Reset Package Cache" and see if there is anything different.

Sure, upgrading to 6.3.0 is also a solution.

Sorry for the inconvenience it may cause.

**Comment by onevcat** [comment]
I am closing this now since I guess it is long enough for projects resolving the locked version. Now the repo is much smaller and the checkout time improved dramatically. The result is satisfied.
