### ISSUE TITLE
NSErrorFailingURLStringKey

### ISSUE THREAD

**Issue by wangrui460** [onevcat/Kingfisher#1694]
NSErrorFailingURLStringKey=https://graphic-arts.bamaying.com/ceres/yawe/196/6dd10a9af1e54f379634c7809f5b5112?e=1619078222&token=whETJFhhtd1CpA5EMMxs9v5Tfaphcruefy_iSzeS:VfGzUcj35sA4mBieuEZyj_N6xuw=

**Comment by wangrui460** [comment]
NSLocalizedDescription=A server with the specified hostname could not be found.

**Comment by wangrui460** [comment]
NSLocalizedDescription=A server with the specified hostname could not be found.

**Comment by onevcat** [comment]
That errors means you have some DNS issue. It is either your device or the DNS provider. So I suggest try to check the network first...
