### ISSUE TITLE
Error on Install: "Cannot call value of non-function type"

### ISSUE THREAD

**Issue by petermichaux** [onevcat/Kingfisher#1697]
I tried installing with Carthage and Swift Package Manager. Both resulted in the same "Cannot call value of non-function type" errors. See image below from the failed attempt at installing with Swift Package Manager. My project is using Swift 5. I'm using Xcode 11.

![Screen Shot 2021-04-26 at 10 39 35 AM](https://user-images.githubusercontent.com/9227/116126842-f6fe9600-a67b-11eb-89b3-de61c807f694.png)

**Comment by onevcat** [comment]
Hi,

The latest version 6.x only supports Xcode 12, so if you are still in Xcode 11, you have to use version 5.x.

And in case you do not know it, Apple has already decided not to accept builds from Xcode 11. Now if you want to submit your app to the App Store, you need to upgrade to Xcode 12 and iOS 14 SDK. [Ref](https://developer.apple.com/news/?id=ib31uj1j)

> iPhone and iPad apps. Starting April 26, 2021, all iPhone and iPad apps submitted to the App Store must be built with Xcode 12 and the iOS 14 SDK or later. The iOS SDK provides access to exciting new features like App Clips, Home screen widgets, ARKit, RealityKit, and much more.

**Comment by petermichaux** [comment]
Thank you for the information. I appreciate it. I will update to Xcode 12.
