### ISSUE TITLE
Error with Xcode 12.5 / SwiftUI

### ISSUE THREAD

**Issue by morad** [onevcat/Kingfisher#1698]
Hello, with Xcode 12.5, I am having a serious problem with KF SwiftUI:

Getting this error through out with this line of code when I add options parameters. Without options params, it works fine.

`KFImage(URL(string: post.postImage), options: [.cacheOriginalImage])`

"Cannot convert value of type 'URL' to expected argument type 'Source?'"

Assist?

**Comment by DavidSReich** [comment]
I'm having problems with layouts in SwiftUI for iOS 14.5 that are fine in iOS 14.4.
This is on all Simulator models I've tested and on one physical iPhone XS Max.
I'm trying to isolate the problem.
I'll report back here if I discover anything useful.

**Comment by DavidSReich** [comment]
My problem was not `KFImage`.  It was SwiftUI's handling of layout sizes when an `Image` is nested inside a couple of layers of `Views`.  iOS 14.5 didn't size my `View` at runtime based upon the size of a contained `Image`.  iOS 14.4 did do that.
The solution was to explicitly use `frame` to set the desired size of the outer `View`.

**Comment by timothyerwin** [comment]
@morad I had this same problem and changed my version to exact at `6.0.1`

**Comment by onevcat** [comment]
@morad @timothyerwin 

Umm,

The method is still there untouched (although it is already deprecated for a while), but it seems the new Swift version fails to search them. Not sure why yet.

For your case, maybe consider to switch to the new syntax:

```swift
KFImage.url(url)
    .cacheOriginalImage()
```

And if that causes any issues (such as image not showing up in some cases), you can also try to add `.loadImmediately()`:

```swift
KFImage.url(url)
    .cacheOriginalImage()
    .loadImmediately()
```
