### ISSUE TITLE
Crash when loading big image with progressive decoding enabled

### ISSUE THREAD

**Issue by anton-filimonov** [onevcat/Kingfisher#1699]
### Issue Description
On some devices (I reproduced on iPhone 7) when loading big image (in my case its' size is aboun 11Mb) with progressive decoding enabled I get the app crashed

#### Reproduce

Unfortunately can't add the file I use to reproduce the problem because it's 11 Mb in size but only less then 10Mb is allowed. And the URL I use is private. But the code to reproduce the problem is here:

```swift
let source = ImageResource(downloadURL: url!)
self.task = self.imageView.kf.setImage(with: source,
                                       placeholder: nil,
                                       options: [.forceRefresh, .progressiveJPEG(.default), .transition(.fade(0.1))],
                                       completionHandler: nil)
```
run it with URL to big image (11,1Mb in my case) on iPhone 7 (and probably older devices) and you'll get crash in SessionDataTask.swift on line 119: `mutableData.append(data)`. At the same time another thread is stopped in ImageFormat.swift on line 120: `for (index, item) in buffer.enumerated() {`

the info from console:
```
malloc: can't allocate region
:*** mach_vm_map(size=12697600, flags: 100) failed (error code=3)
 malloc: *** set a breakpoint in malloc_error_break to debug
```

If I remove ` .progressiveJPEG(.default)` from options, everything works well

**Comment by onevcat** [comment]
From the error, it is the memory issue. The system forbids an allocation of more memory. Loading a 11MB image itself is not a trivial behavior, it consumes lots of memory, especially when loading progressively (which actually load the same image for multiple times). Loading big picture like that requires some trick.

Maybe you can try to use the `DownsamplingImageProcessor` to make your image smaller before actually decoding it, which may solve your loading issue (normal such a huge image is not necessary for your UI, so pick a good smaller size):

```swift
imageView.kf.setImage(with: url, options: [
                        .forceRefresh,
                        .progressiveJPEG(.default),
                        .processor(DownsamplingImageProcessor(size: .init(width: 800, height: 600)))
])
```

(And not sure why you need `.forceRefresh`, but I personally suggest not use it until you have a special reason. Leave Kingfisher to decide reusing a cached image would be also helpful for memory usage.)
