### ISSUE TITLE
Add some kind of Activity Indicator

### ISSUE THREAD

**Issue by vCrespoP** [onevcat/Kingfisher#170]
Could it be done easily? Would be nice to have!

Thanks.

**Comment by onevcat** [comment]
Maybe you mean the [`kf_showIndicatorWhenLoading`](http://cocoadocs.org/docsets/Kingfisher/1.8.2/Extensions/UIImageView.html#/s:vE10KingfisherCSo11UIImageView27kf_showIndicatorWhenLoadingSb)?

**Comment by vCrespoP** [comment]
Yeah! That's it, I didn't notice that.

Thanks for the quick response, I'm searching for a replacement made in swift for SDWebImage and this might be it!

**Comment by NikKovIos** [comment]
swift 3
imageV.kf.indicatorType = .activity
