### ISSUE TITLE
Cannot find 'KFAnimatedImage' in scope

### ISSUE THREAD

**Issue by shial4** [onevcat/Kingfisher#1710]
### Issue Description
Cannot find 'KFAnimatedImage' in scope
#### What

SwiftUI iOS 14+ while trying to use 'KFAnimatedImage' I get the message:
```
Cannot find 'KFAnimatedImage' in scope
```
However, KFImage works just fine.

#### Reproduce

Create a new project. Add Kingfisher to project & try using `KFAnimatedImage `

**Comment by onevcat** [comment]
Although it is already in the master branch, it is not tagged and released now yet. 

You can point your version to branch master if you need that now. I will prepare a release for that later when I can have a full test and make sure everything goes fine. But it requires some time.

**Comment by tianskylan** [comment]
For additional context, looks like `master` doesn't build for device at the moment, while it worked fine on Simulator.
I tried putting back `import Combine` locally in several files and that fixed the build errors.

Thanks for adding `KFAnimatedImage` support!

**Comment by onevcat** [comment]
Ummm, thanks for reporting this. I will check to see what's going on.

**Comment by onevcat** [comment]
Seems I [encountered this](https://stackoverflow.com/a/62085591/1468886). Really frustrating.

Now the master should be fine, I believe.

**Comment by tianskylan** [comment]
Weird stuff, thanks for the fix!

**Comment by jkelol111** [comment]
This still happens in a SwiftUI Multiplatform project (iOS 15.2, macOS 12.1). KFImage works fine, KFAnimatedImage complains with the same error. Kingfisher is added to both targets.

**Comment by onevcat** [comment]
@jkelol111 Can you create a sample project in which I can reproduce this?

**Comment by jkelol111** [comment]
> @jkelol111 Can you create a sample project in which I can reproduce this?

@onevcat I've uploaded one here: https://gofile.io/d/Osjcj0

**Comment by onevcat** [comment]
@jkelol111 Oh. OK...

That is because the `KFAnimatedImage` is just a `UIViewRepresentable`. It is not cross-platform from the very beginning. (and also the underhood `AnimatedImageView`, which is a sub-class of `UIImageView` now).

We can try to port the class also to `NSImageView` and allow `KFAnimatedImage` a cross-platform type (such as `KFImage`), but it is not a trivial work for now.

**Comment by MadeByDouglas** [comment]
I have this issue too, which is fine but it took a while to track down what was happening. Until it is updated to be cross-platform can the documentation be updated at least so it's known that KFAnimatedImage is iOS only? Right now it says it also supports macOS on the DocC

https://swiftpackageindex.com/onevcat/kingfisher/7.6.1/documentation/kingfisher/kfanimatedimage
