### ISSUE TITLE
carthage update issue

### ISSUE THREAD

**Issue by Alrassas** [onevcat/Kingfisher#1714]
trying to update carthage framework but i received this error
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/onevcat/Kingfisher.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/linkdev/Library/Caches/org.carthage.CarthageKit/dependencies/Kingfisher)) failed with exit code 1

**Comment by onevcat** [comment]
It is more likely a Carthage issue and maybe you can try to clean its cache (`/Users/linkdev/Library/Caches/org.carthage.CarthageKit`) and try again.

Or maybe asking it in Carthage repo instead...

**Comment by dougalg** [comment]
@onevcat I had the same issue, and your solution resolved it for me. Thanks!

**Comment by Alrassas** [comment]
@onevcat , Thanks your answer is perfect. your solution resolved it . Thanks Dear
