### ISSUE TITLE
TabView referencing selection makes KFImage load forever

### ISSUE THREAD

**Issue by sameersyd** [onevcat/Kingfisher#1728]
- I have a TabView which generates BatchView in loop, inside which there's a KFImage. The selection binding passed into TabView when referenced some where else in code, makes the KFImage load.
- Also in TabView when we swipe to a next tab and wait for a second without releasing the gesture, the KFImage again starts loading.

Swiping to the other views and coming back fixes the image.

Here's a code snippet,

```
@State var selection = 0
var body: some View {
    ZStack {
        TabView(selection: $selection) {
            ForEach(0..<media.count, id: \.self) { i in
                BatchCell(media: media[i])
            }
        }.onAppear {
            selection = 10    // adding this line makes the KFImage load forever
        }
    }
}
```

**Comment by onevcat** [comment]
😂

Hi, again!

Any chance to also paste the content of `BatchCell` or an equivalent implementation? So I can also reproduce this issue and check it in detail?

> Swiping to the other views and coming back fixes the image.

And it really sounds another similar one as #1723 ? Did you try to replace it with a normal image to see if it loads there?

**Comment by sameersyd** [comment]
Hey! Here's the code in BatchCell.

```
KFImage.url(viewModel.media.mediaURL)
    .placeholder {
        ZStack {
            LottieView(animType: .loading).frame(width: 250, height: 250)
        }
    }
    .resizable().scaledToFit()
    .frame(width: viewModel.size.width).clipped()
```

**Comment by onevcat** [comment]
```swift
struct ContentView: View {
    @State var selection = 0
    var body: some View {
        ZStack {
            TabView(selection: $selection) {
                ForEach(0..<3, id: \.self) { i in
                    BatchCell(url: url(index: i))
                        .tabItem { Text("Tab \(i)") }
                }
            }.onAppear {
                selection = 2
            }
        }
    }
    
    private func url(index: Int) -> URL {
        URL(string: "https://raw.githubusercontent.com/onevcat/Kingfisher-TestImages/master/DemoAppImage/Loading/kingfisher-\(index + 1).jpg")!
    }
}

struct BatchCell: View {
    let url: URL
    var body: some View {
        KFImage.url(url)
            .placeholder {
                ZStack {
                    Color.blue
                }
            }
            .resizable().scaledToFit()
            .frame(width: 300).clipped()
    }
}
```

Tried this code but without a luck to reproduce. The `KFImage` in center of the screen loads without problem.

Is there any more context or information?

**Comment by sameersyd** [comment]
Add the onChange listener to selection. Add this exact code!

```
struct BatchMediaView: View {
    
    @Environment(\.presentationMode) var presentationMode: Binding<PresentationMode>
    @StateObject var viewModel: BatchMediaViewModel
    
    @State var selection = 0
    
    var body: some View {
        GeometryReader { geo in
            Color.black.edgesIgnoringSafeArea(.all)
            ZStack {
                TabView(selection: $selection) {
                    ForEach(0..<viewModel.batches.count, id: \.self) { i in
                        BatchMediaCellView(viewModel: BatchMediaCellViewModel(size: geo.size, media: viewModel.batches[i].media))
                    }
                }
                .tabViewStyle(PageTabViewStyle(indexDisplayMode: .never))
                .onChange(of: selection, perform: { i in
                    print("i =", i)
                })
            }.edgesIgnoringSafeArea(.all).clipped()
        }
    }
}
```

**Comment by onevcat** [comment]
Ummm,

Still not reproducible, with the code below:

```swift
struct ContentView: View {
    @Environment(\.presentationMode) var presentationMode: Binding<PresentationMode>
        
    @State var selection = 2
        
    var body: some View {
        GeometryReader { geo in
            Color.black.edgesIgnoringSafeArea(.all)
            ZStack {
                TabView(selection: $selection) {
                    ForEach(0..<3, id: \.self) { i in
                        BatchCell(url: url(index: i))
                    }
                }
                .tabViewStyle(PageTabViewStyle(indexDisplayMode: .never))
                .onChange(of: selection, perform: { i in
                    print("i =", i)
                })
            }
            .onAppear {
                selection = 2
            }
            .edgesIgnoringSafeArea(.all).clipped()
        }
    }
    
    private func url(index: Int) -> URL {
        URL(string: "https://raw.githubusercontent.com/onevcat/Kingfisher-TestImages/master/DemoAppImage/Loading/kingfisher-\(index + 1).jpg")!
    }
}

struct BatchCell: View {
    let url: URL
    var body: some View {
        KFImage.url(url)
            .placeholder {
                ZStack {
                    Color.blue
                }
            }
            .forceRefresh()
            .resizable().scaledToFit()
            .frame(width: 300).clipped()
    }
}
```

https://user-images.githubusercontent.com/1019875/122032313-7b62cf00-ce0a-11eb-9e88-8bdf07ea61af.mov

It seems that you are having a `presentationMode` binding. Are you trying to show it in some container?

And it would be nice if you can:

- Try appending `loadImmediately` to `KFImage` to make sure it is not a lifecycle limitation.
- Create a sample project in which we can stably reproduce it, so the debugging process could be smoother.

Thanks for helping on this!

**Comment by sameersyd** [comment]
Thanks, the above method works. But passing a `@StateObject` or `@ObservedObject` triggers it.
Rather than directly passing url, add it in a ViewModel and pass it., Like I did!

**Comment by onevcat** [comment]
Oh, I see.

OK, so it depends how you use the `@StateObject viewModel`. It is quite hard to say what can trigger this base on the code you now provided, but I guess there is some other lifetime issue in your model, which prevents the image loading. 

Is it possible for you to make your `@StateObject viewModel` as `private`? And how are you passing the `viewModel` to the cell (as well as to `KFImage`). The way you construct the data (and dependencies for the `View`) decides how the whole thing work.

A sample project is welcomed so I can take a deeper look to find how's it going.

**Comment by sameersyd** [comment]
Hey @onevcat, I've emailed you my details. Please look into it, so we can figure out the issue.
