### ISSUE TITLE
How I can set max concurrent thread for upload Images?

### ISSUE THREAD

**Issue by Max-Fox** [onevcat/Kingfisher#1731]
Hello. Please tell me. How can I set limit the thread number of images downloaded so as not to load my CPU?

For example I have 50 images that I want to upload. But I need them to load not in 50 threads, but in 10

**Comment by onevcat** [comment]
Kingfisher does not contain a feature to upload images.

If you mean downloading, there is an [`httpMaximumConnectionsPerHost `](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1407597-httpmaximumconnectionsperhost) you can set. Kingfisher uses `URLSession` under the hood for downloading images and the session configuration is exposed in the `ImageDownloader` [here](https://github.com/onevcat/Kingfisher/blob/master/Sources/Networking/ImageDownloader.swift#L124).

**Comment by Max-Fox** [comment]
Thank you so much for your quick response
