### ISSUE TITLE
Kingfisher facing error with iOS 15 during archive on Xcode 13 beta.

### ISSUE THREAD

**Issue by aleemtoor** [onevcat/Kingfisher#1736]
Failed to build module 'Accelerate'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.17.216 clang-1300.0.18.1)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.19.104 clang-1300.0.18.4)'). Please select a toolchain which matches the SDK.

**Comment by onevcat** [comment]
Duplicated with #1725.

**Comment by lakshminarayana254** [comment]
Is this issue got fixed?? I'm using XCode 13 beta 2 still unable to archieve...

**Comment by onevcat** [comment]
Using any 7.0.0 beta version should help you out. https://github.com/onevcat/Kingfisher/releases
