### ISSUE TITLE
Xcode 13 Beta 1 Archive Error

### ISSUE THREAD

**Issue by aiaagentapp** [onevcat/Kingfisher#1740]
Trying to Compile in Xcode 13 Beta getting Archive Error

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Kingfisher' from project 'Kingfisher')
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'Kingfisher' from project 'Kingfisher')
	CompileSwift normal armv7 (in target 'Kingfisher' from project 'Kingfisher')

**Comment by onevcat** [comment]
Duplicated #1725

**Comment by ZHAORAY123** [comment]
> 尝试在 Xcode 13 Beta 中编译时出现存档错误
> 
> ** 存档失败 **
> 
> 以下构建命令失败： CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Kingfisher' from project 'Kingfisher') CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target '来自项目'Kingfisher'的Kingfisher'） CompileSwift普通armv7（在来自项目'Kingfisher'的目标'Kingfisher'中）

I also have this problem. Has anyone solved it?
