### ISSUE TITLE
KFAnimatedImage performance issues (high CPU, frame drops)

### ISSUE THREAD

**Issue by chrysb** [onevcat/Kingfisher#1759]
Hi all,

Thanks for making this library and adding animated GIF support! Props to @Binlogo 

I was looking to alternatives to `SDWebImageSwiftUI` and decided to try Kingfisher again. It's definitely more stable, but I'm noticing that there's higher cpu usage with `KFAnimatedImage`:

KF: 30% cpu with one GIF on screen
SD: 3% cpu with one GIF on screen

I also notice some low FPS during transitions.

**Comment by onevcat** [comment]
It is a trade-off to use more CPU to decode image on air, or load most frames to memory to minimize the CPU usage. For now, the related API is not exposed to SwiftUI, but it should not be hard to add an interface and allow user to set it.

**Comment by onevcat** [comment]
Now you should be able to config the preload count by using `configure` in the master branch (and later I will tag it as a 7.0 beta version).

You can now tweak and make some trade-off between CPU and memory now:

![截屏2021-08-03 22 37 35](https://user-images.githubusercontent.com/1019875/128030959-6da1da40-a541-4978-9be1-fcb950e34773.png)
![截屏2021-08-03 22 37 52](https://user-images.githubusercontent.com/1019875/128030968-433b1912-92d9-4829-8291-b32485b1dcdc.png)
