### ISSUE TITLE
第一次加载程序崩溃

### ISSUE THREAD

**Issue by LiFuPeng** [onevcat/Kingfisher#1760]
第一次家在程序崩溃在这里
private func setupCacheChecking() {
            maybeCachedCheckingQueue.async {
                do {
                    self.maybeCached = Set()
                    try self.config.fileManager.contentsOfDirectory(atPath: self.directoryURL.path).forEach { fileName in
                        self.maybeCached?.insert(fileName)
                    }
                } catch {
                    // Just disable the functionality if we fail to initialize it properly. This will just revert to
                    // the behavior which is to check file existence on disk directly.
                    self.maybeCached = nil
                }
            }
        }

具体是泵在try self.config.fileManager.contentsOfDirectory(atPath: self.directoryURL.path).forEach { fileName in
                        
                    }

**Comment by onevcat** [comment]
Do you have a reproducing example or some more detail stack information when this crash happens?
