### ISSUE TITLE
喵神，我发现了一个crash 帮忙看下，堆栈信息如图，#5 0x0000000102c19a4c in closure #2 in CallbackQueue.execute(_:) at /Pods/Kingfisher/Sources/Utility/CallbackQueue.swift:52

### ISSUE THREAD

**Issue by xiaohanWW** [onevcat/Kingfisher#1761]
![WechatIMG1643](https://user-images.githubusercontent.com/15844513/127133805-9dd96927-0854-461b-a0e0-bc40dcac4fdf.png)
![WechatIMG1642](https://user-images.githubusercontent.com/15844513/127133811-4ab0d59b-da84-40e8-ac36-832a3f4038ff.png)
![WechatIMG1640](https://user-images.githubusercontent.com/15844513/127133829-fa740a46-9903-46ad-9cef-062cba0d5cc2.jpeg)
![WechatIMG1636](https://user-images.githubusercontent.com/15844513/127133846-ed72f40c-b858-424a-bbe5-658dc830b270.png)

**Comment by onevcat** [comment]
最后是在 WebPImageCreateWithData 里崩溃的，应该和 Kingfisher 没什么关系。

建议看看 `CGImage+WebP.m` 第 261 行是什么。如果是内存申请之类的话，也许是和内存不足相关。这边的话很难提供什么支持和帮助。

**Comment by xiaohanWW** [comment]
> 最后是在 WebPImageCreateWithData 里崩溃的，应该和 Kingfisher 没什么关系。
> 
> 建议看看 `CGImage+WebP.m` 第 261 行是什么。如果是内存申请之类的话，也许是和内存不足相关。这边的话很难提供什么支持和帮助。

看到了 的确是在`CGImage+WebP.m` 第 261 行处内存申请的时候崩了，感谢喵神大大
