### ISSUE TITLE
Xcode 11.3.1  New a swift project，import by pod，build and report an error

### ISSUE THREAD

**Issue by MiftMy** [onevcat/Kingfisher#1771]
Xocde verson 11.3.1，new a swift project，use KingFisher verson 6.0.1 or newer.
build directly，and I get an error，Cannot call value of non-function type 'Delegate<RetrieveImageResult, Void>'
screenshot：
<img width="946" alt="image" src="https://user-images.githubusercontent.com/16330710/128619711-eeaeef0a-8f2e-493d-a4c5-5c6d7dda6b4a.png">

**Comment by onevcat** [comment]
I suggest you try to upgrade to a new Xcode version. If you want to submit your app to AppStore, Xcode 12 is already a must:

https://developer.apple.com/news/?id=ib31uj1j

> Starting April 26, 2021, all iPhone and iPad apps submitted to the App Store must be built with Xcode 12 and the iOS 14 SDK or later. The iOS SDK provides access to exciting new features like App Clips, Home screen widgets, ARKit, RealityKit, and much more.
