### ISSUE TITLE
在 iPhone 7plus   13.7系统上加载某个图片失败 其他手机正常

### ISSUE THREAD

**Issue by zhangyunfeiFly** [onevcat/Kingfisher#1778]
imageview   width 18  height 18   加载   https://tpcdn.whfpsoft.com/media/costume/2021-01/1629182575946_87.jpeg失败  加载其他图片又没问题如 https://tpcdn.whfpsoft.com/media/costume/2021-01/1617873980436_89.jpeg。 目前 只在 7plus上无法加载这个图片  其他手机都可以正常加载  ，  我切换 sdwebimage 加载后所有图片都可正常显示

**Comment by onevcat** [comment]
This is a WebP image and only built-in supported from iOS 14.

![截屏2021-08-19 13 30 37](https://user-images.githubusercontent.com/1019875/130007985-1db31bde-1e50-4380-9277-7026bbc02e2b.png)

For other iOS versions, try solutions mentioned in [the FAQ](https://github.com/onevcat/Kingfisher/wiki/FAQ#can-i-load-some-special-image-format-like-webp).

**Comment by zhangyunfeiFly** [comment]
但是 sdwebimage 同样的手机和系统上是可以加载的。。。。。！ kingfisher有对应的解决方案么？

**Comment by onevcat** [comment]
据我所知，SDWebImage 在 5.0 以后也把 WebP 的支持放到另外的 repo，作为 plugin 提供了 https://github.com/SDWebImage/SDWebImageWebPCoder

能在旧系统上加载的前提基本是集成了 libWebP。如果这样 OK 的话，Kingfisher 里也可以参照我刚才贴的 FAQ 的连接，使用 KingfisherWebP 并把它作为 processor 使用，就能达到一样的效果了。
