### ISSUE TITLE
Custom view in SwiftUI/iOS 13 shows KFImage as black when inside a Button

### ISSUE THREAD

**Issue by jnimis** [onevcat/Kingfisher#1784]
**Issue:**
A custom SwiftUI view containing a `KFImage`, when nested inside a SwiftUI `Button`, show black images when using iOS 13.

**Description:**
I have a custom view that is loaded into a SwiftUI list of buttons. The custom view contains a `KFImage`. It works fine an iOS 14 simulator, but when using iOS 13, all of the images are solid black. 

Here is some sample code:

```
...
List(sortedItems) { itemData in
  Button(action: {
    // navigate to another screen
  }) {
    ListItem(itemData) // this is my custom view, which contains a KFImage
  }
}
...

// here is the list item:

struct ListItem : View {
  let ICON_SIZE : CGFloat = 80
  var itemData : ItemData

  var body: some View {
    HStack {
      VStack {
        Text(itemData.title)
        Text(itemData.description)
        Text("TAGS")
      }
      KFImage(imageData.imageUrl)   // I added the modifiers below in response to other similar issues
                  .resizable()
                  .loadImmediately()
                  .frame(width: ICON_SIZE, height: ICON_SIZE, alignment: .center)
    }
  }
}
```

I have tried adding `onSuccess` modifiers to the KFImage element, and can see that the images load successfully. I resolved this by using a view with an `onTapGesture` modifier, but am still reporting this as a bug with SwiftUI `Button` elements and Kingfisher. 

Below are simulator screenshots, the first from iOS 13, the second from iOS 14 (text and images are blurred because it is proprietary information):

<img width="686" alt="iOS13Screenshot" src="https://user-images.githubusercontent.com/12100888/130488035-47b750a2-5936-4a92-af55-a7c9d7e9b485.png">
<img width="398" alt="iOS14Screenshot" src="https://user-images.githubusercontent.com/12100888/130488047-9d3ecc6e-2da7-4a24-9748-8a384331a999.png">

**Comment by onevcat** [comment]
Maybe you need [this](https://developer.apple.com/documentation/swiftui/image/renderingmode(_:)) and set it with `.original` to solve it.

**Comment by jnimis** [comment]
Wow, that works! Do you happen to know if it is expected for the images to behave differently inside a `Button`?

**Comment by onevcat** [comment]
It is just how SwiftUI works (or worked on iOS 13) and the changing is also an internal decision of Apple. So I guess it is better for Kingfisher to just follow what Apple and the platform works.
