### ISSUE TITLE
image downsampling error

### ISSUE THREAD

**Issue by arslan311** [onevcat/Kingfisher#1790]
### Issue Description

**KingFisher Image downsampling error**

**The issue is:**
 
Processing image failed. Processor: GeneralProcessor(identifier: "com.onevcat.Kingfisher.DownsamplingImageProcessor((0.0, 0.0))|>com.onevcat.Kingfisher.RoundCornerImageProcessor(0.0)"

**Comment by arslan311** [comment]
Hi I am getting below error while downloading image from server using KingFisher iOS

Processing image failed. Processor: GeneralProcessor(identifier: "com.onevcat.Kingfisher.DownsamplingImageProcessor((0.0, 0.0))|>com.onevcat.Kingfisher.RoundCornerImageProcessor(0.0)"

**Comment by onevcat** [comment]
Seems you are setting a `{0,0}` to the download sampling size. 

Maybe #1455 ? Please check and not give Kingfisher such a size. Kingfisher won't know what to do to downsample an image to `{0,0}`.
