### ISSUE TITLE
How to loading Local data JPG Type

### ISSUE THREAD

**Issue by PROCW** [onevcat/Kingfisher#1797]
I wanna loading from local data on Kingfisher, but I don't know method of URL in KFImage.swift file for loading of local data path.

**Comment by onevcat** [comment]
You can just create a URL pointing to the local file and send it to `KFImage` initializer. It should just load a local file as well.

```
let url = URL(fileURLWithPath: "/var/...")

var body: some View {
    KFImage.url(url)
}
```
