### ISSUE TITLE
程序闪退

### ISSUE THREAD

**Issue by Kittycats** [onevcat/Kingfisher#1799]
```
Kingfisher/KingfisherManager.swift:677: Fatal error: This case should not happen in CacheCallbackCoordinator: originalImageCached - cacheInitiated
```

![image](https://user-images.githubusercontent.com/11718561/132443409-8001c756-5311-40f7-9698-7eefc2aeac6d.png)

**Comment by onevcat** [comment]
Thanks for it. Do you have a way to reproduce it in a stable way? Say, do you have any code snippet when this happens?

**Comment by setoelkahfi** [comment]
I encountered this problem multiple times in the simulator. Let's see if it's reproducible.
