### ISSUE TITLE
Is it possible to set different cache timers?

### ISSUE THREAD

**Issue by alexdd55** [onevcat/Kingfisher#18]
I would like to use cache for 2 different kind of images.
- first is like an avatar, this should be cached for a week or more
- second is user added content images that should be cached for a day or just a couple of hours.

is that possible?

**Comment by onevcat** [comment]
Hi, @alexdd55 

Thanks.

It is an interesting feature and could be achieved if we implement a multi-cache system. 

However, currently there is not a good way to do such things in Kingfisher since its single cache structure. A possible solution would be set/replace different cache object in the shared KingfisherManager object. But there is risk of thread issues since the cache property is not thread safe now.

It will not be difficult to add this feature but the hardest part is how to design the API.

I will consider it later. Thank you.

**Comment by alexdd55** [comment]
thanks for the quick answer. :)

**Comment by onevcat** [comment]
Oh, I guess we'd better leave it open since there is possibility to add it later. :)

**Comment by onevcat** [comment]
By the way, if you need to separate the disk cache duration, a possible way for now would be giving up the `UIImageView` category (the `kf_setImageWithURL` methods), but to use the downloader and cache classes solely. 

You are always free create and config your own cache with a name and duration. When you need an image, just check if a url is already cached there. If not, you can download with the default downloader and then store it in the cache you need. Although it is a bit hard to use :(

**Comment by alexdd55** [comment]
you right, keep that open :)

this is not a showstopper, it would just be very comfortable ;)

**Comment by onevcat** [comment]
Implemented in #30 . Waiting for merging.

**Comment by alexdd55** [comment]
nice! :+1:

**Comment by onevcat** [comment]
Added in version 1.2.0

Now you can use this code to use different caches for your images:

```swift
let avatarCache = ImageCache(name: "avatar")
avatarCache.maxCachePeriodInSecond = 100

let contentCache = ImageCache(name: "content")
contentCache.maxCachePeriodInSecond = 200

avatarImageView.kf_setImageWithURL(NSURL(string: "avatar_image_url")!, 
                                                         placeholderImage: nil, 
                                            optionsInfo: [.TargetCache: avatarCache])

contentImageView.kf_setImageWithURL(NSURL(string: "content_image_url")!, 
                                                           placeholderImage: nil, 
                                              optionsInfo: [.TargetCache: contentCache])
```

Please let me know whether it works for you. Please notice that the `options` APIs are now deprecated, and you need to switch to the new `optionsInfo` version.

**Comment by alexdd55** [comment]
what can i say? Awesome Job! :+1: 

I might test it over the weekend.
Great work!
