### ISSUE TITLE
设置RoundCornerImageProcessor的backgroundColor = .clear时，实际存在沙盒中的图片会有白色背景

### ISSUE THREAD

**Issue by kylomooa** [onevcat/Kingfisher#1800]
代码如下：
```
 let size = CGSize(width: 23, height: 23)
                icon.kf.setImage(with: URL(string: netIcon),placeholder: defaultIcon,options: [.processor(ResizingImageProcessor(referenceSize:size ,mode: .aspectFit) |> RoundCornerImageProcessor(cornerRadius: 11.5, targetSize: size,backgroundColor: .clear))])
```

**Comment by kylomooa** [comment]
![27c58884b9627caae5effa9bfeb11fe1](https://user-images.githubusercontent.com/16423068/132797880-48433b13-3a7c-4a6d-8d1a-86fb45def373.png)

**Comment by onevcat** [comment]
Please check https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#serializer-to-force-a-format

**Comment by onevcat** [comment]
And there is a plan to forcibly apply a PNG serializer. But not yet have a chance to implement it.

**Comment by kylomooa** [comment]
Thanks
