### ISSUE TITLE
Kingfisher stops the app from archiving on Xcode 13 RC

### ISSUE THREAD

**Issue by TizianoCoroneo** [onevcat/Kingfisher#1802]
### Issue Description

Kingfisher produces a large number of build errors when building for "Any iOS device (arm64)" with Xcode 13 RC.

#### What

It seems that it cannot find references to SwiftUI data types, even the `import SwiftUI` statement is present.

There is a workaround, but it's not nice: we forked and bumped the minimum version for iOS in KF's `Package.swift` to iOS 13, and the issue disappeared.

<img width="348" alt="Screen Shot 2021-09-15 at 09 59 26" src="https://user-images.githubusercontent.com/15340382/133394151-9b6661c1-72e3-4b25-b352-836ab8783ca9.png">

<img width="1085" alt="Screen Shot 2021-09-15 at 10 00 42" src="https://user-images.githubusercontent.com/15340382/133394342-1532bb12-e054-4f27-ae4c-1d6aa2ede09e.png">

#### Reproduce

I made a sample project that reproduces the issue: 
[KingfisherArchiveIssue.zip](https://github.com/onevcat/Kingfisher/files/7168018/KingfisherArchiveIssue.zip)

Select "Any iOS Device (arm64)" and try to build (or archive).

**Comment by onevcat** [comment]
Duplicated as #1725

As indicated in the Xcode 13 release note:

> Swift libraries may fail to build for iOS targets that use armv7. (74120874)
> Workaround: Increase the platform dependency of the package to v12 or later.

For now, using SPM requires a target version in Kingfisher's `Package.swift` to iOS `.v12` and it was released as a part of Kingfisher v7 (currently in beta).

If you still need to use Kingfisher v6 with Xcode 13, choose another integrating way (CocoaPods, Carthage or so).

**Comment by TizianoCoroneo** [comment]
> For now, using SPM requires a target version in Kingfisher's `Package.swift` to iOS `.v12` and it was released as a part of Kingfisher v7 ([currently in beta](https://github.com/onevcat/Kingfisher/releases), but should be quite stable) and here is the [migration guide](https://github.com/onevcat/Kingfisher/wiki/Kingfisher-7.0-Migration-Guide).
> 
> If you still need to use Kingfisher v6 with Xcode 13 (say, you still need to support iOS 10 and 11), choose another integrating way (CocoaPods, Carthage or so).

We have a minimum deployment target of iOS 13.2 and we still have this issue. For us there is no migration path possible without dropping iOS 13, and moving to KF v7, unless we make our own fork and bump KF's target version.

**Comment by onevcat** [comment]
@TizianoCoroneo 

That is also a reasonable workaround for now to fork from v6 and only update the deployment target version without any changes of other part, until you are prepared to migrate to the new Kingfisher version 7.

**Comment by panviktor** [comment]
Hi, you can use Xcode 13+ and Kingfisher and iOS 11 (tested) if you will remove pods and install from SPM

**Comment by ZeroOnet** [comment]
Use Xcode 13 Release and drop support under iOS 11 will fix for me. 
emmmm.... Maybe Apple Document have a mistake!

**Comment by Siemian** [comment]
Since my min supported iOS version is 13.0.
This did the trick for me to fix cocoapods integration:
```
post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
```

**Comment by ZeroOnet** [comment]
> Use Xcode 13 Release and drop support under iOS 11 will fix for me.
> emmmm.... Maybe Apple Document made a mistake!

Some project need to modify configuration as follows:

```ruby
post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end
```
Confused behaviour! 😂

**Comment by ZeroOnet** [comment]
> > Use Xcode 13 Release and drop support under iOS 11 will fix for me.
> > emmmm.... Maybe Apple Document made a mistake!
> 
> Some project need to modify configuration as follows:
> 
> ```ruby
> post_install do |pi|
>     pi.pods_project.targets.each do |t|
>         t.build_configurations.each do |config|
>             config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
>         end
>     end
> end
> ```
> 
> Confused behaviour! 😂

We noticed this issue can be fixed by changing Project Format to Xcode 3.2-compatible within iOS 11. And then Architectures became `ARCHS_STANDARD_64_BIT`, Archiving will not include armv7. But We recommend to set Xcode 12.0-compatible.

**Comment by onevcat** [comment]
For anyone still need to use Kingfisher v6 (for supporting iOS 11 UIKit or iOS 13 SwiftUI), but wants to use it in Xcode 13, now there is a compatible branch `version6-xcode13`. Pointing your dependency of Kingfisher to that branch would help you to avoid this issue.

The only change in that branch, compared to the released 6.3.1, is dropping of iOS 10 for UIKit support. That allows Xcode 13 skip the ARMv7 compilation so it won't trigger this issue anymore. That branch would exist for at least one year so you can migrate to version 7 eventually.

Again, the deployment increment in Kingfisher v7 (iOS 12 for UIKit, iOS 14 for SwiftUI) is intended and important to provide a correct data model. If you do not need to support older system anymore, it is encouraged to upgrade to the latest version.

**Comment by VilemKurz** [comment]
We use 6.3.0, have iOS 11 support and build/archive with Xcode13 with no problem - however - we already had in our podfile what @ZeroOnet recommends [here](https://github.com/onevcat/Kingfisher/issues/1802#issuecomment-939268592). That is the alternative solution for those who do not want to switch to `version6-xcode13` branch

**Comment by zhudi12358** [comment]
因为项目需要适配iOS10，并且项目没有使用到swiftui，所以就使用ruby脚本将报错相关代码移除掉
在Podfile文件中添加以下钩子函数，然后运行pod install

pre_install do |installer|
    remove_swiftui()
end

def remove_swiftui
  system("rm -rf ./Pods/Kingfisher/Sources/SwiftUI")
  code_file = "./Pods/Kingfisher/Sources/General/KFOptionsSetter.swift"
  code_text = File.read(code_file)
  code_text.gsub!(/#if canImport\(SwiftUI\) \&\& canImport\(Combine\)(.|\n)+#endif/,'')
  system("rm -rf " + code_file)
  aFile = File.new(code_file, 'w+')
  aFile.syswrite(code_text)
  aFile.close()
end

**Comment by onevcat** [comment]
Xcode 13.2 was released (as RC although) in which a fix for this is contained. Now even Kingfisher v6 could be used in Xcode 13.2.
