### ISSUE TITLE
Kingfisher找不到对应SwiftUI的东西 

### ISSUE THREAD

**Issue by GFredR** [onevcat/Kingfisher#1809]
喵神您好，我更新了Xcode 13和您的最新版本的Kingfisher，但是不是创建的SwiftUI项目，项目报错找不到SwiftUI的相关东西，我导入了SwiftUI但是仍然报错，请问这个是Xcode 13的锅吗
<img width="424" alt="A34439FF-8D17-4C22-8911-07A21B7237DC" src="https://user-images.githubusercontent.com/31023863/134306301-5cf87fc1-ff11-4ecc-bd1c-6037b9bbe7f8.png">
？

**Comment by onevcat** [comment]
是的！

Duplicated #1802 

[Xcode 13 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes)

> ### Known Issues 
> Swift libraries may fail to build for iOS targets that use armv7. (74120874)
> Workaround: Increase the platform dependency of the package to v12 or later.
>
> Swift libraries depending on Combine may fail to build for targets including armv7 and i386 architectures. (82183186, 82189214)
> Workaround: Use an updated version of the library that isn’t impacted (if available) or remove armv7 and i386 support (for > example, increase the deployment target of the library to iOS 11 or higher).

This is not a thing can be fixed easily in a library like Kingfisher. So please try to upgrade to Kingfisher v7 (and consider to drop support under iOS 12).
