### ISSUE TITLE
Extension on UIImageView/UIButton to cancel download

### ISSUE THREAD

**Issue by vCrespoP** [onevcat/Kingfisher#181]
Hi, I only miss this feature from SDWebImage, so I don't need to have a reference to the "task", just writing something like:

```myImageView.kf_cancelImageDownload() ```

Or whatever you find it's good naming, of course. It's really useful for list/collection views :D

Thank you!

**Comment by onevcat** [comment]
It is useful and seems not difficult to implement. I will add it later. Thanks for it.

**Comment by onevcat** [comment]
Implemented in #185
