### ISSUE TITLE
6.3.1版本，xcode更新到13，报错

### ISSUE THREAD

**Issue by CtrlJone** [onevcat/Kingfisher#1810]
![image](https://user-images.githubusercontent.com/8390188/134307634-182264f3-9a11-473b-b079-9bdf6e59b912.png)

**Comment by onevcat** [comment]
Duplicated #1802

**Comment by CtrlJone** [comment]
哥，我是用的 cocopad集成的kf，但是一直报这个错误是什么原因呢？我们需要支持ios10，11的版本，没法升级到v7

**Comment by CtrlJone** [comment]
> Duplicated #1802

哥，我是用的 cocopad集成的kf，但是一直报这个错误是什么原因呢？我们需要支持ios10，11的版本，没法升级到v7

**Comment by CtrlJone** [comment]
> Duplicated #1802

我也看了1802，好像没有解决我的这种问题

**Comment by onevcat** [comment]
> 我们需要支持ios10，11的版本，没法升级到v7

这种情况的话暂时没什么办法，只能继续用 Xcode 12，然后等着看 Xcode 13.1 之类的能不能修好了，绕不过去的。

**Comment by CtrlJone** [comment]
> > 我们需要支持ios10，11的版本，没法升级到v7
> 
> 这种情况的话暂时没什么办法，只能继续用 Xcode 12，然后等着看 Xcode 13.1 之类的能不能修好了，绕不过去的。

暂时把涉及的SwiftUI的文件去除掉就可以临时解决，虽然这样不是很稳妥，但暂时项目用不到swiftUI，算是可以勉强解决我的问题，这里还是要感谢喵神的库，一直致力于提高生产力
