### ISSUE TITLE
使用Carthage(0.38.0) update时候build failed.

### ISSUE THREAD

**Issue by yn288163** [onevcat/Kingfisher#1815]
由于项目支持的最低版本是11.0，想继续使用6.0版本的Kingfisher，但是使用`carthage update --use-xcframeworks --platform iOS --no-use-binaries`后出现Build Failed的情况。

Cartfile文件中的配置为`github "onevcat/Kingfisher" ~> 6.0`

问题在5.0和6.0的时候发生，4.0和最新的7.0都可以成功。
其它的第三方库也暂时没有发现问题。

Carthage版本：`0.38.0`
Xcode版本：`13.0`
Mac os版本：`11.6 `

错误信息如下：
```
Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/ink/Desktop/project_path/Carthage/Checkouts/Kingfisher/
Kingfisher.xcworkspace -scheme Kingfisher -configuration Release -derivedDataPath /Users/ink/Library/Caches/
org.carthage.CarthageKit/DerivedData/13.0_13A233/Kingfisher/6.3.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO 
CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO 
-archivePath /var/folders/vw/_lz28zt57yjgsyy2skwq6w0c0000gn/T/Kingfisher SKIP_INSTALL=YES 
GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO 
(launched in /Users/ink/Desktop/project_path/Carthage/Checkouts/Kingfisher)
```

**Comment by EdgarDegas** [comment]
只能用回 Xcode 12。

**Comment by onevcat** [comment]
Duplicated #1802

**Comment by onevcat** [comment]
> 其它的第三方库也暂时没有发现问题。

任何依赖了 Combine 的库都不行（就算你不在项目中使用）。Kingfisher 为了方便使用，选择了把 SwiftUI 的支持也放到了同一个 package 里，所以避免不了依赖 SwiftUI 和 Combine。

> Swift libraries depending on Combine may fail to build for targets including armv7 and i386 architectures. (82183186, 82189214)
> Workaround: Use an updated version of the library that isn’t impacted (if available) or remove armv7 and i386 support (for
example, increase the deployment target of the library to iOS 11 or higher).

这个是 Xcode 13 的 bug，暂时 Kingfisher 没有除了升级到 v12 的办法来绕开这个编译的问题。如果您还需要支持 iOS 11 的话，建议是暂时继续用一段时间 iOS 12，看看 Apple 能不能在 Xcode 13.1 修好。

**Comment by yn288163** [comment]
> > 其它的第三方库也暂时没有发现问题。
> 
> 任何依赖了 Combine 的库都不行（就算你不在项目中使用）。Kingfisher 为了方便使用，选择了把 SwiftUI 的支持也放到了同一个 package 里，所以避免不了依赖 SwiftUI 和 Combine。
> 
> > Swift libraries depending on Combine may fail to build for targets including armv7 and i386 architectures. (82183186, 82189214)
> > Workaround: Use an updated version of the library that isn’t impacted (if available) or remove armv7 and i386 support (for
> > example, increase the deployment target of the library to iOS 11 or higher).
> 
> 这个是 Xcode 13 的 bug，暂时 Kingfisher 没有除了升级到 v12 的办法来绕开这个编译的问题。如果您还需要支持 iOS 11 的话，建议是暂时继续用一段时间 iOS 12，看看 Apple 能不能在 Xcode 13.1 修好。

好的，谢谢
