### ISSUE TITLE
Xcode13 canImport is not recognized

### ISSUE THREAD

**Issue by SummerTimer2016** [onevcat/Kingfisher#1816]
use Xcode13  Archive , happen not find 'Binding' and not find 'Image'

**Comment by DeadHipo** [comment]
+

**Comment by DeadHipo** [comment]
Reproduced when use SwiftPM,  maybe problem here `#if canImport(SwiftUI) && canImport(Combine)`

Add via cocoapods solve problem

**Comment by EdgarDegas** [comment]
You guys should browse the existing issues before creating a new one.

Anyway, the resolution is rather simple: upgrade to Kingfisher 7.0.0. While it might be also catastrophic depending on your project, since you have to drop support for all users under iOS 12.0.

Check [issue#1802](https://github.com/onevcat/Kingfisher/issues/1802) and [issue#1725](https://github.com/onevcat/Kingfisher/issues/1725). Also this [migration guide](https://github.com/onevcat/Kingfisher/wiki/Kingfisher-7.0-Migration-Guide).

**Comment by Arrankar** [comment]
Hello. Version 7.0, but still have troubles with building. Has anyone solved this problem? 

<img width="317" alt="Снимок экрана 2021-09-23 в 20 34 32" src="https://user-images.githubusercontent.com/38263241/134556519-f8c13d57-568e-49ee-9039-282d78be7e52.png">

**Comment by EdgarDegas** [comment]
> Hello. Version 7.0, but still have troubles with building. Has anyone solved this problem?
> 
> <img alt="Снимок экрана 2021-09-23 в 20 34 32" width="317" src="https://user-images.githubusercontent.com/38263241/134556519-f8c13d57-568e-49ee-9039-282d78be7e52.png">

iOS < 12.0 is no longer supported.

**Comment by Arrankar** [comment]
> > Hello. Version 7.0, but still have troubles with building. Has anyone solved this problem?
> > <img alt="Снимок экрана 2021-09-23 в 20 34 32" width="317" src="https://user-images.githubusercontent.com/38263241/134556519-f8c13d57-568e-49ee-9039-282d78be7e52.png">
> 
> iOS < 12.0 is no longer supported.

But our application is for iOS 12 and newer...

<img width="456" alt="Снимок экрана 2021-09-23 в 22 51 40" src="https://user-images.githubusercontent.com/38263241/134574738-fa08661a-fb1f-40b2-b96a-22b5da8ae8a5.png">

**Comment by Arrankar** [comment]
> > Hello. Version 7.0, but still have troubles with building. Has anyone solved this problem?
> > <img alt="Снимок экрана 2021-09-23 в 20 34 32" width="317" src="https://user-images.githubusercontent.com/38263241/134556519-f8c13d57-568e-49ee-9039-282d78be7e52.png">
> 
> iOS < 12.0 is no longer supported.

Thank u! I solved the problem by correcting iOS 10 to iOS 12 in my PodFile. 

```
post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
  end
 end
end
```

**Comment by andrei115** [comment]
> You guys should browse the existing issues before creating a new one.
> 
> Anyway, the resolution is rather simple: upgrade to Kingfisher 7.0.0. While it might be also catastrophic depending on your project, since you have to drop support for all users under iOS 12.0.
> 
> Check [issue#1802](https://github.com/onevcat/Kingfisher/issues/1802) and [issue#1725](https://github.com/onevcat/Kingfisher/issues/1725). Also this [migration guide](https://github.com/onevcat/Kingfisher/wiki/Kingfisher-7.0-Migration-Guide).

It's not catastrofic to drop support for iOS 12.0, but it is to drop support for iOS 13.0, if the app is written in SwiftUI like in my case

**Comment by onevcat** [comment]
@andrei115 For SwiftUI support, it is the planned dropping of iOS 13 support (and starting from iOS 14) since we need to use `@StateObject` to make the image loading logic correctly following SwiftUI design pattern. SwiftUI on iOS 13 is so broken and brings very heavy maintenance burden.

**Comment by andrei115** [comment]
@onevcat I know, but still...I am not able to get away with not supporting ios 13 for a production grade app, considering it accounts to about 8% of user base. 
Fortunately, I managed to solve this by copying Kingfisher 6.3 source code in my app and it seems to work fine.

**Comment by onevcat** [comment]
@andrei115 
Wow, that's nice! Thanks for the feedback. Really wish Apple could fix this in the toolchain :(
