### ISSUE TITLE
Latest 7.00V7 doesn't load image on A9 device, iOS 14.8, Xcode 13.0, macOS 11.6

### ISSUE THREAD

**Issue by iaomw** [onevcat/Kingfisher#1819]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [x] I want to report a problem instead of asking a question.  

### Issue Description
As the title above. I updated to 7.00V7 with my project, it works fine on iOS simulator and A12 device. But the image never came up on old A9 device with iOS 14.8. And there is no warning no error. I already confirmed there is no connect problem from this device to server.

#### What
![IMG_5566](https://user-images.githubusercontent.com/2307692/134767152-39186558-a6a6-4c88-b362-a1c6f3b5a150.jpg)

#### Reproduce
It should be easy to reproduce it on A9 device. But I don't guarantee it.

```
KFImage.url(URL(string: preview_link ?? ""))
                                        .scaleFactor(scale)
                                        .backgroundDecode()
                                        .fade(duration: 0.2)
                                        .cancelOnDisappear(true)
                                        .placeholder {ProgressView()}
                                        .resizable().scaledToFit()
```

**Comment by iaomw** [comment]
Update. If the cache is cleaned or the app is clean installed, this version could load image without any problem.

Probably, there are some issue trying to reuse the existing cache created by elder version kingfisher.

**Comment by onevcat** [comment]
I have to say that is very weird..It sounds like that Kingfisher recognized that the file is cached (on disk), but it does not load correctly.

> And there is no warning no error

Do you still have any chance to add an `onFailure` block to see if the loading fails with some reason when this happen (if you have a way to reproduce it)? Normally, regardless of the result, there should be some error there:

```swift
KFImage(url)
  .onFailure { e in
    print("err: \(e)")
  }
```

**Comment by iaomw** [comment]
I guess it's not very possible to reproduce the bug.  The old cache has been cleaned in previous session.

I installed the old version of my app, cached some images, then updated to new version. But the bug didn't show up.
