### ISSUE TITLE
Load assets file when download error

### ISSUE THREAD

**Issue by josmanperez** [onevcat/Kingfisher#182]
Hello! 

I am trying to detect whether an image has not been downloaded. In my app, I have a server folder with all the images that I need and another server to obtain the information, and it could be the case when an image isn't there or just the server is down but I still have the information, what I want to achieve is to show a default image in my assets folder every time I could not download the corresponding image.

I've been reading the docs but can't figure out how to do it

Thank you so much for this incredible work 

:)

**Comment by onevcat** [comment]
Maybe you could just use the UIImageView extension with placeholder.

```swift
let defaultImage = UIImage(named: "your_default_image")
imageView.kf_setImageWithURL(URL, placeholderImage: defaultImage)
```

The `image` property of `imageView` will not be set when there is an error during getting image from disk or net. So you will keep the `defaultImage` shown when there is a downloading problem.

**Comment by josmanperez** [comment]
Yes...you were absolutely right. Thanks and sorry for such a silly question :)

Thanks again!
