### ISSUE TITLE
Cancel download via `downloadImageForURL`

### ISSUE THREAD

**Issue by schickling** [onevcat/Kingfisher#183]
Is there a way to cancel a download started via `ImageDownloader.downloadImageForURL`?
Shouldn't it return a task object or something like that?

**Comment by onevcat** [comment]
Good catch! I will give a patch on it later.

**Comment by onevcat** [comment]
Added in #184

**Comment by schickling** [comment]
Wow. That was fast @onevcat!
Thanks mate! :+1:
