### ISSUE TITLE
Kingfisher with LazyVGGrid (Xcode 13, iOS 15)

### ISSUE THREAD

**Issue by iOSappssolutions** [onevcat/Kingfisher#1839]
Hello,
I have problem when want to display LazyVGGrid that contains icons which images are downloaded, I just use KFImage.init(URL("https://something.png")) for each grid item and get this message below:

LazyVGridLayout: the ID Kingfisher.KFImage.Context<SwiftUI.Image> is used by multiple child views, this will give undefined results!

Result of that is that only one item in grid appears even thought there should be more.

**Comment by onevcat** [comment]
Thanks for your feedback!

Yes. Wrapping it in a container like another stack would omit the image from its direct parent, so the lazy stack won't see the same cell. But it is just a workaround and I am trying to see if we can have a solution for it.

**Comment by iOSappssolutions** [comment]
@onevcat  yeah I thought something like that may be the case. You are welcome, thank you for very fast response.
