### ISSUE TITLE
ios15  'Kingfisher', '~> 7.0'  有gif图片的列表会导致列表图片重用出现问题

### ISSUE THREAD

**Issue by TheCodeor** [onevcat/Kingfisher#1856]
滑动列表的时候会出现gif第一帧的图片加载到了其他位置导致显示错误

**Comment by onevcat** [comment]
听起来就是正常的 cell 重用，但是前面的图片在新图片加载时还在有显示的情况。
试试看在 cell 的 `prepareForReuse` 里把 image view 置空？
