### ISSUE TITLE
启动崩溃

### ISSUE THREAD

**Issue by dongq0916** [onevcat/Kingfisher#1874]
线上app启动时闪退， iOS13以上测试正常

iOS版本 12.3.1
设备 iPhone XR
kingfisher版本 7.1.1

![image](https://user-images.githubusercontent.com/12602855/143172506-0d48ebae-9605-4631-80c5-07f7f800e4ce.png)

**Comment by onevcat** [comment]
A temporary fix for it is contained in #1875 

I will prepare a release for it soon.
