### ISSUE TITLE
Issue in having 400+ rows in uitableview cell

### ISSUE THREAD

**Issue by iZeDeveloper** [onevcat/Kingfisher#1884]
i have uitableview of around 400+ rows, in which i download user avatar, the problem is if there is no cache and user scrolls too fast, when user reaches bottom cells, the images will start randomizing until the last cell, and after that its fine, i have canceled download tasks , will display , did end display all are implemented, i am not sure what is missing or problem here. i am sure, i must be doing something wrong, can you please have a look ?

**Comment by onevcat** [comment]
What are you doing to cancel the download task? I would suggest some identical thing like this: https://github.com/onevcat/Kingfisher/blob/master/Demo/Demo/Kingfisher-Demo/ViewControllers/NormalLoadingViewController.swift#L44-L51

It would be nice if you can paste some code snippet of exactly what you are doing, so I can help more.

**Comment by iZeDeveloper** [comment]
i took help from this example you pasted. 

 public func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        
            let item = viewModel.itemAtIndex(with: indexPath.row, section: indexPath.section)
        (cell as? ContactListingForSingleChatTableViewCell)!.startDownload(with: item)
    }
    public func tableView(_ tableView: UITableView, didEndDisplaying cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        (cell as? ContactListingForSingleChatTableViewCell)!.cancelDownload()
        /*
        if let cell = tableView.cellForRow(at: indexPath) as? ContactListingForSingleChatTableViewCell {
            
        }
        */
    }

**Comment by iZeDeveloper** [comment]
https://user-images.githubusercontent.com/528785/145159985-11a4cd38-e244-4263-8554-96472587f179.mov

Please check the video

**Comment by onevcat** [comment]
What the content of `startDownload` and `cancelDownload`? Or in other word, how are you using Kingfisher to set an image and how you cancel it?

**Comment by iZeDeveloper** [comment]
![Screen Shot 2021-12-08 at 11 41 56 AM](https://user-images.githubusercontent.com/528785/145161067-2c1af903-f482-4f12-81d8-ee1faa84da1d.png)


`func setImageWithKF(with url: String, placeHolderImage: UIImage? = nil, backgroundColor: UIColor? = .clear, option: KingfisherOptionsInfo? = nil, contentMode: UIView.ContentMode = .scaleAspectFit) {
        self.contentMode = .center
        if placeHolderImage != nil {
            self.image = placeHolderImage
        }
        if backgroundColor != nil {
            self.backgroundColor = backgroundColor
        }
        guard let imageUrl = URL(string: url), url.count > 0 else {
            return
        }
        
            let resource = ImageResource(downloadURL: imageUrl)

            KingfisherManager.shared.retrieveImage(with: resource, options: option, progressBlock: nil) { result in
                switch result {
                case .success(let value):
                    self.contentMode = contentMode
                    self.image = value.image
                case .failure(let _):
                    break
                }
            }
    }`

**Comment by onevcat** [comment]
The `KingfisherManager` does not link your image view to its state, so you cannot cancel it by the image view `kf` extension.

I suggest if there is no special reason, you should always choose the image view extension methods to set the image: 

```swift
imageView.kf.setImage(with: url)
```

**Comment by iZeDeveloper** [comment]
ok, i will use kf then, many thanks for guidance.
