### ISSUE TITLE
Carthage build error

### ISSUE THREAD

**Issue by mrchenhao** [onevcat/Kingfisher#189]
The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/mrche/Library/Developer/Xcode/DerivedData/Kingfisher-aidfpiamhsnrtyedwcpobgclnjdw/Build/Intermediates/Kingfisher.build/Release-iphoneos/Kingfisher.build/Script-D1249CF91C12B01E002C62D8.sh
(1 failure)

1.9.0版本的Demo中存在强制转换，Swiftlint检测没通过，暂时指定1.8.5解决

**Comment by onevcat** [comment]
@mrchenhao Just want to confirm that did #190 fix it?

**Comment by mrchenhao** [comment]
@onevcat   Yes, i fix it in #190

**Comment by onevcat** [comment]
Cool, thanks for it.

**Comment by andreyz** [comment]
SwiftLint stops Carthage build from finishing. My Cartfile is
`github "onevcat/Kingfisher" "2.0.2"`

**Comment by andreyz** [comment]
@onevcat maybe you've forgot to include your custom `.swiftlint.yml`?

**Comment by onevcat** [comment]
The `.swiftlint.yml` is in the repo.
It seems to be the version problem. Since there is no version pinning option in SwiftLint, it will break since they added addition rules that produce an error. 

I will add a step of upgrading to latest `swiftlint` in Kingfisher's CI to prevent this happens again later.

**Comment by onevcat** [comment]
@andreyz Hi, just checked the latest version of SwiftLint and there are only warnings instead of error. Could I know the error log of yours? Which does prevent the building process?

**Comment by andreyz** [comment]
It was probably SwiftLint's fault. Just updated to v0.9.1 and Kingfisher builds with no errors

**Comment by onevcat** [comment]
Cool. Thanks let me know it. :)
