### ISSUE TITLE
Report errors  of SwiftUI 1.0 and  Kingfisher 6.3.1.

### ISSUE THREAD

**Issue by Yaozitao0322** [onevcat/Kingfisher#1894]
pod Kingfisher 6.3.1 in SwiftUI1.0 / iOS 13.
report error `Xcode is missing components needed to preview on IOS`.
selected Simulators of iOS15.

![image](https://user-images.githubusercontent.com/81727090/147461162-9633ae64-2279-4b6c-9efd-55b048d4ca52.png)
)

**Comment by onevcat** [comment]
Cannot reproduce it. Maybe it is an integrating error? Does linking SwiftUI strongly to your app/or to the Kingfisher target resolve this issue?

**Comment by odanu** [comment]
Had the same issue, within a non-swiftui project, freshly installed XCode 13.2.1 and Kingfisher 6.3.0 version.
Upgrading to KF7.0.0 fixed it.

**Comment by 4brunu** [comment]
I think the issue is that Kingfisher 6.X.Y is not compatible with Xcode 13.
Instead of pointing to a tag, you need to point to the following branch `version6-xcode13`.
Here is the info in the readme related to this.
https://github.com/onevcat/Kingfisher#requirements
