### ISSUE TITLE
现在支持APNG的图片吗

### ISSUE THREAD

**Issue by BlankSpace007** [onevcat/Kingfisher#1900]
支持的话，怎么使用
不支持的话，未来会不会支持

**Comment by onevcat** [comment]
暂时应该不支持。之后有计划把 [APNGKit](https://github.com/onevcat/APNGKit) 作为一个可选组件集成过来，但是并没有时间表（最近看起来能花在开源项目上的时间不容乐观）。

如果需要使用 APNG 的话，可以看看 APNGKit 的相关内容，然后自己做一下 download 和 cache 的部分（这两个组件在 Kingfisher 中是独立的，使用起来也应该不是很困难）。如果不需要像 Kingfisher 这样的 cache 管理，那直接自己下载然后扔给 APNGKit 就好了。
