### ISSUE TITLE
Won't Archive - but will run on device.

### ISSUE THREAD

**Issue by redimongo** [onevcat/Kingfisher#1906]
So I just updated the Kingfisher plugin and went to build for production and I got greeted with loads of errors. (see pic)
However I can run the app on my phone - just can't seem to archive.
<img width="607" alt="Screen Shot 2022-02-12 at 12 54 10 pm" src="https://user-images.githubusercontent.com/8399907/153697301-aa8f8cf1-4556-437c-a5af-13836d6592ac.png">

I am using the latest Xcode and the latest KingfisherSwiftUI.

**Comment by onevcat** [comment]
What is your version of Kingfisher? In the latest Kingfisher, there is already no KingfisherSwiftUI module. If you were upgrading across major versions, please read and follow the migration guides: https://github.com/onevcat/Kingfisher#migrating

**Comment by maybekylecodes** [comment]
I'm having the same issue on version 5.15.8 & 6.3.1 (need to support iOS 13)
I'm happy to provide any additional information if needed

**Comment by redimongo** [comment]
Solution is to upgrade to the latest version. 

If using 5.x.x version like I was. A few things have changed and you will need to redo some image code. Very easy fix though.

**Comment by canry41341** [comment]
> I'm having the same issue on version 5.15.8 & 6.3.1 (need to support iOS 13) I'm happy to provide any additional information if needed
> 
> EDIT:
> 
> I was able to successfully archive after updating the dependency version to `version6-xcode13` <img alt="Screen Shot 2022-02-13 at 4 32 14 PM" width="796" src="https://user-images.githubusercontent.com/16695327/153782462-4ac4d687-9578-4544-b74c-05fd55941aba.png">

can you please tell me how u solved the problem?, because i'm having the same issue.

**Comment by DrJapan** [comment]
I'm having the same issue, but for some reason can't seem to find the solution. If I compile using Xcode 11, with a target version of 12.0, and Kingfisher version 6.3.0, I have no issues. 

As soon as I move to Kingfisher version 6.3.1, or higher I can't archive. Upgrading to Xcode 13.2.1 and adding Kingfisher via SPM didn't solve the issue either. Any suggestions would be greatly appreciated.

Thank you!

**Comment by bcsezer** [comment]
are there any updates here? I have the same problem

**Comment by jakernodle** [comment]
I believe I may have had a similar Archive issue, so posting my solution just in case. Apologies if it's not the same.  In my case it ended up being a corrupt Derived Data file. Running the following command in terminal fixed it.

`rm -rf ~/Library/Developer/Xcode/DerivedData/*
`
