### ISSUE TITLE
Download image from Post request

### ISSUE THREAD

**Issue by nick70007** [onevcat/Kingfisher#1916]
Hello sir, in my SwiftUI app i am storing images to IPFS Data Store and they have recently made the url as a POST request from GET request. In that case the third party library is not able to render the image. How can i resolve this?

This is the example url i am trying to render

https://ipfs.infura.io:5001/api/v0/cat?arg=QmVHLDEY4DhzJeW7G47QgpdibU6QX8g8He6CS83qRbpcDB

**Comment by onevcat** [comment]
Maybe try the request modifier. Something like this:

```swift
KF.url(url)
  .requestModifier { $0.httpMethod = "POST" }
  .set(to: imageView)
```

For more information, you can check [the related wiki](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending).

**Comment by onevcat** [comment]
Oh, for SwiftUI app, use the `KFImage` instead of `KF`, and there is also a same `.requestModifier` modifier.

**Comment by nick70007** [comment]
> Oh, for SwiftUI app, use the `KFImage` instead of `KF`, and there is also a same `.requestModifier` modifier.

yeah let me try

**Comment by nick70007** [comment]
> ```swift
> .set(to: imageView)
> ```

not working

**Comment by nick70007** [comment]
> > ```swift
> > .set(to: imageView)
> > ```
> 
> not working

not able to use .set and i am using SwiftUI

**Comment by nick70007** [comment]
can you give me an swift ui example @onevcat

**Comment by onevcat** [comment]
For SwiftUI, just change to `KFImage`:

```swift
KFImage.url(url)
  .requestModifier { $0.httpMethod = "POST" }
```
