### ISSUE TITLE
set cache expire time for KFImage for SwiftUI

### ISSUE THREAD

**Issue by carlhung** [onevcat/Kingfisher#1922]
is it possible to set cache expire time for KFImage?

**Comment by onevcat** [comment]
`KFImage` is using the same cache as for its UIKit variance, so you can still [use this](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#set-default-expiration-for-cache) to set a global expiration.

```swift
// Memory image expires after 10 minutes.
ImageCache.default.memoryStorage.config.expiration = .seconds(600)

// Disk image never expires.
ImageCache.default.diskStorage.config.expiration = .never
```

 If you want to set a per task expiration, use the corresponding modifiers:

```swift
KFImage(url)
  .memoryCacheExpiration(StorageExpiration)
  .diskCacheExpiration(StorageExpiration)
```
