### ISSUE TITLE
CarPlay ?

### ISSUE THREAD

**Issue by redimongo** [onevcat/Kingfisher#1929]
I am trying use KFImage for my apple CarPlay screen item.setImage = KFImage
However CarPlay requires UIImage for setImage and I am wondering if we can wrap KF around UIImage.

 ```

              item.setImage(Downloader.downloadImageWithURL(url: station.imageurl))


class Downloader {
    
    class func downloadImageWithURL(url: String) -> UIImage! {
        let date = NSData(contentsOf: URL(string: url)!)
        return KFImage(url:url)
        //return UIImage(data: date! as Foundation.Data)
    }
}

```

I get 
`Cannot convert return expression of type 'KFImage' to return type 'UIImage?'`

**Comment by onevcat** [comment]
`KFImage` is for SwiftUI. In your case, since Kingfisher also supports CarPlay, maybe you can try the [extension methods here](https://github.com/onevcat/Kingfisher/blob/master/Sources/Extensions/CPListItem%2BKingfisher.swift). Just use it on a `CPListItem` should do the trick:

```swift
let item: CPListItem = //...
item.kf.setImage(with: url)
```
