### ISSUE TITLE
UIImageView contentMode 为UIViewContentModeTopLeft UIViewContentModeTopRight时，会造成图片的变形

### ISSUE THREAD

**Issue by frickyps** [onevcat/Kingfisher#1944]
当我设置图片为UIViewContentModeTopLeft ，或 UIViewContentModeTopRight模式时，用kf下载显示图片，图片会严重拉伸变形。

**Comment by onevcat** [comment]
Since there is no additional information and no way to reproduce this issue, I am closing it.
