### ISSUE TITLE
NSTextAttachment + KF 图片会模糊

### ISSUE THREAD

**Issue by cczufish** [onevcat/Kingfisher#1946]
KF.url(URL(string: avatar)!)
                .resizing(referenceSize: CGSize(width: 26, height: 26))
                .roundCorner(radius: .point(13))
                .set(to: attachment, attributedView: titleLabel)

NSTextAttachment + KF 图片会模糊

**Comment by onevcat** [comment]
resizing 的话会按照像素处理，如果没有指定 `scale` 默认会使用 1.0 (因为网络图片并没有默认的 scale)。可以考虑加上一个 `.scaleFactor` 来改善：

```swift
KF.url(URL(string: avatar)!)
  .scaleFactor(UIScreen.main.scale)
  .resizing(referenceSize: CGSize(width: 26, height: 26))
  .roundCorner(radius: .point(13))
  .set(to: attachment, attributedView: titleLabel)
```
