### ISSUE TITLE
is it available a zoom functionality???

### ISSUE THREAD

**Issue by PaolinoAngeletti** [onevcat/Kingfisher#1949]
simple request

**Comment by onevcat** [comment]
Not quite sure about what you mean by "zoom". Is the [`ResizingImageProcessor`](https://swiftpackageindex.com/onevcat/kingfisher/master/documentation/kingfisher/resizingimageprocessor) what you want?

**Comment by PaolinoAngeletti** [comment]
i mean the "pinch-to-zoom" function on the downloaded image.

**Comment by onevcat** [comment]
That is not an image feature but the view. It is not related to Kingfisher as an image downloading/cache framework. I would suggest you check some posts like this: https://stackoverflow.com/questions/30014241/uiimageview-pinch-zoom-swift
