### ISSUE TITLE
「iOS13.0~iOS13.2」didn't load image when use `Branch:version6-xcode13`

### ISSUE THREAD

**Issue by kangnux** [onevcat/Kingfisher#1964]
### Issue Description

I want to use Kingfisher in iOS13 with `swiftUI` in `UIHostingcontroller`, in 「iOS13.0~iOS13.2」it didn't load image but over iOS13.3 everything is ok.

### Version
Branch:version6-xcode13
Xcode:13.4
iOS: iOS13.0-iOS13.2

#### Reproduce
Code:
```
KFImage.url(url)
    .placeholder {
        placeholderContent
    }
    .fade(duration: 0.25)
    .resizable()
    .scaledToFit()
```

**Comment by onevcat** [comment]
Maybe again related to this Apple bug (https://github.com/onevcat/Kingfisher/issues/1717). Seems that the `objectWillSend` is not working well before iOS 13.3.

**Comment by onevcat** [comment]
A [new commit](https://github.com/onevcat/Kingfisher/commit/d0494dd78f7adf2d3526fdf3267176553020c041) was just appended to the `version6-xcode13` branch. 

@kangnux Can you help to verify and check how it works with that change? Thanks!

**Comment by kangnux** [comment]
https://github.com/onevcat/Kingfisher/commit/d0494dd78f7adf2d3526fdf3267176553020c041
👆Not work with this commit.

**Comment by onevcat** [comment]
Ummm. Any chance to try the demo sample in this repo? You can clone this repo, checkout the branch, and run the demo app in it. 

I do not have an iOS 13.0 device anymore, but it works fine in the simulator, as in the screenshot below.

![截屏2022-07-12 14 08 36](https://user-images.githubusercontent.com/1019875/178413168-4b965afe-027e-4f11-a897-0be4ef5b3480.png)

If it is working in the sample app but not in your project, I would suggest trying to confirm it is the correct commit in use. Try to clean the cache/project/app or reinstall the library. If still not working, can I have a minimal code snippet so I can also have another attempt?
