### ISSUE TITLE
How can I get the locally cached gif image data

### ISSUE THREAD

**Issue by plkgq** [onevcat/Kingfisher#1966]
How can I get the locally cached gif image data for saving to the album，The retrieveImage method only returns UIImage，but I need the data type

**Comment by onevcat** [comment]
Maybe try `image.kf.gifRepresentation()`? It gives you the data of that image, if it is a GIF:

```swift
imageView.kf.setImage(with: gifURL) { value in
  switch value {
  case .success(let result):
    let data = result.image?.kf.gifRepresentation()
  case .failure:
    break
  }
}
```

**Comment by plkgq** [comment]
3Q
