### ISSUE TITLE
Cannot find type 'Binding' in scope , Xcode  version 13.4.1 (13F100)

### ISSUE THREAD

**Issue by alijalali** [onevcat/Kingfisher#1969]
<img width="1114" alt="Screenshot 2022-07-16 at 20 03 15" src="https://user-images.githubusercontent.com/17569675/179364906-42929e57-9e56-41ca-8c2b-e71ff805faaa.png">

Hello , I am facing this error while archiving. I had the same problem before with other version of Kingfisher, i used package manager and problem solved but now i am facing this problem again. Used package manager and also  pods but no changes.

**Comment by sohaib-sajjad** [comment]
import SwiftUI
 add this line in your file

**Comment by ptrkstr** [comment]
Where did you add `import SwiftUI` @sohaib-sajjad ?
@alijalali did you resolve your issue?
I believe I'm experiencing the same.

**Comment by abesmon** [comment]
same problem here. Building for 10.3+ with Xcode 13.4.1. Kingfisher is 6.3.1 from spm. I can't update to kingfisher 7, because its 12+

**Comment by onevcat** [comment]
Can you try to add `SwiftUI.framework` to the Link Binary With Libraries and see how it can work? (Maybe you also need to set it to optional too, to allow it working with iOS 12 or earlier.)

![截屏2022-09-19 17 57 29](https://user-images.githubusercontent.com/1019875/190983032-dfbc75dd-5d47-4ddf-b94f-ae6e16680e89.png)

**Comment by abesmon** [comment]
@onevcat unfortunately it doesn't help :( Tried just now. I'm now trying to update to Xcode 14, so I'll report if that can fix the issue

**Comment by abesmon** [comment]
Xcode update not helping. Even worse ;( Xcode 14 says, that SPM package is 11+ (but in fact package is 10+)
In my situation it's easier to bump up to 11+ than trying to resolve the issue

**Comment by onevcat** [comment]
Xcode 14 has dropped the support for iOS 10 so it won't work for sure.

**Comment by onevcat** [comment]
By the way, if it is possible to drop iOS 10, then maybe you can try the `version6-xcode13` branch. I remember it is a special branch with some modifications to let the framework run under Xcode 13.

For any earlier version, I am now trying to see what is happening. But I cannot ensure that there would be a fix for that. Version 6 has been deprecated for a long time and there is no guarantee it can work with the recent Xcode versions.

**Comment by onevcat** [comment]
OK. I checked the reason and recalled the investigation long ago.

As [indicated here](https://github.com/onevcat/Kingfisher/issues/1802#issuecomment-940051756), SwiftUI only contains 64bit slice on device (arm64) so there is no way to link it to the target with 32bit environment (armv7). So you have to at least upgrade your deployment target to iOS 11 and please consider using the `version6-xcode13` branch.

| UIKit | SwiftUI | Xcode | Kingfisher |
|---|---|---|---|
| iOS 10+ | iOS 13+ | 12 | ~> 6.3.1 |
| iOS 11+ | iOS 13+ | 13 | `version6-xcode13` |
| iOS 12+ | iOS 14+ | 13 | ~> 7.0 |

There seems to be no way to support iOS 10 under Xcode 13 or later with the SwiftUI part of Kingfisher.
