### ISSUE TITLE
在tableview列表使用它滑动的时候卡顿

### ISSUE THREAD

**Issue by chenfeilaksa** [onevcat/Kingfisher#1974]
感觉像是在绘制的时候堵塞了主线程，设置了.backgroundDecode好像没起作用

**Comment by ZClee128** [comment]
同样问题

**Comment by guiqiang107** [comment]
同样问题，cpu和内存都暴涨，低端机直接kill

**Comment by onevcat** [comment]
我们自己使用的没有发现什么问题。如果有更确切的信息，还请一并附上。

个人建议检查一下 cell 里加载的图像是不是太大。如果是无意义的高清图片的话，数量过多肯定会造成绘制和内存压力，可以考虑先用 [Downsampling 处理](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#using-downsamplingimageprocessor-for-high-resolution-images)一下。

因为没有什么特别有意义的信息，这个 issue 我先关了。如果能提出具体的问题或者例子的话，请再reopen。

**Comment by guiqiang107** [comment]
iphone6(低端机)上快速滑动tableView,cell上有几十kb的小图展示，当滑动速度很快时会导致卡主线程，跟了一下源码发现.backgroundDecode模式默认仅仅只会在下载的时候做后台解码工作，如果是已经下载到内存和磁盘缓存中，显示的时候并没有在后台解码，通过self.base.image = value.image直接将从缓存中拿到的image设置到了imageView上，这一步在主线程解码会卡主线程，所以这应该是卡顿的根本原因，设置了backgroundDecode但实际上没有起作用.测试做了以下优化后，主线程卡顿有较好的解决效果。
![image](https://user-images.githubusercontent.com/8225765/195787407-486cda69-3418-425e-8daf-d7419b0045ea.png)

**Comment by guiqiang107** [comment]
还有后台解码的时机问题，源码中实在下载图片完成后开始解码，但是当我快速滑动tableView列表时，有没有可能下载后解码的位图已经被系统回收掉，我再把tableView往回滑动到tableView的起始位置，此时图片已经下载到缓存中，滑回去后会从缓存中拿到图片，这种情况下载后解码的位图实际上已经没有实际的优化效果了(因为可能已经被系统回收了)，所以我觉得解码这一步的时机应该是在回调completionHandler之前，其他任务之后会不会更好一点呢？

**Comment by guiqiang107** [comment]
添加了这个处理内存改善不少 [Downsampling 处理](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#using-downsamplingimageprocessor-for-high-resolution-images)
