### ISSUE TITLE
这个内存导致的crash有什么处理方式吗

### ISSUE THREAD

**Issue by chenfeilaksa** [onevcat/Kingfisher#1985]
crash信息：
<img width="715" alt="WechatIMG58" src="https://user-images.githubusercontent.com/85677330/188570643-992ef6db-24a5-4df9-9de7-08d2b4d7591d.png">
<img width="963" alt="WechatIMG57" src="https://user-images.githubusercontent.com/85677330/188570671-06055549-e3b6-4324-b59f-1e26ae8d961b.png">

我在App启动时这样操作：
        KingfisherManager.shared.cache.memoryStorage.config.totalCostLimit = 300 * 1024 * 1024
        
        KingfisherManager.shared.cache.memoryStorage.config.countLimit = 150

但是好像并不能解决我这个问题,totalCostLimit、countLimit应该怎样去设置呢

**Comment by onevcat** [comment]
Any idea on how big this image is? If there is a chance that you are trying to load a huge image, it is possible that the cache limitation has no chance to be triggered before your memory goes out.

If you are trying to load an unnecessary huge image, try to use [`DownsamplingImageProcessor`](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#using-downsamplingimageprocessor-for-high-resolution-images) to get a smaller version of it, then show and cache it.

**Comment by chenfeilaksa** [comment]
好的，谢谢

目前不确定图片的尺寸大小，也不确定是哪里的具体某个视图造成的crash，我再追踪观察一下，然后再进行设置DownsamplingImageProcessor 来优化它
