### ISSUE TITLE
Lots of typos in methods

### ISSUE THREAD

**Issue by alexdd55** [onevcat/Kingfisher#2]
there are a lot of typos e.g. retrive -> retrieve, cahe -> cache and so on...
this should be fixed with highest priority

**Comment by onevcat** [comment]
Thanks for pointing it out. Some of them should be fixed in #3 
But I cannot find "cahe" in the project.

**Comment by alexdd55** [comment]
no problem, you fixed that already in "retriveImageInMemoryCaheForKey" ;)

good job :)
