### ISSUE TITLE
Image does not load anymore when removed from cache

### ISSUE THREAD

**Issue by lukasrosenke** [onevcat/Kingfisher#2007]
I discovered this issue by coincidence. I have cards in my app which can have multiple pictures. However, by default, only the first image is displayed (and thus loaded). 
The images are loaded with KF and cached. The initial of download of all images works and behaves as expected. If i reload the app and thus the pictures, they are now fetched from the cache which also works as expected.
The problem is, if you do not click through the images and thus not load the images for a certain amount of time (i think the default is 7 days) they are removed from the cache. This also is intended and not the problem. However, the re-download of the images now does not work anymore. It keeps displaying an endless loading indicator.

**Comment by onevcat** [comment]
It is the first time we receive this kind of report. Considering the amount of Kingfisher users, I guess it might be something in your use case only.

You can set the cache expiration duration by code like this:

```swift
KingfisherManager.shared.cache.memoryStorage.config.expiration = .seconds(10)
KingfisherManager.shared.cache.diskStorage.config.expiration = .seconds(20)
```

So it should be quite easy to "simulate" the expiration situation. I myself do not meet the endless loading with these expiration configurations. May I know if it is possible to have a good way to reproduce this issue? Thanks!
