### ISSUE TITLE
If I use swiftUI how do I set the cookie?

### ISSUE THREAD

**Issue by csmagics** [onevcat/Kingfisher#2012]

**Comment by onevcat** [comment]
You can always use the `.requestModifier` to apply any modification to your request. (See the [wiki here](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending)) It is also available [as a modifier](https://swiftpackageindex.com/onevcat/kingfisher/master/documentation/kingfisher/kfimage/requestmodifier(_:)-l42h) of the `KFImage`.
