### ISSUE TITLE
Xcode Version 14.3 beta (14E5197f) build error

### ISSUE THREAD

**Issue by BestiOSDev** [onevcat/Kingfisher#2033]
Kingfisher 7.4.0

![image](https://user-images.githubusercontent.com/15530810/220024828-c2c8e86e-eca9-49ab-88ef-eeacabfaca40.png)

![image](https://user-images.githubusercontent.com/15530810/220024652-22d34c65-f60b-4863-b1e8-bc97da2101ba.png)

**Comment by onevcat** [comment]
Duplicated #2029 and version [7.6.1](https://github.com/onevcat/Kingfisher/releases/tag/7.6.1).

**Comment by BestiOSDev** [comment]
many thanks. use 7.6.1 build success
