### ISSUE TITLE
Kingfisher 7 fails to build in Xcode 14.3

### ISSUE THREAD

**Issue by konkontos** [onevcat/Kingfisher#2052]
I'm receiving the following when trying to build with the latest Xcode version:

<img width="2289" alt="ScreenCapture 2023-03-31 at 09 20 13" src="https://user-images.githubusercontent.com/67760/229039600-137b6342-b74c-4ce7-95f9-a0959f5fe762.png">

**Comment by ameyerow** [comment]
I'm getting the same issue

**Comment by stefanomondino** [comment]
Seems like it's already fixed and only waiting for proper release, am I wrong?

**Comment by MihailPreis** [comment]
If possible, update the dependency to 7.6.1 (https://github.com/onevcat/Kingfisher/pull/2029)

**Comment by onevcat** [comment]
This has already been fixed in 7.6.1 a month ago. Please try to upgrade your versions and check again.

> Changing the dependency (Either with SPM or Cocoapods) and having it pointing to master should be a good temporary workaround.

I would suggest performing a repo update or cache clear if it is the issue of a package manager not getting the latest versions.

**Comment by konkontos** [comment]
> This has already been fixed in 7.6.1 a month ago. Please try to upgrade your versions and check again.

Well noted. My bad for using `master` branch in the dependency.
Appreciate the quick response.

**Comment by dev-abdul02** [comment]
update it to latest pod/spm to 7.6.2 @skelet2394, by default SPM is set to 7.0

**Comment by lexuanquynh** [comment]
right click on the Kingfisher package and "Upadte package". It's work for me.

**Comment by animalcommunitydev-0116** [comment]
[!] CocoaPods could not find compatible versions for pod "Kingfisher":
In Podfile:
Kingfisher (~> 7.6.1)

Hi guys, not able to find version

**Comment by onevcat** [comment]
@animalcommunitydev-0116 Maybe you can try `pod repo update` and then run pod install/update again.

**Comment by stormpang** [comment]
[!] CocoaPods could not find compatible versions for pod "Kingfisher":
  In Podfile:
    Kingfisher (~> 7.6.1)

**Comment by stormpang** [comment]
how to fix it
