### ISSUE TITLE
Initializer for conditional binding must have Optional type, not 'AnyView'

### ISSUE THREAD

**Issue by Eric-Catalyst** [onevcat/Kingfisher#2054]
### Issue Description

Build error: Initializer for conditional binding must have Optional type, not 'AnyView' in KFImageRenderer.swift:48

#### What

The code has an "if let" for a non-optional value:

`if let placeholder = context.placeholder, let view = placeholder(binder.progress) {
`
contect.placeholder is an optional, but placeholder has type AnyView, not AnyView?

#### Reproduce

Update Xcode to Version 14.3 (14E222b), this error appears to be new with this version of Xcode.

#### Other Comment

Recommend this line be changed to: 

`if let placeholder = context.placeholder {
     let view = placeholder(binder.progress)
`

**Comment by ayhanhakan** [comment]
same issue

**Comment by Eric-Catalyst** [comment]
See this has been fixed already

**Comment by ailinykh** [comment]
fixed in #2029

**Comment by iOSdevManoj** [comment]
Hello @Eric-Catalyst 
I'm using pod pod 'Kingfisher', '~> 7.4.1'  how can fix this? can you suggest if you have any idea?
Thank You

**Comment by onevcat** [comment]
@iOSdevManoj 

Usually a `pod update` can help you out. If not, please check to see if you have the latest repo by `pod repo update` or explicitly set the Kingfisher's version to things like `pod 'Kingfisher', '~> 7.6.2'`, remove your Pods folder and run `pod install` again.
