### ISSUE TITLE
https://i.imgur.com/uoBwCLj.gif 这张gif图加载不出来，一直提示"The request timed out"

### ISSUE THREAD

**Issue by MingYik** [onevcat/Kingfisher#2067]
# https://i.imgur.com/uoBwCLj.gif 这张gif图加载不出来，一直提示"The request timed out", 但是网页可以显示出来，请问喵神这个是什么原因呢，是因为图片太大了么？
![1682476263480](https://user-images.githubusercontent.com/5554494/234451441-d94c5c90-1e41-449c-afb5-171b6c779c5f.jpg)

以下是错误信息：
`Task <E0639A58-51C2-4A5F-9C43-0F6B55EA511F>.<1> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x281a10480 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <E0639A58-51C2-4A5F-9C43-0F6B55EA511F>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <E0639A58-51C2-4A5F-9C43-0F6B55EA511F>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://i.imgur.com/uoBwCLj.gif, NSErrorFailingURLKey=https://i.imgur.com/uoBwCLj.gif, _kCFStreamErrorDomainKey=4}`

**Comment by onevcat** [comment]
<img width="1106" alt="截屏2023-04-26 11 53 50" src="https://user-images.githubusercontent.com/1019875/234454651-54d2e51f-614a-45b4-9fa9-eb9c57ba0c87.png">

我这边变没什么问题呢...个人建议检查一下手机或者模拟器的网络情况，是不是有需要翻墙的原因...

**Comment by MingYik** [comment]
谢谢，是翻墙的原因
