### ISSUE TITLE
KFImage missing options object?

### ISSUE THREAD

**Issue by LilaQ** [onevcat/Kingfisher#2069]
Hi there,

I'm stumped right now, I've been reading up for the last 2 hours, but can't make any progress: 
- How do I add options / requestModifier to a KFImage in SwiftUI ?

I've even seen video tutorials that show an options object being passed to the initialiser, but it seems like that's not possible anymore? 

I tried looking through the classes & protocols and couldn't make any sense of it.

(Latest Kingfisher installed by github -> SPM)

**Comment by onevcat** [comment]
I think it is just the `requestModifier`

![截屏2023-04-30 16 02 36](https://user-images.githubusercontent.com/1019875/235340298-d061dd91-3745-44e9-9dc5-bdf2cb6c9f45.png)

Can you try this?

```swift
KFImage(url)
  .requestModifier({ request in
    request.setValue("Hello", forHTTPHeaderField: "World")
  })
```
