### ISSUE TITLE
Clarify WebP support on documentation

### ISSUE THREAD

**Issue by tfcporciuncula** [onevcat/Kingfisher#2072]
The current documentation around WebP support is giving mixed signals as [the wiki says](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#creating-your-own-processor):

>WebpFramework is an external framework you may use to parse WebP data. Currently, Kingfisher does not support WebP image out of the box.

But then there’s [this comment here](https://github.com/onevcat/Kingfisher/issues/1778#issuecomment-901601660) from @onevcat saying:

>This is a WebP image and only built-in supported from iOS 14.

Which also points to [the FAQ where it says](https://github.com/onevcat/Kingfisher/wiki/FAQ#can-i-load-some-special-image-format-like-webp):

>Can I load some special image format like WebP?
>
>Yes, but it is not built-in supported in Kingfisher. You may need to implement your own `ImageProcessor` and `CacheSerializer`. It is also already done by some other libraries, for example, [KingfisherWebP](https://github.com/yeatse/KingfisherWebP). For more discussion on this topic, search for "webp" in the issues.

It’s not clear to me whether [iOS 14 built-in support](https://developer.apple.com/documentation/uniformtypeidentifiers/uttype/3551599-webp) is automatically “absorbed" into Kingfisher or not, and I think the wiki and the FAQ could be a bit more clear about this answering in an explicit way whether WebP is supported by Kingfisher on iOS 14+ or not.

If possible, I’d prefer to avoid using KingfisherWebP since it doesn’t seem very active and based on [this comment](https://github.com/yeatse/KingfisherWebP/issues/59#issuecomment-948205320) from the author they’re not yet taking advantage of the iOS 14 support?

>I also noticed that from iOS 14 webp format has a built-in support. We're planning to implement this feature to reduce the memory footprint in iOS 14 devices.

[I’ve asked about this on StackOverflow](https://stackoverflow.com/questions/76121385/does-kingfisher-support-webp-on-ios-14), but I thought it would make sense to file an issue here as well since I believe the wiki could be improved regardless of the answer.

**Comment by YoLogi** [comment]
Solution:

The Kingfisher library supports WebP images on iOS 14+.

To use WebP images with Kingfisher, follow these steps:

1. Ensure that you are using the latest version of Kingfisher.
2. Add the following line of code to your project's Podfile:

pod 'Kingfisher/WebP'

3. Run 'pod install' to install the KingfisherWebP dependency.
4. Use the 'kf.setImage(with:)' method to load WebP images with Kingfisher.

If you encounter any issues, please refer to the Kingfisher documentation or contact the Kingfisher support team for assistance.

Thank you for using Kingfisher!

**Comment by tfcporciuncula** [comment]
>The Kingfisher library supports WebP images on iOS 14+.

But only if I use [KingfisherWebP](https://github.com/yeatse/KingfisherWebP)? Based on my tests, WebP has been working fine without KingfisherWebP on iOS 14+, so do I really need it?

**Comment by onevcat** [comment]
@tfcporciuncula 

You do not need any external library if you are deploying to iOS 14+. The wiki is outdated and I will try to update it now. Thanks for reporting!
