### ISSUE TITLE
XCode15打包问题

### ISSUE THREAD

**Issue by crazypoo** [onevcat/Kingfisher#2089]
ITMS-90338: Non-public API usage - The app links to non-public libraries in Frameworks/Kingfisher.framework/Kingfisher: /System/Library/PrivateFrameworks/AVFCore.framework/AVFCore

**Comment by onevcat** [comment]
I don't believe Kingfisher is linking to any private framework or performing any trick like that.

Xcode 15 is still in early beta and you cannot submit your app with the beta version. So it is high possible a false positive. I suggest waiting for a few months and see what would change.

**Comment by crazypoo** [comment]
ok,wait

**Comment by guo-pf** [comment]
Successfully used cocoapods, but failed to use Carthage.
 
carthage bootstrap --platform iOS --cache-builds --use-xcframeworks
... ... ...
*** Downloading Kingfisher binary at "7.9.1 - Lastest Xcode 15 beta"
*** Building scheme "Kingfisher" in Kingfisher.xcworkspace
Build Failed
  Task failed with exit code 65:
... ... ...
The following build commands failed:
  CompileSwift normal arm64 (in target 'Kingfisher' from project 'Kingfisher')
  SwiftCompile normal arm64 Compiling\ ImageModifier.swift,\ CacheSerializer.swift
... ... ...
