### ISSUE TITLE
大神,您好,请教个问题:kingfisher是以怎样一个思路解决gif图片的性能问题(SDWebImage存在的问题)

### ISSUE THREAD

**Issue by stackJolin** [onevcat/Kingfisher#211]
大神,您好,请教个问题:kingfisher是以怎样一个思路解决gif图片的性能问题(SDWebImage存在的问题)

**Comment by onevcat** [comment]
SDWebImage 存在这个问题么？不清楚，有相关的 issue 么？

**Comment by 110440** [comment]
kingfisher gif 的内存太高了，我用YYWebImage 没事，，这个有什么办法吗

**Comment by 110440** [comment]
或者怎么样不用你的默认解码GIF?
