### ISSUE TITLE
About cache

### ISSUE THREAD

**Issue by ed-mejia** [onevcat/Kingfisher#212]
Hi guys, One question about this great library :smile: 

In my app I will require to download a set of images, let say 100... one requirement is to keep all those images available for offline use once downloaded the first time.

Is there any feature in the actual cache that allows me to keep any cached images indefinitely on Disk?

Thanks.

**Comment by onevcat** [comment]
Hi, there is no guarantee for a cache to be accessible indefinitely on disk. If so, it should not be a cache, but a persistence. Kingfisher is using the cache folder of your app to store the disk cache, which could be wiped by system whenever the device disk space is not enough.

You could set the `maxCachePeriodInSecond` and `maxDiskCacheSize` to something large, or infinity. By doing this, Kingfisher will never remove your disk cache and you could expect a long period of the cache. However, as said above, it does not guarantee a persistence store.

You could consider to download them and store the data in Document folder. But from Apple's guide, if the content is not user created and could be restored later, it should be placed in cache folder, or your app may in a risk to be rejected.

**Comment by ed-mejia** [comment]
Thanks @onevcat that's what I was thinking :disappointed_relieved:
