### ISSUE TITLE
Kingfisher.KingfisherError.ImageSettingErrorReason.emptySource

### ISSUE THREAD

**Issue by vanniktech** [onevcat/Kingfisher#2127]
I use the following code:

```
KFImage(URL(string: url))
    .resizing(referenceSize: CGSize(width: 100, height: 0), mode: .aspectFill)
    .onFailure {
        print("NII: \($0) at \(url)")
    }
```

to load an image from this url: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhRbLu9dwRmje0uCorM452KkwrinxAkJyLAnOFrnSudSoG2Fa79AqULGQCYMSwFtaRN8NEzxvcm7pF0ZJ6lZ1tb0b67RIjEEkOlUAxnP1Y0VpEzLj_8M7WPdb7WxVI4umj-QJrpY-90y0iesZogD0uNKwMgwscJil8BzQvb0dgyiUshYEYv2uMrtb5txWNk/s320/Café_expreso_corto.jpg

If you open this in the browser, it also loads correctly. However on my Simulator running with Kingfisher 7.9.0 & iOS 16.4 I'm getting:

> NII: imageSettingError(reason: Kingfisher.KingfisherError.ImageSettingErrorReason.emptySource) at https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhRbLu9dwRmje0uCorM452KkwrinxAkJyLAnOFrnSudSoG2Fa79AqULGQCYMSwFtaRN8NEzxvcm7pF0ZJ6lZ1tb0b67RIjEEkOlUAxnP1Y0VpEzLj_8M7WPdb7WxVI4umj-QJrpY-90y0iesZogD0uNKwMgwscJil8BzQvb0dgyiUshYEYv2uMrtb5txWNk/s320/Café_expreso_corto.jpg

**Comment by onevcat** [comment]
Usually, it means the you are passing in a `nil` to Kingfisher as the URL. I noticed that you have a letter `é` in your URL string, which does not result a valid `URL` when given to `URL(string:)` method:

```
let url = URL(string: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhRbLu9dwRmje0uCorM452KkwrinxAkJyLAnOFrnSudSoG2Fa79AqULGQCYMSwFtaRN8NEzxvcm7pF0ZJ6lZ1tb0b67RIjEEkOlUAxnP1Y0VpEzLj_8M7WPdb7WxVI4umj-QJrpY-90y0iesZogD0uNKwMgwscJil8BzQvb0dgyiUshYEYv2uMrtb5txWNk/s320/Café_expreso_corto.jpg")

// url is nil
```

Instead, try

```swift
let urlComp = URLComponents(string: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhRbLu9dwRmje0uCorM452KkwrinxAkJyLAnOFrnSudSoG2Fa79AqULGQCYMSwFtaRN8NEzxvcm7pF0ZJ6lZ1tb0b67RIjEEkOlUAxnP1Y0VpEzLj_8M7WPdb7WxVI4umj-QJrpY-90y0iesZogD0uNKwMgwscJil8BzQvb0dgyiUshYEYv2uMrtb5txWNk/s320/Café_expreso_corto.jpg")
let url = urlComp?.url
```

**Comment by vanniktech** [comment]
Oh wow, crazy. Thanks for spotting this! It works now.
