### ISSUE TITLE
Problems with disk caching

### ISSUE THREAD

**Issue by uclort** [onevcat/Kingfisher#2129]
If you run the emulator, you can see the cache directory `Library/Caches/com.onevcat.Kingfisher.ImageCache.default`. If you clear the whole cache directory of Caches through FileManager, `com.onevcat.Kingfisher. ImageCache.default` directory will not be re-created after emptying the entire cache directory through FileManager, resulting in the inability to count the real cache size, and you can only re-open the app by killing it again to see `com.onevcat.Kingfisher.ImageCache.default` will be re-created.

Kingfisher version: 6.2.1

**Comment by onevcat** [comment]
This is an issue that the cache folder is not re-created if the whole folder is deleted externally. It prevents the disk cache working expected until the next `ImageCache` creation (usually the next app session).

Fixed in #2162. Now we tried to re-create the cache folder if it does not exist.
