### ISSUE TITLE
No ability to load images as opaque

### ISSUE THREAD

**Issue by Arko4576** [onevcat/Kingfisher#213]
For performance reasons I like to set everything as opaque, now with blended layers on images loaded with Kingfisher are shown as blended. This could be caused by misaligned images to but through research I've seen that its possible to remove the alpha from downloaded images and with no obvious way to do this with Kingfisher I was wondering if this is a planned feature or maybe has a workaround?

**Comment by onevcat** [comment]
Thanks for mention it. I will check it later. And could you supply some reference for it, on removing the blend layer and how it could involve the performance.

Thank you.

**Comment by Arko4576** [comment]
So some googling revealed that by default images are rendered in a graphic context with alpha so to remove this you have to supply your own graphics context where you remove the alpha channel [link](http://stackoverflow.com/questions/23940220/show-blended-layers-reveals-red-uiimage-but-it-does-not-have-an-alpha-channel). Performance wise I don't have any concrete sources other than being able to see how changing views to opaque boosts performance.

**Comment by taufikobet** [comment]
+1

Also for more reference: https://yalantis.com/blog/mastering-uikit-performance/

**Comment by onevcat** [comment]
Just had a detail look into this problem.

And I believe instead of adding an option to remove alpha channel of the image, we could solve it in a more generic way. By implementing a method of transforming/re-render the image data would be better. 

See #248 .

So, it would be cleaner to pass a special image transformer. I will update this issue when the transforming block implemented.

**Comment by onevcat** [comment]
As mentioned above, should be customizable from Swift 3.

**Comment by SebastianCrow** [comment]
Hi @onevcat,

what would be your recommendation to achieve a fully opaque image?
There is no built-in Kingfisher Image processor for that so rather creating a custom ImageProcessor removing an alpha channel from the source image?

When you're loading a lot of images from the backend endpoint (and you can be sure that they're all opaque) to the collection, it's really helpful (performance wise) to avoid blending.

Migrating to the _UIGraphicsBeginImageContextWithOptions(size, true, scale)_ works but, as mentioned above, it's not a clean and generic solution.

Thanks for help! :)

**Comment by SebastianCrow** [comment]
OK, something like that works for me:
```
import Kingfisher

struct OpaqueImageProcessor: ImageProcessor {

	// `identifier` should be the same for processors with same properties/functionality
	// It will be used when storing and retrieving the image to/from cache.
	let identifier = "com.sebastiancrow.OpaqueImageProcessor"

	// Convert input data/image to target image and return it.
	func process(item: ImageProcessItem, options: KingfisherOptionsInfo) -> Image? {
		switch item {
		case .image(let image):
			return getOpaqueImage(fromSourceImage: image, withScaleFactor: options.scaleFactor) ?? image

		case .data(let data):
			if let image = UIImage(data: data) {
				return getOpaqueImage(fromSourceImage: image, withScaleFactor: options.scaleFactor) ?? image
			}
			return nil
		}
	}

	///

	private func getOpaqueImage(fromSourceImage image: Image, withScaleFactor scale: CGFloat) -> Image? {
		UIGraphicsBeginImageContextWithOptions(image.size, true, scale)
		defer { UIGraphicsEndImageContext() }

		image.draw(in: CGRect(origin: .zero, size: image.size))

		return UIGraphicsGetImageFromCurrentImageContext()
	}
}
```

The only thing is that it needs to be appended at the end because another processors can overwrite this to the transparent context... Still good enough for my use case. Sorry for bringing a confusion ;)
