### ISSUE TITLE
How to change the default  disk storage directory？

### ISSUE THREAD

**Issue by chenqiuliang** [onevcat/Kingfisher#2131]
I want to change the default cache directory instead of having to set it separately every time I cache images.

To be specific，
how to change ImageCache.default.diskStorage

Instead of using the following way

let cache = ImageCache(name: "my-own-cache")
imageView.kf.setImage(with: url, options: [.targetCache(cache)])

The specific scenario is that I need to store resources in the app group and share them with widget

**Comment by onevcat** [comment]
I believe you can set to the `KingfisherManager.shared.cache`. Check [this](https://swiftpackageindex.com/onevcat/kingfisher/master/documentation/kingfisher/kingfishermanager/cache).
