### ISSUE TITLE
Images scaled twice/wrong when retrieved from ImageCache

### ISSUE THREAD

**Issue by schickling** [onevcat/Kingfisher#214]
It seems that images previously stored in the `ImageCache` and retrieved later via `KingfisherManager` are scaled twice. Consider following example:

```swift
KingfisherManager.DefaultOptions.scale = 1

// resizedData is a JPG with 1000x1000
KingfisherManager.sharedManager.cache.storeImage(UIImage(data: resizedData)!, originalData: resizedData, forKey: resizedURL)

// retrieve when cached
KingfisherManager.sharedManager.retrieveImageWithURL(resizedURL, ...) { (image, _, _, _) in
    // image is sized 2000x2000 on iPhone 6
}

// retrieve when not cached
KingfisherManager.sharedManager.retrieveImageWithURL(resizedURL, ...) { (image, _, _, _) in
    // image is correctly sized 1000x1000 on iPhone 6
}
```

**Comment by onevcat** [comment]
Thanks for reporting this. I will check it later.

**Comment by onevcat** [comment]
Hi, @schickling I just did some tests on it. I cannot reproduce your issue and the size is correct for me from both cache and internet.

Is it possible that you are using something like "@2x" suffix in your image name?

**Comment by schickling** [comment]
I'm sorry @onevcat. Turns out it was a problem on my end. Closing this...

**Comment by onevcat** [comment]
Never mind. :)
