### ISSUE TITLE
Couldn't Generate Swift Representation Error (from SourceKit): "Could not load module: Kingfisher"

### ISSUE THREAD

**Issue by LCSomeSSSS** [onevcat/Kingfisher#2140]
it's showing error when I click "import Kingfisher" and  jump to the "Kingfisher" the new page.

<img width="752" alt="截屏2023-09-01 22 45 41" src="https://github.com/onevcat/Kingfisher/assets/19978628/fd017526-45a0-460f-9052-0fddc44a1e3e">

Xcode Version 14.3.1 (14E300c)

<img width="1440" alt="截屏2023-09-01 22 35 03" src="https://github.com/onevcat/Kingfisher/assets/19978628/66fc051d-b3fb-4632-8def-6282ca70a0bc">

**Comment by LCSomeSSSS** [comment]
The problem still cannot be solved after trying all the settings.Finally, it works fine after changing to open Xcode in Rosetta.For the setting details please check the link:https://sarunw.com/posts/open-using-rosetta-in-xcode-14-3/

**Comment by onevcat** [comment]
If this is related to a build configuration (say, if you are trying to not building arm64 by setting something in `EXCLUDED_ARCHS`), then I would suggest you check one of [my post here](https://onevcat.com/2022/10/spm-in-xcode/) (in Chinese, maybe you need a translator to read it). Maybe it is the same issue.

**Comment by LCSomeSSSS** [comment]
> If this is related to a build configuration (say, if you are trying to not building arm64 by setting something in `EXCLUDED_ARCHS`), then I would suggest you check one of [my post here](https://onevcat.com/2022/10/spm-in-xcode/) (in Chinese, maybe you need a translator to read it). Maybe it is the same issue.

It's just the simulator that runs successfully after changing to open Xcode in Rosetta, I'm sorry I ignored the mistake.
The error disappeared after adding Any iOS Simulator SDK with value `arm64` inside Excluded Architecture. It’s  really work fine now.
Thank you very much!
