### ISSUE TITLE
Xcode15 beta8 Carthage

### ISSUE THREAD

**Issue by guo-pf** [onevcat/Kingfisher#2143]
Successfully used cocoapods, but failed to use Carthage.
 
carthage bootstrap --platform iOS --cache-builds --use-xcframeworks
... ... ...
*** Downloading Kingfisher binary at "7.9.1 - Lastest Xcode 15 beta"
*** Building scheme "Kingfisher" in Kingfisher.xcworkspace

### Build Failed
  Task failed with exit code 65:
... ... ...
The following build commands failed:
  CompileSwift normal arm64 (in target 'Kingfisher' from project 'Kingfisher')
  SwiftCompile normal arm64 Compiling\ ImageModifier.swift,\ CacheSerializer.swift
... ... ...

**Comment by onevcat** [comment]
@guo-pf 

Hi,

Any luck with the latest [Carthage 0.39.1](https://github.com/Carthage/Carthage/releases/tag/0.39.1), which was released a few days after you posted this issue.

Frankly, with the support of SPM and xcframework, we found there is now very little reason to continue the support of Carthage (although indeed it does not require much effort). If the framework still cannot be built with the latest Carthage, we are considering to remove the declaration of Carthage support from the documentation of Kingfisher.
