### ISSUE TITLE
XCode升级到15运行，ImageResource文件名与系统库文件方法名冲突

### ISSUE THREAD

**Issue by lxm1799** [onevcat/Kingfisher#2148]
### Issue Description
XCode升级到15运行，ImageResource文件名与系统库GeneratedAssetSymbols.swift中的方法名名冲突

#### What

[Tell us about the issue]
<img width="882" alt="image" src="https://github.com/onevcat/Kingfisher/assets/30572071/03507d25-24d4-4dbc-b542-a045d14adace">

[Add anything else here]
Kingfisher version (7.2.4)

**Comment by onevcat** [comment]
Duplicated #2092 and already fixed in 7.8.0.

**Comment by IshuRocks** [comment]
Use  `let resource = KF.ImageResource(downloadURL: url)` instead of  `let resource = ImageResource(downloadURL: url)`
