### ISSUE TITLE
Can't see this image url 

### ISSUE THREAD

**Issue by Maiiosdeveloper** [onevcat/Kingfisher#2153]
let url = URL(string: "https://msha3lil.rocket.chat/avatar/mai30.png")
userImageView.kf.setImage(with: url, placeholder: UIImage(named: "avatar"))

**Comment by onevcat** [comment]
Although the URL contains a `png` as its extension in file name, the actual content is a svg, which is not yet directly supported by Kingfisher.

Maybe [search "svg" in the issues](https://github.com/search?q=repo:onevcat/Kingfisher+svg&type=issues) to find a possible solution.
