### ISSUE TITLE
URL for cached image

### ISSUE THREAD

**Issue by Patresko** [onevcat/Kingfisher#2154]
How do I get url of cached image if exist in cache?

I would like to show image in .quickLookPreview.

**Comment by onevcat** [comment]
If you already knows the URL and didn't use a customized cache key or any image processor (`ImageProcessor`), then you can just use the methods in `ImageCache` to find out if an image is cached:

```swift
let cached = ImageCache.default.isCached(forKey: url.absoluteString)
```
