### ISSUE TITLE
KFImage goes out of bounds and does not respect frame(widht, height)

### ISSUE THREAD

**Issue by vanniktech** [onevcat/Kingfisher#2164]
Using 7.10.0 I have the following code:

```swift
KFImage(URL(fileURLWithPath: flashcards.fileHandler.absolutePath(path: image.path())))
    .loadDiskFileSynchronously()
    .cacheMemoryOnly()
    .resizable()
    .aspectRatio(contentMode: .fill)
    .frame(width: size.width, height: size.height)
```

I have a fixed aspect ratio on the `size` and would like to have the image shown in the entire size and center it and cut off the trailing top / bottom. However, currently KFImage is just upsizing itself and then it looks like this:

![IMG_CFA1CAA179F7-1](https://github.com/onevcat/Kingfisher/assets/5759366/3bc0579a-0333-42aa-8385-ad2feb10af07)

I only want to show the image portion where you can see the overlay. How can I achieve this? I'm somewhat certain I had this working properly in some earlier version of Kingfisher with the above code, but don't remember the version I had used at that time.

**Comment by onevcat** [comment]
Maybe you want to add a `.clipped()` after your frame?

**Comment by vanniktech** [comment]
Huh that does the trick indeed. I thought I had tried this out. Thanks!
