### ISSUE TITLE
How to set cache key while downloading image using kingfisher?

### ISSUE THREAD

**Issue by SravanPeddi** [onevcat/Kingfisher#2166]
### Issue Description
How to set cache key while downloading image using kingfisher?

#### What
i am using following method to display image
setImage(with: url, placeholder: nil, options: nil, progressBlock: nil, completionHandler: nil)
here the is dynamic i.e., S3 presigned url. For same image presigned url is vary for every request. i would to cache an by some identifer instead of url. So, everytime no need to download image from server (I can see image is cached by given url but i need with some identifier like image name/code).

Can you please help me on this.

**Comment by onevcat** [comment]
You can use the `Resource` to create a loading entry with url and a customized cache key. See [this](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#using-another-cache-key) for more. More some snippet:

```swift
let resource = KF.ImageResource(downloadURL: url, cacheKey: "my_cache_key")
imageView.kf.setImage(with: resource)
```
