### ISSUE TITLE
Decryption for network image

### ISSUE THREAD

**Issue by nicop2000** [onevcat/Kingfisher#2168]
Is it possible to decrypt images on download?
I have stored image data on a public server but it is encrypted and I need to decrypt it after downloading and before displaying the image

**Comment by onevcat** [comment]
I believe [this](https://swiftpackageindex.com/onevcat/kingfisher/master/documentation/kingfisher/imagedownloaderdelegate/imagedownloader(_:diddownload:for:)-61ezn) is what you need.

```swift
KingfisherManager.shared.downloader.delegate = self

extension YourClass: ImageDownloaderDelegate {
    func imageDownloader(_ downloader: ImageDownloader, didDownload data: Data, for url: URL) -> Data? {
        return data.decrypted
    }
}
```

**Comment by nicop2000** [comment]
Thank you very much :)
