### ISSUE TITLE
firebase Crash on KingfisherWrapper----Crash on iPhone X during TestFlight Release

### ISSUE THREAD

**Issue by make1a** [onevcat/Kingfisher#2170]
version: 
 Kingfisher (7.10.0)

```
HeadTitle:
Fatal Exception: NSMallocException
Failed to grow buffer


Fatal Exception: NSMallocException
0  CoreFoundation                 0x940c __exceptionPreprocess
1  libobjc.A.dylib                0x15c10 objc_exception_throw
2  CoreFoundation                 0x19c5c8 -[NSInvocation retainArguments].cold.1
3  CoreFoundation                 0x194504 __CFReallocationFailed
4  CoreFoundation                 0x83160 __CFSafelyReallocate
5  Foundation                     0x5f428 _NSMutableDataGrowBytes
6  Foundation                     0x49de4 -[NSConcreteMutableData appendBytes:length:]
7  ImageIO                        0x2faf4 (缺少 UUID ae75c2c0e49e3058825402afc7a4b4ad)
8  ImageIO                        0x72e5c (缺少 UUID ae75c2c0e49e3058825402afc7a4b4ad)
9  AppleJPEG                      0x1a9fc aj_ostream_write
10 AppleJPEG                      0x38088 aj_block_encode_ac
11 AppleJPEG                      0xc51c aj_encode_buffers_baseline
12 AppleJPEG                      0x8178 aj_encode_row
13 AppleJPEG                      0x688c applejpeg_encode_image_row
14 AppleJPEG                      0x26160 recode_all
15 ImageIO                        0x1bdd3c (缺少 UUID ae75c2c0e49e3058825402afc7a4b4ad)
16 ImageIO                        0x1961dc (缺少 UUID ae75c2c0e49e3058825402afc7a4b4ad)
17 ImageIO                        0x31dac (缺少 UUID ae75c2c0e49e3058825402afc7a4b4ad)
18 ImageIO                        0x9a34 (缺少 UUID ae75c2c0e49e3058825402afc7a4b4ad)
19 UIKitCore                      0x3f485c _UIImageJPEGRepresentation
20 xxx               0x3dbb52c specialized closure #1 in KingfisherWrapper<A>.data(format:compressionQuality:) + 237 (Image.swift:237)
21 xxx               0x3dbaf60 DefaultCacheSerializer.data(with:original:) + 121 (CacheSerializer.swift:121)
22 xxx               0x3ddc2bc closure #2 in ImageCache.store(_:original:forKey:options:toDisk:completionHandler:) + 319 (ImageCache.swift:319)
23 xxx               0x3de4330 partial apply for closure #2 in ImageCache.store(_:original:forKey:options:toDisk:completionHandler:) (<compiler-generated>)
24 xxx               0x83478 thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
25 libdispatch.dylib              0x637a8 _dispatch_call_block_and_release
26 libdispatch.dylib              0x64780 _dispatch_client_callout
27 libdispatch.dylib              0x3f6fc _dispatch_lane_serial_drain$VARIANT$armv81
28 libdispatch.dylib              0x401b0 _dispatch_lane_invoke$VARIANT$armv81
29 libdispatch.dylib              0x49f14 _dispatch_workloop_worker_thread
30 libsystem_pthread.dylib        0x1bd0 _pthread_wqthread
31 libsystem_pthread.dylib        0x1720 start_wqthread
```
Device Information:

Model: iPhone X
Screen Orientation: Portrait
Available RAM: 38.16 MB
Available Disk Space: 21.4 GB
Issue Description:
We are experiencing crashes on iPhone X, specifically during TestFlight release when the user base reaches around 200. It seems to be related to FOOM (Out of Memory). We are eager to reduce the crash rate and are seeking advice on potential solutions.

Question:
Do you have any recommendations or solutions to address this issue? We already invoke the following method during the app's cold launch:

```-swift
func setupImageMemory() {
    ImageCache.default.memoryStorage.config.totalCostLimit = 100 * 1024 * 1024
    ImageCache.default.memoryStorage.config.countLimit = 100
    ImageCache.default.diskStorage.config.sizeLimit = 1000 * 1024 * 1024
    SDImageCache.shared().maxMemoryCost = 100 * 1024 * 1024
}
```
We appreciate any insights or suggestions you can provide to help resolve this crash. Thank you!

**Comment by peter-Kings** [comment]
Me too. Attached crash stack file
[7dab52fc837d4a2ca5a676044f48432b-symbolicated.crash.zip](https://github.com/onevcat/Kingfisher/files/13901049/7dab52fc837d4a2ca5a676044f48432b-symbolicated.crash.zip)

**Comment by onevcat** [comment]
From the crash log, it is an out-of-memory. As you set the memory limitation, Kingfisher will ensure the **accumulated** cache in memory not beyond the set value (here, 100MB as you set). However, it does not prevent the lack of memory from loading a single huge image. If you are loading images without your control (say, you are just accepting the user's submission without check or resize the image to a reasonable size), it is possible that you are trying to load a huge image and the image itself takes a lot of memory, in turn it causes a OOM.

If that is a possible case, I suggest you either limit the images which have a chance to be loaded (say, resize it on your server after received from the user); Or you can try to use the `DownsamplingImageProcessor` to load a thumbnail one instead of putting every pixel of the original image into the memory (https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#using-downsamplingimageprocessor-for-high-resolution-images).
