### ISSUE TITLE
Kingfisher.xcframework: a sealed resource is missing or invalid

### ISSUE THREAD

**Issue by kimi-santander** [onevcat/Kingfisher#2178]
### Issue Description
Thanks very much for such a great project. I have found an issue using Kingfisher's xcframework, delivered in the release section of the GitHub page.

There is a problem using the provider XCFramework with XCode related to framework signature.

![kingfisher-xcode-error-1](https://github.com/onevcat/Kingfisher/assets/145996046/c10d5d04-7fd0-4b7a-944f-be812593c765)

![kingfisher-xcode-error-2](https://github.com/onevcat/Kingfisher/assets/145996046/67d23308-459a-401f-ac49-a6eb1e3e0e62)

#### Reproduce
* download the xcframework for the latest release
* use any dependency management to import the framework into an app
* build and run to a device

**Comment by onevcat** [comment]
Ummm, thanks for reporting this. Let me check...

**Comment by onevcat** [comment]
It turn out to be an issue that symlinks are not kept during zipping. Fixed in #2179 and will give it a tag very soon.

**Comment by onevcat** [comment]
The pre-built xcframework has been recompiled and uploaded to the release pages (I did it for the last 3 versions: 7.10.1, 7.10.0 and 7.9.1).

@kimi-santander Any chance to check if it is working for you now? Thanks!

**Comment by kimi-santander** [comment]
Works like a charm. Thank you very much.

**Comment by AlbGarciam** [comment]
@onevcat the latest version still has the issue 🥲

**Comment by onevcat** [comment]
@AlbGarciam Just tried the zip file of the latest version and it works fine to me.

Any idea or error reason?

![截屏2024-01-19 17 16 59](https://github.com/onevcat/Kingfisher/assets/1019875/bf4e5913-7b2c-43e1-aaa6-6c612d5c864a)

**Comment by AlbGarciam** [comment]
Nevermind it is an issue on the way we move the location of the xcframework. Sorry
