### ISSUE TITLE
Kingfisher Support Base64 ?

### ISSUE THREAD

**Issue by Theeranail** [onevcat/Kingfisher#2193]
If I use the Kingfisher library and want to use it with Base64 images, can this library work? How can I do it?

**Comment by FaisalShabbir007** [comment]
Yes, the Kingfisher library supports loading images from Base64 encoded strings. You can achieve this by providing the Base64 encoded string directly to Kingfisher's KFImage or UIImageView instance.

Here's how you can load a Base64 encoded image using Kingfisher in Swift:

import Kingfisher
import UIKit

// Assuming you have a Base64 encoded string representing your image
let base64String = "YOUR_BASE64_ENCODED_IMAGE_STRING_HERE"

// Convert the Base64 string to Data
guard let imageData = Data(base64Encoded: base64String) else {
    // Handle invalid Base64 string
    return
}

// Create a Kingfisher image provider from the Base64 encoded Data
let provider = ImageDataProvider(data: imageData)

// Use Kingfisher to load the image
KFImage(provider)
    .resizable()
    .placeholder(UIImage(named: "placeholder")) // Optional: Provide a placeholder image
    .onFailure { error in
        // Handle image loading failure
        print("Error loading image: \(error)")
    }
    .onSuccess { _ in
        // Image loaded successfully
        print("Image loaded successfully")
    }
    .load()


By following these steps, you can easily load Base64 encoded images using the Kingfisher library in your iOS app.

Replace "YOUR_BASE64_ENCODED_IMAGE_STRING_HERE" with your actual Base64 encoded image string.
Convert the Base64 string to Data using Data(base64Encoded:).
Create a ImageDataProvider instance with the Base64 encoded image data.
Use KFImage to load the image, passing the ImageDataProvider as the image provider.
Optionally, you can specify a placeholder image using the placeholder() modifier.
Handle loading success or failure using the onSuccess and onFailure modifiers.

**Comment by onevcat** [comment]
@Theeranail 

There is a `Base64ImageDataProvider` you can use once you have the base64-encoded string.

https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#image-from-base64-string
