### ISSUE TITLE
support visionOS via CocoaPods

### ISSUE THREAD

**Issue by grachyov** [onevcat/Kingfisher#2202]
[!] The platform of the target `App visionOS` (visionOS 1.0) is not compatible with `Kingfisher (7.10.2)`, which does not support `visionOS`.

**Comment by onevcat** [comment]
I believe it just needs to uncomment these https://github.com/onevcat/Kingfisher/blob/master/Kingfisher.podspec#L34-L35

Before an official upgrade can be made, you can also try to fork and edit it temporarily for a while.

**Comment by onevcat** [comment]
I am having a pod lib linter error, which prevents me from releasing a tag and publish the pod spec.

Seems we need to wait for the next CocoaPods version to get it.

Ref: https://github.com/CocoaPods/CocoaPods/pull/12159 (which is in the master branch, but not yet released.)
