### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by zrzrv5** [onevcat/Kingfisher#222]
我在用UICollectionView实现图片瀑布流时发现当图片是Gif时，内存会上升地非常厉害。
<img width="1281" alt="2016-01-25 1 24 28" src="https://cloud.githubusercontent.com/assets/10773382/12551114/2bf18a8c-c3a3-11e5-99c9-96dab34b3c77.png">

**Comment by onevcat** [comment]
Kingfisher 会下载并将 GIF 进行逐帧解码，所以如果一次性下载和显示的 GIF 太多的话肯定会占用很多内存。建议瀑布流中使用静态缩略图，而没有必要使用 GIF 原图。

如果有其他内存泄露方面的问题，欢迎再提出。

**Comment by xspyhack** [comment]
Hi, 非常感谢喵大给我们带来这么好用的一个库。

在使用的过程中，我发现了一些内存相关的问题：

当加载部分 GIF 图片时，Kingfisher 中对 GIF 图片的处理，会使得内存特别大。所以我尝试过用其他的方式[SwiftGif](https://github.com/bahlo/SwiftGif/blob/master/SwiftGifCommon/UIImage%2BGif.swift)来处理 UIImage，发现和 Kingfisher 几乎一样。

但是用 [OLImageView + OLImage](https://github.com/dtorres/OLImageView) 或者 [YYImage + YYAnimatedImageView](https://github.com/ibireme/YYWebImage) 时，内存的使用，会比前面的两种方式大大的减少。

一组测试数据：

Kingfisher/SwiftGif image1: 106 MB, image2: 180 MB, image3: 201 MB

OLImageView: image1: 37 MB, image2: 38 MB, image3: 39 MB

YYWebImage: 32 MB, image2: 33 MB, image3: 36 MB

我写了一个 [Demo](https://github.com/xspyhack/KingfisherDemo)

**Comment by onevcat** [comment]
@xspyhack 

Kingfisher 暂时对于 GIF 的支持非常初级，因为我自己并没有使用这个框架来加载 GIF 的需求，所以就只是很简单地实现了一下，现在 Kingfisher 对于 GIF 是直接全部加载，对于时间较长，尺寸较大的 GIF，确实会存在内存占用上的问题。

我没有细看 OLImageView 或者 YYWebImage 的实现，不过可以猜测基本是只预先加载两三帧，而不是一次全部解码，这样显然可以减少内存占用。但我最近并没有时间和精力为 Kingfisher 添加更好的 GIF 支持，还请见谅。

如果您有兴趣的话也可以参照他们的实现发 p-r 过来帮助改进~

谢谢！

**Comment by onevcat** [comment]
另外，如果你想用 Swift 来显示和处理 GIF 的话，可能 [Gifu](https://github.com/kaishin/Gifu) 会是一个不错的选择。

如果你想为 Kingfisher 贡献代码改善这块的话，参考一下 Gifu 的实现应该也会很有帮助。

**Comment by xspyhack** [comment]
Thanks,
我来尝试一下。

**Comment by onevcat** [comment]
:)
