### ISSUE TITLE
Upload Privacy Policy

### ISSUE THREAD

**Issue by BenoitDeguine** [onevcat/Kingfisher#2227]
Apple says "Starting May 1, 2024: You'll need to include approved reasons for the listed APIs used by your app's code to upload a new or updated app to App Store Connect."

Please add privacy policy so we can use this library

https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by Ded77** [comment]
It should be done by https://github.com/onevcat/Kingfisher/releases/tag/7.10.0
