### ISSUE TITLE
How do I add suffixes to cache paths, such as.jpg 

### ISSUE THREAD

**Issue by tzgd** [onevcat/Kingfisher#2248]
let cachePath =  ImageCache.default.diskStorage.cacheFileURL(forKey: url.absoluteString)

**Comment by zeroskylian** [comment]
You can use ImageResource:
```swift
UIImageView().kf.setImage(with: KF.ImageResource(downloadURL: URL(string: "your url")!, cacheKey: "your cacheKey"))
```

**Comment by tzgd** [comment]
> You can use ImageResource:
> 
> ```swift
> UIImageView().kf.setImage(with: KF.ImageResource(downloadURL: URL(string: "your url")!, cacheKey: "your cacheKey"))
> ```
多谢了
