### ISSUE TITLE
kf_setImageWithURL with Authentication Challenge ?

### ISSUE THREAD

**Issue by hshah2811** [onevcat/Kingfisher#226]
My app is using below API to download image async manner.   

`public func kf_setImageWithURL(URL: NSURL, placeholderImage: UIImage?, optionsInfo: Kingfisher.KingfisherOptionsInfo?, completionHandler: Kingfisher.CompletionHandler?) -> Kingfisher.RetrieveImageTask`

Problem i am facing is - how to provide authentication challenge response if my server is requesting to download any response. I know there are ways in normal NSURLConnection connection with delegate  - 
`(void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler `

Is there any way in kingfisher where i can provide my credential before downloading image?

**Comment by onevcat** [comment]
If you are using `NSURLAuthenticationMethodServerTrust`, you can add your server host to `trustedHosts` of `ImageDownloader` to mark your server trusted:

```swift
ImageDownloader.defaultDownloader.trustedHosts!.insert("yourhost.com")
```

And if you are using HTTP basic authentication, you could just modify the request by injecting with `requestModifier` of the downloader.

However, if you are using other authentication methods, like client certificate, currently there is no way in Kingfisher for it. 

I believe we should add a delegate of it for better extensibility. I will check it to see whether I could do something on this later.

**Comment by onevcat** [comment]
Now you should be able to use `authenticationChallengeResponder` for it.

**Comment by onevcat** [comment]
[Version 2.1.0](https://github.com/onevcat/Kingfisher/releases/tag/2.1.0) is released, which contains this feature.

**Comment by TNikolai** [comment]
Could you write example ho to use authenticationChallengeResponder, basicaly i want to download image like this :
imageView.kf_setImageWithURL(url, placeholderImage: UIImage(named: PlaceHolderImageName))
