### ISSUE TITLE
Get UIImage only

### ISSUE THREAD

**Issue by patonz** [onevcat/Kingfisher#227]
I need to get a UIImage only instead of loading a normal UIImageView

for a trick, i used the callback method with an unused UIImageView:

`let imageView = UIImageView()
        
        imageView.kf_setImageWithURL(NSURL(string: cpa.imageName)!, placeholderImage: nil,
            optionsInfo: [.Transition(ImageTransition.Fade(1))],
            progressBlock: { receivedSize, totalSize in
                print("\(receivedSize)/\(totalSize)")
            },
            completionHandler: { image, error, cacheType, imageURL in
                anView!.image = image //anView IS NOT an UIImageView
                anView!.frame.size = CGSize(width: 15.0, height: 15.0)
                print("Finished")
        })`

that code works perfectly, but i want to use a cleaner solution. 
Does it exist a method for get a UIImage only? Async and chached

**Comment by onevcat** [comment]
Hi,

You could always use the `ImageDownloader` and `ImageCache` separately to download or cache/retrieve images.

Using image view extension of Kingfisher is not a must but an option and convenient way.
