### ISSUE TITLE
Ability to check for existence of image in cache

### ISSUE THREAD

**Issue by GodIsI** [onevcat/Kingfisher#228]
Hi, 

I have the following scenario, I have a thumb image, and once that is downloaded I get the high res version. This works well, but if the image is already in the cache I get a flicker as it switches between images.

It would be good to know if either the thumb or full sized image is already available as I can then make a better decision about placeholder images etc.

**Comment by onevcat** [comment]
Hi, @GodIsI 

You could use the methods in `ImageCache` to check whether an image is already cached or not.

I believe the following code snippet would help if you are using the default cache:

```swift
let cacheResult = ImageCache.defaultCache.isImageCachedForKey("your_image_url")

cacheResult.cached // true or false
cacheResult.cacheType // .None, .Memory or .Disk
```

**Comment by GodIsI** [comment]
Thanks, that works just as I need. Appreciate the quick responses.
