### ISSUE TITLE
About data:image/svg+xml;base64

### ISSUE THREAD

**Issue by dowhilenet** [onevcat/Kingfisher#229]
你好喵神。 :)

请教个问题
我有一些图片的资源的URL 类似于这样：

url  `data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5 ........`

swift code
```swift
imageView.kf_setImageWithURL(NSURL(string: url)!)
```
并没有显示出图片来。想请教，类似于这样的资源的图片，怎么去处理。:)

**Comment by dowhilenet** [comment]
查了查，好像知道了。 是对 ` svg+xml `进行了 `base64 `编码。得到的 `PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53.....` 😄

**Comment by onevcat** [comment]
:) So could you please close this issue?
