### ISSUE TITLE
关于Kingfisher缓存新浪微博GIF报错的问题

### ISSUE THREAD

**Issue by cache0928** [onevcat/Kingfisher#231]
<img width="877" alt="2016-02-12 14 11 13" src="https://cloud.githubusercontent.com/assets/7350995/13000210/9b504eca-d192-11e5-8fb0-c4644db34d2e.png">
喵神你好，我在微博上向您反馈过这个问题，上图是我的代码，代码中的gif地址为新浪微博api返回的。在浏览器中可以正常访问：http://ww3.sinaimg.cn/thumbnail/62037b5agw1f0vw2yxnqxg209v0587wm.gif
但是在downloader中却下载出错。其他格式的图片没有出现该问题

**Comment by onevcat** [comment]
单帧的 GIF 图片解析有点问题。已经在 #234 中修正，稍后 update 版本号。

谢谢！
