### ISSUE TITLE
Build Xcode 14.2-Swift5 error

### ISSUE THREAD

**Issue by gitliubo** [onevcat/Kingfisher#2311]
1.error:
/Pods/Kingfisher/Sources/Views/AnimatedImageView.swift:489:55: error: converting function value of type '@MainActor (AnimatedImageView) throws -> T' to '(AnimatedImageView) throws -> T' loses global actor 'MainActor'
        return try withoutActuallyEscaping(operation) { (_ fn: @escaping Isolated) throws -> T in
2.env:
Xcode 14.2,Swift5

how can handle it?

![image](https://github.com/user-attachments/assets/e96de2af-8655-4cd0-a4fa-d0c893018f0f)

**Comment by onevcat** [comment]
The latest versions of Kingfisher (v8) supports from Swift 5.9. We do not have enough resource to maintain these old Xcode/Swift versions. Sorry for that!

<img width="468" alt="截屏2024-10-20 1 11 38" src="https://github.com/user-attachments/assets/4bb253b0-70db-41b2-bd01-2d1f0918805e">

**Comment by gitliubo** [comment]
OK,thanks!
