### ISSUE TITLE
Not using cookies from the assigned cookie storage

### ISSUE THREAD

**Issue by anohren** [onevcat/Kingfisher#232]
I'm doing this when launching my app:

`        KingfisherManager.sharedManager.downloader.sessionConfiguration.HTTPCookieStorage = NSHTTPCookieStorage.sharedHTTPCookieStorage()
`

But it seems that the cookies in the shared storage aren't being applied to any of kingfisher's requests.

**Comment by onevcat** [comment]
Hi, the `sessionConfiguration` will be used to create the session. Instead of setting its property, you may need to set the whole `sessionConfiguration` to recreate a session. Would you please try this?

```swift
let c = KingfisherManager.sharedManager.downloader.sessionConfiguration
c.HTTPCookieStorage = NSHTTPCookieStorage.sharedHTTPCookieStorage()

KingfisherManager.sharedManager.downloader.sessionConfiguration = c
```

**Comment by anohren** [comment]
Hello, thank you for your answer.

I was thinking the same thing and tried some combinations without success. But now it seems that both your solution and assigning a new ephemeral session configuration work :+1: :+1: :+1:

**Comment by shailyglobal83** [comment]
hi, How to apply Signed cookies in Kingfisher, I have tried above but unable to download image getting "Forbidden" error. That is what I am doing 
       let kingfisherManagerSession = KingfisherManager.shared.downloader.sessionConfiguration
        kingfisherManagerSession.httpCookieStorage = HTTPCookieStorage.shared
        KingfisherManager.shared.downloader.sessionConfiguration = kingfisherManagerSession

        self.kf.setImage(with: _url, placeholder: #imageLiteral(resourceName: "placeholder"), options: [.requestModifier(modifier)], progressBlock: { (receivedSize, totalSize) in
            let percentage = (Float(receivedSize) / Float(totalSize)) * 100.0
            self.kf.indicatorType = .activity
            print(percentage)
        }) { (image, error, cacheType, url) in
            print(error?.localizedDescription)
        }

Can you please help me what am I doing wrong?

**Comment by shintarogit** [comment]
@shailyglobal83 
change
```
let kingfisherManagerSession = KingfisherManager.shared.downloader.sessionConfiguration
kingfisherManagerSession.httpCookieStorage = HTTPCookieStorage.shared
KingfisherManager.shared.downloader.sessionConfiguration = kingfisherManagerSession
```
to
```
KingfisherManager.shared.downloader.sessionConfiguration = URLSessionConfiguration.default
```
