### ISSUE TITLE
你好,有些图片加载不出来

### ISSUE THREAD

**Issue by QiuYeHong90** [onevcat/Kingfisher#2341]
https://cdn.aurapura.app/aurapura/mbti/TestedeSaúdeMental.png
上么的图片,使用SDWebImage 可以加载出来,但是咱们这个缺加载不出来,不知道什么原因

**Comment by onevcat** [comment]
这个地址给了我一个 access error（可能需要一个 auth 的 header？），所以暂时无法判断问题。

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>S621BZT528AFE9NA</RequestId>
<HostId>nYft0xhldtfp1iD5dDAJB098zQK+a6GEJmTlaKhJSkqBqQgDABldbU5y51nCMOO1ecMbWtjIKos=</HostId>
</Error>
```

不过看描述的话可能应该是图片格式的问题。Kingfisher 只用了系统层级默认支持的格式，像是 WebP 之类的，可能会加载不了。虽然文件名后缀是 png，不过还是建议确认一下实际的文件格式。

**Comment by QiuYeHong90** [comment]
谢谢, 我找到原因了,需要编码一次才可以正常加载
addingPercentEncoding(withAllowedCharacters: CharacterSet.urlQueryAllowed)

**Comment by QiuYeHong90** [comment]
里面有特殊字符, URL 不支持巴西语言,需要url 编码一次

**Comment by onevcat** [comment]
Swift 的 `URL(string:)` API 在 iOS 17 后已经可以自动编码了（[参考](https://developer.apple.com/documentation/foundation/url/3126806-init)）。不过为了统一，建议确实对于带有特殊字符的 string 先编码后再创建 URL。

另外，如果给 Kingfisher 的 URL 是 nil 的话，应该会给出 empty source 的错误作为结果。可以监测一下回调中的错误信息。

因为没有特别需要对应的，所以我先关掉这个 issue 了。

祝好。
