### ISSUE TITLE
自定义ImageDownloader时可能造成内存泄露

### ISSUE THREAD

**Issue by dopcn** [onevcat/Kingfisher#235]
在 ImageDownloader 里 session 是一个 strong property
` private var session: NSURLSession?`
在 ImageDownloader 的 init 里
```
session = NSURLSession(configuration: sessionConfiguration, delegate: self, delegateQueue: NSOperationQueue.mainQueue())
```
NSURLSession 的文档提到

> IMPORTANT
The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you do not invalidate the session by calling the invalidateAndCancel or finishTasksAndInvalidate method, your app leaks memory until it exits.

defaultDownloader 是不会 deinit 的单例所以不影响，但是如果自定义 ImageDownloader 有可能会造成内存泄露

**Comment by onevcat** [comment]
Should be fixed in #236
