### ISSUE TITLE
ImageTransition not working

### ISSUE THREAD

**Issue by Tramvai** [onevcat/Kingfisher#237]
Hi.

I am having trouble getting ImageTransition to work. I have the exact same example that is displayed in the README.

`imageView.kf_setImageWithURL(NSURL(string: "your_image_url")!, placeholderImage: nil, optionsInfo: [.Transition(ImageTransition.Fade(1))])`

Tried different animations, none of them worked. Also tried different time intervals, didn't help either. The image I am loading from URL is displayed instantly, with no animation.

iOS 9, XCode 7, KingFisher (2.0.2).

**Comment by onevcat** [comment]
Currently, the image transition will only work when the image is downloaded. Support for forcing transition is in plan but not implemented yet.

Could you please try to clean your cache & try to see whether it works?

**Comment by Tramvai** [comment]
Thank you for clearing that up for me, it does work as intended when I clear the cache. I use Kingfisher to switch between images in a view and sometimes it flashes the view background color before loading the image. Is that an indication of using the disk cache?

Thanks again.

**Comment by onevcat** [comment]
Maybe this will help? #228

**Comment by tooolbox** [comment]
> Currently, the image transition will only work when the image is downloaded. Support for forcing transition is in plan but not implemented yet.

Just ran into this same behavior; did this never get implemented?  Should I do a PR?  😄

**Comment by tooolbox** [comment]
Funnily enough, I am doing another project and find myself running into this again, and back at this same issue two years later.

...I suppose I should pull up the previous project and find out what I did to get around this 😢
