### ISSUE TITLE
如何使用Kingfisher缓存图片到磁盘?

### ISSUE THREAD

**Issue by Jatstar** [onevcat/Kingfisher#242]
`
            for url in urls
            {
                dispatch_group_enter(group)
                
                // 缓存图片
                SDWebImageManager.sharedManager().downloadImageWithURL(url, options: SDWebImageOptions(rawValue: 0), progress: nil, completed: { (_, _, _, _, _) -> Void in
                    dispatch_group_leave(group)
                })
            }
`

使用 Kingfisher 应该怎么写

**Comment by Jatstar** [comment]
` 
dispatch_group_enter(group)
                
                let downloader = KingfisherManager.sharedManager.downloader
                
                downloader.downloadImageWithURL(url, progressBlock: nil, completionHandler: { (image, error, imageURL, originalData) -> () in
                    dispatch_group_leave(group)
                })
            }
`
??? am I right?

**Comment by onevcat** [comment]
这种问题请到 Stackoverflow 提..GitHub issue 并不是问答的地方。不好意思。
