### ISSUE TITLE
Return statusCode from ImageDownloader callback if failures occur

### ISSUE THREAD

**Issue by stephenvisser** [onevcat/Kingfisher#245]
I'd like to differentiate between 404's (image doesn't exist) and auth / server exceptions.

One option:

`NSError(domain: KingfisherErrorDomain, code: KingfisherError.NotModified.rawValue, userInfo: ["statusCode": ...])`

**Comment by mrstone** [comment]
+1 This would be a great addition

**Comment by onevcat** [comment]
Basically implemented in #346
