### ISSUE TITLE
Global options in v2

### ISSUE THREAD

**Issue by greg3z** [onevcat/Kingfisher#246]
Hello,

I read the 2.0 migration guide, but I'm not sure what happened to global options.
I used to set the scale I wanted globally thanks to KingfisherManager.DefaultOptions.scale before 2.0. 
Is there a way to do the same with 2.x or do I have to set the scale manually each time I need it?

Thank you!

**Comment by onevcat** [comment]
There is not a default options now. And the original default options is not intended to be public in fact. It was a API design mistake and prevents the flexibility of the options. So we removed it in version 2.0.

If you really need such a thing, I suggest you could create a helper method for the Kingfisher image extension, with setting/passing the scale option.

**Comment by greg3z** [comment]
Got it, thank you ;)
