### ISSUE TITLE
Feature request: add transformation block before setting image

### ISSUE THREAD

**Issue by burczyk** [onevcat/Kingfisher#248]
It would be great if we had one more callback in method:

```swift
public func kf_setImageWithResource(resource: Resource,
                                placeholderImage: Image?,
                                     optionsInfo: KingfisherOptionsInfo?,
                                   progressBlock: DownloadProgressBlock?,
                               completionHandler: CompletionHandler?) -> RetrieveImageTask
```

to make a transformation to downloaded image before setting it to `UIImageView`. Something like 
```swift
transformation: ((image: Image?) -> Image?)? = nil
``` 
where we could make some manipulations of downloaded image before assigning it to `imageView.image`. 

Right now we have a 'bare' walkaround for it by using `KingfisherManager.sharedManager.retrieveImageWithURL` but then we lose all nice features like activity indicator and cancelling this task from imageView directly.

Real world use case: I would like to add blur effect to downloaded image but when I do it in `completionHandler` it takes some time and in result original image is assigned, it renders for a fraction of second and then blurred image replaces it.

What do you think about it?

**Comment by ivanbruel** [comment]
I've actually been using my own fork with a primitive version of an image filter block, still needs polish before doing a PR though. (https://github.com/ivanbruel/Kingfisher)

**Comment by onevcat** [comment]
@burczyk Yes, I agree that this would be a useful feature. I will see how could I implement it in a good way. Instead of a callback in the `kf_setImage` methods, I guess some hooks in the cache or downloader would be a better place for them. By doing so, you could even cache your blurred or cornered image instead of the original one, so there is no need to process it again and again.

@ivanbruel Great to know your implementation. However it seems there is quite a lot of work to do if it is used. So I guess I could implement it myself later for it.

**Comment by nitinbizsingh** [comment]
@onevcat This will also be useful in the situation where the image source is not in your control and supplies higher or lower resolution images. In such cases we can do the resizing based on UiImageView size before applying it instead of doing it on the fly which has impact on performance.

**Comment by yonaskolb** [comment]
Any updates on this?

**Comment by onevcat** [comment]
Implemented in Kingfisher 3. Check [`ImageProcessor`](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#processor) for more.

**Comment by burczyk** [comment]
Great news. Thanks for providing some implemented processors!
