### ISSUE TITLE
内存缓存问题

### ISSUE THREAD

**Issue by wackosix** [onevcat/Kingfisher#250]
把项目中的AlamofireImage框架换成Kingfisher，然后在有UImageView的控制器总多次切换发现，内存很高，而Alamofire得很低，怀疑Kingfisher在内存缓存处理有问题。

**Comment by onevcat** [comment]
If you find a issue, you could go deeper to find what happens and then submit it with detail to point out where and how the problem is.

Opening an issue like this has nothing to help, but a waste of time.
