### ISSUE TITLE
UIImage extension

### ISSUE THREAD

**Issue by MattTimmons** [onevcat/Kingfisher#261]
I am digging through the repro still, but is there a way to just set a UIImage from a URL with the callback? I do not need to set an image view in this stage.. I could make a fake imageView, but I thought I would ask about it anyways.

Best,
Matt

**Comment by onevcat** [comment]
Maybe you can see [this](http://stackoverflow.com/questions/35204620/get-uiimage-only-with-kingfisher-library).
