### ISSUE TITLE
Using the default downloader doesn't cache any images

### ISSUE THREAD

**Issue by anohren** [onevcat/Kingfisher#267]
I need to download images before I have access to an `UIImageView`, so my solution was to use

```
ImageDownloader.defaultDownloader.downloadImageWithURL(imageUrl, options: [], progressBlock: nil) { (image, error, imageURL, originalData) -> () in
```

But doing this for the same URLs always downloads the images over and over. I don't know if Kingfisher heeds caching headers, but just in case: `Cache-Control` looks like this: `private, no-transform, max-age=2592000` for these images.

Should I do something differently?

**Comment by anohren** [comment]
Okay, I just found the `KingfisherManager.sharedManager.retrieveImageWithURL(imageUrl, optionsInfo: .None, progressBlock: nil)` which seems to do what I wanted :)

I looked in the downloader first though (because of the name), and it wasn't apparent that the downloader didn't use the cache. Maybe you can refer future users to the manager methods instead if they want the cache to come into play.

**Comment by vCrespoP** [comment]
+1

And it would be nice to use the downloader so we have a timeout as well
Kingfisher.sharedManager.downloader.downloadTimeout

Thanks!

**Comment by codwam** [comment]
+1

It need to cache manually...

ImageCache.defaultCache.storeImage(self, forKey: url.absoluteString)

**Comment by onevcat** [comment]
Now you could use the `ImagePrefecher` for this.
