### ISSUE TITLE
Is there a version for using in App Extension ?

### ISSUE THREAD

**Issue by macbaszii** [onevcat/Kingfisher#269]
I couldn't compile code because of the error in ImageCache.swift is using UIApplication.SharedApplication() 

`'sharedApplication()' is unavailable: User View Controller based solution where appropriate instead.`

**Comment by yonaskolb** [comment]
Having this issue too

**Comment by macbaszii** [comment]
@yonaskolb I changed to use SDWebImage for an extension.

**Comment by onevcat** [comment]
Fixed in #290
