### ISSUE TITLE
Do you plan to add animations?

### ISSUE THREAD

**Issue by szuniverse** [onevcat/Kingfisher#27]
Hi

Do you plan to add some animation if the image downloaded?
use case:
set placeholder image
waiting till the image is downloaded
fade in the downloaded image on the uiimageview

I think it would be great and simple to use somehow

**Comment by onevcat** [comment]
It is not the core feature for a downloading and cache framework.

And the same effect could be implemented by extending the framework with simple UIAnimation. So I guess this will not be implemented in Kingfisher, to keep it a lightweight framework.

**Comment by szuniverse** [comment]
Okey, yes you're right. Thanks+

**Comment by leizard** [comment]
`And the same effect could be implemented by extending the framework with simple UIAnimation.`
@onevcat , @szuniverse , I'm interested and not clear about what you said and how to implement animation when download image. Is there any way I could check if image is cached and not set animation in that case ?

**Comment by leizard** [comment]
I'm sorry I didn't read the Readme carefully. This is how I implement the animation:

```
        imageView.kf_setImageWithURL(url,
                                     placeholderImage: nil,
                                     optionsInfo: nil,
                                     progressBlock: { (receivedSize, totalSize) -> () in
                                        print("Download Progress: \(receivedSize)/\(totalSize)")
                                        imageView.alpha = 0
                                        
            },
                                     completionHandler: { (image, error, cacheType, imageURL) -> () in
                                        UIView.animateWithDuration(2, animations: { imageView.alpha = 1 })
                                        print("Downloaded and set!")
            }
```
Hope I was right 😃
