### ISSUE TITLE
Caching to disk not working

### ISSUE THREAD

**Issue by bistrform** [onevcat/Kingfisher#272]
Kingfisher doesn't cache images to disk for me. It seems like there's a problem in KingfisherManager.downloadAndCacheImageWithURL:

line 188: `targetCache.storeImage(image, originalData: originalData, forKey: key, toDisk: options?.cacheMemoryOnly ?? true, completionHandler: nil)`

here `toDisk: options?.cacheMemoryOnly ?? true` will return `false` if `options?.cacheMemoryOnly == false`. Doesn't seem like expected behaviour from the flag description =)

**Comment by onevcat** [comment]
@bistrform What's your version of Kingfisher? It should be already fixed here https://github.com/onevcat/Kingfisher/pull/224/files

**Comment by bistrform** [comment]
I didn't verify the exact version, just have it as a pod in my project (without specifying the exact version in the podfile). Sorry for bothering in this case, something wrong at my end.
