### ISSUE TITLE
Demo files pollute workspace

### ISSUE THREAD

**Issue by jarsen** [onevcat/Kingfisher#274]
I think having a demo project is terrific. However, when I add the Kingfisher project to my workspace, because the project includes all the demo files and targets, it really pollutes the workspace. It also makes it difficult if you want to, say quick open AppDelegate, as you may open the wrong file.

I can see two possible solutions:
1. Have a separate repo for the demo
2. have a separate demo project within this repo

I am more than willing to PR this and help out, but I wanted to open it to discussion first.

**Comment by onevcat** [comment]
Hi, @jarsen 

Thanks for opening this issue.

If you are integrating Kingfisher by CocoaPods, only the classes files will be imported and built. If you are using Carthage, although all the files will be fetched to your Carthage folder, only the framework will be built and no demo things will be used. Neither will cause the polluting problem. However, yes, if you integrate by dragging the project file into your project and then build the framework, it will happen.

Containing a demo in the repo is very common, so the potential users could just download and see the demo without much effort, then choose whether they want adopt in. So, I prefer solution 2 on it, maybe just like the way [Alamofire](https://github.com/Alamofire/Alamofire) is doing. A p-r on this is warmly welcomed!

Thanks in advance.

**Comment by onevcat** [comment]
I think I could do this later.

**Comment by frankrausch** [comment]
Hi,

just wanted to ask if you need any help with this.

I have solved the potential demo file “workspace pollution” in one of my projects by adding a subfolder for the demo project:
https://github.com/frankrausch/Typographizer

So how about adding a subfolder `KingfisherDemo` and then adding the framework to the demo?

Thanks.

**Comment by onevcat** [comment]
@frankrausch Sorry for my laziness. 😂

Sure. It would be great if you'd like to do so! However, in fact we have already have a "Demo" folder, in which demo files are located. Instead of moving the demo files, this issue is related to make another Kingfisher-Demo project to hold all the demo targets.

**Comment by onevcat** [comment]
BTW, your work of Typographizer looks fancy!

**Comment by frankrausch** [comment]
Yeah, sorry—I took another look and found out that everything is already in place, except for a separate demo app project. :)

**Comment by frankrausch** [comment]
Which would be the best commit to build a PR on? Latest commit on `master`?

**Comment by onevcat** [comment]
I just merge the most recent commit to master, so you could just start from master! Thanks!

**Comment by frankrausch** [comment]
Cool, I’ll give it a try now. 😅

**Comment by frankrausch** [comment]
Done.

**Comment by onevcat** [comment]
Fixed in #869 

Thank you @frankrausch !
