### ISSUE TITLE
etag support?

### ISSUE THREAD

**Issue by ogezue** [onevcat/Kingfisher#275]
Is it planned to support eTags to let the server decide is an image is outdated?

**Comment by onevcat** [comment]
Hi, @ogezue 

Kingfisher will not store the ETag information from server or handle it transparently. It is possible to implement a ETag based cache yourself. There was a wiki for it and still valid for current version. You can find it here: https://github.com/onevcat/Kingfisher/wiki/How-to-implement-ETag-based-304-(Not-Modified)-handling-in-Kingfisher

However, it is not recommended to do so strongly. The cache policy used in Kingfisher is very simple by only checking the URL or cache key, so it could avoid to sending requests to your server at all. A much easier implementation for the same purpose might be changing your image url with something like a time stamp query (e.g. http://domain.com/image.jpg?t=123456) then let the client to know the latest URL.
