### ISSUE TITLE
When i install this library so many error is occuring

### ISSUE THREAD

**Issue by sreeji44** [onevcat/Kingfisher#276]
![screen shot 2016-03-28 at 3 52 49 pm](https://cloud.githubusercontent.com/assets/16497980/14076128/8da090e0-f4fc-11e5-88c6-3ca22da8c735.png)

**Comment by FredholmIsak** [comment]
Yep, I am getting this exact error aswell.

**Comment by onevcat** [comment]
@sreeji44 @FredholmIsak 
Hi, as mentioned in README, the newest version of Kingfisher (version 2.2.0) supports Xcode 7.3 and Swift 2.2. If you are using an earlier Xcode/Swift version, you may want to spin your version to 2.1.0.
