### ISSUE TITLE
Additional headers in requests

### ISSUE THREAD

**Issue by arn00s** [onevcat/Kingfisher#279]
Hi there,

I'd like to pass some additional headers to my image requests, how can I manage this ?

thx!

**Comment by onevcat** [comment]
http://cocoadocs.org/docsets/Kingfisher/2.2.0/Classes/ImageDownloader.html#/s:vC10Kingfisher15ImageDownloader15requestModifierGSqFCSo19NSMutableURLRequestT__

**Comment by arn00s** [comment]
Thx @onevcat ! :+1:

**Comment by camill-a** [comment]
@arn00s Could you explain how you sorted it out?

**Comment by arn00s** [comment]
@camill-a I can't find back the code, I finally used Alamofire and Alamofire-Image !

**Comment by camill-a** [comment]
It's find I sorted it out, but Xcode is updating. I'll post my code asap

**Comment by camill-a** [comment]
`      myImageView.kf_setImageWithURL(URL, optionsInfo: [...]).downloadTask?.ownerDownloader?.requestModifier = { request in
        request.addValue("application/json", forHTTPHeaderField: "Content-Type")
    ...
      }`

**Comment by onevcat** [comment]
Since the image setting methods will use the default downloader, you could just set the modifier block to the default downloader to make things easier:

```swift
ImageDownloader.defaultDownloader.requestModifier = {
    request in
    // Set request header here
}
```

**Comment by camill-a** [comment]
Looks better indeed, but where does this instance of `ImageDownloader` come from?

**Comment by onevcat** [comment]
:) Never mind~

**Comment by liuweicode** [comment]
Very useful, thanks!
