### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by zhangbozhb** [onevcat/Kingfisher#280]
version: Using Kingfisher (2.2.0)
When I use instrument to detect memory leaks. It alway report leaks. call stack  is:

Kingfisher specialized _GeneratorBox.__allocating_init(A) -> _GeneratorBox<A> ...Pods/Kingfisher/Sources/String+MD5.swift:0
Kingfisher MD5.calculate() -> [UInt8] Pods/Kingfisher/Sources/String+MD5.swift:206
....

**Comment by onevcat** [comment]
Thanks for reporting this. I will take a look at it.

**Comment by onevcat** [comment]
Should be fixed in #281

**Comment by zwang** [comment]
Thanks for fixing this. Had the same issue. After figured it might be related to this library, I came here and already saw a solution for it. :+1:
