### ISSUE TITLE
kf_setImageWithURL/Resource params non-default

### ISSUE THREAD

**Issue by VladislavJevremovic** [onevcat/Kingfisher#284]
After updating to 2.2.1, now one has to call kf_setImageWithURL/Resource with all 5 params even if nil. Why not make last four ones default to nil?

**Comment by onevcat** [comment]
Oops, Forgot it :(

**Comment by VladislavJevremovic** [comment]
Thanks for a quick response! ;)

**Comment by onevcat** [comment]
It should be fixed in [2.2.2](https://github.com/onevcat/Kingfisher/releases/tag/2.2.2). 

Thanks for catching it!
