### ISSUE TITLE
Load Facebook Profile Picture

### ISSUE THREAD

**Issue by bluesoulx** [onevcat/Kingfisher#286]
Is it possible  to load image from Url with a http redirect?
just like 

> http://graph.facebook.com/{Fb_UserId}/picture?type=large

Perhaps I missing something in ReadMe
Any Help is appreciated, Thanks a lot

**Comment by onevcat** [comment]
I guess currently is not supported automatically.
We may need to implement [this](https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSURLSessionTaskDelegate_protocol/index.html#//apple_ref/occ/intfm/NSURLSessionTaskDelegate/URLSession:task:willPerformHTTPRedirection:newRequest:completionHandler:) for redirecting. 

Feature in plan.

**Comment by jaimeagudo** [comment]
I confirm is not supported, I have suffered it myself implementing a 307 with NGINX and HSTS as iOS requirement to server images through https is coming. You can test it with 
https://p.aidto.party:41337/parse/files/Paid2Party/ca398f02933ab89ddd0b9f3f43bfbcd5_p1w7xaoRAL_0.jpg, the browser does it just fine.

I think it worth to mention on the docs. Thanks for sharing the good work guys 👍

**Comment by onevcat** [comment]
Sorry but I wish I could have time to implement it soon, in next week. Let's see.  :(

**Comment by onevcat** [comment]
@bluesoulx Just tested with Kingfisher and Facebook image url. It seems that the 302 redirect is already handled by `NSURLSession` now and I could load the image from the "http://graph.facebook.com/{Fb_UserId}/picture?type=large" without problem. Could you confirm this too?

**Comment by bluesoulx** [comment]
@onevcat Today I try this url with Kingfisher
I can confirm this is fixed! Thanks for your helps ^^

**Comment by Foriger** [comment]
Hi guys, sorry for hijacking this issue, but I have a question related to that :)
I have  GET REST call, which returns 302 and redirects to Azure Blob store URL.To download image correctly I need to modify Blob store URL a bit (I need to add one key to URL).Is this possible with you library?
