### ISSUE TITLE
Images are interchanging in Table View cells when scrolling

### ISSUE THREAD

**Issue by sukhvir1313** [onevcat/Kingfisher#288]
I have created a Table View using google contact's data with name, email and contact image into TableCell, when I scroll the table view, images are interchanging between cells and some of the images are not loading.

**Comment by alexdd55** [comment]
Is it possible that you are not setting the image view to nil if no pic is available?

**Comment by sukhvir1313** [comment]
It is resolved now, I think problem was with imageview's drag and drop into related view controller. After doing all that process again, everything resolved.

Thanks

**Comment by avityagi5** [comment]
I am face same problem.  
May be I am doing some wrong
Sample : 
if let imageUrl = AdvisorInfoModel.info.clientDetails[sections[indexPath.section].index + indexPath.row].objectForKey("avatarUrl") as? String
            {
                clientImageView.kf_setImageWithURL(NSURL(string: imageUrl)!)
            }

Thanks

**Comment by alexdd55** [comment]
Set your imageview = Nil at the beginning - then your code - else it will reuse the tablecell and the image will be reused, too.

I hope this will do the trick

**Comment by avityagi5** [comment]
Thanks it helped a lot...
Also got a workaround by:

 override func prepareForReuse() {
        clientImage.image = UIImage(named: "default_profile")
    }

**Comment by fukemy** [comment]
better setplaceholder  UIImage(named: "default_profile") when using kf
