### ISSUE TITLE
is that memory leak?

### ISSUE THREAD

**Issue by zhangbozhb** [onevcat/Kingfisher#294]
seemed leak in file: ImageCache.swift
line: 286 "var sSelf: ImageCache! = self"

**Comment by onevcat** [comment]
I didn't see a leak here since the strong self will be released in either of the completion handler. However, I will check it twice later to ensure that.

**Comment by kylebegeman** [comment]
Any updates? Getting the same leak

**Comment by onevcat** [comment]
@kylebegeman How did you profile for this? I didn't see any leak in Instruments for it.
