### ISSUE TITLE
Prefetcher内存泄漏？

### ISSUE THREAD

**Issue by Hesse-Huang** [onevcat/Kingfisher#295]
喵神你好，最近在毕业论文里使用到ImagePrefetcher，检查内存泄漏时意外发现一堆情况。我附了两张截图。
我的代码：
```
    private var prefetcher: ImagePrefetcher?
    private func prefetchPictureWithURLString(strings: [String]) {
        let urls = strings.flatMap({ NSURL(string: $0) })
        self.prefetcher = ImagePrefetcher(urls: urls,
                                          optionsInfo: nil,
                                          progressBlock: nil,
                                          completionHandler: { _ in self.prefetchDidFinish() })
        self.prefetcher!.start()
    }
    private func prefetchDidFinish() {
        self.prefetcher?.stop()
        self.prefetcher = nil
        tableView.reloadData()
    }
```
也不知道是不是我没用对。
第一次在GitHub提Issue，希望有用 : )

![1 pic_hd](https://cloud.githubusercontent.com/assets/12207083/14765729/e0806e78-0a20-11e6-9f87-013302968243.jpg)
![2 pic_hd](https://cloud.githubusercontent.com/assets/12207083/14765730/e4886ed0-0a20-11e6-81b8-da273636b7b7.jpg)

**Comment by onevcat** [comment]
Duplicated with #280 

It's an Apple issue instead of Kingfisher and we already have a workaround in recent version.

**Comment by Hesse-Huang** [comment]
嗯嗯，我将Kingfisher由2.1.0更新到最新就解决了。
谢谢喵神，我还打算重写我自己的代码呢。
