### ISSUE TITLE
So such module "Kingfisher"

### ISSUE THREAD

**Issue by chrisserra** [onevcat/Kingfisher#296]
Error occurs when doing the import:

import Kingfisher

...after pod install and opening the xcworkspace file.

Xcode v. 7.2
iOS v. 9.0
Swift 2

**Comment by onevcat** [comment]
The latest version of Kingfisher only supports from Swift 2.2. So maybe you need to pin your version to an earlier one if you are using Xcode 7.2. Please see README for more.
