### ISSUE TITLE
1.x -> 2.x MigrationGuide: alternative to .DefaultOptions

### ISSUE THREAD

**Issue by mheicke** [onevcat/Kingfisher#298]
hi, I'm just migrating an old project and used KingfisherManager.DefaultOptions. Is there anything similar in 2.x or should I just add the used options to all retrieveImageWithURL calls?
best regards,
matt

**Comment by onevcat** [comment]
Hi,

The default options in version 1.x was not intended to be mutable. So we removed it in version 2.x.

You could simply create a wrap method and pass your options there to make things easier.

**Comment by mheicke** [comment]
okay, that seems reasonable. You probably want to put that in your migration guide :-) thanks for your time and great work
