### ISSUE TITLE
Several "Expected Separator" Errors

### ISSUE THREAD

**Issue by troy21688** [onevcat/Kingfisher#301]
I am new to iOS development and recently came across this library. I integrated it into my application by using CocoaPods, however, I am receiving several "Expected Separator" errors.

I was always told not to modify external libraries and keep them locked. Any idea why I am receiving these errors?

![image](https://cloud.githubusercontent.com/assets/16483832/14903851/b9a1c33c-0d69-11e6-83c6-7125271eeb76.png)

**Comment by troy21688** [comment]
This image is actually more comprehensive:

![image](https://cloud.githubusercontent.com/assets/16483832/14903876/efc8bc22-0d69-11e6-9c74-c79441bb5beb.png)

**Comment by onevcat** [comment]
Hi, it seems that you are still using Swift 2.1 or earlier. The latest version of Kingfisher supports from Swift 2.2. You could solve it by upgrading to the latest Xcode 7.3 (which contains Swift 2.2) or specify an earlier version of Kingfisher in you Podfile.

**Comment by onevcat** [comment]
And I believe Kingfisher 2.1.0 is the latest version which is compatible with Swift 2.1.

**Comment by troy21688** [comment]
Is there an easier way to download the latest XCode other than through the Apple Store? I simply want to update and the progress bar is stating it may take a few hours...

**Comment by onevcat** [comment]
You can find a download link for the dmg file here https://developer.apple.com/downloads/

But you may need a developer account to access this page.
