### ISSUE TITLE
Licensing of String+MD5 is incorrect

### ISSUE THREAD

**Issue by meh-uk** [onevcat/Kingfisher#302]
I appreciate that this is a tedious t crossing issue.

However strictly this file should be licensed under the Apache license as that's the licence on the project it comes from.

**Comment by onevcat** [comment]
Hi,

Thanks for pointing it out!

In fact this file is not quite different from the one being used in `HanekeSwift`. It's now more likely another derivation from the original one in `CryptoSwift`. I will check whether I can remove the description about Haneke and make it following CryptoSwift's license directly.

Thank you for pointing it out!

**Comment by meh-uk** [comment]
Cool :).

**Comment by onevcat** [comment]
See #310 for more.

**Comment by meh-uk** [comment]
Thanks :).
