### ISSUE TITLE
memory leak? it happens when reopen wifi connection

### ISSUE THREAD

**Issue by x1911** [onevcat/Kingfisher#303]
ImageView+Kingfisher.swift
line 148:  sSelf.image = image

the App crash in that line, when the WIFI connection is closed, then reopen it, 
dont know why

open App with WIFI, image is loaded and App run well

close App then close WIFI, image still show and the App is fine

close App then open WIFI, crash...

**Comment by onevcat** [comment]
I cannot reproduce this crash.
