### ISSUE TITLE
KingFisher fully support IPv6?

### ISSUE THREAD

**Issue by racer1988** [onevcat/Kingfisher#314]
Hello,

Due to http://9to5mac.com/2016/05/04/apple-will-require-ios-app-store-apps-to-support-ipv6-only-networks-from-june-1/

I am opening this to ask a question.

Is KingFisher fully supporting IPv6?
referencing the doc from Apple 
https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1

I didn't find any low level API call in the code myself, but I'd rather raise the issue as a question that get the app rejected later on ;)

Thanks

**Comment by onevcat** [comment]
Hi, @racer1988 

Thanks for the link and information.

I checked the doc from Apple. Since there is no low level calling in Kingfisher at all, so I believe there should be no need to do any modification in Kingfisher to fully support IPv6.

**Comment by racer1988** [comment]
@onevcat Thanks! I will close this then

**Comment by SwiftySpartan** [comment]
Hi there,

I recently just had one of my apps rejected as the images were not loading.

Are you entirely sure that KingFisher fully supports IPv6?

![temp sczhwwnb](https://cloud.githubusercontent.com/assets/20083774/17550250/67ace322-5ef4-11e6-9dcc-3df4727556c8.png)

the attached screenshot is from apple

**Comment by onevcat** [comment]
Yes, Kingfisher fully supports IPv6 only network. I am using Kingfisher in my company project and it was approved several weeks ago and today. So I believe it might be other reason for you. Are you using any thing like IP address to access any resource?

**Comment by SwiftySpartan** [comment]
@onevcat thank you, i found out the this morning that my app was approved. Didnt change anything but except for handling my errors properly. I believed the images were not loading at all  as you could see not even the first two had loaded.

Thank you so much for creating a great framework/module! honestly love it!
