### ISSUE TITLE
Placeholder image GIF support?

### ISSUE THREAD

**Issue by andrewabdalla** [onevcat/Kingfisher#315]
Is it possible to use a GIF as the placeholder image while loading a photo?

I've have tried while using AnimatedImageView() but I only see the first frame of the GIF until the URL image loads.

**Comment by onevcat** [comment]
Currently no. But it will be an interesting feature. I will consider it in a later version. (P-R for it will be welcome as well, let me know if you want to do so.)

**Comment by jdmoreira** [comment]
I'll do this if that's ok with you. P-R soon.

**Comment by onevcat** [comment]
@jdmoreira Sure!

**Comment by jdmoreira** [comment]
Pull Request -> #425

**Comment by onevcat** [comment]
Merged.
