### ISSUE TITLE
setImageWithUrl(_:) sometimes failes. 

### ISSUE THREAD

**Issue by mrfarukturgut** [onevcat/Kingfisher#321]
I dont know why but just this method sometimes fails. After two or three times recalling this function it works properly. 
I am just using this code, by the way;

`imageView.kf_setImageFromUrl(url!)`

**Comment by onevcat** [comment]
It could be more help if you could supply more information on it.

For example, is there any useful log or information? Could it be just a slow network connection?

**Comment by mrfarukturgut** [comment]
It turns out, downloading doesn't fails but it takes some time. 

There is a new issue here, when it starts the download the new image, old image disappears. Now the question is, is there a way to show downloading animation while download task?

**Comment by onevcat** [comment]
You could set the placeholder image to your current old image to prevent the disappearance. And there is already an out-of-box indicator to use. Try to set `kf_showIndicatorWhenLoading` of `UIImageView` to `true` to show an indicator while downloading.
