### ISSUE TITLE
kf_setImageWithResource isn't tolerant to nil NSURL

### ISSUE THREAD

**Issue by kostapappas** [onevcat/Kingfisher#330]
The programmer must be sure that NSURL in kf_setImageWithURL isn't nil. 

If kf_setImageWithURL accepted optional NSURL and select placeholder image in the case of nil, it would be handy. 

I will try to send a pull request If you think it's a  good idea.

**Comment by onevcat** [comment]
Hi, @kostapappas 

Thanks for the idea. A pull request on this will be welcomed!

**Comment by matthewsommer** [comment]
I am having this same issue. I have to make a network query to get a URL of an image before I then download the image. What would be cool is if I can check if an image is already cached based on a resource cache key and if not then I'd run my two network calls (get the URL, then get image from the URL).

**Comment by matthewsommer** [comment]
As I workaround I used the code below. Is this okay?

```
            if let image:Image = KingfisherManager.sharedManager.cache.retrieveImageInDiskCacheForKey("112312321") {
                cell.imageViewAvatar?.image = image
            }
```
