### ISSUE TITLE
kingfisher crash

### ISSUE THREAD

**Issue by meng03** [onevcat/Kingfisher#336]
遇到一个crash，下面是通过bugly收集的堆栈信息，麻烦看看是什么问题😊
SIGSEGV
SEGV_ACCERR
0 ??? 000000000000000000 000000000000000000 + 0
1	Kingfisher	0x00000001012e3ffc	_TFC10Kingfisher15ImageDownloader20downloadImageWithURLfTCSo5NSURL17retrieveImageTaskGSqCS_17RetrieveImageTask_7optionsGSqGSaOS_25KingfisherOptionsInfoItem__13progressBlockGSqFT12receivedSizeVs5Int649totalSizeS4__T__17completionHandlerGSqFT5imageGSqCSo7UIImage_5errorGSqCSo7NSError_8imageURLGSqS1__12originalDataGSqCSo6NSData__T___GSqVS_25RetrieveImageDownloadTask_ + 164
2	Kingfisher	0x00000001012f9a14	_TFFC10Kingfisher17KingfisherManager33tryToRetrieveImageFromCacheForKeyFTSS7withURLCSo5NSURL17retrieveImageTaskCS_17RetrieveImageTask13progressBlockGSqFT12receivedSizeVs5Int649totalSizeS3__T__17completionHandlerGSqFT5imageGSqCSo7UIImage_5errorGSqCSo7NSError_9cacheTypeOS_9CacheType8imageURLGSqS1___T__7optionsGSqGSaOS_25KingfisherOptionsInfoItem___T_U0_FTGSqS4__GSQS6___T_ + 1308
3	Kingfisher	0x00000001012f8634	_TPA__TFFC10Kingfisher17KingfisherManager33tryToRetrieveImageFromCacheForKeyFTSS7withURLCSo5NSURL17retrieveImageTaskCS_17RetrieveImageTask13progressBlockGSqFT12receivedSizeVs5Int649totalSizeS3__T__17completionHandlerGSqFT5imageGSqCSo7UIImage_5errorGSqCSo7NSError_9cacheTypeOS_9CacheType8imageURLGSqS1___T__7optionsGSqGSaOS_25KingfisherOptionsInfoItem___T_U0_FTGSqS4__GSQS6___T_ + 200
4	Kingfisher	0x00000001012d8bc4	_TPA__TTRXFo_iTGSqCSo7UIImage_GSQO10Kingfisher9CacheType___iT__XFo_oGSqS__dGSQS1___dT__ + 76
5	Kingfisher	0x00000001012d9844	_TPA__TFFFC10Kingfisher10ImageCache19retrieveImageForKeyFTSS7optionsGSqGSaOS_25KingfisherOptionsInfoItem__17completionHandlerGSqFTGSqCSo7UIImage_GSQOS_9CacheType__T___GSqbT_T__U0_FT_T_U1_FT_T_ + 72
6	libdispatch.dylib	0x00000001820c94bc	__dispatch_call_block_and_release + 24
7	libdispatch.dylib	0x00000001820c947c	__dispatch_client_callout + 16
8	libdispatch.dylib	0x00000001820ceb84	_dispatch_main_queue_callback_4CF + 1844
9	CoreFoundation	0x0000000182634d50	___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
10	CoreFoundation	0x0000000182632bb8	___CFRunLoopRun + 1628
11	CoreFoundation	0x000000018255cc50	CFRunLoopRunSpecific + 384
12	GraphicsServices	0x0000000183e44088	GSEventRunModal + 180
13	UIKit	0x000000018783e088	UIApplicationMain + 204
14	Client	0x00000001004b8fa8	main (AppDelegate.swift:22)
15	libdyld.dylib	0x00000001820fa8b8	_start + 4

**Comment by onevcat** [comment]
Not sure what happened. But there is no other report on it, so I guess it should be a rare case.
