### ISSUE TITLE
Activity Indicator

### ISSUE THREAD

**Issue by Codeido** [onevcat/Kingfisher#341]
Do you think that an optional UIActivityIndicator during the loading can be a right solution for the loading process?

If yes, i can create a pull request that implement this feature.

Thanks
-Paolo-

**Comment by onevcat** [comment]
Hi, @Codeido 

Thanks for contacting. It's a great idea. However, I believe this feature is already contained in Kingfisher.

You could set `kf_showIndicatorWhenLoading` for your ImageView (both `UIImageView` and `NSImageView`) to enable the indicator during loading image from web. I should add it readme file to make it clear. (And if you'd like, you could create a p-r for the readme file to add this).

Of course, any contribution on improving it is warmly welcomed. :)

**Comment by Codeido** [comment]
Thanks @onevcat. You're right.
