### ISSUE TITLE
Process image before set image to UIImageView using kf_setImageWithURL:

### ISSUE THREAD

**Issue by faisalrasbihan** [onevcat/Kingfisher#348]
Is there a way to process the image that I got before showing my image using `kf_setImageWithURL:` method? For example, if I found the image that I downloaded is too big I want to be able to reduce the resolution of that image before showing it in my Table View Cell. I tried to download my image asynchronously using `downloadImageWithURL(_:progressBlock:completionHandler:)` and reduce the resolution of the downloaded image in my completionHandler: before showing it in my table view cell but this create a problem that when I scroll in my table view sometimes the cell display the wrong image.

**Comment by onevcat** [comment]
Feature in plan. See #320 and #326

**Comment by onevcat** [comment]
Implemented in Kingfisher 3. Check [`ImageProcessor`](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#processor) for more.
