### ISSUE TITLE
CommonCrypto.swift

### ISSUE THREAD

**Issue by onmyway133** [onevcat/Kingfisher#349]
Hi, I see in this https://github.com/onevcat/Kingfisher/blob/master/Sources/String%2BMD5.swift that you mention `CommonCrypto.swift` cannot be made as Swift framework.

I made a comment to that thread http://stackoverflow.com/a/37125785/1418457, and a repo https://github.com/onmyway133/CommonCrypto.swift

Can you take a look? Thanks

**Comment by onevcat** [comment]
Hi. @onmyway133 

Thanks for letting me know your repo. It seems great and cool!

CommonCrypto could be used in a Swift app or extension target, but not in a framework. 

I would like to use your work if I am working on an app project. However, Kingfisher is a framework itself, so I prefer to depend less or no other frameworks. So the users could have no concern about conflicting with other frameworks.

I hope you could understand it. Thank you!
