### ISSUE TITLE
请教对于线程安全的问题

### ISSUE THREAD

**Issue by xylxi** [onevcat/Kingfisher#354]
喵神，在ImageCache使用的是`dispatch_async(self.ioQueue,block)`，串行队列保证读写磁盘缓存线程安全，那么为什么在ImageDownloader不使用串行队列的`dispatch_sync(串行队列,block)`，而是用`dispatch_barrier_sync(self.barrierQueue,block)`呢？两者有什么区别吗

**Comment by onevcat** [comment]
It's not an issue so I am closing this.

And by using barrier, you could ensure the safety of multiple thread instead of just one. The resource will not be shared until the barrier queue exits.
