### ISSUE TITLE
Q: play GIF only once with AnimatedImageView

### ISSUE THREAD

**Issue by szuniverse** [onevcat/Kingfisher#356]
Is it possible to play the gif only once with AnimatedImageView ?

**Comment by halonsoluis** [comment]
..and also known when it has ended.

**Comment by onevcat** [comment]
TODO: Add `repeatCount` and related delegate methods to `AnimatedImageView`.

**Comment by JacobMao** [comment]
@halonsoluis I created a PR for this issue

**Comment by onevcat** [comment]
Supported in #829
