### ISSUE TITLE
Can't load image from URL is protected with headers

### ISSUE THREAD

**Issue by TheSwifter** [onevcat/Kingfisher#358]
I want to get an Image from server but the access to  this image needs to set specific headers (Token).

I am using KingFisher with Swift 2.2, is there any features for this case ?

**Comment by Bargetor** [comment]
also need

**Comment by TheSwifter** [comment]
Anyone could help us ?

**Comment by onevcat** [comment]
@TheSwifter I believe you could use the `requestModifier` of `ImageDownloader` to modify the image request. You could find some description of it in the README.md:

```swift
let downloader = KingfisherManager.sharedManager.downloader

// requestModifier will be called before image download request made.
downloader.requestModifier = {
    (request: NSMutableURLRequest) in
    // Do what you need to modify the download request. Maybe add your HTTP basic authentication for example.
}
```

**Comment by Mazorati** [comment]
+1

**Comment by onevcat** [comment]
`requestModifier` was removed from Kingfisher from version 3. Instead, you may need to use a modifier to change your request. See [this](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending) for more.
