### ISSUE TITLE
download policy: same url but updated image content?

### ISSUE THREAD

**Issue by wangbourne** [onevcat/Kingfisher#36]
Is the framework capable of identifying whether the image content has changed and then it schedules a  force download, rather than reuses the cached content?

**Comment by onevcat** [comment]
Currently no. This issue is duplicated to #35 

It is a planned feature and will be added later. Right now, you can only use different url/key for different images or force a download by using the `ForceRefresh` option.

**Comment by onevcat** [comment]
Closing since duplicated. See #35
