### ISSUE TITLE
图片地址中有感叹号

### ISSUE THREAD

**Issue by jeffreylyg** [onevcat/Kingfisher#361]
hi，喵神，现在云服务比如七牛，阿里云都支持图片转小图等服务，这样会在原url中加入!180的后缀，表示将原图片最小边为180等比例压缩，发现Kingfisher是拿不到这样的图片的，SDWebImage也拿不到，，但这个url在mac的浏览器是可以拿到的。Kingfisher是可以拿到原地址的图片的。我感觉问题是出在url上，但google了好久没有找到解决办法，BTW，我原来的OC项目用SDWebImage是可以的。

**Comment by 13hoop** [comment]
＋1 👍

**Comment by onevcat** [comment]
@jeffreylyg 请问下有实例的图片么？我可以用来测试一下..

**Comment by jeffreylyg** [comment]
首先感谢喵神 @onevcat 的回复。 
原地址：http://qiniu.22double.com/Fq8hbzaEfBTkaMIWB8Mp2g1PlN-G
按照七牛的规则 http://qiniu.22double.com/Fq8hbzaEfBTkaMIWB8Mp2g1PlN-G!180

在两个地址在浏览器中都是可以访问的，但Kingfisher只能拿到原地址的图片，访问加后缀的地址后报出的错误为 error: Optional(Error Domain=com.onevcat.Kingfisher.Error Code=10000 "(null)")

**Comment by onevcat** [comment]
我的 Safari 也是不能识别的，不过 Chrome 可以。
加感叹号的版本七牛返回的是一个 webp 图片，暂时 Kingfisher 不支持 webp 格式，所以无法使用。

我没用过七牛的服务，你可以看看有没有保持 png 的设置方法。

**Comment by cherishloveyou** [comment]
我的safari能打开哦

**Comment by LvJianfeng** [comment]
http://img03.sogoucdn.com/app/a/100520091/20161111122624 这种是不支持的么？
