### ISSUE TITLE
Imagecache init from path bug report. 

### ISSUE THREAD

**Issue by lastMove** [onevcat/Kingfisher#364]
Hello, 
Thanks for this library, I love your prefetcher (That I use as a multiple downloader) and the way that the code is divided ; It so easy to use just some parts of the framework. 👍 
A little bug (or not) 
when initialising a custom ImageCache, if the path given start with "file://" it doesn't work. 
Can be annoying if we work with URL :

``` Swift
 let fileManager = NSFileManager.defaultManager()
 let directoryURL = fileManager.URLsForDirectory(.DocumentDirectory, inDomains: .UserDomainMask)[0]
let cache =  ImageCache(name: "custom", path: url.absoluteString) // not working
```

It doesn't work because NSURL absoluteString method give a string with scheme like this one ""file:///Users/lastMove/Library/Developer/CoreSimulator/Devices/6F2A9EAE-FEAC-4699-A2E4-E4CC2BA5B32C/data/Containers/Data/Application/E348EA47-08C1-468C-B22E-F75E6DB85159/Documents/images_firstAid/com.onevcat.Kingfisher.ImageCache.images_firstAid"

Some possibility to improve the behavoir : 
- add a convenience init(name:String, url:NSURL)
- or just remove the stringByReplacingOccurrencesOfString("file://", withString: "")

**Comment by 0xpablo** [comment]
You should use `url.path`, not `url.absoulteString`.
