### ISSUE TITLE
Test `SSLCertificateValidation` is failing because the remote URL is offline

### ISSUE THREAD

**Issue by macecchi** [onevcat/Kingfisher#365]
The tests for all targets are failing because the following URL, used to validate the test `testSSLCertificateValidation` is offline and the requests time out:

https://testssl-expire.disig.sk/Expired.png

**Comment by onevcat** [comment]
What a bad news.

I think we could commit it out temporarily until we find another way to test it.

**Comment by onevcat** [comment]
`testSSLCertificateValidation` is removed temporarily in #366
