### ISSUE TITLE
AnimatedImageView

### ISSUE THREAD

**Issue by mixlan123** [onevcat/Kingfisher#370]
tableView中使用 AnimatedImageView 卡顿明显

**Comment by leviathan** [comment]
@mixlan123 could you elaborate a bit further (add a more detailed explanation) ? 
I don't understand what this issue is about.

**Comment by onevcat** [comment]
You could try to set `preloadAllGIF` to true to decode all data at once to get better scrolling performance (with more using of memory although.)
