### ISSUE TITLE
Directly set UIImage to UIButton without NSURL or Resource

### ISSUE THREAD

**Issue by shahdhiren** [onevcat/Kingfisher#372]
I am fetching Contacts using CNContactStore. From there I am directly getting images rather than any URL or imageName.

I want to set this UIImage using Kingfisher, so that UITableView dequeue cell issues will be resolved. I tried few things but didn't worked as the Resources ultimately work with NSURL.

Let me know if it supports UIImage as well or not.

**Comment by onevcat** [comment]
So what you need is the cache feature. You could use `ImageCache` class standalone for this, instead of setting a resource.
