### ISSUE TITLE
imageView.kf_load("http://your_image_url.png") shortcut

### ISSUE THREAD

**Issue by selwin** [onevcat/Kingfisher#373]
Thanks for this excellent library!

What do you think of adding a shortcut to `kf_setImageWithURL` make sense? I was thinking something like `imageView.kf_load("http://your_image_url.png")` or `imageView.kf_setImage("http://your_image_url.png")`.

These add nothing new, functionality wise, just a nicer syntax.

**Comment by onevcat** [comment]
It's a good shorthand and I'd like to see it in Kingfisher.

Would you mind to add it and send me a p-r? I'd prefer "kf_setImageWithURLString" as the API name for Swift 2.2, which would be verbose and more suitable for current API guide. 

And I could later give it a more Swifty name in Swift 3.0.

**Comment by onevcat** [comment]
In Swift 3, we made `Resource` a protocol and to be the only acceptable thing for any extension method. Now you can implement this easily by making `String` adopt to `Resource` protocol.

I guess we could make it default in a later update.

**Comment by onevcat** [comment]
After some reconsideration, it's better to leave it to users of framework.
