### ISSUE TITLE
Reason: Image not found

### ISSUE THREAD

**Issue by thanhdevapp** [onevcat/Kingfisher#374]
My Log, run with IP6PLUS IOS 9.3 and Kingfisher at "2.4.2"

dyld: Library not loaded: @rpath/Kingfisher.framework/Kingfisher
  Referenced from: /Users/thanhngoxuan/Library/Developer/CoreSimulator/Devices/9FA2F252-0249-4637-BFA6-BE3181C88476/data/Containers/Bundle/Application/DF99B81D-1BA0-4C2D-8C62-C360260B4D92/Alumni.app/Alumni
  Reason: image not found
(lldb) 

` button.kf_setImageWithURL(url, forState:.Normal)`

**Comment by onevcat** [comment]
Please ensure you have embedded Kingfisher.framework in your Embed Framework build phase.

**Comment by thanhdevapp** [comment]
fixed, close issue, thanks
