### ISSUE TITLE
one-frame gif disappears on UINavigationController transition

### ISSUE THREAD

**Issue by kubajakowski** [onevcat/Kingfisher#375]
GIFs are loaded using  UIImage.animatedImageWithImages when preloadAll flag is true. For GIFs this flag is always true and there's no way to opt-out.

```
//somewhere in kf_setImageWithResource
if shouldPreloadAllGIF() {
    options.append(.PreloadAllGIFData)
}
```

```
extension ImageView {
    func shouldPreloadAllGIF() -> Bool {
        return true
    }
}
```

Now when we have such image, it disappears when i.e UINavigationController transition is performed (easy to check on swipe-to-back gesture).
When GIF contains only one frame, Image should be created as regular image (without animation, just like when preloadAll flag is set to false) to prevent this disappearing.

**Comment by onevcat** [comment]
Now you can use `onlyLoadFirstFrame` to load the first frame of a GIF.
