### ISSUE TITLE
Setting a cached image is too slow

### ISSUE THREAD

**Issue by MHX792** [onevcat/Kingfisher#376]
I have a tableView with user images as the initial view controller. When my app starts it first shows the placeholder image and then the cached image. To test this I created a blank view controller and set it to be the initial view controller:

```
class ViewController: UIViewController {
    @IBOutlet var userImage: UIImageView!

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let imageUrl = "..."
        let url = NSURL(string: imageUrl)!
        let resource = Resource(downloadURL: url, cacheKey: "thumbnailImage")
        self.userImage.kf_setImageWithResource(resource, placeholderImage: UIImage(named: "profile_blank"))
    }
}
```
 Unfortunately the lag occurs there, too. Note that I close the app after compiling and re-run it again. Because compiling will clean(?) the disk cache. You can see the flashing only if you have set a placeholderImage, taht is different from the background color.

How to fix this? Can't I access the cached image on the disk directly for the initial load? Or maybe run it on the main thread (for this I need to be sure that there is a cached version of the image. Is there a check for this?)

**Comment by MHX792** [comment]
**Update**: To test disk performance I wrote some functions on my own to save images to the disk and retrieve them form there. It's way faster than kingfisher. But why? Does kingfisher look for the cached images in the memory first when the app gets started? Is there an option to skip this step and directly look for on the disk?

**Comment by onevcat** [comment]
@MHX792 

The default implementation of retrieving an image from cache is an async operation. It is intended to be an optimization for loading a lot of images in a table view or collection view, to keep the scrolling smoothly. If you are try to load only one image, there is no need to use the async way. Instead, you could use the `retrieveImageInDiskCacheForKey` in `ImageCache` to do a sync accessing to your disk cached image.

Kingfisher will look for images in memory first, and then in disk. However, it is not the reason which causes your issue.

**Comment by MHX792** [comment]
@onevcat Thanks it seems like `retrieveImageInDiskCacheForKey` solves the problem.

So I think loading it sync on the first init of the view is better for a good user experience. But how to make sure that afterwards only the async method gets fired?
  
```
// first load sync from disk cache
self.userImageView.image = ImageCache.defaultCache.retrieveImageInDiskCacheForKey("thumbnailImage_\(userId)")

// then async from memory / disk and for possible updates
let url = NSURL(string: imageUrl)!
let resource = Resource(downloadURL: url, cacheKey: "thumbnailImage_\(userId)")
self.userImageView.kf_setImageWithResource(resource, placeholderImage: UIImage(named: "profile_blank"))
```

**Comment by onevcat** [comment]
The `kf_setImage` method will be always an async operation.

**Comment by titopalito** [comment]
Maybe it can be a problem with the images size, that's my case using another pod with similar functions.
you can make an hybrid cache with something like this:
     //ViewController variable "cache"
     var cache                           : NSCache<AnyObject, AnyObject>!

                               if let objImagen = self.cache.object(forKey: urlString+"reduced" as AnyObject)  {
                                    cell.imageView.image = objImagen as? UIImage
                                    print("Size cached: \(cell.imageView.image?.size ?? CGSize(width: 0, height: 0))")
                                }else {
                                    cell.imageView.sd_setImage(with: URL(string: artworkUrl), completed: {
                                        (image, error, imgCacheType, url) in
                                        print("Size real: \(image?.size ?? CGSize(width: 0, height: 0)))")
                                            let imgReduced = image?.resized(toWidth: imgWidth)
                                            cell.headerImageView.image = imgReduced
                                            self.cache.setObject(imgReduced!, forKey: urlString+"reduced" as AnyObject)
                                    })
                                }

And an extension for the resizing image:

extension UIImage {
func resized(toWidth width: CGFloat) -> UIImage? {
        let canvasSize = CGSize(width: width, height: CGFloat(ceil(width/size.width * size.height)))
        UIGraphicsBeginImageContextWithOptions(canvasSize, false, scale)
        defer { UIGraphicsEndImageContext() }
        draw(in: CGRect(origin: .zero, size: canvasSize))
        return UIGraphicsGetImageFromCurrentImageContext()
    }
}


You can make something similar with your kingfisher pod cause it has completion handlers like SDWebImage.
Best regards
