### ISSUE TITLE
Integrating with Alamofire as Extension or somehow

### ISSUE THREAD

**Issue by indrajitsinh** [onevcat/Kingfisher#377]
Currently almost 95% iOS app uses some kind of Networking library like Alamofire
so instead of creating own networking and all of stuff in Kingfisher 
it would be  batter if Kingfisher utilise those networking libs 

So  User can have choice to which networking libs they wan't to use 
and they Specify like
```swift
Kingfisher.setDownloader(Alamofire()) 
```
or
by default it using own implementation of Networking
like  
```swift
Kingfisher.setDownloader(Kingfisher()) 
```
and all the network stuff is done by respective library and all post work is done by Alamofire.

**Comment by onevcat** [comment]
Hi,

Thanks for the suggestion. But Kingfisher itself is a standalone framework and it is not always a wise decision to introduce a coupling between different framework.

In another perspective, it requires either of Kingfisher or another network framework keeping a set of rule to make network request. In fact there is no such protocol or standards on how to make a request or data downloading. So it could really difficult to add it in a meaning way. So it will not be added, at least for a while.
