### ISSUE TITLE
ImageCache: expiration date

### ISSUE THREAD

**Issue by lonsky** [onevcat/Kingfisher#381]
@onevcat 

Is it possible to extend expiration date for cached image on the disk?

When I try to store the same file with the same key it seems like nothing happens.

Maybe something like this could be helpful for `ImageCache` class:
```
func touch(cacheKey: String)    //updates modified date
``` 
also it could be useful to call this method when you load file from cache (`retrieveImageForKey`).

in this case recently used files won't expire

**Comment by onevcat** [comment]
Kingfisher is using the modification date of a file to determine the expiration. So you should be able to extend the date by modify the file. Did you try to remove that cache first and then store the same file again? (I am not sure whether it could work though..)

Maybe we should use the access day instead of modification date to check the expiration. It might work better. How do you think about it?

**Comment by lonsky** [comment]
@onevcat thank you for reply and for great framework!

remove/add should work. but it's not neat solution :)

i can think about two different cache strategies:

1) (the current one) image file (or group of file) after downloading has _limited lifetime_ (equal `maxCachePeriodInSecond`) before subsequent download of new version of file.
With this strategy image file will have fixed expiration date: `expirationDate = downloadTime + maxCachePeriodInSecond ` and will be removed even if it was used recently.

2) image file (or group of file) after downloading modify its `NSFileModificationDate` attribute while being accessed via `retrieveImageForKey`.
With this strategy image file will shift its expiration date every time it is accessed and "garbage collector" will remove only unused/less used files.
Also, as "side effect", if cache will run out of available free space, it's possible to remove less relevant files first.

maybe it can be a property that will allow to switch between these strategies

**Comment by onevcat** [comment]
Use access date instead of modification date. So, just access that image from disk will extend the expiration date for the same. Implemented in #406
