### ISSUE TITLE
How to cache?

### ISSUE THREAD

**Issue by kwstasna** [onevcat/Kingfisher#382]
Hello.
I'm new to swift dev. and i'm using Parse server.
So i have a collection view with some cells which contain an UIImageView of the recipe for example.
So this is the code that i'm using to show the images on each cell

 
```
   cell.coverImage.image = ImageCache.defaultCache.retrieveImageInDiskCacheForKey(recipesClass.objectId!)
   
        if let imageFile = recipesClass[RECIPES_COVER] as? PFFile {
    
        
        
        let URL = NSURL(string: imageFile.url!)!
        let resource = Resource(downloadURL: URL, cacheKey: recipesClass.objectId)
        print("downloaded it")
        cell.coverImage.kf_setImageWithResource(resource)
        } else {
             cell.coverImage.image = UIImage(named:"logo")
        }

```

The problem is that even if i save it with cache the objected id of each recipe which is unique, it still prints "downloaded it" when i pull to refresh and it doesnt load them from cache.

Is there any proper way to make this work so it prevent the image to be downloaded each time?

Thanks and sorry for the noobie question.

Updated my code to this and i have a much better results but still when i refresh i get the print "Finished"

```
        let myCache = ImageCache(name: recipesClass.objectId!)
        let queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)
        let optionInfo: KingfisherOptionsInfo = [
            .DownloadPriority(0.5),
            .CallbackDispatchQueue(queue),
            .Transition(ImageTransition.Fade(1)),
            .TargetCache(myCache)
        ]
        if  let imageFile = recipesClass[RECIPES_COVER] as? PFFile {
        
        let URL = NSURL(string: imageFile.url!)!
        
        cell.coverImage.kf_setImageWithURL(URL, placeholderImage: nil,
            optionsInfo: optionInfo,
            progressBlock: { receivedSize, totalSize in
                print("\(indexPath.row + 1): \(receivedSize)/\(totalSize)")
            },
            completionHandler: { image, error, cacheType, imageURL in
                print("\(indexPath.row + 1): Finished")
        })
        
        } else {
             cell.coverImage.image = UIImage(named:"logo")
        }
```
        

Does this means that my image is downloaded again or its stored from cache???
P.S. The refresh simply makes a query to Parse to see if there is a new Recipe and then it reloads collection view's data.

**Comment by victorg1991** [comment]
You have a variable cacheType in the callback where you can check where the image comes from

**Comment by kwstasna** [comment]
Can you write me an example?

**Comment by victorg1991** [comment]
The same as you did, in the completionhandler block add the variable to the print function
print("cacheType: \(cacheType) \(indexPath.row + 1): Finished")

**Comment by kwstasna** [comment]
Ah, so now it prints
`Finished: cachType: Disk`
So now i'm sure that it is loaded from cache thanks !

**Comment by kwstasna** [comment]
Let it be. I closed the app and opened it again. 
If i run the app for the very first time it downloads 20mb
but if i open it again it has 0.1mb on network so it uses disk!
Thanks :D

**Comment by victorg1991** [comment]
I’m happy to help
