### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by nowfalsalam** [onevcat/Kingfisher#384]
Issue:- 
When i tried following url "https://img.evbuc.com///http%3A%2F%2Fcdn.evbuc.com%2Fimages%2F22654689%2F430201477%2F1%2Foriginal.jpg?h=200&w=450&rect=0%2C166%2C4626%2C2313&s=80150cb3cc27420a81ce636487ff45d8"
Optional unwrapping issue happened in completionhandler :- 
completionHandler?(image: cacheImage, error: nil, cacheType: cacheType, imageURL: URL)
here image and cachetype was nil , unwrapping of this nil values makes problem
// initialisation of completion handler :- here image is optional but cachetype is not optional
public typealias CompletionHandler = ((image: Image?, error: NSError?, cacheType: CacheType, imageURL: NSURL?) -> ())

Solution:- 
I set both image and cacheType as optional , 
public typealias CompletionHandler = ((image: Image?, error: NSError?, cacheType: CacheType?, imageURL: NSURL?) -> ())

**Comment by onevcat** [comment]
@nowfalsalam 

Hi, the `CacheType` will never be a `nil`. It will only be one of `.None`, `.Memory` or `.Disk`. The compiler could ensure that it will always has a value. So I believe the optional unwrapping issue you encountered is from somewhere else. (maybe you are trying to unwrap a nil image?)

**Comment by nowfalsalam** [comment]
Hi,
 But my problem solved when i changed CacheType as optional,

Regards
Nowfal E Salam

**Comment by onevcat** [comment]
Maybe you are using an earlier version?

I could remember there is a commit for it: #334 

So I believe you could solve it by upgrading to the latest 2.4.2.
