### ISSUE TITLE
Using Kingfisher with Swift 3

### ISSUE THREAD

**Issue by Minitour** [onevcat/Kingfisher#388]
I am using Xcode 8 beta and experimenting with iOS 10 and swift 3. I tried installing Kingfisher both manually and through cocoapods. However when I use cocoa pods I seems that the lib is in an older syntax and when xcode offers to convert it to swift 3 it simply breaks and the code just doesn't work with like 90+ swift compiler issues. Even when I install the Sources folder (from the Kingfisher swift-3 branch) it still doesn't work and has many compiler issues.
I am really at a dead end here and I am not sure what to do.

**Comment by Minitour** [comment]
## Update:
I realized I didn't have the lasted Xcode beta, therefor there was an issue with the syntax. I updated to Xcode 8 beta 4 and it works fine now.

**Comment by onevcat** [comment]
Good news!

**Comment by anooj1483** [comment]
I have the latest Xcode 8.0 (8A218a). After installing Kingfisher via pods, Xcode prompts me to convert it to Swift 3. When I choose to convert, it gives me lots of conversion issues.
 
![screen shot 2016-09-23 at 8 00 08 pm](https://cloud.githubusercontent.com/assets/6260395/18789383/6b1419bc-81c8-11e6-93e2-5d261f921f29.png)

![screen shot 2016-09-23 at 7 50 42 pm](https://cloud.githubusercontent.com/assets/6260395/18789055/10ef100a-81c7-11e6-8c30-06712e487916.png)

**Comment by onevcat** [comment]
@anooj1483 
:(
Didn't receive other reports on it. Did you try something like restart your Xcode or clean the project?

You may also need to add the SWIFT_VERSION option in your build setting.

**Comment by anooj1483** [comment]
@onevcat 
Thanks. I found your comment in Cocoapods GitHub. 
This issue got fixed by updating pods. ( `pod update` )
