### ISSUE TITLE
Sticky scroll from cached images in Swift 2

### ISSUE THREAD

**Issue by kwstasna** [onevcat/Kingfisher#389]
Hello.
I an using this code to display some image inside a UICollectionView but lets say that the cells are 25. When i go down to the last cell and then i try to go up to the first the images are loading again (from cache but still it shows the loading indicator.
My phone is iPhone SE and i dont have many apps and the phone is running perfect. If i load my app to an older iphone with many data on it then the scrolling it becomes sticky and its very annoying. How can we avoid this happening inside the collections view function cell for item at index path ???

```
    // Get Cover image
        let myCache = ImageCache(name: recipesClass.objectId!)
        let queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)
        let optionInfo: KingfisherOptionsInfo = [
            .DownloadPriority(0.5),
            .CallbackDispatchQueue(queue),
            .Transition(ImageTransition.Fade(1)),
            .TargetCache(myCache)
        ]
        if  let imageFile = recipesClass[RECIPES_COVER] as? PFFile {

        let URL = NSURL(string: imageFile.url!)!

        cell.coverImage.kf_setImageWithURL(URL, placeholderImage: nil,
            optionsInfo: optionInfo,
            progressBlock: { receivedSize, totalSize in
                print("\(indexPath.row + 1): \(receivedSize)/\(totalSize)")
            },
            completionHandler: { image, error, cacheType, imageURL in
                print("\(indexPath.row + 1): Finished")
                print("cacheType: \(cacheType) \(indexPath.row + 1): Finished")
        })

        } else {
             cell.coverImage.image = UIImage(named:"logo")
        }
```

Does anyone has the same issue?
Thanks!

**Comment by kwstasna** [comment]
With the code above i make a new Cache each time a cell deques? Or the cache remains the same even though the cell deques?

**Comment by onevcat** [comment]
If the `recipesClass.objectId` is different for each index path, you are creating multiple caches, and throwing your image there. And the same, if you are seeking an image in that cache but it isn't there, Kingfisher will try to download it again.

It is not a recommended way to create a cache for each image (as I understand from your code). A cache object should represent a kind of images, like all user thumbnails images in a cache, or all video previews. Or just use the default shared cache (`ImageCache.sharedCache`) would be a better choice.

And also specify a `CallbackDispatchQueue` to your customized queue is not necessary, if you are not sure what you are doing and/or it is not a must, just leave it empty to use the default implementation.

So, maybe you could try just use:

```swift
let optionInfo: KingfisherOptionsInfo = [
            .Transition(ImageTransition.Fade(1))
        ]
```

and see whether it could solve your problem.

**Comment by kwstasna** [comment]
So the problem is partially fixed. Only the images with >2mb takes some time to be displayed at the cell and this is a bit annoying too.
