### ISSUE TITLE
Save/restore cache locally.

### ISSUE THREAD

**Issue by hifall** [onevcat/Kingfisher#392]
First of all, nice lib! Simple yet powerful.

I wonder if it provides any interface for saving/restoring cache locally? This is useful when an app using Kingfisher has accumulated some [remote url -> local path] mappings, and before the device restarts, the app can save such mappings so that after restarted, the app can read the mappings from drive locally, so that it doesn't have to fetch images from the server again.

Thanks!

**Comment by onevcat** [comment]
Maybe you could use `ImageCache` for it? There is a [`storeImage(_:originalData:forKey:toDisk:completionHandler:)`](http://cocoadocs.org/docsets/Kingfisher/2.4.2/Classes/ImageCache.html#/s:FC10Kingfisher10ImageCache10storeImageFTCSo7UIImage12originalDataGSqCSo6NSData_6forKeySS6toDiskSb17completionHandlerGSqFT_T___T_) method for it. You could call it with your images/keys(which is the absolute string of your url by default) to add it to Kingfisher's cache system.
