### ISSUE TITLE
Progress bar completion handler is not being called

### ISSUE THREAD

**Issue by jayisidoro** [onevcat/Kingfisher#393]
I'm trying to add a custom progress bar, but I'm not able to because the progress block isn't being called / returning the receivedSize and total size. I'm doing kf_setImageWithURL ; i've used the code provided in the documentation but haven't had any luck. Anyone know why?

**Comment by onevcat** [comment]
Have no idea, since the tests for progress are working well. And I just had a try in the demo app, the progress callback works well for me.

A possible reason is you are loading a cached image, so there is no downloading progress.
