### ISSUE TITLE
Placeholder image not replaced when downloading is interrupted.

### ISSUE THREAD

**Issue by hifall** [onevcat/Kingfisher#394]
I am using Kingfisher to download image for an image view in a table cell. And I am seeing this issue where the placeholder image is not replaced. To reproduce this issue, I did:

1 add a table cell with an image view whose image is managed by Kingfisher, i.e., imageView?.kf_setImageWithURL(...); a placeholder image is passed in while calling kf_setImageWithURL. Now the cell appears with the placeholder image;
2 take the app to the background, so that the downloading is interrupted;
3 after a while (maybe ~1 minute), take the app to the foreground;
4 the placeholder is never replaced if I do nothing;
5 if I tap the placeholder image to switch to fullscreen, it can show the "real" image after a while; but then if I tap it again to quite fullscreen, the table cell still shows the placeholder image, rather than the "real" image.

My question is: how to replace the placeholder image once the real image is downloaded, if the downloading has been interrupted like described above?

Thanks!

**Comment by onevcat** [comment]
As I know, there should be several seconds left for app to finish the downloading. If the downloading process could finish, the placeholder images should be replaced by the downloaded ones.

If the downloading process is interrupted (which should be a rare case or you are in a bad network environment), the completion handler should be called with an error, maybe you could use that for retrying when you come back to foreground.

If the image representation is very important to you, observe the `UIApplicationWillEnterForegroundNotification` and do a `reloadData` is also a good idea.

**Comment by hifall** [comment]
Thanks! I will go ahead and try what you recommend.
