### ISSUE TITLE
OSX Activity Indicator center position bug

### ISSUE THREAD

**Issue by sendyhalim** [onevcat/Kingfisher#395]
Hi first of all, thanks for the awesome library!

I found a bug on activity indicator center position (OSX). When we show activity indicator in collection view, sometimes the cell (and the image view in the cell) gets re-used, if the re-used cell image view is set with image that has different image size, activity indicator center position will be invalid (because the indicator will be re-used for each individual image view)

https://github.com/onevcat/Kingfisher/blob/master/Sources/ImageView%2BKingfisher.swift#L234
https://github.com/onevcat/Kingfisher/blob/master/Sources/ImageView%2BKingfisher.swift#L104

Currently I'm creating an abstraction for `Kingfisher` so that every time url is set, I'm forcing the activity indicator to be recreated.

```
extension NSImageView {
  func setImageWithUrl(url: NSURL) {
    showActivityIndicator()
    kf_setImageWithURL(url)
  }

  func showActivityIndicator() {
    kf_showIndicatorWhenLoading = false // Remove old activity indicator
    kf_showIndicatorWhenLoading = true // Will create new activity indicator
  }
}
```

I guess one way to fix this is to create a method to invalidate `kf_indicator` cache and let api users to call it manually, something like

```
  func kf_invalidateActivityIndicatorCache() {
    if kf_showIndicatorWhenLoading {
      kf_showIndicatorWhenLoading = false
      kf_showIndicatorWhenLoading = true
    }
  }
```

I'm willing to create a pull request for this if you're ok with the approach, don't know if it's a best practice tho 🍻

**Comment by onevcat** [comment]
Hi, @sendyhalim 

I am a newbie on macOS development. So I am not sure about what is the right way to use `NSProgressIndicator`. However, instead of adding a `kf_invalidateActivityIndicatorCache` and letting users to call it manually, is there a better way to center the position automatically when reused? I would like to prefer that it keeps in superview's center.

**Comment by sendyhalim** [comment]
@onevcat I'm a newbie in macOS and iOS development too. Yep, there's a way to automatically center the position, that is by calculating new frame everytime `viewWillDraw` is called (tested manually)

```
extension ImageView {
  public override func viewWillDraw() {
    guard let indicator = kf_indicator where kf_showIndicatorWhenLoading else {
      return
    }

    let centerPoint = CGPoint(x: CGRectGetMidX(bounds), y: CGRectGetMidY(bounds))

    let indicatorFrame = indicator.frame
    indicator.frame =  CGRect(
      x: centerPoint.x - indicatorFrame.size.width / 2.0,
      y: centerPoint.y - indicatorFrame.size.height / 2.0,
      width: indicatorFrame.size.width,
      height: indicatorFrame.size.height
    )
  }
}
```

but I'm not sure if it's efficient, any thoughts?

**Comment by onevcat** [comment]
There should be a better way for it. I will take a look at it later today!

**Comment by MattTimmons** [comment]
Hi, any progress in exposing a fix?

**Comment by onevcat** [comment]
Maybe related to #797
