### ISSUE TITLE
Caching non-image files.

### ISSUE THREAD

**Issue by hifall** [onevcat/Kingfisher#398]
Hi,

Is it possible to cache non-image files, like audio (e.g., m4a)? If not, any plan to add it?

Thanks!

**Comment by onevcat** [comment]
No. Kingfisher is a framework focusing on image. Maybe some cache specified framework would be a better choice for you, like [AwesomeCache](https://github.com/aschuch/AwesomeCache)?

**Comment by hifall** [comment]
Cool, thanks for the suggestion!
