### ISSUE TITLE
When cache is full

### ISSUE THREAD

**Issue by hifall** [onevcat/Kingfisher#404]
I searched in Kingfisher's documentation and Google, but did not find the exact behaviour of Kingfisher in such a scenario:

1 set up the disk cache to use space no larger than, say, 50MB;
2 the images in the cache don't expire for a long time, say, 6 months;
What happens if the cache is full and no image in the cache is going to expire, then I call kf_setImageWithURL to fetch another image? Will Kingfisher clear some image(s) from the cache so that the new image can be cached? If so, based on what strategy (like LRU, etc.) are such image(s) chosen to be cleared?

Thanks!

**Comment by onevcat** [comment]
Currently the cache will fail silently. 

A lookup strategy to remove the oldest images or just do a clean would be an improvement to the framework.

**Comment by hifall** [comment]
Thanks for your reply.

I think limiting the disk cache's size and keep the images in it for a long time (or even indefinitely) is a useful case, and phasing out old images to make room for the latest ones should benefit in such case.

Any plan to add this in the future?

Thanks!

**Comment by onevcat** [comment]
Ah, I misunderstand your words. I thought you were meaning to set an unlimited size and trying to add images to the cache when the whole disk of phone is full.

For your case:

1. Set disk limit to 50MB
2. No images expired
3. Now the cache is 49.9MB

Adding another images to cache will not fail, even it exceeded the disk size limitation. The disk cleaning work will not happened unless the app is switched to background or terminated. So your images will be cached, it will only fails when your phone disk is full (which is a rare case I think).

The disk cleaning work will follow a LRU way to clean the images when the size exceeded or there are images expired. First Kingfisher will check whether there are any expired images and remove them. Then, if the disk size usage is larger than what set, Kingfisher will delete the earliest cached files, until it gets to the target size (which is half of the max disk size you set).

**Comment by hifall** [comment]
Awesome! This is what one can expect from a nice cache system!

**Comment by drbarto** [comment]
5 years later, and this is exactly the info I was looking for 😅 Still didn't find it mentioned in the docs.

**Comment by onevcat** [comment]
For 99.9% of cases, users should not worry about how the cache exactly works. I want to provide just a valid and working way by default. 

For Kingfisher, it is just an implementation detail. Writing it to the documentation just brings more noise for users. And worse for maintainers (like me), it also limits the possibility of changing another way of cache in the future without breaking some convention.

After these years of evolving, Kingfisher now also support a more fine-tuned cache policy by [this](https://kingfisher.onevcat.com/kingfisheroptionsinfoitem/#kingfisheroptionsinfoitem.memorycacheexpiration) and [this](https://kingfisher.onevcat.com/kingfisheroptionsinfoitem/#kingfisheroptionsinfoitem.diskcacheexpiration). But again, they are some advanced usage and for most of framework users, knowing them won't make their life easier or different.
