### ISSUE TITLE
Extending expiration date for images in disk cache.

### ISSUE THREAD

**Issue by hifall** [onevcat/Kingfisher#405]
Say I have dozens of images in disk cache. And my app uses some of them frequently, and doesn't want those to expire. How would I prevent Kingfisher from expiring them? More specifically, say:

1 I have 50 images cached in disk, and my app accesses 30 of them. By "accesses", I mean calling kf_setImageWithURL to supply the image;
2 I set up maxCachePeriodInSecond to be 7 days, with the intention that images not accessed in the last 7 days will be expired, and purged.

So in such a setting, would calling kf_setImageWithURL extend the image's expiration date to 7 days from the moment of calling? If not, what can I do to extend it?

Thanks!

**Comment by hifall** [comment]
Now I see your reply in https://github.com/onevcat/Kingfisher/issues/381.

You stated:
"Maybe we should use the access day instead of modification date to check the expiration. It might work better."

In all fairness, I agree with you on using something other than modification date to check for expiration. Using modification date doesn't seem all that elegant to me. After all, if the app keeps reading the image without modifying it, the image should be kept in cache for faster processing, right?

**Comment by onevcat** [comment]
Use access date instead of modification date. So, just access that image from disk will extend the expiration date for the same. Implemented in #406

**Comment by hifall** [comment]
WOW, can't believe this is happening so quickly. Amazing!
