### ISSUE TITLE
URLTransfrom character escaping messes up AWS signatures

### ISSUE THREAD

**Issue by sherwinzadeh** [onevcat/Kingfisher#409]
The July 7th commit for URLTransform added character escaping. However AWS signatures on media have % characters in them so that get's messed up now. Character escaping should be an option or something.

**Comment by onevcat** [comment]
@sherwinzadeh May I know which commit and which line of code you are meaning? I didn't find anything like `URLTransform` or escaping things.

**Comment by sherwinzadeh** [comment]
https://github.com/Hearst-DD/ObjectMapper/commit/9b8163a46882351674925dc585291fd996c6edd9#diff-fd8dda171c388a06dceed295b00c3d2a

**Comment by sherwinzadeh** [comment]
My apologies! This was a bug for ObjectMapper, not Kingfisher.

**Comment by onevcat** [comment]
:)
