### ISSUE TITLE
No kf_setImageWithUrl in Swift 3 branch?

### ISSUE THREAD

**Issue by JustinM1** [onevcat/Kingfisher#410]
just a heads up in case you aren't aware, it appears setImageWithURL is not in Podfile. I'm only getting the option to setImageWithResource. After checking all files in Podfile I did not see setImageWIthURL method. 

thanks

**Comment by onevcat** [comment]
Kingfisher for Swift 3 is not back compatible. You now need to use `kf_setImage(with:)`. And `Resource` is now a protocol. `URL` conforms it by default.

We will work on the migration guide later when Xcode 8 GM version is out. Before that, you might need to adopt and explore the change yourself. Generally speaking, you could expect that the APIs of Kingfisher for Swift 3 following the Swift 3 API guideline.

**Comment by JustinM1** [comment]
Got it, thanks for clearing that up
