### ISSUE TITLE
ImageDownloader: ability to modify HTTP header for each request

### ISSUE THREAD

**Issue by lonsky** [onevcat/Kingfisher#413]
Feature request:

Now it's possible to set `requestModifier` closure for the whole ImageDownloader object (general for each request).

It'd be useful to have ability to add specific header keys for each request (maybe as addition to values returned from general `requestModifier`).

Alamofire's ImageDownloader allows to pass header dictionary to request (as optional parameter though).

Thanks!

**Comment by onevcat** [comment]
Not a bad idea. I guess we could add another option case like `RequestHeader` in `KingfisherOptionsInfoItem`.

**Comment by onevcat** [comment]
Implemented in Kingfisher 3.

**Comment by linhaosunny** [comment]
it's there any example for modify http header? @onevcat

**Comment by onevcat** [comment]
Check https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending
