### ISSUE TITLE
在当次启动程序，第二次从缓存中加载该图片，就不显示transition fade等等，请教如何实现？

### ISSUE THREAD

**Issue by yangzhixiao** [onevcat/Kingfisher#415]
因为默认是第一次加载网络图片的时候，可以设置动画；第二次从缓存中读取就不会显示动画，但是可以通过设置foreTransition来强制显示动画，但是那样的话，一个tableview在重用cell，从缓存中设置图片，也会显示动画，我想要的效果是，在这次启动程序，第一次从缓存中加载图片，就显示fade动画，第二次cell重用的时候再设置这张图片的时候，就直接显示图片，不要动画，如何实现？谢谢！！！

**Comment by MaeseppTarvo** [comment]
Please use english. What do you even mean when you start typing inside hieroglyphics?

**Comment by onevcat** [comment]
So you could just pass `forceTransition` for the first time, and opt it in later setting.

**Comment by onevcat** [comment]
Since it is not an issue but instead a question, I closed it.
