### ISSUE TITLE
completionHandler not being called

### ISSUE THREAD

**Issue by vethos** [onevcat/Kingfisher#416]
Hi,
I'm trying to download a gif
i get callback of the progressBlock and it prints 

> Download Progress: 43/43

but the completionHandler isn't being called. 

``` Swift 
        let imageView = AnimatedImageView()
        imageView.kf_setImageWithURL(NSURL(string: "http://www.gifbin.com/bin/4802swswsw04.gif")!,
                                     placeholderImage: nil,
                                     optionsInfo: nil,
                                     progressBlock: { (receivedSize, totalSize) -> () in
                                        print("Download Progress: \(receivedSize)/\(totalSize)")
            },
                                     completionHandler: { (image, error, cacheType, imageURL) -> () in
                                        print("Downloaded and set!")
            }
        )
```

**Comment by vethos** [comment]
any url i use it doesn't work

**Comment by onevcat** [comment]
If there is no other strong reference to `imageView`, it will be released and the completion handler will not be called since it is already released. Kingfisher will not hold the image view.

**Comment by onevcat** [comment]
Since there is no further response from @vethos . I am closing it.

If there is any similar case, feel free to reopen.
