### ISSUE TITLE
modify image?

### ISSUE THREAD

**Issue by MylesCaley** [onevcat/Kingfisher#418]
I was trying to find the best way to modify an image before its put into the cache. When subclassing ImageCache to override storeImage it doesn't have the objc prefix so I couldn't. I modified it in my local copy. I can put a PR , but not sure that is the best approach for tweaking an image before putting it into the cache.

**Comment by MylesCaley** [comment]
Well, unfortunately the first time the image is shown it will be the unmodified image. I think what I am looking for is a callback before the image is saved and displayed. Since this involves both the UI and the cache not sure what the cleanest approach is. imageModifierHandler on downloadAndCacheImageWithURL ?

**Comment by onevcat** [comment]
It's a planned feature and being implemented now. But it will only appear in next major version of Kingfisher (for Swift 3).

See #348 and https://github.com/onevcat/Kingfisher/tree/feature/image-processor

**Comment by MylesCaley** [comment]
Ah, perfect . I will just cobble something together for now then dump my changes when this is released.
