### ISSUE TITLE
My cache is not working

### ISSUE THREAD

**Issue by cosmo1234** [onevcat/Kingfisher#423]
I am using kingfisher library to cache images but it is not working when i switch off my wifi or restart the app here is my code
```
    let urls = [food.imageString!].map { NSURL(string: $0)! }
    let prefetcher = ImagePrefetcher(urls: urls, optionsInfo: nil, progressBlock: nil) { (skippedResources, failedResources, completedResources) in

        print(skippedResources)
        if skippedResources.count != 0 || completedResources.count != 0{

            for iu in completedResources{
                self.foodImage.kf_setImageWithResource(iu, placeholderImage: self.imagepLace, optionsInfo: nil, progressBlock: nil, completionHandler: { (image, error, cacheType, imageURL) in
                    print("DOWNLOADED CACHE")
                })
            }

        }else{

        }

    }.start()


    if imageView?.image == nil{
        foodImage.kf_showIndicatorWhenLoading = true
        foodImage.kf_setImageWithURL(NSURL(string: food.imageString!), placeholderImage: imagepLace)
    }
```

**Comment by onevcat** [comment]
Does your `imageString` keep the same? Kingfisher is using the url as cache key by default. If the url varies (even only the query part), it will not be in the cache.

And I am not sure why you need a prefetcher here. 

Is it enough to just do an image setting like this for you?

```swift
foodImage.kf_setImageWithURL(NSURL(string: food.imageString!), placeholderImage: imagepLace)
```

**Comment by cosmo1234** [comment]
Yes i can do that . But i want to display the cached image when offline

**Comment by cosmo1234** [comment]
Can i load images when device is offline?

**Comment by onevcat** [comment]
Sure, Kingfisher will first search in memory and disk cache, if not found, it will try to download.

So if your images are already in disk cache, you could load and display it offline.

**Comment by cosmo1234** [comment]
Ok so i don't need to prefetcher?

**Comment by onevcat** [comment]
Hi, @cosmo1234 

It depends on you, but both should work with cache.

**Comment by cosmo1234** [comment]
Yes but when i turn off my wifi or there is no internet connection it is not loading the cached image

**Comment by onevcat** [comment]
It should not happen. 
Could you supply a demo so I can dig into?

Or you could just try the demo app inside this framework to see how it work?
