### ISSUE TITLE
[Swift 3 branch] cache GIF data to disk

### ISSUE THREAD

**Issue by leobarrospereira** [onevcat/Kingfisher#426]
Hi,

I'm trying the swift 3 branch in one of my projects and I found this problem:

I have some gif files that I download and store in the cache using Kingfisher, it used to work before but now when Kingfisher try `serializer.data(with: image, original: original)` it always returns nil.

I noticed that in the master branch it checks if there is an original data to store before try to convert the image to data, but in the swift 3 branch it is different.

Follow the code's part I'm talking about in both branches:

master (ImageCache.swift):
```
let data: NSData?
switch imageFormat {
case .PNG: data = originalData ?? ImagePNGRepresentation(image)
case .JPEG: data = originalData ?? ImageJPEGRepresentation(image, 1.0)
case .GIF: data = originalData ?? ImageGIFRepresentation(image)
case .Unknown: data = originalData ?? ImagePNGRepresentation(image.kf_normalizedImage())
}
```

swift3 (CacheSerializer.swift):
```
let data: Data?
switch imageFormat {
case .PNG: data = image.pngRepresentation()
case .JPEG: data = image.jpegRepresentation(compressionQuality: 1.0)
case .GIF: data = image.gifRepresentation()
case .unknown: data = original ?? image.kf_normalized().pngRepresentation()
}
```

So I'm asking to you to consider apply the same validation used on master on swift3 branch, even because we don't need convert the image to data if was informed the original data.

Thanks.

**Comment by onevcat** [comment]
Hi,
In swift3 branch we introduced an `ImageProcessor` to process images. Here we want to store the processed images instead of its original data (which is downloaded from web).

I just tried the `gifRepresentation` on a sample gif image (http://www.sherv.net/cm/emo/funny/2/big-dancing-banana-smiley-emoticon.gif) and it works well for me. `serializer.data(with: image, original: original)` returns correct data for it. So I guess it is a image decoding issue for you to get `nil`. May I know one of your gif files so I could look deeper to see what happens.

And for you to workaround quickly now, you can implement your own `CacheSerializer` and behave exactly what Kingfisher did before (by returning `originalData`), then pass it in as an option.

**Comment by leobarrospereira** [comment]
Hi @onevcat,

This is an example of one of the gifs that I'm using (https://raw.githubusercontent.com/leobarrospereira/files/master/images--KO9Glhl2T7C_b3qLKcX.gif)

In my case I download the image from the server not using the Kingfisher, I'm using the Firebase Storage. It returns the Data of the file, so I create a UIImage using this data and then I save it in the Kingfisher cache passing the image and the data.

This is a sample of the code after download the data from Firebase Storage:

```
let image = UIImage(data: data)
KingfisherManager.shared.cache.store(image, original: data, forKey: identifier, toDisk: true, completionHandler: {
    // Do something
})
```

And in this case the file is not added into the cache because `serializer.data(with: image, original: original)` returns nil.

I'm having this kind of problem only with gifs, for jpg it works.

Thanks!

**Comment by onevcat** [comment]
The system `UIImage(data:)` will not work for GIF data. How about changing it to the Kingfisher gif parser, I believe this should work for you:

```swift
if let image = DefaultImageProcessor.default.process(item: .data(data), options: []) {
    // You could check whether the image could be created correctly.
    print(image)

    KingfisherManager.shared.cache.store(image, original: data, forKey: identifier, toDisk: true, completionHandler: {
    // Do something
    })
}
```

**Comment by leobarrospereira** [comment]
Hi @onevcat 

I tried your suggestion and it worked!
You can close the issue.

Thanks for your support!

**Comment by onevcat** [comment]
Cool.

**Comment by JGVB** [comment]
Where's the gif parser?
