### ISSUE TITLE
VM:ImageIO_jpeg_Data takes 77% memory..

### ISSUE THREAD

**Issue by AdvanceYe** [onevcat/Kingfisher#428]
Hi Wang Wei,
My demo consists of several tableViewControllers with cells containing images downloaded from url, so I use:
cell.breadImageView.kf_setImageWithURL(NSURL(string: (bread.photoUrl!))!, placeholderImage: UIImage.init(named: "placeHolder")) 

while sliding tableView in several different tableViewControllers, the memory booms rapidly from 12M to 500M..which will getting higher if I keep on sliding and never getting lower.. It shows to be induced by VM:ImageIO_jpeg_Data, when analyzing with Xcode instrument..

Is there code I miss to add, which leads to this problem? Thanks a lot.

![a4fdbb6c-ada6-41a2-b4a7-ea70aead27f6](https://cloud.githubusercontent.com/assets/13606956/18335252/8ae12b0a-75b0-11e6-9b03-38331d9946f3.png)

**Comment by onevcat** [comment]
Kingfisher will cache the images in memory by default. If a memory warning is received, the memory cache will be purged automatically for you, so there is no worry about it.

If you need to limit the memory cache usage, set the `ImageCache.defaultCache. maxMemoryCost`.

**Comment by AdvanceYe** [comment]
I see, thanks a lot~

**Comment by onevcat** [comment]
Or you can call the `clearMemoryCache` of `ImageCache` to do a force purge too. But IMO, it is not necessary. It is already proved that Kingfisher could manage it very well (at least in all apps I am working on).
