### ISSUE TITLE
|> operator conflicts with Prelude

### ISSUE THREAD

**Issue by alexpopov** [onevcat/Kingfisher#429]
I extensively use robrix's µframework [Prelude](https://github.com/robrix/Prelude) which also defines a `|>` operator, albeit a lot more generally. 

Would you consider changing your operator into either `+` or `++` since that seems more natural for concatenating two things?

I totally get it if not ¯\_(ツ)_/¯

**Comment by onevcat** [comment]
I think you are right on it. Defining a new operator sometimes is not a good idea.

Thanks for catching it.

**Comment by onevcat** [comment]
However, `+` or `++` cannot express the meaning of pipeline well. And there is no commutative property too (which might lead misunderstanding when using `+`). So I decide to use `>>` instead.

**Comment by onevcat** [comment]
Fixed in https://github.com/onevcat/Kingfisher/pull/371/commits/3ac0dd1a06ec127f3cfd53b423e46884ec872037
