### ISSUE TITLE
Pod install not working with 3.0

### ISSUE THREAD

**Issue by byrustamzade** [onevcat/Kingfisher#434]
When i try to install Kingfisher with Pod install it gives error: 

None of your spec sources contain a spec satisfying the dependency: `Kingfisher (~> 3.0)`.

**Comment by onevcat** [comment]
It works for me well.

Maybe you need update your pod spec with `pod update` first.
Since it is a CocoaPods issue instead of Kingfisher, I will close it.

**Comment by Viktormax** [comment]
I've the same issue too... tried to update source repos, nothing change

**Comment by onevcat** [comment]
@Viktormax Kingfisher 3.x is [already in](https://cocoapods.org/pods/Kingfisher) CocoaPods's repo, so you'd better to submit it to CocoaPods if you are sure it's an issue.

ref: https://github.com/CocoaPods/CocoaPods/issues/5260 & https://github.com/CocoaPods/CocoaPods/issues/5545
