### ISSUE TITLE
App Rejection when used KingFisher

### ISSUE THREAD

**Issue by Sunitadaffodil** [onevcat/Kingfisher#438]
Hey Hi,

First of all, thank you so much for such a great library. 
So , I have submitted app to apple review , there it got rejected with following reason

Performance - 2.5.1 Your app uses or references the following non-public APIs: 1. imageCache The use of non-public APIs is not permitted

So from the reason , we can conclude , that apple has problem with imageCache keyword which may be apple is using somewhere in their own framework and is not documented or is not exposed to developers. So , Apple treat imageCache as non-public API.

Then I searched my complete project for keyword "imageCache". I came to know that kingfisher is using this and that might be the reason of rejection.

So, it would be very helpful if you guys can change the "imageCache" to something different or if you guys can suggest something in this regard.
This would help me in re-submitting the app for review.

**Comment by onevcat** [comment]
Hi,

Only `ImageCache` is used as a very basic type name in Kingfisher and there is no `imageCache` property/syntax in Kingfisher. This (`ImageCahce` as type name) should never trigger a static analysis failing in private API. 

Since there is no other report on this kind of rejecting until now, I believe it is more likely a bug of Apple's system or only your case (if you are using the letter-case `imageCache` in your code.)

Have you argued it with Apple's guys for it?

**Comment by Sunitadaffodil** [comment]
Hey,

No I have not argued it with Apple's guys for it.
But I have confirmed , that imageCache is not used in project code.
 Let me argue with Apple , may be they can give exact insight into it.

Thanks for this qiuck response.

**Comment by onevcat** [comment]
@Sunitadaffodil Sure!

Please let me know the result so I could see whether we should do something on it.

**Comment by MaeseppTarvo** [comment]
I can say that in my previous version of application I also used erlier version of Kingfisher and I had no problems uploading my application. Now I converted to Swift 3, should I be scared? Which version of Kingfisher you are using?

**Comment by onevcat** [comment]
@Sunitadaffodil Hi, any progress on it? Does it still gets rejected?

**Comment by Sunitadaffodil** [comment]
Hi, my app is now approved by Review Team. But its strange , that they rejected app previously.

**Comment by onevcat** [comment]
:) So I am closing this.

It is not surprising since they are also human and could make mistake on this time to time.
