### ISSUE TITLE
Caching with redirect URL

### ISSUE THREAD

**Issue by yigitserin** [onevcat/Kingfisher#439]
Hey there, in my application, I don't have access to final url of the image. I have to use a service to get to the URL. Which works fine. 

However the problem is caching. Since I am using a service, once the image is downloaded, the cache key will be the same always (Service URL). But the image itself might have been changed.

What I need is to use the URL from result of the service instead of the service URL as cache key. 

Is it possible ?

**Comment by onevcat** [comment]
When you are passing a url, it is converted to a `Resource` with the url and its absolute string as cache key in fact.

So instead of barely passing a url, you could create a `Resource` with an URL and a customized cache key, then pass it to Kingfisher to process.

**Comment by BhavinBhadani** [comment]
customize cache key??? how? If same url is there I got always the old one except new one.. any simple solution without force refresh?

**Comment by onevcat** [comment]
Please read our wiki:

Customize cache key:
https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#use-a-specified-key-other-than-the-url-for-cache

Force downloading:
https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#skip-cache-searching-force-downloading-image-again

**Comment by BhavinBhadani** [comment]
so I have a collectionview and image in every cell .. so I need to make cache key for image to check if its there or not but how do I know that same url cached and need to remove from cache and send a new one .. sorry but too much confused with this functionality

**Comment by BhavinBhadani** [comment]
And how do I know that both url is same but image is different on a same view after refresh collection or table view?

**Comment by Panajev** [comment]
To be fair the force download option, for static URL’s where the content may change, could work more similarly to SDWebImage where it would serve the image in cache of present, discard the item in the cache, fetch the image from the remote server, and call the completion block again with the updated image (even if it did we would have the image next time we fetch it from the cache anyways). What do you think?

**Comment by BhavinBhadani** [comment]
@Panajev right .. this process is complicated .. better to have a single line of code or option that can make the difference.. Lots of threads and issue regarding this anyway
