### ISSUE TITLE
kf_setImageWithURL not respone!

### ISSUE THREAD

**Issue by HighmoreJx** [onevcat/Kingfisher#444]
completionHandler: {[weak base] image, error, cacheType, imageURL in
                DispatchQueue.main.safeAsync {
                    guard let strongBase = base, imageURL == self.webURL else {
                        return
                    }
                    self.setImageTask(nil)
                    guard let image = image else {
                        maybeIndicator?.stopAnimatingView()
                        completionHandler?(nil, error, cacheType, imageURL)
                        return
                    }
}
这是源码的片段，老版本的时候在
guard let strongBase = base, imageURL == self.webURL else {
                        return
 }这个代码段有completionHandler?(nil, error, cacheType, imageURL)
但是版本升级以后就取消了这句代码，感觉不是特别合理，无论怎么样都需要一个出口，即使是返回了错误

**Comment by onevcat** [comment]
No, there was no callback from long ago. It is not an error, but indicating the image view itself gets released. Since the owner of this code does not existing in this case anymore, there seems no reason to have any callback to be invoked. No one should expect a result here.
