### ISSUE TITLE
leaks issue

### ISSUE THREAD

**Issue by yuyongmao** [onevcat/Kingfisher#450]
using xcode8 and swift 3
<img width="1023" alt="screen shot 2016-09-21 at 22 44 10" src="https://cloud.githubusercontent.com/assets/8936260/18715791/194956d2-804d-11e6-8e15-b3ba619be8e3.png">

**Comment by onevcat** [comment]
May I get a demo or any hits for this?
I cannot reproduce any leak in the demo project (Kingfisher-Demo) in the repo.
