### ISSUE TITLE
"Module file was created by an older version of the compiler..."

### ISSUE THREAD

**Issue by jayisidoro** [onevcat/Kingfisher#451]
Module file was created by an older version of the compiler; rebuild 'Kingfisher and try again:"

I'm getting this message after I installed the using Cocoapods. I put this in my pod file:
    pod 'Kingfisher', '~> 3.0'

Any ideas why this is happening / how to fix it? i've tried reinstalling, i've tried cleaning and building. But nothing is working!

**Comment by onevcat** [comment]
Sometimes you need to restart your Xcode to make the error gone. :(

And you might also need the newest CocoaPods (1.1.0 or its RC versions) for Swift 3 support.
