### ISSUE TITLE
Modifying requests once

### ISSUE THREAD

**Issue by adrianhr91** [onevcat/Kingfisher#453]
In 2.x we I used `downloader.requestModifier` do add some additional headers to each request. Now that property has been removed and there are 2 contradicting alternatives. 

1. The wiki here on github says to pass a closure to `setImage`. I don't want to do this ideally as all requests would have the same headers added.
2. In the code the `requestModifier` method is annotated and states 

> `requestModifier` is removed. Use 'urlRequest(for:byModifying:)' from the 'ImageDownloaderDelegate' instead

However there's no such method in the delegate.
Is there a way of achieving what I had on 2.x on 3.1.0?

**Comment by adrianhr91** [comment]
Actually found a solution to my problem, posting it here in case someone is having the same issue.

```swift
let downloader = KingfisherManager.shared.downloader
        
let headers = ["header1": "valu1"]
        
let configuration = URLSessionConfiguration.default
configuration.httpAdditionalHeaders = headers
downloader.sessionConfiguration = configuration
```

**Comment by onevcat** [comment]
@adrianhr91 Oops, the comment is outdated. Use [this](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending) instead.

If you were mentioning this in your 1, you can have only one `AnyModifier` and pass it as an option everywhere.
