### ISSUE TITLE
可否增加一个新功能？

### ISSUE THREAD

**Issue by weichencoder** [onevcat/Kingfisher#455]
是否可以增加一个等比缩放图片的功能。。网络图片尺寸大小不一，需要裁剪一下，因此要等比缩放才能保证不压缩。。试图在你的里进行修改。可没找到这么做。。
方法如下：
    private func imageCompressForSize(sourceImg : UIImage, targetSize : CGSize) -> UIImage{
        var newImg : UIImage? = nil
        let imgSize : CGSize = sourceImg.size
        let width : CGFloat = imgSize.width
        let height : CGFloat = imgSize.height
        
        let targetWidth : CGFloat = targetSize.width
        let targetHeight : CGFloat = targetSize.height
        
        var scaleFactor : CGFloat = 0.0
        
        var scaledWidth : CGFloat = targetWidth
        var scaledHeight : CGFloat = targetHeight
        
        var thumbnailPoint : CGPoint = CGPoint.init(x: 0.0, y: 0.0)
        
        if __CGSizeEqualToSize(imgSize, targetSize) == false {
            let widthFactor : CGFloat = targetWidth / width
            let heightFactor : CGFloat = targetHeight / height
            if widthFactor > heightFactor {
                scaleFactor = widthFactor
            } else {
                scaleFactor = heightFactor
            }
            scaledWidth = width * scaleFactor
            scaledHeight = height * scaleFactor
            if widthFactor > heightFactor {
                thumbnailPoint.y = (targetHeight - scaledHeight) * 0.5
            } else if widthFactor < heightFactor {
                thumbnailPoint.x = (targetWidth - scaledWidth) * 0.5
            }
        }
        UIGraphicsBeginImageContext(targetSize)
        var thumbnailRect : CGRect = CGRect.init(x: 0, y: 0, width: 0, height: 0)
        thumbnailRect.origin = thumbnailPoint
        thumbnailRect.size.width = scaledWidth
        thumbnailRect.size.height = scaledHeight
        
        sourceImg.draw(in: thumbnailRect)
        newImg = UIGraphicsGetImageFromCurrentImageContext()
        if newImg == nil {
            print("scale image fail")
        }
        UIGraphicsEndImageContext()
        return newImg!
    }

**Comment by onevcat** [comment]
Hi,

If you are using Swift 3 and Kingfisher 3, it could be easily implemented with an `ImageProcessor`. 

You could create a type which conforms to `ImageProcessor` and pass it as an option into the image setting extension method. Please see [`Processor`](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#processor) part of wiki to get more info about this. :)

**Comment by weichencoder** [comment]
谢大喵神
