### ISSUE TITLE
How to support SVG' Image

### ISSUE THREAD

**Issue by Herb-Sun** [onevcat/Kingfisher#462]
How to support SVG' Image

**Comment by onevcat** [comment]
Hi,

You need to implement your own `ImageProcessor` to convert svg data to an image object (`UIImage` or `NSImage`). I believe you can find some other libraries for it. So generally speaking you need to have Kingfisher and that converting library working together.

**Comment by onevcat** [comment]
See [Create and use your own processor](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#create-and-use-your-own-processor) part too.

**Comment by Codeido** [comment]
+1 for this feature 👍

**Comment by Codeido** [comment]
Try to see my solution here: https://github.com/onevcat/Kingfisher/issues/623

**Comment by vaibhav-varshaaweblabs** [comment]
@Codeido Can you please show step by step how to implement this SVGProcessor and how to call?

**Comment by Codeido** [comment]
There is the entire code on above post, but -for reporting- the solution doesn't work with all SVG types, it depends on the file format.

**Comment by vaibhav-varshaaweblabs** [comment]
@Codeido Oh. Do you have a better Idea how to support SVG's in Kingfisher

**Comment by vaibhav-varshaaweblabs** [comment]
@Codeido Check this image. I'm trying to implement your code, but how to import PocketSVG inside KingFisher Pods?

![screen shot 2017-07-21 at 3 35 33 pm](https://user-images.githubusercontent.com/21377276/28459266-63931324-6e2a-11e7-8bd2-8af4ba512a08.png)

**Comment by Codeido** [comment]
You don't have to modify the Kingfisher's pod, simply use a new class where you add the struct and read the doc of Kingfisher about how to use ImageProcessor

**Comment by saish98** [comment]
Use this code snippet for downloading svg image from url...
Create Kingfisher+Svg.swift file and add below code...
`import UIKit
import Kingfisher
import PocketSVG

// Convert SVG images from Server to UIImage
struct SVGProcessor: ImageProcessor {
    
    // `identifier` should be the same for processors with the same properties/functionality
    // It will be used when storing and retrieving the image to/from cache.
    let identifier = "svgprocessor"
    var size: CGSize!
    init(size: CGSize) {
        self.size = size
    }
    
    // Convert input data/image to target image and return it.
    func process(item: ImageProcessItem, options: KingfisherParsedOptionsInfo) -> UIImage? {
        switch item {
        case .image(let image):
            return image
        case .data(let data):
            if let svgString = String(data: data, encoding: .utf8) {
                let path = SVGBezierPath.paths(fromSVGString: svgString)
                let layer = SVGLayer()
                layer.paths = path
                let frame = CGRect(x: 0, y: 0, width: size.width, height: size.height)
                layer.frame = frame
                let img = self.snapshotImage(for: layer)
                return img
            }
            return nil
        }
    }
    
    // Get actual image
    func snapshotImage(for view: CALayer) -> UIImage? {
        UIGraphicsBeginImageContextWithOptions(view.bounds.size, false, UIScreen.main.scale)
        guard let context = UIGraphicsGetCurrentContext() else { return nil }
        view.render(in: context)
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return image
    }
}

// For SVG rendering only
extension UIImageView {
    
    /// Use this function for downloading SVG image from URL
    /// - Parameters:
    ///   - url: SVG image url
    ///   - processor: SVG Image Processor
    func svgImage(from url: URL?, processor: SVGProcessor) {
        guard let url = url else {
            self.image = nil
            return
        }
        
        KingfisherManager.shared.retrieveImage(with: url, options: [.processor(processor), .forceRefresh]) {  result in
            switch result {
            case .success(let value):
                DispatchQueue.main.async {
                    self.image = value.image
                }
            case .failure(let error):
                Logger.log("Image download fail:\(error.localizedDescription)")
            }
        }
    }
}
`

In your controller or cell..use this code
`   let processor = SVGProcessor(size: CGSize(width: 17, height: 17))
     imageView.svgImage(from: svgImageUrl, processor: processor)`
