### ISSUE TITLE
Access-Token for all requests

### ISSUE THREAD

**Issue by Mazorati** [onevcat/Kingfisher#463]
Hello!
Thanks for this library!
I have a question: How to implement Access-Token header for all requests?

With [this](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending) cheat i have huge amount of code.. Thanks again!

**Comment by onevcat** [comment]
Currently the default options cannot be modified. So a possible solution would be creating a helper method and pass that modifier there. Then you could use your helper method instead of original one in Kingfisher.

**Comment by Mazorati** [comment]
@onevcat but what about solution in [this issues](https://github.com/onevcat/Kingfisher/issues/452)?

**Comment by phimage** [comment]
@Mazorati the issue you point out #452 is described also here https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#use-your-own-session-configuration-in-a-downloader and must work

**Comment by onevcat** [comment]
It turned out to be an optional interpolation. Since it was fully discussed in #452, I am closing it now.
