### ISSUE TITLE
Swift 3 slow compile time issue 

### ISSUE THREAD

**Issue by pajapro** [onevcat/Kingfisher#468]
Hi guys, 

we just converted our project to Swift 3 and noticed significantly slower compile time. This morning Ayaka Nonaka tweeted a link to an interesting article [Profiling your Swift compilation times](http://irace.me/swift-profiling). I compile our app with the proposed command:

`xcodebuild -workspace App.xcworkspace -scheme App clean build OTHER_SWIFT_FLAGS="-Xfrontend -debug-time-function-bodies" | grep .[0-9]ms | grep -v ^0.[0-9]ms | sort -nr > culprits.txt`

I got the following output:
```
2109.3ms    /pathToProject/Pods/Kingfisher/Sources/String+MD5.swift:213:10  func calculate() -> [UInt8]
2040.5ms    /pathToProject/Pods/Kingfisher/Sources/String+MD5.swift:282:20  (closure)
1715.3ms    /pathToProject/Pods/Kingfisher/Sources/String+MD5.swift:213:10  func calculate() -> [UInt8]
1656.7ms    /pathToProject/Pods/Kingfisher/Sources/String+MD5.swift:282:20  (closure)
402.9ms /pathToProject/myCode.swift
```

It seems that the `calculate()` function takes ~ 6 seconds to compile. Has anyone experienced the same performance drop?

**Comment by onevcat** [comment]
I will give it a tag and release a new version now.

**Comment by pajapro** [comment]
Awesome thanks @frankrausch, @onevcat
