### ISSUE TITLE
Problems with cache and custom image processor

### ISSUE THREAD

**Issue by AlbertoGuerreroMartin** [onevcat/Kingfisher#471]
I have implemented a custom ImageProcessor for applying a grayscale filter when downloading images with Kingfisher, and I'm using it on a tableview's cells (one image per cell).

The problem that I've found is that, while I was developing the filter, Kingfisher cached the images without applying the processor. In an attempt to surround this (at least while developing), I added a  bar button item for clearing the image cache whenever I want.
But the cache is not been cleared. Kingfisher always fetches previously cached images without the filter applied, and it doesn't even call the "process" method of my custom processor (it's just being ignored).
For clearing the cache, I've tried both:
`KingfisherManager.shared.cache.clearDiskCache()`
`KingfisherManager.shared.cache.clearMemoryCache()`

The only way I've found for clearing the cache successfully is to add the **.forceRefresh** option when calling to kf_setImage, but of course I don't want Kingfisher to ignore the cache every time I scroll the tableview (in fact, it would destroy the cache system).

¿Am I doing something wrong? ¿Could it be an issue on ImageProcessor or ImageCache?

**Comment by onevcat** [comment]
May I know how did you set the image with processor?

If you are using the image view extension, Kingfisher will send the processed image to cache by default, so it is intended that the processor method not being called again when retrieving data from cache, since the data should already be precessed before being stored.

**Comment by onevcat** [comment]
@AlbertoGuerreroMartin Hmmm, interesting. You mean the `process` method didn't get called at all?

Could you post your implementation of `grayscaleProcessor` here? Or even better, preparing a sample project which could reproduce it. I could have a detail look at it then.

**Comment by AlbertoGuerreroMartin** [comment]
ok @onevcat , nevermind, I had an old version of Kingfisher. After updating it, everything is working fine 😅  sorry and thanks!
