### ISSUE TITLE
Gif support - stop & resume gif

### ISSUE THREAD

**Issue by vuvan01** [onevcat/Kingfisher#472]
Does Kingfisher support stop & resume gif animation? 
Currently when I do: kf.setImage(url) with url is remote gif file, the gif file is automatically playing after Kingfisher finish downloading the file

**Comment by onevcat** [comment]
Maybe you need [this](https://developer.apple.com/reference/uikit/uiimageview/1621057-stopanimating) if you are using `UIImageView`.

And it is not the correct place in GitHub issue to ask questions.
