### ISSUE TITLE
KingfisherOptionsInfoItem.Options(KingfisherOptions.ScreenScale) how to use in Xcode8 swift2.3 kingfisherversion(2.60)

### ISSUE THREAD

**Issue by BaiCanLin** [onevcat/Kingfisher#474]
KingfisherOptionsInfoItem.Options(KingfisherOptions.ScreenScale) how to use in Xcode8 swift2.3 kingfisherversion(2.60)

**Comment by onevcat** [comment]
This should be compatible with earlier version of Kingfisher.

What's your current code and it could be a great help if you paste the error you encountered here too.
