### ISSUE TITLE
Perform changes on UIImage before it is set on UIImageView

### ISSUE THREAD

**Issue by Minitour** [onevcat/Kingfisher#475]
Hi, I was wondering if there is a function where I can make changes to the UIImage before it is set on the UIImageView. For example in this code:

```swift
imageView.kf.setImage(with: url, completionHandler: { 
    (image, error, cacheType, imageUrl) in
   //Crop a part of `image` then set it on the `imageView`
})
```
Of course I can modify the uiimage inside the closure and then set it on the ImageView again but it would be just redundant memory consumption.

**Comment by onevcat** [comment]
The `ImageProcessor` should be your choice. See [this](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#processor) for more.

**Comment by Minitour** [comment]
This ImageProcessor is quite limited, I need to run my own functions on the image.
I was actually thinking that for future updates you can implement a function like this one:
```swift
kf.setImage(with: url, completionHandler: (image, error, cacheType, imageUrl) -> UIImage?
```

where the usage would be as the following:
```swift
imageView.kf.setImage(with: url, completionHandler: { 
    (image, error, cacheType, imageUrl) -> UIImage? in

   if let image = image {
          //make modifications to image
          return image
   } else {
          return nil
   }
})
```

**Comment by onevcat** [comment]
Maybe you mean this one? https://github.com/onevcat/Kingfisher/issues/465

I do not have a chance to implement it yet, but any p-r for this is welcomed.

**Comment by Minitour** [comment]
@onevcat Alright I'll see if I can do it myself. Can you refer to me inside the source code where is the function "setImage" is implemented?

**Comment by onevcat** [comment]
There should be no need to worry about the `setImage` things. You could just add a struct which conforms to `ImageProcessor` and implement the logic of converting some data and/or an image to the cropped one. You can find other built-in `ImageProcessor` in the file with the same name, and follow the implementation there. :)

**Comment by Minitour** [comment]
Yeah that's seems like the perfect solution for now. Thanks a lot :D
