### ISSUE TITLE
缓存读取时间长

### ISSUE THREAD

**Issue by fuboyou** [onevcat/Kingfisher#477]
hi，喵神，当我使用下面的方法获取网络图片时，通过第一次调用，图片已经通过网络请求缓存到了本地，当第二次调用时，placeholderImage仍然会显示大概一秒，才会显示网络图片，但是如果placeholderImage设置为nil，之前图片会先消失，等一秒左右才显示正确的图片。
`public func kf_setImageWithURL(URL: NSURL?,
                                   placeholderImage: Image? = nil,
                                   optionsInfo: KingfisherOptionsInfo? = nil,
                                   progressBlock: DownloadProgressBlock? = nil,
                                   completionHandler: CompletionHandler? = nil) -> RetrieveImageTask`

**Comment by onevcat** [comment]
It should not happen unless you are trying to load an image with huge size (and I/O matters most of the time in such case.)

**Comment by fuboyou** [comment]
感谢回复，的确有可能是图像问题，使用的高清图，我将在较小的图片再次验证，先关闭这个issue
