### ISSUE TITLE
Typo in Cheat Sheet

### ISSUE THREAD

**Issue by Maikol** [onevcat/Kingfisher#479]
There's a typo [here](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#set-longest-time-duration-of-the-cache-being-stored-in-disk) on the Cheat Sheet.

<img width="720" alt="screen shot 2016-10-13 at 10 12 42 am" src="https://cloud.githubusercontent.com/assets/1027660/19330996/9ed48f74-912d-11e6-883c-1f5f61d461a6.png">

This should be

```swift
ImageCache.default.maxCachePeriodInSecond = 60 * 60 * 24 * 3
```

**Comment by onevcat** [comment]
Oops. Thanks for pointing it out!

**Comment by onevcat** [comment]
Fixed.
