### ISSUE TITLE
Undefined symbols linking issue.

### ISSUE THREAD

**Issue by hifall** [onevcat/Kingfisher#480]
Using Xcode 8/Swift 2.3, with Whole Module Optimization (WMO) on, I am seeing the following issue with our project with Kingfisher integrated:

    Undefined symbols for architecture i386:
      "type metadata for (extension in DemoViewer):__ObjC.UIImageView.IndicatorType", referenced from:
          DemoViewer.ImgCell.(retryLoadImage (__ObjC.UIImageView?, url : __ObjC.NSURL, defaultImage : __ObjC.UIImage, displayLoadingIndicator : Swift.Bool, completionHandler : (Swift.Bool) -> ()) -> ()).(closure #1) in ImgCell.o

Turning off WMO seems to make the issue go away.

As pointed out by this link: https://bugs.swift.org/browse/SR-913, it seems to be Apple's bug. But would a workaround on Kingfisher's side make sense?

Currently we don't have the luxury to upgrade to Swift 3, and are stuck in this issue, unless we turn WMO off, which is not desired.

**Comment by onevcat** [comment]
Maybe choose Kingfisher 2.5.1 could be a workaround (if you are not using the new indicator type) for now. Another possible solution is extract `IndicatorType` from `UIImageView`, I have to consider this twice since it would introduce a public API change and breaks semantic version rule.

**Comment by onevcat** [comment]
@hifall It seems that it will not break current API if we extract `IndicatorType` out. I pushed a commit to `swift2.3` branch and would you please to give it a try and see whether it could solve your issue? If so, I will give it a tag and release an update soon.

**Comment by hifall** [comment]
@onevcat,

Thanks so much for such a quick turnaround! I have tested the new changes, and it seems that the issue is gone now.

**Comment by onevcat** [comment]
Great, I will tag and release it now.

**Comment by onevcat** [comment]
Solved in version 2.6.1.
