### ISSUE TITLE
swift3 imageView一片空白

### ISSUE THREAD

**Issue by NSLogxiaoyu3** [onevcat/Kingfisher#481]
使用kf.setImage(with:url, placeholder:,...) ，completeHandler中image不为nil，error=nil，用Xcode自带UI查看器查看，发现image也是有的，但是没有显示出来。
imageView为52x52，网络图片240x240
请问我应该如何调试它？

**Comment by onevcat** [comment]
Does it relate to this iOS 10 issue? https://github.com/onevcat/Kingfisher/issues/421

If you are setting round corner or any other layer property, you may need to call layoutSubviews. You can find more information in [this page](http://stackoverflow.com/a/39380129/340508)

**Comment by profesori** [comment]
Re install Kingfisher (pod install) solves the issue

**Comment by NSLogxiaoyu3** [comment]
I add "imageview.layoutIfNeeded()" and fixed
