### ISSUE TITLE
Invalid redeclaration of 'ImageView'

### ISSUE THREAD

**Issue by profesori** [onevcat/Kingfisher#482]
I have two build errors from KingFisher

- Invalid redeclaration of 'ImageView' form Kingfisher.swift file and
- Method does not override any method from its superclass from AnimatedImageView

No animated imageView though in code

Swift 3 iOS 10

**Comment by profesori** [comment]
Re installing Kingfisher solves the problem

**Comment by onevcat** [comment]
Thanks for the feedback.
