### ISSUE TITLE
ImageView size

### ISSUE THREAD

**Issue by pentarex** [onevcat/Kingfisher#483]
Hi,
I am using your library since not long ago, but I have noticed something strange. We have implemented our own processor which determents  the correct aspect fit to the image, resizing it and returning it.
~~~swift
// Convert input data/image to target image and return it.
    func process(item: ImageProcessItem, options: KingfisherOptionsInfo) -> Image? {
        switch item {
        case .image(let image):
            return getAspectImage(image: image)
        case .data(let data):
            if let image = Image(data: data, scale: 1) {
                return getAspectImage(image: image)
            }
            
            return nil
        }
    }
    
    func getAspectImage(image: Image) -> Image {
        var desiredHeight = targetSize.height
        var desiredWidth = targetSize.width
        
        
        let ratio = image.size.width / image.size.height
        let desiredRatio = targetSize.width / targetSize.height
        if ratio > desiredRatio {
            desiredHeight = targetSize.width / ratio
        } else {
            desiredWidth = targetSize.height * ratio
        }
        
        print("image height \(image.size.height)")
        print("desired height \(desiredHeight)")
        
        return UIImage.scaleTo(image: image, w: desiredWidth, h: desiredHeight)
    }
~~~
We are using it the following way
~~~swift
var options: KingfisherOptionsInfo = [.transition(.fade(0.3)), .backgroundDecode]
            let processor = CustomImageProcessor(targetSize: CGSize(width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height))
            options.append(.processor(processor))
cell.imageImageView.kf.setImage(with: URL(string: "\(Constants.server)/\(post!.image)")!, options: options)
~~~
The problem that we have is the following. The UIImageView (or in our case is imageImageView) is bigger than expected... to be precise - UIScreen.main.bounds.height so big. The question is: Is this a bug or a wanted feature. In both cases how we can fix it? Thank you!

**Comment by onevcat** [comment]
Kingfisher should have nothing to do with the image view size. I noticed that you are trying to scale your image to a size of `CGSize(width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height)`, so does it mean that your processed image is full screen? If so, AND if your image view does not have a size constraint (which means it will use the `intrinsicContentSize` and resize itself), this could happen.

Is this your case?

**Comment by pentarex** [comment]
you can close the issue, for no reason the problem was in 
~~~swift
return UIImage.scaleTo(image: image, w: desiredWidth, h: desiredHeight)
~~~
Ive used your function kf.resize and now everything is fine :)
