### ISSUE TITLE
Module compiled with Swift 3.0 can not be used in Swift 3.0.1

### ISSUE THREAD

**Issue by helloniklas** [onevcat/Kingfisher#484]
What's the easiest way to use Kingfisher with Xcode8 beta that runs Swift 3.0.1 Do I need to rebuild it?

I find my self needing to frequently switch between Xcode8 and Xcode8 beta, as I have different devices and not all of them running 10.1 beta.

Is there an easy way around this without doing the Xcode select and rebuild?

**Comment by onevcat** [comment]
Maybe you could use CocoaPods to integrate Kingfisher, so you can have it built with Xcode instead of the the command line tool.

**Comment by yn288163** [comment]
carthage update --no-use-binaries
