### ISSUE TITLE
'one-time completion handler' for async image display inside a tableviewcell

### ISSUE THREAD

**Issue by faisalrasbihan** [onevcat/Kingfisher#487]
I need to display an image inside a tableViewCell asynchronously, so I need to call self.tableView.reloadData() when the download is complete (because the image height is varying and the tableView height needs to be updated) and I did it inside the completion handler in kf.setimage but this create problem because the completion handler is called continuously inside tableView:cellForRowAtIndexPath: and make my project crash. Can you make an option to call the completion handler only once?

**Comment by onevcat** [comment]
What's the problem by just using the image view extension described [here](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#simply-set-an-image-from-url-to-an-image-view)? There should be no need to reload your table view.

**Comment by faisalrasbihan** [comment]
I used that, but my project have a dynamic cell height so the cell height is dependent on the size of the image. And since I load the image asynchronously I need to call tableView.reloadData() in the completion handler. I eventually get around this issue by creating an array of bool to check if I should reload the table view for a specific cell. What would be nice is if there is an option to call the completion handler only once.

**Comment by onevcat** [comment]
No, it is not the correct logic to call the handler only once when you set it multiple times actually. 

It's more likely that you are choosing a not-so-good strategy by reloading the whole table view and set the image again. I'll choose just relayout/update the cell without reseting the cell image view by Kingfisher. Maybe it's also worth to reconsider your table view setting flow and choose a better way to update the cell.
