### ISSUE TITLE
Can I manually change cache directory? 

### ISSUE THREAD

**Issue by kiwo12345** [onevcat/Kingfisher#489]
I wonder if I manually can change cache directory(URLSession) for Kingfisher? 

I use another lib for a image carousel that already has cache built in and I would like to make the lib share the same cache directory as Kingfisher

**Comment by onevcat** [comment]
No, it is a black box to framework users and not intended to be changed.

**Comment by heeween** [comment]
manually change class ImageCache function "defaultDiskCachePathClosure(path:, cacheName:)" maybe solve your problem @kiwo12345
