### ISSUE TITLE
Determine cached content?

### ISSUE THREAD

**Issue by Dbigshooter** [onevcat/Kingfisher#490]
Hi there,

I'm using this library for the first time, and it seems pretty awesome. However I tried to print out the cacheType of my images, and I guess I'm missing a way to say if an image is cached or not? My app still download all the JSON and such, and just show the imagine from the disk. So what I essentially want, is to check my disk before even making the call to the webservice, is that possible? Otherwise I'm fetching a lot of JSON data for no use at all.

**Comment by onevcat** [comment]
What do you mean on the JSON file?

And you could use [`isImageCache`](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#use-imagecache-to-store-or-get-images) to determine whether an image at that url cached or not.
