### ISSUE TITLE
Header 'Kingfisher-Swift.h' not found

### ISSUE THREAD

**Issue by Hanwp** [onevcat/Kingfisher#491]
喵神你好，
我刚才用cocoapods更新了你的框架。Installing Kingfisher 3.1.4 (was 3.1.3)
然后又在Xcode中update到了swift3.0
现在报错，该怎么解决，谢谢！
<img width="818" alt="kingfish-bug" src="https://cloud.githubusercontent.com/assets/10218623/19849729/ba61a568-9f8f-11e6-8a61-274bc363659b.png">

**Comment by onevcat** [comment]
尝试 Clean 一下之类的吧…我并没有改什么特别大的东西

Wei Wang (@onevcat)

2016年10月31日 +0900 18:31 Hanwei <notifications@github.com>，写道：

**Comment by Hanwp** [comment]
我重新clean还是那个错误，我用的xcode8.1

**Comment by onevcat** [comment]
升级 cocoapods，删 derived data 文件夹，删 Pods 文件夹重新 pod install 等等等等..
如果你新建一个项目导入没问题的话基本就是你的本地环境的问题了。pod lint 和验证都是 pass 的，所以我这边没什么可做的。
