### ISSUE TITLE
Display gif as non animated image by default

### ISSUE THREAD

**Issue by gkye** [onevcat/Kingfisher#492]
Is it possible to opt out of displaying animated images by default? (its causing some memory issues). I only want to display the animated image using `AnimatedImageView` when the user chooses to do so.

**Comment by onevcat** [comment]
Currently no. Maybe we could implement an option to load first several frames for a GIF in a later version.

**Comment by kubajakowski** [comment]
besides memory issues it's also related to https://github.com/onevcat/Kingfisher/issues/375

**Comment by onevcat** [comment]
Should be added in version 3.4.0. Use `.onlyLoadFirstFrame` for that purpose.
