### ISSUE TITLE
Avoid setting the imageView.image to nil before it has finished downloading image

### ISSUE THREAD

**Issue by danieldelouya** [onevcat/Kingfisher#494]
I have a feed of images (sort of like snapchat), so everytime I tap on the imageview i get the next prefetched image. 
When using .kf.setImage it seems like for a split second it sets the imageView.image to nil before setting the cached/downloaded image in the imageview, which causes a flicker where it briefly shows the imageViews background color. 
Is there a way to avoid this? Thought about setting the previous displayed image as a placeholder for the new one, but that's not the best solution. 

So, is there a way one can wait setting the imageView's image until the image has actually completed downloading?

**Comment by onevcat** [comment]
I'll suggest to just use the current image of image view as the placeholder as you mentioned. It should be a fairly good and reasonable solution, at least to me.

What's your concern about that?

**Comment by danieldelouya** [comment]
I guess it can work yeah, but it would feel 'safer' if there was a feature when you could wait setting the image in the imageview until the image has downloaded. I know that's possible with AlamofireImage, but I just prefer Kingfisher way more 👍

**Comment by danieldelouya** [comment]
And thank you for the quick response! Really appreciate it.

**Comment by onevcat** [comment]
Um, I agree with you that it will be clearer to have an option to describe it explicitly, instead of just using current image. I will find some time to implement this.

Thanks.

**Comment by onevcat** [comment]
Added in 3.2.0
