### ISSUE TITLE
Module compiled with Swift 3.0.1

### ISSUE THREAD

**Issue by Skyna** [onevcat/Kingfisher#496]
Greetings,

I use CocoaPods for the integration of this library. However, sinds recently when i updated my Xcode to 8.1. I am getting this issue from within my project:

"Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1"

So my question is. When will there be a release of this library which is compiled in Swift 3.0.1? 

Thanks!

**Comment by onevcat** [comment]
Kingfisher is distributed with source code, and there is no API change needed for Swift 3.0.1. So it is you who should compile the framework in the newer version of Swift.

I believe you could try to do a full clean for your project as well as Pods to solve it.

**Comment by onevcat** [comment]
As well as to try the latest version of cocoa pods
