### ISSUE TITLE
Always show indicator option?

### ISSUE THREAD

**Issue by mikkelam** [onevcat/Kingfisher#497]
Is there an option to always show the indicator for imageviews? I'm too lazy to activate it every time.
I was not able to find any information, I'm sorry if this has already been adressed.

**Comment by onevcat** [comment]
What do you mean by "always show"? Once you set the `indicatorType`, the indicator should be automatically shown on downloading and hidden after that.

**Comment by mikkelam** [comment]
I mean an option to have the indicator always be present without having to set it for each imageview

**Comment by onevcat** [comment]
Instead of making it a property for all the original `ImageView` class,I believe it would be more general and simpler to create your own subclass of `UIImageView` and set the `indicatorType` there, then use the subclass.
