### ISSUE TITLE
Is there an option to load progressive jpeg ?

### ISSUE THREAD

**Issue by tahirSmartboy** [onevcat/Kingfisher#498]
![1](https://cloud.githubusercontent.com/assets/10927636/19965514/5753f524-a1ed-11e6-9846-92861285b230.gif)

Left: normal loading
Right: Progressive loading

**Comment by onevcat** [comment]
No, not yet. And there is no such plan for it currently.

**Comment by asad-khan92** [comment]
Hi, @onevcat any updates on this feature?

**Comment by onevcat** [comment]
It's already implemented in [version 5.5.0](https://github.com/onevcat/Kingfisher/releases/tag/5.5.0). Use `.progressiveJPEG` in the loading option to load a progressive JPEG.
