### ISSUE TITLE
Resize image is always blurry

### ISSUE THREAD

**Issue by chenawu2** [onevcat/Kingfisher#504]
Let's say I have a `3024 × 4032` image, and I want to resize it to `77x77`

I use this framework like so:
`let processor = ResizingImageProcessor(targetSize: CGSize(width: 77, height: 77)) >> RoundCornerImageProcessor(cornerRadius: 77/2)`

The result is a very blurry image. How do I maintain the same aspect ratio?

Here is the image I am using:
http://imgur.com/a/lKtI9

Thanks.

**Comment by onevcat** [comment]
The unit of image processor is pixel instead of point. If you are trying to set the image to a 77x77 point retina display (I guess you should need so), it means you need to resize it to 2x at least, which means 154x154.

And if you are also targeting an iPhone x Plus 3x display, you need 231x231.

**Comment by chenawu2** [comment]
Hey Thanks.

Last question, if I reuse the same processor with the same arguments, and I call it on the same image url, is Kingfisher smart enough to know that a `77x77` resize of this image already has been done before?

**Comment by onevcat** [comment]
Sure.
