### ISSUE TITLE
Expose `KingfisherOptionsInfoItem` extension

### ISSUE THREAD

**Issue by ManueGE** [onevcat/Kingfisher#505]
Thanks for this project. 

I see there are some helper methods for `KingfisherOptionsInfoItem` in one extension: 

````swift
extension Collection where Iterator.Element == KingfisherOptionsInfoItem
````

It provides a lot of useful `var` to get info from an Array of `KingfisherOptionsInfoItem`, for instance get the `scaleFactor` or the `transition`.

These methods are really helpful when building custom processors, so exposing this extension would be awesome.

**Comment by onevcat** [comment]
Not a bad idea. Would you mind to send a p-r for this?

**Comment by ManueGE** [comment]
Sure! I'll do it soon

**Comment by ManueGE** [comment]
I just created the pull request #506 . Any comments are welcome.
