### ISSUE TITLE
AnimatedImageView xib outlets 

### ISSUE THREAD

**Issue by Luca9307** [onevcat/Kingfisher#507]
Hello,
I connected an AnimatedImageView as outlet in xib, by linking it to a UIImageView because storyboard not find AnimatedImageView class. So I do not know why the gif is shown correctly but I can not access the attributes of AnimatedImageView, because it cause a crash saying that a UIImageView does not have this attribute. Is there any other option to solve this problem?
Thanks so much.

`@IBOutlet var imageView:AnimatedImageView?`

**Comment by onevcat** [comment]
Hi,

You need to change the class of it to `AnimatedImageView` in your storyboard too.

**Comment by Luca9307** [comment]
Hello,
I've done this but Xcode give me this error: 
Unknown class AnimatedImageView in Interface Builder file.

Thanks you so much

**Comment by onevcat** [comment]
You may need to specify the module to Kingfisher, if you are using it as a dynamic framework.

![](https://gyazo.com/9a2df86693853ae360ca87059d89d7f3)

Do not forget to link to the framework. If this is not shown in your IB, it might be possible that you are not integrating it correctly.

**Comment by Luca9307** [comment]
Works!
Thank you so much
