### ISSUE TITLE
关于 RetrieveImageTask.empty 的访问权限

### ISSUE THREAD

**Issue by yybutcher** [onevcat/Kingfisher#508]
Hi：

我在写 extension 的时候发现 `RetrieveImageTask.empty` 并没有使用 `public` 修饰，还是 `internal`，在外部模块不能使用，这个是出于什么考虑呢？

如果没有其他原因可否改成 `public` 呢？

**Comment by onevcat** [comment]
It should be no harm to be `public`. I'll do it later.
