### ISSUE TITLE
希望把 KingfisherManager 的init 改为 public

### ISSUE THREAD

**Issue by noear** [onevcat/Kingfisher#514]
希望把 KingfisherManager 的init 改为 public

如此可以方便一些高级定制；
可以将不同业务的图片，分类存储在不同的cache里。

**Comment by onevcat** [comment]
No, this is intended and the `KingfisherManager` would not expose its initializer. If you need to use another cache instead of the default one, pass a `.targetCache` option with your customized one in the image loading APIs.

**Comment by noear** [comment]
非常感谢！
