### ISSUE TITLE
does kingfisher support image encryption ?

### ISSUE THREAD

**Issue by tranvutuan** [onevcat/Kingfisher#516]
I am starting switching to Kingfisher and I have a question regarding to the security issue. Can cached images be encrypted ?

**Comment by onevcat** [comment]
You could do that by implementing your own CacheSerializer. Please read the cheat sheet in wiki for more on it.

**Comment by tranvutuan** [comment]
From the cheat sheet in wiki, I created my own CacheSerializer named `NewSerializer` like below
```
struct NewSerializer: CacheSerializer
{
    public func data(with image: Image, original: Data?) -> Data? {
        return RNCryptor.encrypt(data: original!, withPassword: "123456789")
    }
    
    func image(with data: Data, options: KingfisherOptionsInfo?) -> Image?
    {
        var image = Image()
        do {
            image = try UIImage(data: RNCryptor.decrypt(data: data, withPassword: "123456789"), scale: 1)!
        }
        catch{
            
        }
        return image
    }
}
```
For the first method, I'm currently using RNCryptor for encryption and decryption. 
From the sample code, I am doing:
```
_ = (cell as! CollectionViewCell).cellImageView.kf.setImage(with: resource, placeholder: nil, options: [.cacheSerializer(serializer)], progressBlock: nil, completionHandler: { image, error, cacheType, imageUrl in
            print("\(cacheType, indexPath.row): Finished")
        })
```
I am facing an issue : 
```
From the cache folder located at :../Library/Caches/com.onevcat.Kingfisher.ImageCache.default/,  some of the images are still be previewed. 
```

Any thoughts about this.

**Comment by onevcat** [comment]
Just took a look at the RNCryptor and tried your code. It works perfect for me and all images are encrypted and decrypted without problem. None of them could be previewed:

![snip20161121_7](https://cloud.githubusercontent.com/assets/1019875/20475440/4288b74e-b00f-11e6-9232-084adcba1aa2.png)

Are these images you could preview downloaded before you apply the encrypting cache serializer? You could try a `ImageCache.default.clearDiskCache()` to clean your disk cache and have another try.

**Comment by tranvutuan** [comment]
@onevcat: I figured it out. The reason I am able to preview some of them is because prefetching image process which is currently using default serializer. In order to encrypt, I have to pass my own `serializer` to `ImagePrefetcher` like following
`ImagePrefetcher(urls: urls, options: [.cacheSerializer(serializer)]).start()`

and then everything works like expectation.
