### ISSUE TITLE
强烈要求把单元测试的图片删除

### ISSUE THREAD

**Issue by zyxlcr** [onevcat/Kingfisher#522]
由于天朝众所周知的原因,20多M的pod 还是亚历山大的

**Comment by onevcat** [comment]
Thanks for the suggestion. Yes, it might be a problem when using a slow network connection.

I guess at lease currently I will not change this, unless there is a good way to split the test target from framework. It is important to test the images and processors and it seems the current model works well for most cases (for both human and CI).

Furthermore, usually you just need to download them once when integrating the framework until you are ready to upgrade it. If the downloading time is too long for you, please consider to integrate this framework by using a submodule, which could save you from re-downloading these test image when there is no change for them.

Anyway, thank you for it. I will also keep an eye on the repo size and see what I could do in future.

**Comment by zyxlcr** [comment]
可以用git把图片的文件夹中的内容忽略掉,这样就没有影响了

**Comment by onevcat** [comment]
这样 CI 就跑不过了，而且要从 repo 移调需要改动前面的 commit。
