### ISSUE TITLE
KingfisherManager.shared.cache.isImageCached EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by mihaibulic** [onevcat/Kingfisher#525]
`if !KingfisherManager.shared.cache.isImageCached(forKey: url.absoluteString).cached {
    // EXC_BAD_ACCESS when calling isImageCached
}`

That above line worked until today when I updated my Kingfisher CocoaPod to 3.2.1.  I'm not sure what version I was on before- whatever was in CocoaPods on 10/26.

**Comment by mihaibulic** [comment]
I reverted to 3.1.4 and everything works as expected.

**Comment by onevcat** [comment]
Since there is no change between these two versions here, so I believe it is a Swift issue. Maybe you could fix it by do a full clean of the project and/or derived data folder. Or try to remove the old one with Kingfisher 3.1.4 and reinstall the app to your simulator or device.

**Comment by mihaibulic** [comment]
I did do a clean and I uninstalled the app.

**Comment by onevcat** [comment]
@mihaibulic Does it happen for all urls? Or some specified ones. And may I know some more information for it, is there any stacks or other messages besides of EXC_BAD_ACCESS?

**Comment by onevcat** [comment]
There is no other report on this, so I guess it is a special case and currently I have no idea for it.

If anyone find the same issue, feel free to reopen it.
