### ISSUE TITLE
Increase the amount of time the progressBlock is called

### ISSUE THREAD

**Issue by jyounus** [onevcat/Kingfisher#526]
Hey there,

Is there a way to increase the amount of time the progressBlock is called for the setImage function? Current I only ever get the following 5 "notifications", every time I try to download my test image. It's always at the same percentages:

```
progress: 32.9320013668067%
progress: 34.1862475126128%
progress: 67.1182488794195%
progress: 69.1764989648449%
progress: 100.0%
```

Also, am I correct in assuming that the progressBlock will ALWAYS be called at least once when the progress is 100.0%?

Thanks

**Comment by onevcat** [comment]
Hi,

The progress block will be called every time the url session task received a data trunk, so there is no good way to increase the amount in a good way.

And if your server is returning the correct expected size to you, the progress block should be called when it finishes. But a better way to handle the finish things should be the completion handler callback instead.
