### ISSUE TITLE
failed image parameter in kf.setImage: method

### ISSUE THREAD

**Issue by faisalrasbihan** [onevcat/Kingfisher#527]
Could you add a "failed image" parameter in kf.setImage: so that if kingfisher cannot retrieve image from URL or there is an error, the image view can still display an image.

**Comment by onevcat** [comment]
It's no need to create such an image if the request is successful (which would be a normal case), so it seems to be a waste of performance and adding complication to the API. I believe you should just set the "failed image" in the completion handler instead. It would not be hard too if you want create a wrapper for it yourself, if feel like to.
