### ISSUE TITLE
progressBlock is stopped

### ISSUE THREAD

**Issue by ixialuo** [onevcat/Kingfisher#530]
self.kf.setImage(with: url, placeholder: placeholder, options: nil, progressBlock: { (receivedSize, totalSize) in

            let progress : CGFloat = CGFloat(receivedSize) / CGFloat(totalSize)
            self.progressIndicatorView.progress = progress

        }) { (image, error, cacheType, imageURL) in
            self.image = image
            self.progressIndicatorView.reveal()
        }

progressBlock is unused??

**Comment by onevcat** [comment]
I cannot understand what you mean.

**Comment by ixialuo** [comment]
when options is nil, progressBlock is don't go

**Comment by onevcat** [comment]
@ixialuo I cannot reproduce it. `progressBlock` is called when downloading an image for me, even when the options is nil.

Can you build a demo which could reproduce what you said? Thanks!
