### ISSUE TITLE
How to Set PROXY

### ISSUE THREAD

**Issue by Syed2837** [onevcat/Kingfisher#534]
Hi, how can I set proxy for non wifi network in KingFIsher framework extension?

**Comment by onevcat** [comment]
Please describe your question more specified. And it is not a good place for asking questions. If there is no such feature now in Kingfisher, it would be appreciated to post a feature request instead of asking "how can".

**Comment by Syed2837** [comment]
I haven't gone through the entire framework... my mistake.
Yeah, I can say its feature request (to support proxy setting).

**Comment by onevcat** [comment]
If you mean the `connectionProxyDictionary` of session configuration, the configuration used in Kingfisher is already exposed. It should work if you set your proxy settings there and reassign it to `ImageDownloader`:

```swift
let conf = ImageDownloader.default.sessionConfiguration
conf.connectionProxyDictionary = [
    kCFNetworkProxiesHTTPEnable as AnyHashable : true,
    kCFNetworkProxiesHTTPPort as AnyHashable : proxyPort,
    kCFNetworkProxiesHTTPProxy as AnyHashable : proxyURL
]
ImageDownloader.default.sessionConfiguration = conf
```

The session used will be recreated and updated, so you could use a session with proxy you set.

**Comment by Syed2837** [comment]
My code

```
if let url = NSURL(string: collectionSection.sectionImageUrlStr!) {
                        KingfisherManager.sharedManager.retrieveImageWithURL(url, optionsInfo: nil, progressBlock: nil, completionHandler: { (image, error, cacheType, imageURL) -> () in
                            cell.titleImageView.image = image
                            cell.titleImageView.clipsToBounds = true
                        }) } else {
                        print("Doesn’t contain a url")
                        cell.titleImageView.image = UIImage(named: "location_not_found")
                        cell.titleImageView.clipsToBounds = true
                    }
```

Sorry I'm novice developer and I don't know exactly how to include your code. Could you please go through my code and let me know where can I put your code to set proxy.

Note: I added KingFisher through Pod.

**Comment by onevcat** [comment]
So you could just add something like

```swift
ImageDownloader.default.sessionConfiguration = customizeEphemeralSessionConfiguration()
```

to your app did finish launching method of your app delegate to u

**Comment by Syed2837** [comment]
Thanks a lot....
