### ISSUE TITLE
API reference link broken loops everywhere

### ISSUE THREAD

**Issue by jaimeagudo** [onevcat/Kingfisher#536]
http://cocoadocs.org/docsets/Kingfisher/3.2.2/

**Comment by onevcat** [comment]
It seems to be an issue in CocoaDocs or jazzy. I commented it in this issue https://github.com/CocoaPods/cocoadocs.org/issues/493 and I guess they could solve it.

Before that, you can install [jazzy](https://github.com/realm/jazzy) and run `jazzy` in Kingfisher's folder to generate a local copy of reference yourself, if you need it.
