### ISSUE TITLE
WebP Image Format not cached!

### ISSUE THREAD

**Issue by hablema** [onevcat/Kingfisher#54]
Hi all,

Recently i have started using Webp Image format from google and it really saves a lot of bandwidth. But i'm not able to cache the images. I have tried using using other libraries also but no luck, by far this is the best. I get this error when i try :

<Error>: ImageIO: PNG zlib error

It would be great to if anyone could help me out. I use https://github.com/mattt/WebPImageSerialization to display webP images and it works fine.

**Comment by onevcat** [comment]
Webp is not supported yet. However it is a planned feature and will be added later.

**Comment by hablema** [comment]
Thanks. Hope you would update it soon. Waiting for it.

**Comment by onevcat** [comment]
It will not be in a high priority, since webp format is not so widely used currently. So I cannot guarantee a time schedule for it. If you are relying on the format and have a pressing deadline, I suggest to switch to other framework first.

**Comment by hablema** [comment]
No probs... Will wait..! :)

**Comment by morizotter** [comment]
:eyes:

**Comment by kenshincui** [comment]
希望尽快增加webp格式支持！

**Comment by susieyy** [comment]
+1

**Comment by arden** [comment]
+1 for this，i'm hope add webp support quickly.

**Comment by arden** [comment]
https://github.com/seanooi/iOS-WebP

**Comment by bauloc** [comment]
I'm hope WEBP available quickly 👯

**Comment by kenshincui** [comment]
+1

**Comment by skerkewitz** [comment]
@hablema 
Had the same issue. Seems like a bug in WebPImageSerialization. This little change solve the problem for me:
https://github.com/mattt/WebPImageSerialization/pull/12/commits

**Comment by onevcat** [comment]
As mentioned in #362 
since the WebP support will introduce additional dependency and in fact it is not a popular or officially supported format in Apple platform, I decided to not add it for a while.

I will keep an eye to see whether there could be a chance to do it later. But not for now at least.

**Comment by onevcat** [comment]
P.S. There is a WebP framework as plugin for Kingfisher now. Check https://github.com/yeatse/KingfisherWebP
