### ISSUE TITLE
API Reference missing?

### ISSUE THREAD

**Issue by jyounus** [onevcat/Kingfisher#542]
Not sure if this is as intended or if I'm just being stupid, but the API Reference seems to be missing? It simply redirects me to the cocoa pods website: ```http://cocoadocs.org/docsets/Kingfisher/3.2.2/``` but I don't see any real documentation of all classes in there.

Here's the wiki page where I try to click on "API Reference": ```https://github.com/onevcat/Kingfisher/wiki```

**Comment by onevcat** [comment]
Duplicated to #536 

It's a CocoaDoc issue. There seems to be little we could do in Kingfisher for it. For now, you could refer to the API reference version of [3.1.0](http://cocoadocs.org/docsets/Kingfisher/3.1.0/), which should be all compatible with current version.

**Comment by jyounus** [comment]
Ah, sorry! I only searched for "documentation" before opening this issue and that one didn't pop up.
Cool, thanks. Will use version 3.1.0 for now! :)

**Comment by onevcat** [comment]
@jyounus Had a double check and found this issue has been fixed several days ago (but after the deployment of Kingfisher 3.2.2). After a regenerating, the latest doc should work properly now. Try to access the http://cocoadocs.org/docsets/Kingfisher/3.2.2/ (and maybe refresh the browser)!

**Comment by jyounus** [comment]
You're right, that worked for me now. Thanks! :D
