### ISSUE TITLE
UICollcetionViewCell Images change to wrong images while scrolling after async image loading

### ISSUE THREAD

**Issue by llodi** [onevcat/Kingfisher#543]
When I'm scrolling my chat based on UICollcetionView, some images are placed on wrong cells. Here is my code:

import UIKit
import Kingfisher

```
class FriendMessageWithMultimediaCell: FriendMessagesCollectionViewCell {
    
    override func layoutSubviews() {
        super.layoutSubviews()
        updateUI()
    }
    
    override func updateUI() {
        super.updateUI()
        
        guard let attach = message?.lastPhotoAttachment else { return }
        
        if let photo = attach.photo604, let url = URL(string: photo)
        {
            addSubview(attachImageView)
            attachImageView.kf.setImage(with: url)
            setupUIComponents(withImageScale: attach.scaleForHeight)
        }
    }
```
Here screenshot:

![screen](https://cloud.githubusercontent.com/assets/13797475/21303304/8e4938e6-c5ce-11e6-8e74-0296d744b42d.png)

If messages don't include images, code bellow                 
`guard let attach = message?.lastPhotoAttachment else { return } `  aren't executed, but according to screenshot, images appear on screen in wrong place.

**Comment by onevcat** [comment]
I believe it's an issue due to your cell reusing and/or the timing of `updateUI` instead of Kingfisher. 

(It is rare and strange to me to update UI in `layoutSubviews`, which should only update the layout as name indicating).

Would you please check your code, especially the cell reusing timing and logic?

**Comment by llodi** [comment]
I've solved my issue, I just set all outlets to nil or "" before fill them.

And Thanx, I refactored my code, splitted them on setup UI components and update UI with data

**Comment by onevcat** [comment]
:)
