### ISSUE TITLE
Weird blank space appearing before and after image

### ISSUE THREAD

**Issue by tirrorex** [onevcat/Kingfisher#544]
Hello, i'm using this basic code            
      imageView.kf_setImageWithURL(NSURL(string: imageURL)!)

to load an image on my detail view.
If i load an url from facebook (which is a thumbnail) everything is fine but if i load an image from twitter (large image) i will have big white spaces before AND after the image (meaning on top and beneath).
My UIImageview is in a content view which is in turn in a scrollview (to be able to scroll the view if the text after the image is too long to fit in the screen).
The image is set to be equal width with the content view and is pinned to the top, leading and trailing of the content view with a horizontal centering (bottom is pinned to the textview beneath)
The aspect mode is aspect to fit.

You can see both images (which are basically the same) at these urls : 
https://scontent.xx.fbcdn.net/v/t1.0-9/p720x720/15589722_1474708575902936_5199321467736942706_n.jpg?oh=5a70e530c54c0f570d9f049b07934867&oe=58E3F8D6

https://pbs.twimg.com/media/Cztj1ENXUAAW-Wo.jpg:large

Expected behaviour : 
Edges of the images on the edges of the screen, height being redimmensionned to fit the screen.

Any leads on this ?

**Comment by onevcat** [comment]
The image of your url has a white border itself. Could it be the blank space you mentioned?

**Comment by tirrorex** [comment]
By blank space i mean with the same image redimensionned with aspect fit, edges touching the edges of the screen (so lower height), there is half the screen (vertical) being occupied by blank space, this is not related to the tiny white border of the image.
And after that half blank screen there is the image properly sized, followed by another half blank screen and then my textview (which has a top constraint of 15 in relation to my image bottom)
I would take a screenshoot for you guys but i am not allowed to do so yet.

**Comment by onevcat** [comment]
So is it due to your aspect to fit mode?

Kingfisher should do nothing on the content mode, but just setting the image property of an image view. So I guess it's more likely a problem of your image view content mode.

**Comment by onevcat** [comment]
P.S.

![](http://i.imgur.com/1cOU7.png)

**Comment by tirrorex** [comment]
Aspect fit should not behave like this, since the image is properly sized after the huge first blank, the image is supposed to be clipped to the top of the view without any blank actually.

Also i don't have the issue if the post is coming from facebook but just with post coming from twitter (with large image).
Didn't see any issue with uncached images so i assumed kingfisher did some resize on his own.
