### ISSUE TITLE
Rename macOS/tvOS tests to satisfy Swift Package Manager

### ISSUE THREAD

**Issue by ApolloZhu** [onevcat/Kingfisher#547]
When I try to `swift package generate-xcodeproj` or `swift build`, following error shows up: 

![screen shot 2016-12-20 at 22 08 02](https://cloud.githubusercontent.com/assets/10842684/21376182/e69079aa-c700-11e6-81ee-41df9d6c960d.png)

> btw, I'm not sure how this is going to effect CocoaPods and Carthage

**Comment by onevcat** [comment]
Should be fixed in 3.2.4
