### ISSUE TITLE
猫神，如何实现和imageView等比例的圆角？

### ISSUE THREAD

**Issue by Abel94** [onevcat/Kingfisher#551]
之前我提过#548 当初是为了看如何实现和imageView等比例的圆角。貌似kf实现的圆角都是基于image的size的，而不是imageView的size，这样就导致在很多时候做出来的圆角和效果图不一致。

**Comment by onevcat** [comment]
I guess you could try to resize your images to fit your image view size first, and then apply a round corner filter. You could use the `append` method of `ImageProcessor` to concatenate two processors and create a new one.
