### ISSUE TITLE
Progressive Loading

### ISSUE THREAD

**Issue by viral-etymon** [onevcat/Kingfisher#554]
Hi Does Kingfisher support progressive loading of image.
I mean to say that when I give URL to KF image then it start with low quality image then as data download image quality improves.

Something like below

![progressive](https://cloud.githubusercontent.com/assets/23634389/21676285/14670630-d35b-11e6-9625-6f7d7edb2b82.gif)

Thanks

**Comment by onevcat** [comment]
It's not supported in Kingfisher now, and there is no plan for it currently. :(

**Comment by netgfx** [comment]
2 years ahead, is this something that can be looked into?

**Comment by onevcat** [comment]
I believe it was already implemented in [5.5.0](https://github.com/onevcat/Kingfisher/releases/tag/5.5.0)

**Comment by netgfx** [comment]
thanks for the reply! greatly appreciate it!
