### ISSUE TITLE
Q: ImageDownloader.defatult.requestModifier

### ISSUE THREAD

**Issue by szuniverse** [onevcat/Kingfisher#555]
Hi 

Previous I had this code:

        let downloader = KingfisherManager.shared.downloader

        downloader.requestModifier = {
            (request: NSMutableURLRequest) in

        }

but now its not available, how can I solve this with the latest version of Kingfisher?

**Comment by onevcat** [comment]
It is now an option. Please see the [migration guide](https://github.com/onevcat/Kingfisher/wiki/Kingfisher-3.0-Migration-Guide#imagedownloader) and our [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending) for more.
