### ISSUE TITLE
Same Gif is stopped in a second ViewController

### ISSUE THREAD

**Issue by kikettas** [onevcat/Kingfisher#556]
I have a list of images (some of them are Gif) and they are loaded perfect (gif are played properly). When a user press on an item of the list, a detailed view is shown. But in this detailed view the gif's are stopped and I can't make it start (I tried startAnimating() and it didn't work). am I doing something wrong?

Thanks in advance and congratulations for this library, you are really awesome!!

**Comment by onevcat** [comment]
Hi,

Sorry for the late reply. So you means that the GIF is not playing when loaded from cache?

Are you trying to use some your own image cache serializer? And may I know the GIF url you are using or could you even build a demo project so I could investigate it deeper?

Thanks!

**Comment by kikettas** [comment]
Hi,

First of all, sorry for the delay. It was my bad, I was using AnimatedImageView on code but I had not set AnimatedImageView class on IB Identity inspector. Sorry for bothering you, and again congrats for this outstanding library.

Regards.

**Comment by onevcat** [comment]
Great to know that!
