### ISSUE TITLE
Not display url with cyrillic string

### ISSUE THREAD

**Issue by zhanswift** [onevcat/Kingfisher#558]
In my app JSON some images contain cyrillic symblos and Kingfisher is not display this images. Plaese help.

**Comment by onevcat** [comment]
Could you paste a url of that image? I will take a look.

**Comment by zhanswift** [comment]
For example https://halyknews.kz/wp-content/uploads/2016/12/ден6-300x188.jpg

**Comment by onevcat** [comment]
You need to escape (url encoding) it before creating and sending it as an url to Kingfisher. Like this:

```swift
guard let urlString = "https://halyknews.kz/wp-content/uploads/2016/12/ден6-300x188.jpg".addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) else {
    return
}
guard let url = URL(string: urlString) else {
    return
}
imageView.kf.setImage(with: url)
```

**Comment by zhanswift** [comment]
Thank you! It is was helped!

**Comment by onevcat** [comment]
@zhanswift Oops. Sorry for that. Hope it does no harm.
