### ISSUE TITLE
maxCachePeriodInSecond to unlimited

### ISSUE THREAD

**Issue by jovanpreet** [onevcat/Kingfisher#559]
Hi @onevcat currently my app has two types of images. 

1. The one that comes on news feeds. For them image cache of 7 days is good.

2. Images that come in chat. Until user logout and login with different id, i need those images to be cached i.e. to clear disk cache manually only. 

How can i achieve this?

**Comment by onevcat** [comment]
Instead of using the default cache, you could setup and use two different caches (`ImageCache`), one for each.

See the [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#use-customized-downloader-and-cache-instead-of-the-default-ones) for more.

**Comment by jovanpreet** [comment]
I already saw that. My issue wasn't that. I just wanna know how to implement maxCachePeriodInSecond = infinity //Unlimited.
just like maxDiskCacheSize can be set to 0 for unlimited storage size

**Comment by onevcat** [comment]
Oh,

There is no such "infinity" date currently. Maybe you could set `maxCachePeriodInSecond` to a relatively large number, like "300 * 50 * 60 * 60 * 24 * 7" (maybe 300 years?)

**Comment by jovanpreet** [comment]
Okay thanks i would implement that.

Just wanna ask, are you planning to implement this in future?

And one more thing. Is there a callback of images that are going to be deleted? I mean just the image keys might work

**Comment by jovanpreet** [comment]
@onevcat Please help

**Comment by onevcat** [comment]
Sure. It could be clear to add a `forever` option for the cache time. I will do it later.

And there is a `KingfisherDidCleanDiskCache` notification you could use for the images. You can find the API reference [here](http://cocoadocs.org/docsets/Kingfisher/3.2.4/Extensions/Notification.html#/s:ZvE10KingfisherVCSo14NSNotification4Name27KingfisherDidCleanDiskCacheS1_).

**Comment by jovanpreet** [comment]
What if i added this notification on a controller and kingfisher perform cleanup when that controller is not ye initialized. then?
Do i have to implement this on every controller(bad idea).
Please provide a example with best use case.

**Comment by onevcat** [comment]
Your selector will not get called if the instance (target) is not there.
You'd like to add that to a long life time object, for example your app delegate or your very first tab view controller which will exist across the whole app life time.

**Comment by jovanpreet** [comment]
Ok thank you.
Will disturb you again if i got stuck in any other problem...:p
