### ISSUE TITLE
Crash on startup when using 1.4.0 on iPad with iOS 8.0.2

### ISSUE THREAD

**Issue by tomquist** [onevcat/Kingfisher#56]
When updating Kingfisher from 1.3.1 to 1.4.0 (using CocoaPods 0.37.1) our app crashes directly after startup on an iPad 3 with iOS 8.0.2 with following error message:

    dyld: Library not loaded: /System/Library/Frameworks/WatchKit.framework/WatchKit
      Referenced from: /private/var/mobile/Containers/Bundle/Application/[udid]/[app-name].app/Frameworks/Kingfisher.framework/Kingfisher
      Reason: image not found

It works on an iPad Air with iOS 8.3 though. It probably tries to load the WKInterfaceImage extension even though it is not referenced in code anywhere. Any idea how to solve this?

**Comment by onevcat** [comment]
:( It seems caused by the WatchKit. I will have a look at it soon.

**Comment by onevcat** [comment]
@tomquist  Should be fixed in #59 . Please to a `pod install` to take effect in your project. :)

**Comment by tomquist** [comment]
I can confirm that this has been fixed by 1.4.1. Thank you very much!

**Comment by onevcat** [comment]
Thanks for confirming it!
