### ISSUE TITLE
Image completion handler

### ISSUE THREAD

**Issue by Albinzr** [onevcat/Kingfisher#561]
Why is image completion handler gets executed multiple time for single image ?

**Comment by onevcat** [comment]
It should not happen. Can you give some sample for it?

**Comment by Albinzr** [comment]
Ya sure
<img width="1228" alt="screen shot 2017-01-17 at 12 11 27 pm" src="https://cloud.githubusercontent.com/assets/7425577/22010266/20550cb0-dcae-11e6-8a0a-37da0a65c416.png">


If you look at the log you can see it have been called multiple times

**Comment by onevcat** [comment]
I guess your `configure(data:)` also got called multiple times?

**Comment by Albinzr** [comment]
Nop,I checked that too...

**Comment by Albinzr** [comment]
@onevcat this happens only the first time downloading image, not when retrieving from cache

**Comment by onevcat** [comment]
:( Just tried to load the same image in the demo scene and a new project. Cannot reproduce it.

Is it possible to build a demo project which could reproduce this problem?

**Comment by Albinzr** [comment]
Ok I will try that

**Comment by Albinzr** [comment]
When I restarted Xcode it started to work fine, Some wired issue
