### ISSUE TITLE
When we use ResizingImageProcessor on gif, It become non animating

### ISSUE THREAD

**Issue by Albinzr** [onevcat/Kingfisher#562]
When i did ResizingImageProcessor on a .gif image its not animating, Why is it happening and how can I make it animate?

**Comment by onevcat** [comment]
Currently none of the built-in image processors (expect the default one) would work for GIF files.

Kingfisher applied some basic support for GIFs, like downloading and displaying. However, it is neither a professional nor a complete library for processing GIF.

You may need to implement your own `ImageProcessor` for that. And you could even use some other GIF-specified framework to help you for that. The only requirement is you can turn a GIF `UIImage` or even its data to a resized valid GIF image.

**Comment by Albinzr** [comment]
How is it resized valid GIF image ?

**Comment by Albinzr** [comment]
Which lib will you suggest for cropping gif ?
