### ISSUE TITLE
UIImageView 连着两次 setImage，progressBlock 和 completionHandler 问题

### ISSUE THREAD

**Issue by Fnoz** [onevcat/Kingfisher#581]
此时应该把之前 task 中的 block 置空，或者标记一下不执行。
虽然现在判断了 imageURL == self.webURL，使得 completionHandler 没执行，但是 progressBlock还是会执行，如果打印进度，会有下面的情况，另外这样的判断感觉也不太好。
A10%    B50%    A30%    A100%    B60%    ...

本来想给 CallbackPair 加一个 identifier，然后 cancel 或者 removeTaskBlock（setImage时执行）时，用来 removeBlock，发现改动有点大，而且感觉不优雅，所以提了issue。

**Comment by onevcat** [comment]
Thanks for mention it. I will see what I could do with it. Maybe just cancel the previous downloading (but without calling the failure handler) could be a good idea.

**Comment by onevcat** [comment]
The progress block now should only report the latest set url.
