### ISSUE TITLE
Is there a way to cache images with an associated string?

### ISSUE THREAD

**Issue by ilandbt** [onevcat/Kingfisher#587]
Is there a way to cache images with an associated string?
like a tag? title, or image description?

Thanks

**Comment by onevcat** [comment]
You can choose any string as your key. Just create an `ImageResource` and pass it to Kingfisher's image setting methods.

See

https://github.com/onevcat/Kingfisher/blob/master/Sources/Resource.swift#L45-L64

or the [wiki](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#use-a-specified-key-other-than-the-url-for-cache) for more.

**Comment by ilandbt** [comment]
@onevcat thanks for the response, i will explain what exactly i meant.

 I need to cache a image + description together.
I dont want the description to be the key because then i need to save the descriptions in core data or some other DB.

I want the key to be something like image<index> and then i can save my last index in user defaults instead of in a DB.

Thanks

**Comment by onevcat** [comment]
Oh,

No, there is no such feature in Kingfisher. And it is not likely to be added since I didn't see good reason for it in an image downloading framework. You may use some other persistent way for your purpose. :(

**Comment by ilandbt** [comment]
Thanks anyway!!
