### ISSUE TITLE
completionHandler?(nil, error, cacheType, imageURL)

### ISSUE THREAD

**Issue by mingzizhennanqu** [onevcat/Kingfisher#593]
这里图片缓存失败，是nil的时候，显示失败占位图，切换到其它页面，上页面的controller和view已经释放，有时候会崩溃在这里，是不是这里线程没释放，该如何处理？

**Comment by stijnwesterhof** [comment]
?

**Comment by mingzizhennanqu** [comment]
你好：
     在使用kingfisher库进行图片缓存处理时候，
self.iconImageV.kf.setImage(with: URL.init(string: url), placeholder: self.iconImageV.loading(28, h: 28), options: nil, progressBlock: nil, completionHandler: { [unowned self](image, _, _, _) in
                DispatchQueue.main.async {
                    if image == nil{
                        self.iconImageV.image = self.iconImageV.loadFail()
                    }
                }
            })

当view请求图片失败时，进入了completionHandler?(nil, error, cacheType,imageURL) ,此时如果快速返回别的页面，这里线程仍然在进行，而这时页面已经释放了，导致崩溃，请教下，这里如何对kingfisher的失败进行处理

**Comment by onevcat** [comment]
DO NOT use `unowned` unless you really know what does it exactly means. Instead, I suggest you to use `weak` or just keep a strong reference here.
