### ISSUE TITLE
Directly retrieveing a UIImage object from the cache

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [onevcat/Kingfisher#595]
Hi,

I have saved some images in the disk cache. In my app, there's a collection view and a delegate method which I have to return a `UIImage` object for each cell. So using the following method doesn't work since it's asynchronous.
```swift
ImageCache.default.retrieveImage(forKey: "key", options: [.onlyFromCache]) { image, cacheType in
    print(image)
}
```

<hr>

**Attempt 1**

I tried this way to get the image directly but this returns `nil`.
```swift
ImageCache.default.retrieveImageInDiskCache(forKey: "key", options: [.onlyFromCache])?.images?.first
```
But I can see that the cache indeed has the image objects if I print out `ImageCache.default.retrieveImageInDiskCache(forKey: "key", options: [.onlyFromCache])`, I get this `Optional(<UIImage: 0x165f4600>, {30, 30})` in my console.

<hr>

**Attempt 2**

I was able to retrieve the image object like this.
```swift
ImageCache.default.retrieveImageInDiskCache(forKey: "key")?.resizeImage(to: 30)
```

But the problem is resizing the image on-the-go like this inside a delegate method severely affects the scrolling performance.

So is there another, better way to do this?

**Comment by onevcat** [comment]
`ImageCache.default.retrieveImageInDiskCache(forKey: "key", options: [.onlyFromCache])` returns an optional image, so you just need to unwrap and use it. You do not need the `?.imges?.first`, unless you r image is an animating one (GIF image).

**Comment by Isuru-Nanayakkara** [comment]
Thanks!
