### ISSUE TITLE
log訊息一大堆，記憶體資源佔用暴增

### ISSUE THREAD

**Issue by g001613001** [onevcat/Kingfisher#596]
你好
我用cocoapods安裝後
簡單的測試使用一下
let img = UIImageView()
img.kf.setImage(with: URL(string:"http://i.imgur.com/Ajp5A6B.jpg"))

結果發現log訊息吐了一堆，並且持續在刷屏
然後記憶體佔用狂增加都不會停
只有一張圖就佔用了幾十mb的記憶體

不知道這是少設定了什麼造成的？

我是用ios 10 的模擬器測試的，手機也是有相同問題
但是ios9不會log訊息一堆，但是記憶體資源一樣是大量佔用

**Comment by onevcat** [comment]
You image size is 1440x2560, which means it will take more than 10MB. So it is not surprising it will take some amount of memory (but it should be only 10+MB for you)

And it is not wise to do any profiling in a simulator or attaching to debugger. Please always try to profile your app in Instruments and if you find anything strange, you could attach the profile result and log, so I could have a deeper look.

For the log things, you may want to look at [this](http://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-8-logs).
