### ISSUE TITLE
ImagePrefetcher 阻塞主线程

### ISSUE THREAD

**Issue by BrikerMan** [onevcat/Kingfisher#603]
如果使用 `ImagePrefetcher` 会导致主线程阻塞，UI卡顿。注视 `ImagePrefetcher` 就没问题....
是我使用姿势不对？
谢啦喵神~
```swift
extension Controller: UICollectionViewDataSourcePrefetching {
    func collectionView(_ collectionView: UICollectionView, prefetchItemsAt indexPaths: [IndexPath]) {
        let links = urls.flatMap{ URL(string: self.models[$0.row].cover) }
        ImagePrefetcher(urls: links).start()
    }
}
```

**Comment by onevcat** [comment]
:(

It should not happen since `ImagePrefetcher` is using the same downloader as the `ImageView` extension under-hood. Generally speaking they should behave as the same (or at least similar) performance.

But I will check what happened here. Maybe it just because you are trying to load huge amount of images here? May I know the `links.count` you are using? Or you could try to set the `maxConcurrentDownloads` of `ImagePrefetcher` to a number smaller (default is 5) .

**Comment by BrikerMan** [comment]
I don't think the problem is images count. I have only 22 models here~ Maximum links count is 6.

When All image has cached, It will 60 FPS if I disable the prefetch code, and will drop to 40 at the first several time when scroll with prefetch enabled, then back to 60.

```swift
models.count = 22
links.count = 6
```

**Comment by onevcat** [comment]
Maybe related to https://github.com/onevcat/Kingfisher/issues/634, since the delegate queue of url session in `ImageDownloader` is now the main queue. I will try to apply a patch for it, you could check whether it could fix this issue.

**Comment by futomtom** [comment]
How to cancel ImagePrefetcher fetch task in  func collectionView(_ collectionView: UICollectionView, cancelPrefetchingForRowsAt indexPaths: [IndexPath]) {
       //suppose we have   indexPath 
      
        }
    }

**Comment by onevcat** [comment]
Currently, you can only stop the whole created image prefetcher, instead of stopping some specified url.

**Comment by futomtom** [comment]
would using ImageDownloader be a better approach    func collectionView(_ collectionView: UICollectionView, prefetchItemsAt indexPaths: [IndexPath]) {
  
        for indexPath in indexPaths {
            let article = articles[indexPath.row]
            //save task into our model , then we can cancel them , if needed.  
            article.task = ImageDownloader.default.downloadImage(with: article.thumbnail, options: [], progressBlock: nil) {
                (image, error, url, data) in
                article.image = image   //should we save 
            }
        }
    }
    
    func collectionView(_ collectionView: UICollectionView, cancelPrefetchingForItemsAt indexPaths: [IndexPath]) {
        for indexPath in indexPaths {
            let article = articles[indexPath.row]
            article.task?.cancel()
        }
    }

**Comment by EnderTan** [comment]
当ImagePrefetcher 配合WebP使用时，阻塞主线程现象会非常明显，感觉.backgroundDecode没有生效

**Comment by petard** [comment]
ImageDownloader doesn't cache images according to the cheatsheet. I'm using this helper function to prefetch images in the background, I'm loading a a lot of images and ImagePrefcher made my collectionviews stutter.

```swift
class KingfisherPrefetchManager {
    
    static let shared: KingfisherPrefetchManager = KingfisherPrefetchManager()
    
    private lazy var serialQueue: DispatchQueue = DispatchQueue(label: "imageQueue")
        
    public func fetch(urls: [URL]) {
        DispatchQueue.global(qos: .background).async {
            for imageUrl in urls {
                self.serialQueue.sync {
                    self.fetchData(imageUrl)
                }
            }
        }
        
    }
    
    private func fetchData(_ url: URL) {
        
        let _ = KingfisherManager.shared.retrieveImage(
            with: url,
            options: nil,
            progressBlock: nil,
            completionHandler: {_, error, cacheType, imageURL in
               //Add if needed
        })
    }
    
}
```

**Comment by ZeroOnet** [comment]
Using KingfisherWebP will make the same trouble too.

**Comment by jzau** [comment]
@BrikerMan
`func collectionView(_ collectionView: UICollectionView, prefetchItemsAt indexPaths: [IndexPath]) ` This function is called multiple times when you scrolling, while the code inside this function is not associated with indexPaths. which means `ImagePrefetcher(urls: links).start()` will be called multiple times with the same `links`.

Can you please try to move `ImagePrefetcher(urls: links).start()` somewhere else and let me know how it goes?

**Comment by onevcat** [comment]
This should be related to https://github.com/onevcat/Kingfisher/commit/9ce57167d9d95c788e66a6bfdff37ba6cbe63ec2#diff-6589daa66ba3ebddcf378d70a2c29032 and I believe it was fixed now.
