### ISSUE TITLE
Cocoapods: Kingfisher classes not recognized

### ISSUE THREAD

**Issue by NateFuller** [onevcat/Kingfisher#604]
I am developing a framework that we archive as a .framework file and drop into a container application.

I have made sure to include the `import Kingfisher` statements at the top of the source files I am referencing Kingfisher classes in.

Getting compiler errors like "Use of undeclared type 'Resource'", "Use of undeclared type 'ImagePrefetcher'", etc when I set "Build Active Architecture Only" to "No" in Build Settings.

When I set it "Build Active Architecture Only" to "Yes", these errors disappear and I am able to build. Need to be able to set to "No" so our framework archives for all architectures.

Using v2.6.1 on Xcode 7.3.1.

**Edit: Using v2.6.1, not v2.6.0; mentioned that I am using import statements**

**Comment by onevcat** [comment]
How did you include Kingfisher into your framework? You also need to build Kingfisher for all valid architectures if you want your own framework to be compatible with all architectures.

**Comment by NateFuller** [comment]
I've since updated to Xcode 8.3, Swift 3, and am using Kingfisher 3.6.2. Same issue. How would I specify to build Kingfisher for all valid architectures?

**Comment by onevcat** [comment]
Maybe you need to specified it in the Pods target?

Some [Ref](http://stackoverflow.com/questions/19419781/cocoapods-arm64-issue). And I guess it could be done by a post install action in the Podfile.

**Comment by onevcat** [comment]
And I am not sure if you are on the correct way to develop a framework which depends on another.

If my understanding is correct, you are trying to develop your own framework (and archive it as a .framework file) which depends on Kingfisher. First, the CocoaTouch framework (I am not sure whether your framework is a CocoaTouch Framework target, but Kingfisher is) is a dynamic framework and you may need to use `lipo` to combine x64, arm7 and arm64 architectures to a fat binary. Then when you are archiving it in your final app, you may need to resign it (and optionally strip the unused x64 part). The same thing has to be done for Kingfisher if you want to embed Kingfisher into the `Framework` folder in your framework. It is not a trivial work at all.

If you have no idea about what I am talking about, I suggest to use CocoaPods or Carthage to manage the dependency. You could just specify Kingfisher in your `podspec` or `Cartfile`, then deliver your framework as a dependency. It would be much easier.

**Comment by onevcat** [comment]
Maybe related to #647 

I suggest to upgrade both CocoaPods and Kingfisher version to see whether it could work.
