### ISSUE TITLE
Cannot download Image

### ISSUE THREAD

**Issue by malebuffy** [onevcat/Kingfisher#607]
Hello,
I am using Xcode 8 and Swift and I am trying to use Kingfisher in my project. However, I havent managed to load a image  from firebase to a UIImageView. I want to download some images and use them in a Array so that I can use them in a scroll view.

Now although the code compiles, I get: fatal error unexpectedly found nil while unwrapping Optional value. If I use a placeholder image with setImage, the placeholder image is displayed but not the one in the URL and the app doesnt crash. So the setImage is working but not setting the downloaded image, but the placeholder. Can anybody help?

>
> import UIKit
> import Kingfisher
> 
> class Backprogramme: UIViewController {
>     

>     override var prefersStatusBarHidden: Bool {
>         return true
>     }
> 
>     @IBOutlet var BackPScroll: UIScrollView!
>     
>     var imageArray = [UIImage]()
>     var folie1Image = UIImageView()
>     var folie2Image = UIImageView()
>     var anView = UIImageView()
>     
>     override func viewDidLoad() {
>         super.viewDidLoad()
> 
>         
>        let folie1URL = "https://firebasestorage.googleapis.com/v0/b/backmaster-cdb60.appspot.com/o/Folie1.PNG?alt=media&token=efcb8e93-b817-41f3-a96f-946fd47cf468"
>        let resource1 = ImageResource(downloadURL: URL(string: folie1URL)!, cacheKey: folie1URL)
>        folie1Image.kf.setImage(with: resource1)
>         
>         
>         
>         
>         print(folie1Image.frame)
>         if (folie1Image.image == nil) {
>             print("X")
>         
>        }
>               
>       imageArray = [folie1Image.image!]
>    
>         for i in 0..<imageArray.count{
>             
>             let imageView = UIImageView()
>             imageView.image = imageArray[i]
>             let xPosition = self.view.frame.width * CGFloat(i)
>             imageView.frame = CGRect(x: xPosition, y: 0, width: self.BackPScroll.frame.width, height: self.BackPScroll.frame.height)
>             
>             
>             BackPScroll.contentSize.width = BackPScroll.frame.width * CGFloat(i+1)
>             BackPScroll.addSubview(imageView)
>  
>         }
>         
>         // Do any additional setup after loading the view.
>     }
> 
>     override func didReceiveMemoryWarning() {
>         super.didReceiveMemoryWarning()
>         // Dispose of any resources that can be recreated.
>     }
> 
>     
>     
>     
>     /*
>     // MARK: - Navigation
> 
>     // In a storyboard-based application, you will often want to do a little preparation before navigation
>     override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
>         // Get the new view controller using segue.destinationViewController.
>         // Pass the selected object to the new view controller.
>     }
>     */
> 
> }

**Comment by onevcat** [comment]
The `setImage` method of Kingfisher is an async operation. The image property of your `folie1Image` is still `nil` when you trying to force unwrap it.

It is not a Kingfisher issue but the way you use Swift. I suggest to ask in Stackoverflow instead of opening an issue here. You would get more chance to be helped there.
