### ISSUE TITLE
How I can use it for disk cache? And When cache is has cleared? 

### ISSUE THREAD

**Issue by innac-hyuna** [onevcat/Kingfisher#609]
For example, I need download image to disk and then will clear cache.

**Comment by onevcat** [comment]
Please read the [Cheat Sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet) wiki to know how to use a feature. And refer to the [docs](http://cocoadocs.org/docsets/Kingfisher/3.5.0/) for more detail of `ImageCache`.
