### ISSUE TITLE
clearMemoryCache 崩溃

### ISSUE THREAD

**Issue by andy1247008998** [onevcat/Kingfisher#610]
![snip20170301_1](https://cloud.githubusercontent.com/assets/7299189/23443032/30092152-fe67-11e6-96b0-394f1fc32bcf.png)

**Comment by onevcat** [comment]
What is the `sparkAddressString`? 

There is no such method in Kingfisher nor Kingfisher tries to call.

So, ot seems not to be a problem in Kingfisher. Are you using some runtime swizzle or injection to modify the `ImageCache` class?

I guess you are using [Spark Inspector](http://www.sparkinspector.com) in your project? Try to turn it off to see whether it could help.

**Comment by andy1247008998** [comment]
@onevcat Yeah, you are right. I am using SparkInspector.

The solution might be this:

1. let ImageCache inherit from NSObject
`open class ImageCache:NSObject `
2. add super.init()
`        super.init()`
` ioQueue.sync { fileManager = FileManager() }`

**Comment by onevcat** [comment]
It's nothing to do with the quality of Kingfisher project and should be an issue of Spark Inspector.
