### ISSUE TITLE
Slow compile time for "func blurred(withRadius radius: CGFloat) -> Image"

### ISSUE THREAD

**Issue by bes** [onevcat/Kingfisher#611]
Hi,

The Kingfisher project has previously solved issues with slow compile times (#467, #468), so I am posting this in the hopes of you being able to solve this new one that I am seeing since recently upgrading to the latest version (3.5.0 / 5cfa0dd5c9fc48e1c31f574ad8eaa31a3a9d4003):

```
1763.4ms        .../Pods/Kingfisher/Sources/Image.swift:442:17   public final func blurred(withRadius radius: CGFloat) -> Image
1761.1ms        .../Pods/Kingfisher/Sources/Image.swift:442:17   public final func blurred(withRadius radius: CGFloat) -> Image
```

CC @frankrausch @onevcat 

Thanks, BR, Erik

**Comment by frankrausch** [comment]
Do you remember which version you had before? That would make it easier to isolate the problem.

I took a quick look at the `blurred` function but didn’t see anything suspicious (like a complex equation in one line).

**Comment by bes** [comment]
This is showing up since upgrading from 3.3.3, but I can't see any changes in blurred between those versions. Right now blurred is the function that takes the longest time to compile in our project (according to `-debug-time-function-bodies`), but I can't say how accurate that is...

I am coming from 7 years of Android development, and I must say the iOS tool chain is quite bad compared to anything Java / Android related.

**Comment by onevcat** [comment]
Should be fixed in https://github.com/onevcat/Kingfisher/pull/613

It took me about 2000ms before. And now 100ms.

**Comment by bes** [comment]
Thank you!

**Comment by frankrausch** [comment]
Amazing! Still unbelievable that splitting the statement into 3 lines makes such a huge compile time difference.
