### ISSUE TITLE
Imageresize

### ISSUE THREAD

**Issue by kherlopian2** [onevcat/Kingfisher#614]
I HAVE uitableview, and in this uitableview I got a cell. This cell has a 2 uiimageview next to each other with equal widths.I want both this 2 imageviews to take the entire width, 1st imageview half the width screen second imageview the other half. I am getting the images from kingfisher, how can i the image got from url be resized based on width. if image is 200 - 200 for example, and half width i got is 400..i want my image height to resize to 400. If I got 300 - 400, I and I got width 150..I want my image height to resize to 200.And also resize the cell in process.

How can this be done using kingfisher library?

 let processor = ResizingImageProcessor(targetSize: CGSize(width: im1.bounds.width, height: 0))
        //
        let url = URL(string: "http://thediplomat.com/wp-content/uploads/2013/05/2910_52438736b9ef2-386x248.jpg")
        
        im1.kf.indicatorType = .activity
        
        im1.kf.setImage(with: url,options: [.transition(.fade(0.2)), .processor(processor)])

I need something like this, where i pass height 0  and it resizes to me the height based on the width. Thank You.

**Comment by kherlopian2** [comment]
let processor = ResizingImageProcessor(targetSize: CGSize(width: im1.bounds.width, height: 0))
        //
        let url = URL(string: "http://thediplomat.com/wp-content/uploads/2013/05/2910_52438736b9ef2-386x248.jpg")
        cell.im1.kf.indicatorType = .activity
        cell.im1.kf.setImage(with: url,options: [.transition(.fade(0.2)), .processor(processor)], completionHandler: {
            (image, error, cacheType, imageUrl) in
            print(self.cell.im1.bounds.width)
            print(self.cell.im1.bounds.height)
            print(image?.size.width)
            print(image?.size.height)
            
            var hei = (((image?.size.height)!*self.cell.im1.bounds.width)/(image?.size.width)!)
            print(hei)
            var image1 = self.resizeImage(image: image!, targetSize: CGSize(width: self.cell.im1.bounds.width, height: hei))
            
            self.cell.im1.image = image1
            
        })

func resizeImage(image: UIImage, targetSize: CGSize) -> UIImage {
        let size = image.size
        
        let widthRatio  = targetSize.width  / image.size.width
        let heightRatio = targetSize.height / image.size.height
        
        // Figure out what our orientation is, and use that to form the rectangle
        var newSize: CGSize
        if(widthRatio > heightRatio) {
            newSize = CGSize(width: size.width * heightRatio, height: size.height * heightRatio)
        } else {
            newSize = CGSize(width: size.width * widthRatio,  height: size.height * widthRatio)
        }
        
        // This is the rect that we've calculated out and this is what is actually used below
        let rect = CGRect(x: 0, y: 0, width: newSize.width, height: newSize.height)
        
        // Actually do the resizing to the rect using the ImageContext stuff
        UIGraphicsBeginImageContextWithOptions(newSize, false, 1.0)
        image.draw(in: rect)
        let newImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        return newImage!
    }

Do You guys think this is good way of implementing?

**Comment by onevcat** [comment]
I cannot fully understand you, but it seems you are trying to do an aspect fit resizing?

Maybe you could just try the resizing processor with that option:

```swift
let p = ResizingImageProcessor(targetSize: size, contentMode: .aspectFit)
```

where the `size` should be your image view's size.
