### ISSUE TITLE
加载大量图片的时候内存暴涨

### ISSUE THREAD

**Issue by YinSiQian** [onevcat/Kingfisher#615]
喵神,最近在使用Kingfisher的时候,发现一个问题,在加载图片的时候,内存会涨的很厉害.为了排除代码原因,我更换到SDWebImage的时候,内存没有出现过这种情况.
icon.kf.setImage(with: model?.photo?.url())

就使用过这个方法.不知道是不是姿势不对- -

**Comment by onevcat** [comment]
Maybe you could try to do some brief search before open such an issue. Like [this](https://github.com/onevcat/Kingfisher/issues/531) might help.
