### ISSUE TITLE
Podfile Updated, Unable to import Kingfisher

### ISSUE THREAD

**Issue by troy21688** [onevcat/Kingfisher#618]
New to iOS programming and lovin what Kingfisher has to offer, however I cannot get it set up:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/87eJu.png

**Comment by onevcat** [comment]
Have no idea. It should be your project setting instead of a Kingfisher issue. Please try to clean and update the cocoapod repo.
