### ISSUE TITLE
Any detail instruction of how to use the downloader of this library?

### ISSUE THREAD

**Issue by htarwara6245** [onevcat/Kingfisher#62]
First of all,I thank to KingFisher who gave me such fast download and simple image library.

I am now currently developing auction car application.
When i went to each car detail,i will get more than 6 or 10 photos url array which are protected with certificate.And i really don't know how to use this library download manager and image cache.

I also got one problem,too.After i downloaded the images from url,i need to store in some array to show at autolayout scrollview.So,assigning to UIImageView dont work out for me.So i need to know how to use your image downloader and how to pass "https" images url too.I also using SwiftHttp too which include allow all certificate.But i dont know how to embedded with yours.

Here is my old way which show image but taking too long at downloading.And you will see that i append imageFromUrl in image array which will return to scrollview.

Here is the downloading process,i was beginner so my code will be funny to you.:(
http://puu.sh/ibRVg/9e4cf4891b.png
Here is where i show my downloaded images in scrollview.
http://puu.sh/ibRY5/57aa237f06.png

Any help?Please.
Thank you.

**Comment by onevcat** [comment]
Hi, @htarwara6245 
I saw this post. However I am quite busy currently, I will try to reply as soon as possible.

**Comment by htarwara6245** [comment]
Thank you.Sir...I will be glad to wait your reply.

**Comment by onevcat** [comment]
Hi, @htarwara6245 

To download the images from network or get them from cache, you can just use the `-retrieveImageWithURL:optionsInfo:progressBlock:completionHandler:` method. It will search the cache first and if it is not found in cache, Kingfisher will download it from the url. Here is some code snippet for it:

```swift
var urlString = [car.image0, car.image1]
var images = [UIImage]()

for url in urlString {
    let imageUrl = NSURL(string: url)
    KingfisherManager.sharedManager.retrieveImageWithURL(imageUrl, optionsInfo: nil, progressBlock: nil, completionHandler: { (image, error, cacheType, imageURL) -> () in
        if image = image {
            images.append(image)
                    
            //your completion logic
            //...
        } else {
            // Error
        }
    })
}
```

**Comment by htarwara6245** [comment]
Thank you,Sir...I am really appreciated your help.Thank You So Much for your help.I gonna apply in my project now.Thank in advance.

**Comment by htarwara6245** [comment]
I have tried the above instruction like you described.But images that downloaded are not show in scrollview.I dont know what is going with me.Everytime that i enter to that view(detailview) again,images are downloaded and duplicated.Any help please?

**Comment by onevcat** [comment]
Hi, @htarwara6245 
As asked in Stackoverflow, may I know if this issue could be closed or not?

**Comment by htarwara6245** [comment]
yes sir,Thanks for your answer
