### ISSUE TITLE
parse ImageProcessItem Data to raw value

### ISSUE THREAD

**Issue by black-lotus** [onevcat/Kingfisher#623]
Hi, i am working with SVG
i read about cheat sheet and found this

   ```
 func process(item: ImageProcessItem, options: KingfisherOptionsInfo) -> UIImage? {
        switch item {
        case .image(let image):
            print("already an image")
            return image
        case .data(let data):

        }
    }
```

i want to ask, is it possible to parse data to svg raw value... 
i tried to parse using 

`data.base64EncodedString()`

it's not raw svg content

Thank you in advance

**Comment by onevcat** [comment]
I am not familiar with SVG file. However, if you can find a way to convert your SVG file between `Data` and `UIImage`/`NSImage`, you could implement an `ImageProcessor` and a `CacheSerializer` pass it to Kingfisher's manager as an option, then Kingfisher could handle downloading/caching for it.

**Comment by Codeido** [comment]
I used [PocketSVG](https://github.com/pocketsvg/PocketSVG) + Kingfisher.

First of all i implemented the ImageProcessor like this:
```
struct SVGProcessor: ImageProcessor {
    // `identifier` should be the same for processors with same properties/functionality
    // It will be used when storing and retrieving the image to/from cache.
    let identifier = "my.app.svg"
    
    // Convert input data/image to target image and return it.
    func process(item: ImageProcessItem, options: KingfisherOptionsInfo) -> Image? {
        switch item {
        case .image(let image):
            //already an image
            return image
        case .data(let data):
            let frame = CGRect(x: 0, y: 0, width: 250, height: 250)
            let svgLayer = SVGLayer(svgSource: String(data: data, encoding: .utf8)!)
            svgLayer.frame = frame
            return snapshotImage(for: svgLayer)
        }
    }
}
```

and i have this extra method to convert a CALayer to UIImage:
```
func snapshotImage(for layer: CALayer) -> UIImage? {
    UIGraphicsBeginImageContextWithOptions(layer.bounds.size, false, UIScreen.main.scale)
    guard let context = UIGraphicsGetCurrentContext() else { return nil }
    layer.render(in: context)
    let image = UIGraphicsGetImageFromCurrentImageContext()
    UIGraphicsEndImageContext()
    return image
}
```

Let me know if is ok for you.

**Comment by onevcat** [comment]
@Codeido Thanks for the detail explanation!

And you may also want to implement a `CacheSerializer` if you need to cache the image instead of downloading it again and again. (But I believe since the svg files are usually really small, this would not be a big impact on user experience.)

**Comment by black-lotus** [comment]
@Codeido wow nice...
@onevcat noted, i will implement `CacheSerializer`

Thank you

**Comment by Codeido** [comment]
Revisited implementation with CacheSerializer

```
//
//  SVGProcessor.swift
//
//  Created by Paolo Musolino on 21/03/17.
//  Copyright © 2017. All rights reserved.
//

import UIKit
import Kingfisher
import PocketSVG

struct SVGProcessor: ImageProcessor {
    let imgSize: CGSize?
    
    init(size: CGSize? = CGSize(width:250, height:250)) {
        imgSize = size
    }
    
    // `identifier` should be the same for processors with same properties/functionality
    // It will be used when storing and retrieving the image to/from cache.
    let identifier = "my.app.svg"
    
    // Convert input data/image to target image and return it.
    func process(item: ImageProcessItem, options: KingfisherOptionsInfo) -> Image? {
        switch item {
        case .image(let image):
            //already an image
            return image
        case .data(let data):
            return generateSVGImage(data: data, size: imgSize)
        }
    }
}

struct SVGCacheSerializer: CacheSerializer {
    func data(with image: Image, original: Data?) -> Data? {
        return original
    }
    
    func image(with data: Data, options: KingfisherOptionsInfo?) -> Image? {
        return generateSVGImage(data: data)
    }
}

func generateSVGImage(data: Data, size: CGSize? = CGSize(width:250, height:250)) -> UIImage?{
    let frame = CGRect(x: 0, y: 0, width: size!.width, height: size!.height)
    if let svgString = String(data: data, encoding: .utf8){
        let svgLayer = SVGLayer(svgSource: svgString)
        svgLayer.frame = frame
        return snapshotImage(for: svgLayer)
    }
    return nil
}

func snapshotImage(for layer: CALayer) -> UIImage? {
    UIGraphicsBeginImageContextWithOptions(layer.bounds.size, false, UIScreen.main.scale)
    guard let context = UIGraphicsGetCurrentContext() else { return nil }
    layer.render(in: context)
    let image = UIGraphicsGetImageFromCurrentImageContext()
    UIGraphicsEndImageContext()
    return image
}
```

**Comment by timonchev** [comment]
how get size of image from data? Or proportions weight/height

**Comment by timonchev** [comment]
or something like Aspect fit for svg layer?

**Comment by vaibhav-varshaaweblabs** [comment]
@Codeido my code crashes at this line 
![screen shot 2017-07-21 at 4 37 00 pm](https://user-images.githubusercontent.com/21377276/28461134-d95871dc-6e32-11e7-9e23-c76e65b1114e.png)

**Comment by Codeido** [comment]
Probably the type of SVG file that you are passing to PocketSVG is not supported.

**Comment by vaibhav-varshaaweblabs** [comment]
@Codeido how can we handle this crash via try-catch?

**Comment by Codeido** [comment]
Try to open an issue on [PocketSVG](https://github.com/pocketsvg/PocketSVG) repo, the crash is not referred to Kingfisher.

**Comment by vaibhav-varshaaweblabs** [comment]
@Codeido Ohk

**Comment by vaibhav-varshaaweblabs** [comment]
@Codeido Have you used SVGKit instead of PocketSVG?

**Comment by Codeido** [comment]
No, I tried only PockerSVG.

**Comment by vaibhav-varshaaweblabs** [comment]
@Codeido Can you help me add SVGKit in ImageProcessor file?

**Comment by Codeido** [comment]
I don't have much time to dedicate, but I think that the integration process can be the same of PocketSVG. 
Everything you need is in the documentation files (Kingfisher and SVGKit).

**Comment by luongtuananh168** [comment]
@vaibhav-varshaaweblabs  :  SVGKit in ImageProcessor solution 👍 

In struct WebpProcessor: ImageProcessor
//Convert input data/image to target image and return it
`case .data(let data):
                let imageSVG : SVGKImage = SVGKImage(data: data)
                    return imageSVG.uiImage
            }`
// Then pass it to the `setImage` methods:
`let processor = WebpProcessor()
let url = URL(string: "https://yourdomain.com/example.webp")
imageView.kf.setImage(with: url, options: [.processor(processor)])`

**Comment by jacobsapps** [comment]
The imageSVG version works fine some of the time but when trying to load multiple images concurrently it crashes hard.

**Comment by puji26** [comment]
Argument labels '(svgSource:)' do not match any available overloads

**Comment by wmadao11** [comment]
For anyone else uses @pmusolino 's code:
It seems that `SVGLayer(svgSource: svgString)` is not available now, 
but we can set its `paths` after initialization.

And to keep the image proportion, there is a function called `SVGBoundingRectForPaths`.
```swift
static func generateSVGImage(data: Data, width: CGFloat = 250) -> UIImage? {
    if let svgString = String(data: data, encoding: .utf8) {
        let svgLayer = SVGLayer()
        svgLayer.paths = SVGBezierPath.paths(fromSVGString: svgString)
        let originRect = SVGBoundingRectForPaths(svgLayer.paths)
        svgLayer.frame = CGRect(x: 0, y: 0, width: width, height: width * originRect.height / originRect.width)
        return snapshotImage(for: svgLayer)
    }
    return nil
}
```

**Comment by kildos** [comment]
@wmadao11  Didn't know about `SVGBoundingRectForPaths`. Thank you, you saved my day! ❤️
