### ISSUE TITLE
Log Screen 

### ISSUE THREAD

**Issue by adelmorgan** [onevcat/Kingfisher#624]
I would like to know how can I stop receiving these logs during downloading the image and regarding to this error is that considered stack underflow 

**## nw_host_stats_add_src recv too small, received 24, expected 28**

2017-03-15 12:06:40.222792 TestingKingfisher[10481:809410] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-15 12:06:40.226058 TestingKingfisher[10481:809410] [] ____nwlog_simulate_crash_inner_block_invoke dlopen CrashReporterSupport failed
2017-03-15 12:06:40.226263 TestingKingfisher[10481:809410] [] __nwlog_err_simulate_crash simulate crash failed "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
2017-03-15 12:06:40.226990 TestingKingfisher[10481:809410] [] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
        [x86_64] libnetcore-856.30.16
    0   libsystem_network.dylib             0x000000010cf1b666 __nw_create_backtrace_string + 123
    1   libnetwork.dylib                    0x000000010ca56006 nw_socket_add_input_handler + 3164
    2   libnetwork.dylib                    0x000000010ca33555 nw_endpoint_flow_attach_protocols + 3768
    3   libnetwork.dylib                    0x000000010ca32572 nw_endpoint_flow_setup_socket + 563
    4   libnetwork.dylib                    0x000000010ca31298 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
    5   libnetwork.dylib                    0x000000010ca4cae1 nw_endpoint_handler_path_change + 1261
    6   libnetwork.dylib                    0x000000010ca4c510 nw_endpoint_handler_start + 570
    7   libnetwork.dylib                    0x000000010ca641f9 nw_endpoint_resolver_start_next_child + 2240
    8   libdispatch.dylib                   0x000000010cc98978 _dispatch_call_block_and_release + 12
    9   libdispatch.dylib                   0x000000010ccc20cd _dispatch_client_callout + 8
    10  libdispatch.dylib                   0x000000010cc9fe17 _dispatch_queue_serial_drain + 236
    11  libdispatch.dylib                   0x000000010cca0b4b _dispatch_queue_invoke + 1073
    12  libdispatch.dylib                   0x000000010cca3385 _dispatch_root_queue_drain + 720
    13  libdispatch.dylib                   0x000000010cca3059 _dispatch_worker_thread3 + 123
    14  libsystem_pthread.dylib             0x000000010d06b4de _pthread_wqthread + 1129
    15  libsystem_pthread.dylib             0x000000010d069341 start_wqthread + 13
Used disk size by bytes: 0
com.onevcat.Kingfisher.ResizingImageProcessor((1024.0, 760.0))
Used disk size by bytes: 0
Used disk size by bytes: 0
com.onevcat.Kingfisher.ResizingImageProcessor((1024.0, 760.0))
Used disk size by bytes: 0

**Comment by onevcat** [comment]
It's not a Kingfisher issue, but an Xcode 8 simulator debug problem. Maybe [this post](http://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-8-logs) would help.
