### ISSUE TITLE
.backgroundDecode not working with GIF

### ISSUE THREAD

**Issue by wendyabrantes** [onevcat/Kingfisher#625]
Using the option KingfisherOptionsInfo .backgroundDecode make the image still when used with Gif.
I was trying to use this cause gif are being encoded/decoded on the main thread and its really laggy on a collection view

**Comment by onevcat** [comment]
Background decoding does not support back ground decode now. The main reason of lagging gif might mainly be that you trying to use the `AnimatedImageView`. You could try to use the normal `UIImageView` if the size of your GIF image is not large. You have to get a balance of memory/cpu usage between the two modes (all decode at once or decode one image per frame).

**Comment by danleechina** [comment]
I am facing the same problem in 4.10.1 version
