### ISSUE TITLE
how to use AnimatedImageView to load gif image?

### ISSUE THREAD

**Issue by zerozheng** [onevcat/Kingfisher#628]
how to use AnimatedImageView to load gif image? I try this but it doesn't work. the imageView only show the first frame of the gif image.

```
let imageView = AnimatedImageView(Aframe)
imageView.image = UIImage.init(named: AgifImageName)
```

**Comment by onevcat** [comment]
You need to use the extension methods of image view to set it. Please read our [wiki](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#animated-gif) before open such an issue.
