### ISSUE TITLE
Speed up MD5

### ISSUE THREAD

**Issue by LimChihi** [onevcat/Kingfisher#635]
Hi
I found that you used `NSMutableString` in `String` extension to generate MD5 string.
It could be faster if you use `String`.
for 10000 item calculation, Your code need `0.84178680399782s`, if you use `String`, it will only need `0.601265446995967s`.
Although MD5  calculation is fast enough, Swift style is more cool.

你好，我发现您在`String`的拓展中使用了`NSMutableString`来生成 MD5.
如果直接使用`String`会更快一些。
在10000个项目的计算中，您的代码花费了`0.84178680399782s`而如果您改成`String`,这只会花费`0.601265446995967s`.
虽然MD5的计算已经足够快，但用纯Swift style的类型看上去更cool一些。

Here is My code:
```
    var md5: String {
        if let data = base.data(using: .utf8, allowLossyConversion: true) {

            let message = data.withUnsafeBytes { bytes -> [UInt8] in
                return Array(UnsafeBufferPointer(start: bytes, count: data.count))
            }

            let MD5Calculator = MD5(message)
            let MD5Data = MD5Calculator.calculate()
            // 
            var md5String = String()
            for c in MD5Data {
                md5String += String(format: "%02x", c)
            }
            return md5String

//            let MD5String = NSMutableString()
//            for c in MD5Data {
//                MD5String.appendFormat("%02x", c)
//            }
//            return MD5String as String

        } else {
            return base
        }
    }
```

**Comment by onevcat** [comment]
It's cool to know that. Is it possible for you to send a pull request on it? Thanks!

**Comment by LimChihi** [comment]
Cool, I had sent a pull request.

**Comment by onevcat** [comment]
Merged. Thank you!
