### ISSUE TITLE
not showing these type of images. Can you show these?

### ISSUE THREAD

**Issue by AmeerChand** [onevcat/Kingfisher#638]
thumbnail = ["http://www.nust.edu.pk/PublishingImages/pdc-apr17-ws-1.jpg","http://www.nust.edu.pk/PublishingImages/pdc-apr17-ws-2.jpg","http://www.nust.edu.pk/PublishingImages/pdc-apr17-ws-4.jpg","http://www.nust.edu.pk/PublishingImages/pdc-apr17-ws-6.jpg","http://www.nust.edu.pk/PublishingImages/pdc-apr17-ws-7.jpg"]
![screen shot 2017-03-30 at 4 04 39 pm](https://cloud.githubusercontent.com/assets/26761721/24501379/a8c72e56-1562-11e7-8f59-d7db1535ef4b.png)

This is an array of url .
i am unable to get image just get placeholderimage.

imageV.sd_setImage(with: url, placeholderImage: imgFullView.image)

**Comment by onevcat** [comment]
I cannot open your urls (like http://www.nust.edu.pk/PublishingImages/pdc-apr17-ws-2.jpg) even in my browser. So it seems that your images are not served correctly?

**Comment by AmeerChand** [comment]
![screen shot 2017-03-30 at 5 27 33 pm](https://cloud.githubusercontent.com/assets/26761721/24504113/5e5aaeea-156e-11e7-9f8c-e70770491723.png)

see the url

**Comment by onevcat** [comment]
Maybe you need to turn off the ATS, if you are trying to load it in the demo project.

**Comment by AmeerChand** [comment]
ATS???

**Comment by IvanVelickovski** [comment]
@AmeerChand 
Maybe you haven't set transport security in .plist.

More here: http://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http

**Comment by AmeerChand** [comment]
i already seted the ATS but not working.
