### ISSUE TITLE
How does the cache work

### ISSUE THREAD

**Issue by LarsWith** [onevcat/Kingfisher#642]
I have a few thousands images which all have the same url except for a unique id
eg:
```
https://mydomain.imgix.net/1/thumb.jpg
https://mydomain.imgix.net/2/thumb.jpg
https://mydomain.imgix.net/3/thumb.jpg
https://mydomain.imgix.net/4/thumb.jpg
https://mydomain.imgix.net/5/thumb.jpg
etc..
```
I often load a image like this:
`https://mydomain.imgix.net/1/thumb.jpg`
But sometimes I also load the same image like this:
`https://mydomain.imgix.net/1/thumb.jpg?200x200`

Does Kingfisher cache the second url or not? Coz the almost are the same

**Comment by onevcat** [comment]
Yes, it will be recognized as a new and different image, and will be cached as the first kind. The url absolute string will be used as cache key by default.

**Comment by onevcat** [comment]
And I have to say, the GitHub issue is not a good place to ask questions.
