### ISSUE TITLE
Only final image is cached if you use processor. 

### ISSUE THREAD

**Issue by andrei-kuzma** [onevcat/Kingfisher#650]
Only final image is cached if you use processor. 
It means that if you use resizing or other image modifications it will be downloaded few times or you will not see the image if you use another processor and open screen in offline mode

It will be great if you can add option to store original image in cache and use it if needed
Algorithm should be like:
1. Get final image from cache, return image if exist
If failed
2. Get original image from cache, apply processor and store image in cache, return final image if exist
if failed
3.  Load image, store original image in cache, apply processor, store final image in cache return image

**Comment by onevcat** [comment]
It makes sense and definitely to be an improvement. I will consider to see whether we could add an option for it later. Thanks!

**Comment by AlexeyAfanasyev** [comment]
Hello guys,

Do you have any idea when to expect the feature in release?

Thank you.

**Comment by onevcat** [comment]
Implemented in 3.10.0
