### ISSUE TITLE
Image Cache is not purged properly when images are big

### ISSUE THREAD

**Issue by dimalexeev** [onevcat/Kingfisher#652]
App uses UIPageViewController. There are 5 pages. Each page is view controller with image 6000 × 3821. Image takes about 100 mb in memory after loading. It seems ok for these dimensions. (Although it's about 300 kb on disk). Image is set by kingfisher. Images are supposedly cached by kingfisher. This configuration causes a crash on iPhone 5 after memory usage got about 500 mb.

If I put `ImageCache.default.clearMemoryCache()` on viewDidLoad of each page view controller - everything works fine. Memory usage is about 250 mb and is not getting bigger.

How can I make it work without cache cleaning?

**Comment by onevcat** [comment]
I suggest you to set the allowed memory cache to a very small value to avoid memory cache for these huge image:

```swift
ImageCache.default.maxMemoryCost = 1
```

And for your case, maybe it worth to also set the image of image view to `nil` when the page did disappear from the screen, to make sure that only one image is being loaded into memory at one time.

**Comment by dimalexeev** [comment]
Yes, `ImageCache.default.maxMemoryCost = 1` makes it work as well as `ImageCache.default.clearMemoryCache()`.

I would like to find best solution.

Do I understand right that
1) Kingfisher uses two caches: disk, RAM?
2) ImageIO_PNG_data (category presented in Xcode memory debugger) is the RAM cache?

My file (6000 × 3821) is about 300 kb on disk and 100 mb in RAM (ImageIO_PNG_data). It's loaded from network by Kingfisher.

**Is there a way to make Kingfisher cache files on disk but do not cache them in memory?**

Or my understanding is completely wrong?

**Comment by onevcat** [comment]
1. Yes. However, by setting `maxMemoryCost` to 1, you have already disabled the memory cache.
2. It is not the cache. The system needs such memory to display a full bitmap image (approximate for a 32 bit png ~ 6000*3821*8bit*4channel = 733Mbits = 87MB).

**Comment by dimalexeev** [comment]
As I can see in memory debugger that _ImageIO_PNG_data_'s counters and total amount of memory are **somehow related** to Kingfisher memory cache: when I set` ImageCache.default.maxMemoryCost = 1 `_ImageIO_PNG_data_'s total memory and counters are constrained otherwise they are growing.

Thanks a lot for your answers. Now it's clear how to set up best configuration.
