### ISSUE TITLE
图片cookie设置

### ISSUE THREAD

**Issue by gujianxing** [onevcat/Kingfisher#659]
项目中用到图片验证码，需要设置 NSMutableURLRequest.HTTPShouldHandleCookies = YES
SDWebImage中可以设置SDWebImageHandleCookies选项。
但是Kingfisher中没有找到相关设置，是Kingfisher不提供次方法，还是有其它的写法，还请告知。

**Comment by onevcat** [comment]
You could use `ReqeustModifier` for it. Please read our [wiki](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending).

**Comment by gujianxing** [comment]
我们的验证是通过服务器的会话进行验证。我尝试在参数中加入请求头，但还是无法通过验证。

下面是我的代码：

let modifier = AnyModifier { request in
var r = request
for (key, value) in HttpHelper.headers {
r.setValue(value, forHTTPHeaderField: key)
}
return r
}

At 2017-04-26 17:46:57, "Wei Wang" <notifications@github.com> wrote:


You could use ReqeustModifier for it. Please read our wiki.
