### ISSUE TITLE
Images stop downloading or stop showing when the internet connection is low

### ISSUE THREAD

**Issue by htarwara6245** [onevcat/Kingfisher#66]
I have to create this issue because i was occurring that issue when my internet connection is low like using from edge speed.Please check my photos sir.
http://puu.sh/ipib2/b770a1f2c9.png ("&w=150" is requesting the image with the size 150x150)
http://puu.sh/ipidl/398e296c6b.png

As you see,there is two car images which are blank.I don't know it stop downloading or not showing because it doesn't give me any error from your library.

If you need to see my API,i can show you.It use protocol to return API results to my car list controller.
"latestCar[]" is the model array that give the cars information when the controller got the results from delegate method.

**Comment by onevcat** [comment]
Already answered in SO. http://stackoverflow.com/questions/30749494/why-my-image-is-not-display-immediately-after-downloaded/30749996#30749996
