### ISSUE TITLE
No more ".setImage(with: url".

### ISSUE THREAD

**Issue by FreudGit** [onevcat/Kingfisher#661]
Seem they are no more ".setImage(with: url". (the "with" param are for Resource)
Please update the cheatList

let uiButton: UIButton = //...
uiButton.kf.setImage(with: url, for: .normal, placeholder: nil, options: nil, progressBlock: nil, completionHandler: nil)

**Comment by onevcat** [comment]
The `URL` type is conforming `Resource` protocol, so it is fine to have a url as the first parameter.
