### ISSUE TITLE
ImageDownloaderSessionHandler doesn't implement 'didFinishCollecting metrics: URLSessionTaskMetrics' from URLSessionTaskDelegate

### ISSUE THREAD

**Issue by malaba** [onevcat/Kingfisher#662]
If want to measure a task the "didFinishCollecting metrics" delegate method need to be implemented in ImageDownloaderSessionHandler.

But the sessionHandler in ImageDownloader is "fileprivate" so we cannot hope to subclass or use extension...

I see no other way to measure the time it take for an image to be downloaded.

Any idea how to make those measurement ? Or why/when this delegate method could be supported ?

Thanks.

**Comment by onevcat** [comment]
The `ImageDownloaderSessionHandler` is an internal type which is used to handle and encapsulate the `ImageDownloader`. It is intended to be private to hide details from the framework users. A possible way for you would be using the `ImageDownloaderDelegate`. There is a [`imageDownloader(:didDownload:for:with:)`](http://onevcat.github.io/Kingfisher/Protocols/ImageDownloaderDelegate.html#/s:FP10Kingfisher23ImageDownloaderDelegate15imageDownloaderFTCS_15ImageDownloader11didDownloadCSo7UIImage3forV10Foundation3URL4withGSqCSo11URLResponse__T_) method you could use to measure a task. It does contain the processing duration from downloaded data to an image, however, it should be a good measurement if you are using the same processor (or the default processor, if you are not specifying a customized one).
