### ISSUE TITLE
Rename KingfisherOptionsInfoItem preloadAllGIFData

### ISSUE THREAD

**Issue by ShaharHD** [onevcat/Kingfisher#663]
`KingfisherOptionsInfoItem.preloadAllGIFData` is used in the code to indicate for backwards compatibility the need for reading the entire GIF to memory.

I'm suggesting, in order to allow for generic support for animated image formats to rename it to `KingfisherOptionsInfoItem.preloadAllAnimationData` and it's relevant counterparts (like `Collection.preloadAllGIFData`, while having the fallback to the old `.preloadAllGIFData` when processing options using an alias.

If I have a green light for this, I'll create the relevant PR for it.

**Comment by onevcat** [comment]
@ShaharHD Yes, I think that is a good direction. Thanks for it.

**Comment by ShaharHD** [comment]
@onevcat When trying to run the tests on Xcode I'm getting errors on `Kingfisher/Kingfisher-TestImages/Modified/Overlay/onevcat-overlay-red-07-mac.jpg: No such file or directory` Are some files missing from the git repo?

**Comment by ShaharHD** [comment]
Fixed with #664
