### ISSUE TITLE
Two AnimatedImageView with same gif play status

### ISSUE THREAD

**Issue by cpromise** [onevcat/Kingfisher#667]
#### What
I have two different ```AnimatedImageView```s and wanna make them share same gif information.
But I couldn't do that because ```Animator``` object in ```AnimatedImageView``` is a ```private``` property.

#### Reproduce
I designed a structure like below.
```FirstViewController``` - ```FirstImageView```
```SecondViewController``` - ```SecondImageView```
When touching ```FirstImageView```, ```FirstViewController``` pushes ```SecondViewController```.

And I wanna play gif in ```FirstImageView``` and ```SecondImageView``` seamlessly with custom push transition.
[not the same transition but similar example here](https://koenig-media.raywenderlich.com/uploads/2015/07/frontflip-slow.gif)

But I cannot provide any information to play gif to ```SecondImageView``` because many properties such as ```imageResource```, ```animator``` object are ```private```.

Are there any ways to make gif with the correct ```currentFrame```?

#### Other Comment

I really wanna use ```AnimatedImageView``` because of its memory performance.

#### What I Tried
I tried to share AnimatedImageView's layer.contents.
However, it didn't work because ```didMove()``` called when push transition finished.

**Comment by onevcat** [comment]
Hey,

How about just adding the FirstImageView to the SecondViewController? Like this:

```
// In first view controller
let vc = SecondViewController()
vc.imageView = FirstImageView
present(vc animated: false)

// In second view controller
var imageView: AnimatedImageView

override func viewDidLoad() {
    super.viewDidLoad()
    view.addSubview(imageView)
}
```

Maybe you also need to add it back to `FirstViewController` to correct superview when you come back from `SecondImageView`.
