### ISSUE TITLE
Setting headers to all requests

### ISSUE THREAD

**Issue by ldantona** [onevcat/Kingfisher#672]
Hi all,

Here's the suggested solution to set custom headers to the HTTP request: https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending 

Is there a centralised way to pass custom headers to all the image requests?
Otherwise we would have to modify all the occurrences of `setImage` in our project and be sure not to forget to handle this in any future image request, which is not reliable.

Many thanks,
DAN

**Comment by onevcat** [comment]
Not possible now. I am working on a solution (bringing back the `defaultOption` to `KingfisherManager`, which was once existing quite long ago) and will release an update for it later.

**Comment by ldantona** [comment]
@onevcat awesome, thank you!
Will it be released shortly? :)

**Comment by onevcat** [comment]
Implemented in #674

**Comment by onevcat** [comment]
@ldantona 
Sure, I am releasing it now.
