### ISSUE TITLE
3.9.0 breaks on Xcode Version 8.2.1 (8C1002)

### ISSUE THREAD

**Issue by r-a-o** [onevcat/Kingfisher#677]
Errors:
http://imgur.com/DwpH9VU
http://imgur.com/0w4o0Z4

**Comment by onevcat** [comment]
Umm,

Yes, we are using a feature of the latest Swift.

I'll try to fix it later. Before that, you could downgrade to 3.8.0, or even upgrade your Xcode to 8.3.

**Comment by onevcat** [comment]
Fixed in 3.9.1.
