### ISSUE TITLE
Stuck using AwaitKit and PromiseKit on Device

### ISSUE THREAD

**Issue by igordeoliveirasa** [onevcat/Kingfisher#679]
I got a class which has a method encapsulating KingfisherManager.shared.retrieveImage. This method returns a Promise<Image>. It always worked well. However, after I have started to use AwaitKit KingfisherManager.shared.retrieveImage it stucks, not trigering callback. 

Works on simulator but not on real device.

Thanks for the help in advance.

**Comment by onevcat** [comment]
@igordeoliveirasa In fact there were some discussion on it before and I made some un-merged change for it [here](https://github.com/onevcat/Kingfisher/commit/91eb29b1d6c2cce1ff6e83e919d6d516e91be2af). 

I am not familiar about AwaitKit and I am not sure what happens. But does change the delegate queue from `.main` to `nil` (just like in the commit above) solve your problem?
