### ISSUE TITLE
App Crash Frameworks/Kingfisher.framework/Kingfisher when run first time ?

### ISSUE THREAD

**Issue by kristoff2016** [onevcat/Kingfisher#681]

**Comment by onevcat** [comment]
Please add more information on this or there is little we could do.

**Comment by kristoff2016** [comment]
This file KingfisherManager.swift line 122:  forKey: resource.cacheKey I got error this point

**Comment by onevcat** [comment]
What's the crash log or error message? And how could you/I reproduce it?

Please follow the issue template to submit an issue, this could save a lot of time for both of us.
