### ISSUE TITLE
请问：Error Domain=com.onevcat.Kingfisher.Error Code=10000 

### ISSUE THREAD

**Issue by noear** [onevcat/Kingfisher#683]
Error Domain=com.onevcat.Kingfisher.Error Code=10000 

请问，这个提示是什么原因造成的。
哪里可看这些 code 值的意思？(它不太像http status code)

**Comment by noear** [comment]
我用的代码库版本为：3.6.2

**Comment by noear** [comment]
可用于测试的地图地址：https://nos.netease.com/comic/2d7e6a5df8f94debb857f593701cdbeb?NOSAccessKeyId=c92f74b0d48f4fb39271a1109da74cc2&Expires=1495173017&Signature=zQXKqX%2BtOD4bwRMD5s4E4e7CRTfQ2pJ7tF8y1CBRyOc%3D

**Comment by noear** [comment]
找到原因了，code=10000是转换失败的意思。
这个图片格式是：webp。所以转换失败。

可否支持webp 格式？

**Comment by onevcat** [comment]
Please use search before you open an issue. (and also keep the issue template)

https://github.com/onevcat/Kingfisher/search?q=webp&type=Issues&utf8=✓
