### ISSUE TITLE
下载图片时，内存突然升高导致app被杀

### ISSUE THREAD

**Issue by GorCat** [onevcat/Kingfisher#686]
喵神，祝安。

我有一个 tableView，每个 cell 有 0 ~ 9 张的图片，在 cell 将要展示的时候加载图片，但在频繁的滑动 tableView 的时候，CPU 和 Memory 会增高，最后被杀掉。

我使用 Kingfisher 3.2.4 ， maxMemoryCost 设置为 1。

 Allocation 收集在 iPhone6s 10.3.2 上运行的结果如下图显示，每次在杀掉前都走了 VM:ImageIO_jpeg_Data 和 VM:ImageIOGetCachedBlock，
  
![f59ea914-decc-42c4-a399-67ccc6415bcc](https://cloud.githubusercontent.com/assets/17355744/26356046/604581f8-3ffd-11e7-8fd6-92b13c116364.png)

是我使用 Kingfisher 不当而造成的问题么？

**Comment by GorCat** [comment]
这个问题可以 100% 复现

**Comment by onevcat** [comment]
There is little thing I could do unless I can reproduce the problem. How could I reproduce your issue? Anything like a sample project or some steps to crash the app would be a great help.

A common reason according to your description might be that you are using the full version of images as thumbnails (say the image view is only 50x50 but you are loading a 1000x1000 image into it).

**Comment by GorCat** [comment]
图片都是根据实际展示大小对分辨率进行了压缩的，那我先整理出一个 Demo，然后麻烦喵神有空的时候帮忙看一下了，整理好后我吧 Demo 发到你的邮箱哈 ~

**Comment by GorCat** [comment]
已发送 Demo。

**Comment by GorCat** [comment]
问题已解决，是我的问题

**Comment by ddffsg** [comment]
@GorCat 能说一下具体原因吗，我也遇到了类似的问题

**Comment by ddffsg** [comment]
如果我这边需要批量加载缩略图，但服务器那边只给了我完整图，我该怎么处理降低内存啊

**Comment by xiaoyao20084321** [comment]
> 如果我这边需要批量加载之上，但服务器那边只给了我完整图，我该怎么处理降低内存啊

同问， 你怎么解决的
