### ISSUE TITLE
 autoPlayAnimatedImage is not working properly?

### ISSUE THREAD

**Issue by commando24** [onevcat/Kingfisher#688]
I am using collectionview in that every cell have one AnimatedImageView and one label .For play or pause i am using user interaction.when user click on imageview gif will be played and on another click gif will be stopped. To perform that i am reloading cell on each click of user and isPlaying property is toggled.

```
class ViewController : UIViewController {
var isPlaying = false
func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
***
cell.animatedImageView.autoPlayAnimatedImage = isPlaying
}

func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
    isPlaying = !isPlaying
    collectionView.reloadItems(at: [indexPath])
  }
}

``` 
but animation is not stopped even if autoPlayAnimatedImage is false when cell appear.
NOTE : i have checked other issues but i am curious why this is not working ?

**Comment by onevcat** [comment]
`autoPlayAnimatedImage` is only used for playing it automatically when image set.

Maybe you need to use `stopAnimating()` to stop an animation?

**Comment by commando24** [comment]
Yeah i have tried stopAnimating and that's working.
