### ISSUE TITLE
[Xcode7] Use of undeclared type 'RawOptionSetType'

### ISSUE THREAD

**Issue by katopz** [onevcat/Kingfisher#69]
Xcode 7.0 beta (7A121l) breaking thing again :O

![screen shot 2558-06-25 at 15 51 26](https://cloud.githubusercontent.com/assets/97060/8350729/398fcb08-1b52-11e5-9142-c016795cb532.png)

Any hint?

**Comment by onevcat** [comment]
You can switch to the [swift-2.0](https://github.com/onevcat/Kingfisher/tree/swift-2.0) branch if you need to. It will not be merged into master until Swift 2.0 released.

**Comment by katopz** [comment]
I'm using `swift-2.0 branch` with `Xcode 7.0 beta (7A120f)` and it working fine,
but not `Xcode 7.0 beta (7A121l)` which just release tho.

I'm now switching back as workaround while wait.

**Comment by onevcat** [comment]
No, it should work on 7A121l. Maybe you need to clone it again.

**Comment by katopz** [comment]
Aw, now I know what going on, my Podfile need to be change from `swift-2` to `swift-2.0`
![screen shot 2558-06-29 at 11 18 20](https://cloud.githubusercontent.com/assets/97060/8400909/b1b700aa-1e50-11e5-8b7d-958781d36002.png)

It's working now, Thanks
