### ISSUE TITLE
How can I set the cache of expired time?

### ISSUE THREAD

**Issue by pangpingfei** [onevcat/Kingfisher#691]
Tks.

**Comment by onevcat** [comment]
Please read our wiki and issue template before ask such a question.

**Comment by pangpingfei** [comment]
I'm so sorry but I really have just done the reading and searching job before ask my question ... so i need …help

**Comment by onevcat** [comment]
What do you mean on the "cache of expired time"? Did you mean the expired time of cache? Is [this](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#set-longest-time-duration-of-the-cache-being-stored-in-disk) what you want?

**Comment by pangpingfei** [comment]
Maybe, I want to keep the image cache only when  clear it manually.

**Comment by onevcat** [comment]
> Set this value to a negative value (like -1) will make the disk cache never expiring.

**Comment by pangpingfei** [comment]
@onevcat Thank you very much!
