### ISSUE TITLE
Images applied RoundCornerImageProcessor should cache to disk as PNG format

### ISSUE THREAD

**Issue by JunyuKuang** [onevcat/Kingfisher#693]
I use `RoundCornerImageProcessor` to apply round rect for downloaded images like this:

```
extension UIImageView {
    
    func setProfileImage(withURL url: URL) {
        let profileImageSize = CGSize(width: 44, height: 44)
        let roundCornerImageProcessor = RoundCornerImageProcessor(
            cornerRadius: profileImageSize.width / 2, targetSize: profileImageSize)
        let options: KingfisherOptionsInfo = [
            .backgroundDecode, .processor(roundCornerImageProcessor), .scaleFactor(UIScreen.main.scale)]
        
        _ = kf.setImage(with: url, options: options)
    }
}
```

When an image is just downloaded or load from memory cache, it contains alpha channel as expect.
![expected](https://cloud.githubusercontent.com/assets/12454138/26617084/b643336c-4605-11e7-8764-a034514e59aa.png)

When an image is load from disk cache, it doesn't contains alpha channel. (load from disk as JPEG format, JPEG doesn't contains alpha channel)

![not expected](https://cloud.githubusercontent.com/assets/12454138/26617142/04226562-4606-11e7-8205-06d9af37a28e.png)

Set `ImageCache.default.pathExtension = "png"` makes no different.

**Proposal**
1. Cache all images that applied `RoundCornerImageProcessor` to disk as PNG format if possible.
2. When cache an image to disk, if `ImageCache.pathExtension.uppercased() == "PNG" (or "JPEG")`, then cache image as PNG (or JPEG) format. If cannot produce image data as path extension expected, fallback to default produce way (determine by original image format).

Thanks!
Jonny

**Comment by onevcat** [comment]
@JunyuKuang I agree with you on this. I'll try to implement this later.

Or do you want to submit a PR to implement it? 👻

**Comment by JunyuKuang** [comment]
I will try it. 😁

**Comment by ealymbaev** [comment]
I also need this urgently. Could you please merge this asap

**Comment by onevcat** [comment]
Merged.

**Comment by ealymbaev** [comment]
Does not seem to fix anything...

**Comment by JunyuKuang** [comment]
@ealymbaev you need to add an option to your image download request. Check `FormatIndicatedCacheSerializer`'s description.

**Comment by onevcat** [comment]
@ealymbaev 

As @JunyuKuang mentioned, this is a commit without changing current behavior. Instead of invasion of  default serializer by checking an processor option (which will introduce a coupling between these two parts), it is a good idea to leave it to framework users to determine how to store the images to disk.

Just pass `.cacheSerializer(FormatIndicatedCacheSerializer.png)` as an option to your setting methods with round corner process will do the trick.
