### ISSUE TITLE
The strange behavior of RAM.

### ISSUE THREAD

**Issue by alexsanderkhitev** [onevcat/Kingfisher#703]
Hello! I use Kingfisher to load images into the Card View (`UIView`), as in the tinder, I set the Kingfisher to cache the images to disk, but during the paging of the cards, the memory consumption increases dramatically from 39 megabytes to 247 and after a while again becomes 39, But the problem is that when the memory is freed, in the application for a second UI slows down (I think this is blocked by the main thread). This problem is similar to [this one.](https://github.com/onevcat/Kingfisher/issues/686). How can I fix it?
I set the settings for Kingfisher in `AppDelegate` in `didFinishLaunchingWithOptions`

```
fileprivate func setupKingfisherSettings() {
        let megabytes: UInt = 300
        ImageCache.default.maxDiskCacheSize = megabytes * 1024 * 1024
        ImageCache.default.maxMemoryCost = 1
    }
```

![1](https://cloud.githubusercontent.com/assets/12511909/26813116/04c159ac-4a8d-11e7-8bb1-a9a2079f2cfd.jpg)

**Comment by onevcat** [comment]
I've no idea about it. The problem in the link you gave turns out to be a memory leak caused by the framework user who kept adding views but never remove them. So it was not a Kingfisher issue.

And for your case, if you have multiple high resolution images to show, it is quite normally to take hundreds MB images. You could calculate it to see whether it is in reasonable size.

**Comment by alexsanderkhitev** [comment]
Hi @onevcat Yes, I also thought at first that this framework holds a lot of UIView and does not release them. I did an elementary test, commented out the code that is associated with Kingfisher in this UIView, and this behavior was no longer observed. What bothers me most is that during the release of memory, the main queue is blocked (as I think).

**Comment by onevcat** [comment]
Have no idea on this. Kingfisher should be doing nothing when the memory gets released for this case. Can you build a minimal sample to reproduce your issue so I could help to see where the problem is. Thanks!

**Comment by alexsanderkhitev** [comment]
@onevcat Well, I'll try to do it within two days.

**Comment by alexsanderkhitev** [comment]
@onevcat As I said earlier, I'll do the project a little later, but for now I'll show you this screenshot of Instruments, it can help you.
![2](https://cloud.githubusercontent.com/assets/12511909/26817150/78da7abc-4aa6-11e7-941a-3188ce3ebbb6.png)

**Comment by alexsanderkhitev** [comment]
@onevcat Hi again! I found a regularity when this happens. This jump in memory occurs when ImageCache extracts an image that is larger than 5 megabytes. I found it using debugPrint in this method diskImage, if the image is equal to or more than 5 megabytes, then there is a jump, if 4 megabytes, then everything is fine.

I'm testing on the iPhone 7, more than 74 gigabytes of free memory.

```
    func diskImage(forComputedKey key: String, serializer: CacheSerializer, options: KingfisherOptionsInfo) -> Image? {
        if let data = diskImageData(forComputedKey: key) {
            debugPrint("ImageCache data.count", data.count / 1024 / 1024)
            return serializer.image(with: data, options: options)
        } else {
            return nil
        }
    }
```

**Comment by alexsanderkhitev** [comment]
@onevcat At the moment I solved my problem, I wrote my Custom CacheSerializer, and I compress the images up to 3 megabytes.
