### ISSUE TITLE
Can you add an OnClick callback for your UIImageview extension?

### ISSUE THREAD

**Issue by alexliubj** [onevcat/Kingfisher#71]
When the image view is clicked, get response from your UIViewcontroller OnClick method which might be the delegate of KF UIImageview. 

Make the following way easier by just set an property of event in your kf options.

cell.cellImageView.tag = indexPath.row
        cell.cellImageView.userInteractionEnabled = true
        var tapGesture = UITapGestureRecognizer(target: self, action: "SomeMethod:")
        cell.cellImageView.addGestureRecognizer(tapGesture)
    
    func SomeMethod(recognizer:UIPanGestureRecognizer)
    {
        print (recognizer.view?.tag)
    }

**Comment by onevcat** [comment]
Hi, @alexliubj 
Thanks for the advice, but it should not be the responsibility of Kingfisher to handle such things like user interaction, since Kingfisher is an image download & cache framework.

You can implement your own with an extension for it, but it should not exist in Kingfisher.
