### ISSUE TITLE
Flicker when on reloadData() when using any processor

### ISSUE THREAD

**Issue by ealymbaev** [onevcat/Kingfisher#710]
I am using Kingfisher for loading images into my collection view.

When I am calling reloadData() - all images flicker. It only happens if I use processors.

Without using processors everything works as expected.

**Comment by onevcat** [comment]
Maybe try to add `.keepCurrentImageWhileLoading` as an option?

**Comment by ealymbaev** [comment]
This will not help as I am clearing both image and canceling request when the cell is being reused. Otherwise it could end up displaying wrong image while loading new one.

**Comment by ealymbaev** [comment]
Processors seem not to cache processed images in memory or something.

**Comment by onevcat** [comment]
It could also be a reason if the processor or setting method is not implemented correctly.

You could always check the source in the setting completion handler. May I know which processor you are using? And how did you use it?

**Comment by ealymbaev** [comment]
```
let resizeProcessor = ResizingImageProcessor(referenceSize: size, mode: .aspectFill)
let cornerRadiusProcessor = RoundCornerImageProcessor(cornerRadius: size.width * roundness)
let processor = resizeProcessor >> cornerRadiusProcessor

view?.kf.setImage(with: URL(string: url), options: [.cacheSerializer(FormatIndicatedCacheSerializer.png), .transition(.fade(0.2)), .processor(processor)], completionHandler: { [weak self] image, error, cacheType, imageUrl in
    if image == nil {
        self?.showPlaceholder()
    }
})
```

Also please note that I have tried removing all other options except processor (cacheSerializer and transition) and it flickers anyway. Only removing processors does help.

**Comment by onevcat** [comment]
Can not reproduce it in the sample project with your code, as long as the memory cache valid. It is normal if these images are not in memory cache since in Kingfisher the disk cache retrieving is an async operation (that's why `.keepCurrentImageWhileLoading` should work, and I am not sure what's your concern on it).

Could you confirm that your images are from memory cache? You could print it by adding `print(cacheType)` to your setting image completion handler.

**Comment by ealymbaev** [comment]
WITH processors:

 always "none"

WITHOUT processors:

memory
memory
memory
memory
memory
memory
memory
memory
memory
memory
memory
none
memory
memory
memory
memory
memory
disk
disk
memory
memory
memory
memory
none

**Comment by onevcat** [comment]
So what's the size and/or roundness? Could them be different time to time? The processor needs the same `identifier`  to locate the cache. Try to check your `processor.identifier` and make sure they are the same for the same image.

**Comment by ealymbaev** [comment]
As for `.keepCurrentImageWhileLoading`:

Here is my code:

```
override func bindView(toContainer container: UIView, storage: ViewStorage) {
    super.bindView(toContainer: container, storage: storage)

    view?.label.frame = bounds
    view?.label.font = UIFont.systemFont(ofSize: frame.size.width / 2.2)

    if let url = url, let processor = processor {
        view?.kf.setImage(with: URL(string: url), options: [.cacheSerializer(FormatIndicatedCacheSerializer.png), .transition(.fade(0.2))], completionHandler: { [weak self] image, error, cacheType, imageUrl in
            print(cacheType)
            if image == nil {
                self?.showPlaceholder()
            }
        })
    } else {
        showPlaceholder()
    }
}

override func unbindView(storage: ViewStorage) {
    view?.kf.cancelDownloadTask()
    view?.image = nil
    view?.backgroundColor = nil
    view?.label.isHidden = true

    super.unbindView(storage: storage)
}
```

As you can see `unbindView` sets image to `nil`. So when the imageView is reused - it will NOT have the previous image. And as you may know we cannot leave the image in the unbinded view because `collectionView` can use any random view from storage

**Comment by ealymbaev** [comment]
Here are the logs with identifiers:

```
com.onevcat.Kingfisher.ResizingImageProcessor((74.0, 74.0), aspectFill)|>com.onevcat.Kingfisher.RoundCornerImageProcessor(37.0)
com.onevcat.Kingfisher.ResizingImageProcessor((74.0, 74.0), aspectFill)|>com.onevcat.Kingfisher.RoundCornerImageProcessor(37.0)
com.onevcat.Kingfisher.ResizingImageProcessor((74.0, 74.0), aspectFill)|>com.onevcat.Kingfisher.RoundCornerImageProcessor(37.0)
com.onevcat.Kingfisher.ResizingImageProcessor((74.0, 74.0), aspectFill)|>com.onevcat.Kingfisher.RoundCornerImageProcessor(37.0)
com.onevcat.Kingfisher.ResizingImageProcessor((74.0, 74.0), aspectFill)|>com.onevcat.Kingfisher.RoundCornerImageProcessor(37.0)
com.onevcat.Kingfisher.ResizingImageProcessor((74.0, 74.0), aspectFill)|>com.onevcat.Kingfisher.RoundCornerImageProcessor(37.0)
none
none
none
none
none
none
```

**Comment by onevcat** [comment]
It seems fine to me. :(

So I have no idea on why the cache does not work for you now. Maybe if you could build a simple sample which can reproduce it then I'd like to dig in.

**Comment by ealymbaev** [comment]
Ok, just give me some time. I will provide a repo link here soon

**Comment by onevcat** [comment]
@ealymbaev Is it possible that your issue related to this?

**Comment by ealymbaev** [comment]
@onevcat Yes, seems so. Any quick fix for this?

**Comment by onevcat** [comment]
Will release a new version later, maybe in several hours. Now I am rushing home :]

**Comment by ealymbaev** [comment]
Thanks... will be waiting for it. And hope it will fix the issue

**Comment by onevcat** [comment]
Please try the latest version 3.10.2 to see whether it gets resolved.

**Comment by ealymbaev** [comment]
@onevcat I have tried the latest version. But it does not solve the issue. Here is the new log:

```
memory
none
memory
memory
memory
memory
memory
memory
memory
none
none
memory
memory
memory
memory
none
none
memory
none
none
none
memory
memory
memory
memory
none
none
none
memory
none
none
none
```

Please note that I have tried to reopen controller several times and it gives the same log every time.

**Comment by onevcat** [comment]
So no idea on it now. 
I'll wait for your sample project for a further step.
