### ISSUE TITLE
Crash when loading some image with version 3.10.3

### ISSUE THREAD

**Issue by CK11FOR333** [onevcat/Kingfisher#726]
I want to show wallet passes in my APP with image effect but some passes may cause crash.

***Terminating app due to uncaught exception 'NSInvaildArgumentException', reason: '~[CIContext initWithOptions:]: unrecognized selector sent to instance 0x17020c0a0'
<img width="603" alt="screen shot 2017-07-10 at 17 16 59" src="https://user-images.githubusercontent.com/12655810/28011359-9fd905a8-6594-11e7-9781-e427eca18dcc.png">

**Comment by onevcat** [comment]
It's a bug of iOS 8. I am not quite willing to fix it by introducing an Objective-C layer.
I guess it could be a good chance to upgrade the deploy target to iOS 9 now... :[

**Comment by CK11FOR333** [comment]
Yes, I found it on iOS 8.3 at the beginning, and also on iOS 10.3.2 later. Both target is 8.2. This is MrBrown App and I will consider it. Thanks a lot 😊
