### ISSUE TITLE
Cheat sheet is not up to date

### ISSUE THREAD

**Issue by valdirunars** [onevcat/Kingfisher#727]
### Issue Description
Cheat sheet is not up to date
#### What

Use of unresolved identifier 'FormatIndicatedCacheSerializer'

yet the cheat sheet recommended using it when creating a RoundCornerImageProcessor

**Comment by caiovidaln** [comment]
For those who have this problem as I do, just upgrade to the latest version of Kingfisher that will solve.

**Comment by valdirunars** [comment]
Yeah seemed like there was a commit in cheat sheet that went through, ahead of the source.

Thanks
