### ISSUE TITLE
Changing Priority of download-dataTask after it started

### ISSUE THREAD

**Issue by mheicke** [onevcat/Kingfisher#73]
Hi,
since I prefetch a lot of images, but want to show a couple of images as fast as possible, I just looked into prioritization of Kingfisher. Looks quite good to me, besides one point: it's not possible to change the priority of a download, once it's started.

As an example: I start to download the images cat[1-100].png and dog[1-100].png. They are all priorized as low since its only prefetching. Now I open the cat view which has a tableView with cat images. So I want to set a couple of images (of the visible cells) via UIImageViews kf_setImageWithURL. Since there are 200 images currently downloading, I need a higher prioritization for the images cat1.png - cat5.png. 

But since they are part of the batch download of the prefetching, their url is already in self.fetchLoads in ImageDownloader and hence the started-closure is not called again in line 214 and "task.priority" is not changed to default, although the options dictionary in the downloadImageWithURL-call does not contain the lowPriority option.

A solution could be to attach the downloadTask to the ImageFetchLoad. In this case, it would be also possible to provide auto-priorisation (the more callbacks are attached to the ImageFetchLoad, the higher the priority could be. Some rewrite of ImageDownloader would be needed.

What do you think?

Best regards,
Matt

**Comment by schickling** [comment]
This would be a huge improvement! :+1:

**Comment by schickling** [comment]
Also is there a reason for just toggling between `NSURLSessionTaskPriorityLow` and `NSURLSessionTaskPriorityDefault`? The priority parameter is a `float` ranging from 0 to 1. This flexibility shouldn't be hidden.

**Comment by schickling** [comment]
![screen shot 2016-01-02 at 12 25 26](https://cloud.githubusercontent.com/assets/1567498/12074319/f2f88d20-b14b-11e5-8a1f-47554fdac9ae.png)

**Comment by ejoebstl** [comment]
Yes, I a agree. That feature would be very useful.

**Comment by onevcat** [comment]
The original implementation hides the `Float` detail and tries to make things simpler. But I guess it is reasonable to give users more control on it by setting a value for the priority. However, changes on it might means API breaking. I will take a look to see if we could mark current `lowPriority` option as deprecated and introduce a new way to set initial priority for a download task soon.

And for changing the priority on air when downloading, the downloader APIs (as well as the image view extension APIs) are returning a image task. We could just expose the `priority` property of task object to support changing it after download task started. It will be implemented soon in next major version.

**Comment by schickling** [comment]
Really looking forward to this improvement!

**Comment by onevcat** [comment]
Implemented in #194

**Comment by schickling** [comment]
Nice! Can't wait until it gets released!

**Comment by onevcat** [comment]
It will be released later as a part of version 2.0.0.

**Comment by schickling** [comment]
Great!
