### ISSUE TITLE
isImageCached CacheCheckResult redundant fields

### ISSUE THREAD

**Issue by ryango** [onevcat/Kingfisher#733]
Thanks for the library. A suggestion:

Right now ImageCache.isImageCached returns a CacheCheckResult which has a bool isCached and an optional enum which has 3 cases - disk, memory, none

isCached == false is covered by the none case

CacheCheckResult should just return a CacheType - right now to deal with the result you check the isCached, unwrap the enum, and then still have to deal with the .none case

if just returning the enum can just deal with the 3 cases

**Comment by onevcat** [comment]
I think you are right on this. I'll give it a change later. However, instead of breaking the current API, I prefer to add a new one and mark current one as deprecated.

Thanks for the suggestion!

**Comment by onevcat** [comment]
Fixed in #741 and will be contained in Kingfisher 4.

**Comment by ryango** [comment]
sweet!
