### ISSUE TITLE
Customize the indicator while downloading an image from web

### ISSUE THREAD

**Issue by JackLChen** [onevcat/Kingfisher#734]
hi, @onevcat , it's a great honour to use such a wonderful repository--Kingfisher first.  I come across an issue in the process of using it,  when I'd like to customize the indicator as you say in **Cheat Sheet**,  I found it useless for setting its **center** no matter how I set the value for CGPoint. I hope to make it center like the system indicator setting: `imageView.kf.indicatorType = .activity` which can show it in the center of UIImageView.As a matter of fact, It is always located in the lower right corner. My codes are as follows:

```
struct CustomIndicator: Indicator {

    var viewCenter: CGPoint
    
    var view: IndicatorView = UIView()
    
    func startAnimatingView() {
        view.isHidden = false
    }
    
    func stopAnimatingView() {
        view.isHidden = true
    }
    
    init() {
        view.backgroundColor = UIColor.magenta
        
        // This is no use no matter how I set values for center, the indicator is always located in the lower right corner for self.view
        viewCenter = CGPoint(x: 10, y: 10)
        print(viewCenter)
    }
}

```
how can I do for this, thanks a lot in advance.

**Comment by JackLChen** [comment]
[IndicatorScreenshot](http://ww1.sinaimg.cn/large/0065qDengy1fhv0gq2f0uj309d0h7t9b.jpg)

**Comment by onevcat** [comment]
Basically, the `viewCenter` is only for internal using as a way to make indicator generalized. There is already a default implementation for it to center with the image view it attaching. So you could leave the implementation for `viewCenter` as its default.

**Comment by JackLChen** [comment]
Thank you very much. Sorry,  I always set `viewCenter` when comforming to `Indicator` protocol, resulting in a wrong showing.  Maybe you can declare `viewCenter` as `private` when it's already provided a default implement inside. Anyhow, thanks for the trouble again.

**Comment by onevcat** [comment]
We wish we could but it is not permitted to declare a internal thing for public protocol. :[

**Comment by JackLChen** [comment]
ohh, it may be a pity for swift to do so.
