### ISSUE TITLE
When I use Carthage update Kingfisher to 3.10.4,It doesn't work.

### ISSUE THREAD

**Issue by ceeyang** [onevcat/Kingfisher#740]
Last hour,I had updated Kingfisher to `3.10.4`.
When I run my project.All of the imageview where i use `kf.setImage` just show me a clear view.

This is my code   
```swift
        let defaultImage = UIImage(named: "Person_Avator")
        let resource = NSURL(string:"http://pic.58pic.com/58pic/16/00/52/11J58PICD3S_1024.jpg") as? Resource
        mAvatorImageView = UIImageView()
        mAvatorImageView.layer.masksToBounds = true
        mAvatorImageView.image = defaultImage
        //when i use this method,it show me a clear view
        //mAvatorImageView.kf.setImage(with: resource)
        //When i use this method,it will show me the defaultImage
        mAvatorImageView.kf.setImage(with: resource, placeholder: defaultImage, options: nil, progressBlock: nil, completionHandler: nil)
        let tap = UITapGestureRecognizer(target: self, action: #selector(avatorImageClick))
        mAvatorImageView.addGestureRecognizer(tap)
        mAvatorImageView.layer.cornerRadius = 65/2
        backgroundImage.addSubview(mAvatorImageView)
        mAvatorImageView.snp.makeConstraints { (make) in
            make.left.equalTo(backgroundImage.snp.left).offset(20);
            make.bottom.equalTo(backgroundImage.snp.bottom).offset(-20);
            make.size.equalTo(CGSize(width: 65, height: 65));
        }
```
SystemInfo:
        
        MacOS:Version 10.13 Beta (17A315i)

        Xcode:Version 9.0 beta 4 (9M189t)

        Carthage:Version 0.23.0

        Swfit:Version 4.0

**Comment by onevcat** [comment]
The only change from 3.10.3 to 3.10.4 is the indicator size, so it should do nothing about the image loading and setting itself.

What is the previous version you were using? Does it work without issue in the same environment?

**Comment by ceeyang** [comment]
Thanks for reply.

**Comment by ceeyang** [comment]
I updated my MacOS on the same day,The previous version is 3.10.3.
And I don't sure isn't worked well on 3.10.3 in my environment.
Is there some suggestions to find the problem?

**Comment by ceeyang** [comment]
I use built a new project with carthage use Kingfisher 3.10.4.The same proble happend.
```swift
import UIKit
import Kingfisher

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        let imageView = UIImageView(frame: CGRect(x: 20, y: 20, width: 100, height: 100));
        imageView.backgroundColor = UIColor.lightGray;
        view.addSubview(imageView)
        let url = NSURL(string:"http://pic.58pic.com/10/73/59/48bOOOPICe2.jpg")
        imageView.kf.setImage(with: url as? Resource)
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}

```

**Comment by ceeyang** [comment]
When I use `cocoapods ` with the version 3.10.4,I found the problem.
```swift
        guard let resource = resource else {
            base.image = placeholder
            setWebURL(nil)
            completionHandler?(nil, nil, .none, nil)
            return .empty // I made a breakpoint here,it run to this breakpoint,return me a empty
        }
```
Is there problem in my code ?
```swift
        let url = NSURL(string:"http://pic.58pic.com/10/73/59/48bOOOPICe2.jpg")
        imageView.kf.setImage(with: url as? Resource)
```

**Comment by ceeyang** [comment]
OK,I find the reason,I havd used the `NSURL`,When I change it with `URL`,it worked.
Thanks.
But I think you should add  support  for `NSURL`,or let people know should use `URL`.

**Comment by onevcat** [comment]
The `NSURL` should not be able to cast to `Resource`, it should be already assured by compiler.

**Comment by ceeyang** [comment]
When I use `NSURL`,I built it complete.
Is this a bug on my `Xcode version(Version 9.0 beta 4 (9M189t))`.

**Comment by onevcat** [comment]
You are doing this kind of force conversion:

```swift
url as? Resource
```

You may need to know what does this mean before you do it. Instead, `URL` already conforms to `Resource, so there is no need to do such thing for it.

**Comment by ceeyang** [comment]
ahahaha,thanks for your patience.
