### ISSUE TITLE
Could you please add ImageProcessor with border width & color?

### ISSUE THREAD

**Issue by aloveric** [onevcat/Kingfisher#745]
@onevcat 非常好用~~
亲，可以在默认的图片处理加一个边框的么？参数有宽度width和颜色color的，谢谢啦~

**Comment by onevcat** [comment]
Maybe it is no need to use a processor for adding a image border, since you could do it easily by using the image view layer.

**Comment by s4cha** [comment]
+1 @onevcat adding a border through the layer api is fine but it can be very detrimental to the perfomances in a tableview context.
Haven't the time to look at it right now unfortunately but that would be a great addition :)

**Comment by onevcat** [comment]
@s4cha Thanks for the suggestion. Maybe we could reconsider this.

**Comment by onevcat** [comment]
Done in #1753
