### ISSUE TITLE
UIImage.kf.tinted(with: .white) makes full image white

### ISSUE THREAD

**Issue by chanonly123** [onevcat/Kingfisher#748]
UIImage.kf.tinted(with: .white) makes full image white in spite of transparency in image

**Comment by basememara** [comment]
I don't think the tinted processor works as one would expect. In the source code, it says it only works with CG-based images. For everything else, I had to do the following to get tinted colours to work:

```
UIImageView.kf.setImage(
  with: urlResource,
  completionHandler: { (image, error, cacheType, imageUrl) in
    self.tintColor = myTintColor
    self.image = self.image?.withRenderingMode(.alwaysTemplate)
  }
)
```

**Comment by onevcat** [comment]
Maybe you need `BlendImageProcessor`?
