### ISSUE TITLE
ImageView not loading for http urls

### ISSUE THREAD

**Issue by coder360** [onevcat/Kingfisher#749]
I initially wrote about image not loading but, now I have found that only https urls load and not http. Would you know if that is the case?

Thank you

**Comment by onevcat** [comment]
Please check whether you are trying to access with an image resource with "http" scheme. If so, you need to switch to "https" or disable ATS in your Info.plist.

**Comment by coder360** [comment]
Thanks for your response. Yes, after a day worth of scrambling, I had stumbled on to this observation that it worked for https scheme and not http. ATS is no longer optional in iOS 10 but, that is fine. I will go ahead and ensure the use of https.
