### ISSUE TITLE
GIF support

### ISSUE THREAD

**Issue by felipecarreramo** [onevcat/Kingfisher#75]
Do you have Gif  Support?

**Comment by lizhijun** [comment]
+1

**Comment by AbelSu131** [comment]
？

**Comment by huynhphan89** [comment]
+1

**Comment by alexdd55** [comment]
+1

**Comment by onevcat** [comment]
I will add it later.

**Comment by yurijmi** [comment]
@onevcat written you an email about it yesterday.

**Comment by onevcat** [comment]
Added in #129

**Comment by onevcat** [comment]
[Version 1.7.0](https://github.com/onevcat/Kingfisher/releases/tag/1.7.0) contains support for GIF.

**Comment by kean** [comment]
> Version 1.7.0 contains support for GIF.
