### ISSUE TITLE
How to remove all caches of an image?

### ISSUE THREAD

**Issue by ivanstang** [onevcat/Kingfisher#751]
I resized an image and cached it as its original size:
`let processor = ResizingImageProcessor(referenceSize: CGSize(width: 80, height: 80))            
self.imageView.kf.setImage(with: url, options: [ .processor(processor), .cacheOriginalImage])`
And I found there are 2 cache files in the cache directory. One is the original image and another is the resized image.
I want to remove all 2 cached files when the image was changed:
`ImageCache.default.removeImage(forKey: url)`
But it doesn't work, the cached files are still in cache directory.
How to remove them correctly?

**Comment by onevcat** [comment]
You need to also pass the `processorIdentifier` to [this API](http://onevcat.github.io/Kingfisher/Classes/ImageCache.html#/s:FC10Kingfisher10ImageCache11removeImageFT6forKeySS19processorIdentifierSS8fromDiskSb17completionHandlerGSqFT_T___T_).

**Comment by ivanstang** [comment]
@onevcat Thanks, it can work.

Another question: 
Is there a way to remove all cached images produced by processors? Because I have some different processors in different view controllers. I need to remove them at one point.

**Comment by onevcat** [comment]
There is no API to remove cached images for a certain processor. However, you could use the targetCache option to specify your own customized cache and make Kingfisher store the images there. Then you are able to clear that whole cache.
