### ISSUE TITLE
batch resize

### ISSUE THREAD

**Issue by anddygon** [onevcat/Kingfisher#759]
我不知道这个标题是否合适。
有这样一个需求，从server下载图片(https://www.example.com/image_cache/resize/1000x1000/image/catalog/xxx.jpg)，这是一张很大的图假设为1000*1000,这张图要在app很多地方用到，唯一不同的就是尺寸，可能需要100*100,200*200...
对应的url可能是
https://www.example.com/image_cache/resize/100x100/image/catalog/xxx.jpg，https://www.example.com/image_cache/resize/200x200/image/catalog/xxx.jpg
我用ResizingImageProcessor处理
传入多个ResizingImageProcessor
ResizingImageProcessor(referenceSize: CGSize(width: 100, height: 100), mode: ContentMode.aspectFit)
ResizingImageProcessor(referenceSize: CGSize(width: 200, height: 200), mode: ContentMode.aspectFit)
但是源码实现是同类型的Processor只取最后一个，我知道这样的实现是合理的，但是上面的需求也是很常见的，现在我想出的有2中方案，
1.实现一个类似的ImageCache的retrieve方法 当需要一张特定尺寸图片是就去cache找更大尺寸的，找到后进行resize，然后存储，否则下载并存储
2.在setImage的completionHandler中生成对应的一批小图片并存储
但是这2个方案都不够优雅，请问我该怎么更优雅的实现呢？

**Comment by onevcat** [comment]
Maybe this could help?

https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#cache-original-image-while-using-a-processor

**Comment by anddygon** [comment]
非常感谢喵神的及时回复

**Comment by anddygon** [comment]
非常感谢喵神及时回复
我有完整看过
![image](https://user-images.githubusercontent.com/7263780/29992817-addcdc66-8fd7-11e7-89c9-d54cd8383962.png)
期望的结果是原图，resize(100*100),resize(200*200)都会被存储起来，但是现在的结果只会存储原图和resize(200*200)

**Comment by onevcat** [comment]
You should set different images in different images views.
