### ISSUE TITLE
is it possible setting second unit of expiration date ??

### ISSUE THREAD

**Issue by XOneto9** [onevcat/Kingfisher#762]
Hi, I'm David.
It's very nice module of cache!

I searched on this title at google or issue pages.

first of all, I was setting `maxCachePeriodInSecond = 10` because of test, then I want to remove data from my local disk. but after 10 second it still alive in my disk.

At the page of download image page
```
var cache = ImageCache(name: "myReviewCache")
cache.maxCachePeriodInSecond = 10

let resource = ImageResource(downloadURL: URL(string : imgUrl)!, cacheKey: imgUrl)
cell.reviewImage.kf.setImage(with: resource, options : [.targetCache(cache)])
```

After I'm going other page . and then access `var cache = ImageCache(name: "myReviewCache")`.
```
let a = cache.isImageCached(forKey: "www.example.com/test.jpeg")
 print(a)
```

`CacheCheckResult(cached: true, cacheType: Optional(Kingfisher.CacheType.disk))
`
So, I don't know is it right way to expiration date..

**Comment by onevcat** [comment]
The `maxCachePeriodInSecond` does not mean the cache file could be removed just after the period. It is a reference duration for Kingfisher to determine whether a cached file could be removed or not. To actually remove the expired cache, you need to switch your app to background or call `cleanExpiredDiskCache` on `ImageCache`.

**Comment by XOneto9** [comment]
@onevcat Thanks'
hum,, in other words, just checking what the saved cache is removed or not?
the store is not removed, just check cache file for reference of doing other work??

is that??

**Comment by onevcat** [comment]
I am not sure I could understand your comment.

In other words, `maxCachePeriodInSecond` does not play as a timer to count down for removing the cached files. It defines a reference date that Kingfisher could check with it when removing cache.

**Comment by XOneto9** [comment]
@onevcat Ok..
Thank you!

eventually, If I should remove cache, Only one to use `cleanDiskCache` function. :)

Ok, I got it thanks
