### ISSUE TITLE
Use of undeclared type 'Placeholder'

### ISSUE THREAD

**Issue by sergeymild** [onevcat/Kingfisher#765]
<img width="938" alt="screen shot 2017-09-05 at 7 03 27 pm" src="https://user-images.githubusercontent.com/3685209/30070698-f932f2da-926c-11e7-95aa-c213b38fbdb3.png">

**Comment by onevcat** [comment]
It was a protocol added in the latest version. Please try to update you Kingfisher as well as clean your project.

**Comment by sergeymild** [comment]
thanks

**Comment by SVA7** [comment]
I can't fix it 
I try to update  Kingfisher well and clean my project 
But its not fix it

**Comment by onevcat** [comment]
Please make sure you have installed correct version of Kingfisher. If you are using CocoaPods, also make sure you have updated the pod spec repos as well.
