### ISSUE TITLE
Swift 4 error

### ISSUE THREAD

**Issue by djardon** [onevcat/Kingfisher#779]
Hi,

With Kingfisher version 4.01 have an compiler error in the next Struct with Swift 4:

`    public struct Filter {
    
    let transform: Transformer

    public init(tranform: @escaping Transformer) {
        self.transform = tranform
    }
    
    /// Tint filter which will apply a tint color to images.
    public static var tint: (Color) -> Filter = {
        color in
        Filter { input in
            let colorFilter = CIFilter(name: "CIConstantColorGenerator")!
            colorFilter.setValue(CIColor(color: color), forKey: kCIInputColorKey)
            
            let colorImage = colorFilter.outputImage
            let filter = CIFilter(name: "CISourceOverCompositing")!
            filter.setValue(colorImage, forKey: kCIInputImageKey)
            filter.setValue(input, forKey: kCIInputBackgroundImageKey)
            return filter.outputImage?.cropping(to: input.extent)
        }
    }
    
    public typealias ColorElement = (CGFloat, CGFloat, CGFloat, CGFloat)
    
    /// Color control filter which will apply color control change to images.
    public static var colorControl: (ColorElement) -> Filter = { arg -> Filter in
        let (brightness, contrast, saturation, inputEV) = arg
        return Filter { input in
            let paramsColor = [kCIInputBrightnessKey: brightness,
                               kCIInputContrastKey: contrast,
                               kCIInputSaturationKey: saturation]
            
            let blackAndWhite = input.applyingFilter("CIColorControls", withInputParameters: paramsColor)
            let paramsExposure = [kCIInputEVKey: inputEV]
            return blackAndWhite.applyingFilter("CIExposureAdjust", withInputParameters: paramsExposure)
        }
        
    }
}`

Specifically, with the following lines of code

`return filter.outputImage?.cropping(to: input.extent)

            let blackAndWhite = input.applyingFilter("CIColorControls", withInputParameters: paramsColor)

            return blackAndWhite.applyingFilter("CIExposureAdjust", withInputParameters: paramsExposure)`

**Comment by onevcat** [comment]
Please check https://github.com/onevcat/Kingfisher/pull/777 and https://github.com/onevcat/Kingfisher/issues/772
