### ISSUE TITLE
Found on crashlytics

### ISSUE THREAD

**Issue by jovanpreet** [onevcat/Kingfisher#782]
Hi I found a crash on crashlytics. 
EXC_BAD_ACCESS
Please find the attached crash.
[com.fikra.myu_issue_280_crash_903ffa1cf0c647aabf6a2e0e8d44ea94_7b14495ba36911e79a2456847afe9799_0_v2.txt](https://github.com/onevcat/Kingfisher/files/1339543/com.fikra.myu_issue_280_crash_903ffa1cf0c647aabf6a2e0e8d44ea94_7b14495ba36911e79a2456847afe9799_0_v2.txt)

**Comment by onevcat** [comment]
Not sure what what happened on this and it seems to be a crash in Swift `reverse` extension method on `Sequence`. I believe it should not be an issue of Kingfisher and there is actually little we could do with it.
