### ISSUE TITLE
Updating for Swift 4

### ISSUE THREAD

**Issue by asaxionis** [onevcat/Kingfisher#783]
I am having issues with the Swift 4 update, I cannot install through pods for 4.0, and when I continue to use 3.2, I am getting this error in the console for the code:

override func shouldPreloadAllGIF() -> Bool {
        return false
    }

& the error says "Declarations from extensions cannot be overridden yet" 

&& When I try to install pods for Kingfisher 4.0, i get this error

[!] Unable to satisfy the following requirements:

- `Kingfisher (~> 4.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Kingfisher (~> 4.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by onevcat** [comment]
As indicated, you need to run `pod repo update` before `pod install` or `pod update` to get the latest version.
