### ISSUE TITLE
图片加载失败

### ISSUE THREAD

**Issue by RtzX** [onevcat/Kingfisher#784]
https://imasports.oss-cn-shanghai.aliyuncs.com/ProductPicture/d93a8a3bcb592763d4e0972294adee2ax450x300x19.jpg

这个地址的图片加载不出来 什么情况? 而且Safari 浏览器是打不开图片的.. 但是谷歌浏览器可以打开...
版本 Kingfisher', '~> 4.1.0'

**Comment by onevcat** [comment]
WebP is not built-in supported in Kingfisher. See our [FAQ page](https://github.com/onevcat/Kingfisher/wiki/FAQ#can-i-load-some-special-image-format-like-webp) for more.
