### ISSUE TITLE
Declarations from extensions cannot be overridden yet

### ISSUE THREAD

**Issue by rohanvasishth** [onevcat/Kingfisher#787]
I recently upgraded my project from swift 3 to swift 4 and during the migration, the kingfisher has been given me two warnings (Declarations from extensions cannot be overridden yet) for the following lines of code:

   override func shouldPreloadAllAnimation() -> Bool {
        return false
    }

extension AnimatedImageView {
    // This is for back compatibility that using regular UIImageView to show GIF.
    @available(*, deprecated, renamed: "shouldPreloadAllAnimation")
    override func shouldPreloadAllGIF() -> Bool {
        return false
    }
}

The error shows up in the override function lines.

**Comment by onevcat** [comment]
Kingfisher 3.x -> Swift 3.1
Kingfisher 4.x -> Swift 3.2 & Swift 4
