### ISSUE TITLE
upgraded my project from swfit 3 to swift 4, Error in version 4.1.0 and Xcode 9.0

### ISSUE THREAD

**Issue by turkeyaa** [onevcat/Kingfisher#788]
I recently upgraded my project from swift 3 to swift 4 and during the migration, the kingfisher has been given me one error in this:

protocol IntegerPropertyProtocol: Integer, _BuiltInBasicType {
    init?(_ text: String, radix: Int)
    init(_ number: NSNumber)
}

Xcode Prompt solution：'Integer' has been renamed to 'BinaryInteger'/Replace 'Integer' with 'BinaryInteger'

**Comment by onevcat** [comment]
Kingfisher 3.x -> Swift 3.1
Kingfisher 4.x -> Swift 3.2 & Swift 4

And I don't think the code snippet you pasted comes from Kingfisher. There should be no such code in this repo.

**Comment by turkeyaa** [comment]
This error is in HandyJSON. Not here, I'm Sorry...
