### ISSUE TITLE
How can I know if an image url have cached ?

### ISSUE THREAD

**Issue by ZackZheng2014** [onevcat/Kingfisher#789]
I want to know if an image url have cached.

Only the API below may work.
`open func retrieveImageInMemoryCache(forKey key: String, options: KingfisherOptionsInfo? = default) -> Image?

open func retrieveImageInDiskCache(forKey key: String, options: KingfisherOptionsInfo? = default) -> Image?
`

But if I dont's know the key used in cache ?

######

I found the extension of URL.

extension URL : Resource {

    /// The key used in cache.
    public var cacheKey: String { get }

    /// The target image URL.
    public var downloadURL: URL { get }
}

But what's the value of cacheKey when url not in cache ? 
Should it be optional ?

**Comment by ZackZheng2014** [comment]
I found the extension of URL.

extension URL : Resource {

    /// The key used in cache.
    public var cacheKey: String { get }

    /// The target image URL.
    public var downloadURL: URL { get }
}

**Comment by onevcat** [comment]
You could use this: https://github.com/onevcat/Kingfisher/blob/635dbf4b9c21d00c42bcdb6dfae876f10ed5a59a/Sources/ImageCache.swift#L557

**Comment by ZackZheng2014** [comment]
@onevcat I don't know the key...

**Comment by onevcat** [comment]
You could just use `cacheKey` of your URL for it.
