### ISSUE TITLE
Crash since today.

### ISSUE THREAD

**Issue by cikpis** [onevcat/Kingfisher#792]
Hi guys, I'm having this weird crash with your SDK on iOS 11 Xcode 9.0.1. I just updated Xcode and not sure if it is related.

Code used:
```
let scale = UIScreen.main.scale
let resizingProcessor = ResizingImageProcessor(referenceSize: CGSize(width: width * scale, height: width * scale))
imageView.kf.indicatorType = .activity
imageView.kf.setImage(with: URL(string: url),
                      options: [.processor(resizingProcessor)],
                      completionHandler: { [ weak self] image, error, cacheType, imageURL in
                          // do somethig
                      }
)
```
Crash:
```
Signal: SIGABRT (signal SIGABRT)
Terminated due to signal 6
```

Any clue?

**Comment by onevcat** [comment]
No idea. Maybe it is worth to try a full clean or reinstall. BTW, which version of Kingfisher you are using?

**Comment by cikpis** [comment]
4.1.1 and of course I tried full clean/reinstall

I'm using right now another library and all seems ok.

**Comment by cikpis** [comment]
Why did you close the issue?

**Comment by onevcat** [comment]
Cannot reproduce and of course it is not an issue in Kingfisher.

You're using right now another library and all seems ok. 

So I think there is no need to discuss more this unless someone else encounter the same issue. If anyone has the same problem and has more information to share, please reopen it.

**Comment by cikpis** [comment]
When I said I'm using another library I meant that I tried my  code with another one and all is ok so the problem seems in KF. 

Did you try it with Xcode 9.0.1?

**Comment by onevcat** [comment]
Yes. I did.

Signal 6 comes from an abort and if you cannot use any other methods in Kingfisher as well, it could indicate that you are failing on loading (dlopen) the framework. Is there any other logs besides of the signal number?

**Comment by cikpis** [comment]
Unfortunately no. I'll remove all cocoa pods and reinstall them again and see if it is solved.
