### ISSUE TITLE
喵大，发现有个别图片不显示，我用 SDWebImage 也试了试不显示，各种浏览器都试了显示，想问下我这个地址有什么问题

### ISSUE THREAD

**Issue by Baleen-Y** [onevcat/Kingfisher#795]
#### What

图片不显示

#### Reproduce

有问题图片地址: http://edianyuan-oss01.oss-cn-shanghai.aliyuncs.com/edy/photoAlbum/201710296/7643831920856cb11fe27f8b0ea01eb6.jpg
可以显示的图片地址: http://edianyuan-oss01.oss-cn-shanghai.aliyuncs.com/edy/topic/201710284/8f485f170e4f1ca2a7bf65f8570ccea0.jpg

实在没看出什么猫腻。。所以打扰了
#### Other Comment

[Add anything else here]

**Comment by onevcat** [comment]
Hey, @Baleen-Y 

This seems to be a WebP format image. Kingfisher does not support WebP by default, so you may need some other third party library or implement your own deserializer for it.

![snip20171023_1](https://user-images.githubusercontent.com/1019875/31880366-3fe9c6e4-b81b-11e7-8f1d-d019ddecd318.png)

See https://github.com/onevcat/Kingfisher/wiki/FAQ#can-i-load-some-special-image-format-like-webp

**Comment by Baleen-Y** [comment]
好的，谢喵大
