### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by actualfan** [onevcat/Kingfisher#809]
I used the following code.

let url = URL(string: urlString)
        imgProfileViw.kf.indicatorType = .activity
        imgProfileViw.kf.setImage(with: url, placeholder: #imageLiteral(resourceName: "tab_user_active"), options: nil, progressBlock: nil) { (img, err, cacheType, url) in
        }

But failed to download. the error.localizedDescription is saying Request time out.
And there's an error.
2017-11-19 12:23:36.878490-0800 [24945:670809] Task <0AD3ADD7-F4E4-464B-9CEF-57E5AC9BFAC8>.<1> finished with error - code: -1001
2017-11-19 12:23:36.879342-0800 [24945:670809] Task <0AD3ADD7-F4E4-464B-9CEF-57E5AC9BFAC8>.<1> HTTP load failed (error code: -999 [1:89])
I hope your help.

**Comment by onevcat** [comment]
As indicated by the error message, it is a request timeout.

Please make sure you have correct Internet connection to your resource. I believe there is little we could do in Kingfisher.

**Comment by actualfan** [comment]
Thank you for your response.
I think there's a problem.
It always fail to download image.
My internet connection is good.
The other apps using SDWebImage works well.

**Comment by onevcat** [comment]
So can I know the URL you are using? We need more information on this before we could get to know what happens.

**Comment by actualfan** [comment]
https://s3-us-west-1.amazonaws.com/cutup-debug/2008/profile/o0t1j5ec.bho.jpeg

**Comment by onevcat** [comment]
Hey, @actualfan 

It works pretty fine for me, at least in the demo app contained in this repo. 

![snip20171121_1](https://user-images.githubusercontent.com/1019875/33049718-b5657072-cea4-11e7-8a9b-ebef712ed491.png)

So I guess there must be some other reason instead of in Kingfisher for it. I strongly suggest you check your network setting and/or proxy setting in both your system and app.

**Comment by antonioallen** [comment]
Interesting 🤔. I'm encountering this issue as well. It loads some images and for others, this issue occurs.

**Comment by vaibhav-varshaaweblabs** [comment]
Same issue with me

**Comment by htjohn** [comment]
I'm encountering the same issue as well. Using Swift 4

**Comment by florencelomojones** [comment]
I am facing the same issue as well. When the image is .jpeg extension it does not work

**Comment by sp0cket** [comment]
same issue with me, using `Kingfisher 4.7.0`

**Comment by sp0cket** [comment]
Interesting,when I comment`imageView.kf.indicatorType = .activity`, it's works well

**Comment by onevcat** [comment]
@sp0cket This issue should not relate to the indicator, but a thread issue which cannot be reproduced easily. Do you have some code to reproduce this problem stably?

**Comment by anwent** [comment]
Same issue with me,Using `Kingfisher 4.7.0`
Image: `http://rdtest.myhiott.com:8081/uploadImage/2018/04-17/img_1523929328770.png`
`Task <AC6932EE-ACA2-41BE-BB38-AFF8B76F9920>.<1> finished with error - code: -1002`

**Comment by GhaisB** [comment]
Same here, error code -999.

The image displays itself when not using KingFisher 

<img width="503" alt="capture d ecran 2018-10-11 a 17 13 26" src="https://user-images.githubusercontent.com/5504674/46814474-11e8b380-cd79-11e8-8e27-ae790e19a53d.png">

**Comment by techmehra** [comment]
> Interesting,When I comment`imageView.kf.indicatorType = .activity`, It's works well

This solved the timeout issue @onevcat could you please look at this. 
Using the latest version of kingfisher

**Comment by techmehra** [comment]
@onevcat You could reproduce it using the tableview and using same url on multiple cell
