### ISSUE TITLE
Image repetition issue with cache image

### ISSUE THREAD

**Issue by RaviSendhav** [onevcat/Kingfisher#811]
I'm getting image repetition issue during download image from server and reload list. 
I'm using this code to download image and save in cache - 

imageViewTest.kf.setImage(with: URL(string: imageURL), placeholder: nil, options: nil, progressBlock: nil) { (image, error, cacheType, imageURL) -> () in }

**Comment by onevcat** [comment]
Please keep our issue template and describe your problem in a clearer way. There could be little we can do unless we know your issue better.
