### ISSUE TITLE
A question about AnimatedImageView

### ISSUE THREAD

**Issue by Glianze** [onevcat/Kingfisher#826]
# A question about AnimatedImageView
hello onecat
Recently in the use of kingfisher，I met a question about using AnimatedImageView in UICollectionViewCell.

```
func makeUI() -> Void {
        ad_image_view = AnimatedImageView()
        self.contentView.addSubview(ad_image_view);
        ad_image_view.snp.makeConstraints { (make) in
            make.top.left.right.equalTo(0)
            make.bottom.equalTo(-SizeScale(10))
        }
    }
    
    func loadAdvertModel(data:[Any]) -> Void {
        let model : ParteamModel = ParteamModel.fetchHomeAdvertModel(sources: data[0])
        ad_image_view.kf.setImage(with: URL(string: BASEIMGURL+model.picUrl!))
    }
```

Click the cell GIF stop playing，Reuse after cell replayed the Gif.
What is the problem.
Can you please tell me the solution
Thanks for you ```

**Comment by onevcat** [comment]
I am not sure what is your problem. Do you mean that the animation will stop when you click the cell? Have you changed the default [`runLoopMode`](https://github.com/onevcat/Kingfisher/blob/master/Sources/AnimatedImageView.swift#L64)?

**Comment by ACEYL** [comment]
I have already solved the problem
