### ISSUE TITLE
Does Kingfisher support content mode of UIImageView?

### ISSUE THREAD

**Issue by yoshinorisano** [onevcat/Kingfisher#828]
Kingfisher seems to ignore the content mode of ```UIImageView```.
For example, if I set the content mode of a UIImageView to aspect **fill** (via storyboard),
however, Kingfisher ignores the content mode and renders the image as aspect **fit**.
Does anybody know this kind of problem?

**Comment by onevcat** [comment]
Hey,

It should not happen since Kingfisher will not change the content mode of an image view. By default, Kingfisher just get the image from either cache or web, then call `imageView.image = image` underhood.

Are you using any image processor to resize or crop the image, which might need you to specify a content mode. And it would be great if you could attach some code snippet you are using or even better to build a sample project in which this issue could be reproduced.

Thanks!

**Comment by yoshinorisano** [comment]
@onevcat 
Thank you for your reply : )
I see your point. This might be my fault...
I'm not using any image processor.
I'll recheck my code.

**Comment by Dmurph24** [comment]
I am having the exact same problem.

**Comment by onevcat** [comment]
Thanks for the report.

Umm, but it's weird. I tried the demo project under this repo and everything seems fine to me. The images are square and the (collection) cell is a tall rectangle. I got these results:

### Aspect Fit
![simulator screen shot - iphone 8 plus - 2017-12-28 at 10 17 07](https://user-images.githubusercontent.com/1019875/34397320-964fb0c2-ebb8-11e7-9d01-b4cf3011126e.png)

### Aspect Fill
![simulator screen shot - iphone 8 plus - 2017-12-28 at 10 16 48](https://user-images.githubusercontent.com/1019875/34397323-a390a304-ebb8-11e7-8c70-6ccf452de74d.png)

### Scale to Fill
![simulator screen shot - iphone 8 plus - 2017-12-28 at 10 17 22](https://user-images.githubusercontent.com/1019875/34397329-ab2f6802-ebb8-11e7-9f4a-6c60a6e66b91.png)

And all of them are expected.

@Dmurph24 Can you confirm that you are calling the image setting method in main thread? Or can you build a sample project in which this issue could be reproduced?

**Comment by Dmurph24** [comment]
@onevcat yes, I will confirm with you soon. Definitely seems to be working in your example.

**Comment by Dmurph24** [comment]
The problem had nothing to do with Kingfisher. Thanks for closing.

Regards,

Danny Murphy
Co-Founder @ SolutionSmart Software
Website | www.solutionsmartsoftware.com
Phone | 513.878.0934
