### ISSUE TITLE
Value of type 'UIImageView' has no member 'kf' 

### ISSUE THREAD

**Issue by SURYAKANTSHARMA** [onevcat/Kingfisher#830]
### Issue Description
after installing kingfisher it give the error "Value of type 'UIImageView' has no member 'kf'" using swift 3.2 in xcode 9 & pod version 3.x
#### What

 Able to access member variable on compile time by auto complete but after building it give this error.
#### Reproduce

![code](https://user-images.githubusercontent.com/6416095/34294143-278058b6-e72d-11e7-87cf-87df58be40c4.png)
![version](https://user-images.githubusercontent.com/6416095/34294145-2a736d92-e72d-11e7-9400-bfe22ee43c85.png)
![pod](https://user-images.githubusercontent.com/6416095/34294148-2bc2508c-e72d-11e7-844d-65233a46a0e9.png)

**Comment by SURYAKANTSHARMA** [comment]
@onevcat  kindly, can you check please ?

**Comment by onevcat** [comment]
@SURYAKANTSHARMA Can you paste your Podfile.lock as well?

nd remember to add `import Kingfisher` before you try to use any API from Kingfisher.

**Comment by SURYAKANTSHARMA** [comment]
import Kingfisher is previously there.
issue get resolved ,It work perfecty fine now, I don't think it is your library issue because it is while i am upgrading xcode and swift version. But it look weired when autocomplete give suggestion while writing the code and get error on building the project.

**Comment by onevcat** [comment]
Maybe it's an Xcode issue. Usually restart Xcode / clean derived data path would fix it.
