### ISSUE TITLE
Cheat Sheet Typo

### ISSUE THREAD

**Issue by elitree** [onevcat/Kingfisher#833]
### Issue Description
There's a small typo in the Cheat Sheet page.
#### What
The word "identidier" is used a few times, in [this section](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#use-processor-with-imagecache) of the Cheat Sheet page. I think this should be "identifier".

#### Reproduce

https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#use-processor-with-imagecache

#### Other Comment

Loving Kingfisher so far! Thanks!

**Comment by onevcat** [comment]
Fixed. Thanks!
