### ISSUE TITLE
cancelDownloadTask() can crash the app when rotate device

### ISSUE THREAD

**Issue by x1911** [onevcat/Kingfisher#835]
like the example in Cheat Sheet, i try to use it like that    

```
func collectionView(_ collectionView: UICollectionView, didEndDisplaying cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: reuseIdentifier, for: indexPath) as! PostCollectionViewCell2
        cell.imageView.kf.cancelDownloadTask()
    }
```

everything works fine, just dont rotate the phone, if rotate, the app crash
in the main viewcontroller is so:

```
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)

        collectionView.collectionViewLayout.invalidateLayout()
        guard  let layout = self.collectionView.collectionViewLayout as? PinterestLayout else{ return }
        layout.attributesCache = [] 
        
    }
```

its the problem with this line: 
```
collectionView.collectionViewLayout.invalidateLayout()
```

maybe the layout not works with the cancel?
i have tried to find answer in issues, but not found it

it happens in my phone, 6p iOS 8, not in simulator
please help....
love your work ^-^ 

HAPPY NEW YEAR!  Onevcat!

**Comment by onevcat** [comment]
Hi, @x1911 
Sorry for the late reply.

It is strange that you were "dequeue" a cell in the `didEndDisplaying` delegate method. Why don't you just use the `cell` comes from invocation directly?

I am not sure whether this is an issue in Kingfisher or not, but it seems likely being caused by a misuse of collection view. Is there any stack information or console log to help understand what happened?

**Comment by x1911** [comment]
sorry with the mistake, its used ` func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell `

and i found the way to solve the problem.

sorry for disturb
