### ISSUE TITLE
图片加载不出来

### ISSUE THREAD

**Issue by XaviorXiao** [onevcat/Kingfisher#838]
proImage.kf.setImage(with: ImageResource(downloadURL:url!), placeholder: UIImage(named:"allSelectedV4"), options: nil, progressBlock: nil, completionHandler: nil)
这句代码展示不出来图片
图片地址
http://yanxuan.nosdn.127.net/455eee1712358dbcb2e33d54ab287808.png?imageView&quality=85&thumbnail=330x330

**Comment by khanhshopback** [comment]
Can you describe more details when posting an issue?

**Comment by x1911** [comment]
i use like this

`   extension UIImageView {      
  
     func ZImgWithProgressAndCallback(_ url : String, completion:@escaping (UIImage?) ->Void) {
        self.contentMode = UIViewContentMode.scaleAspectFill
        self.kf.indicatorType = .activity
        self.kf.setImage(with: URL(string: url),
                         placeholder: nil,
                         options: nil,

            progressBlock: { receivedSize, totalSize in

                let progressView = getPview() 
                let progress = Float(receivedSize) / Float(totalSize)
                if ( progress < 1 ){  
                    progressView.setProgress(progress, animated: true)
                }
                else{
                    progressView.removeFromSuperview()
                }

            },
            completionHandler: { (image, error, cacheType, imageUrl) in

                if let _ = error{

                    AlertInfo("image not exist", dismissTime: 2)
                    completion(nil)
                }
                print("image Size::", image!.size, "  cache type：：", cacheType)
                completion( image )
            } //completionHandler:
        )   //self.kf.setImage
    }  //func ZImgWithCallback 
 }   `


every thing works fine with loading indicator

but 

> GIF file only show once

the gif from cache type "disk" shows, from cache type "memory" show nothing

**Comment by onevcat** [comment]
@XaviorXiao I have no problem to open the url you posted. I noticed that it was a url starting with "http", maybe you forgot to disable the ATS?

@x1911 I am not sure what do you mean. Could you describe the issue more clear? Thanks!

**Comment by x1911** [comment]
@onevcat  thank you for you reply, i found the problem with the lib hero

https://github.com/lkzhao/Hero

after import the Hero lib, the Gif file shows only once,

in the seconde time when i open the viewcontroller, which use hero

the gif file didn't show, only a blanc view

**Comment by Au12th0psav** [comment]
@x1911 I have also encountered this problem, do you have a solution?

**Comment by x1911** [comment]
@Au12th0psav  got an answer from hero,

>  try using .useNoSnapshot on your kingfisher imageView

but it dosent work in my case.

so here is my temporary solution:

```
        let canUseHero = data?.type != "gif"
        self.navigationController.isHeroEnabled = canUseHero
```
dont use hero, when file type is gif.....  it looks so sad....

**Comment by onevcat** [comment]
Seems it is not a Kingfisher issue. So I am closing it.
