### ISSUE TITLE
某些特殊情况下，jpg格式图片存储后会放大十倍的大小

### ISSUE THREAD

**Issue by OctWu** [onevcat/Kingfisher#84]
因为代码中是把下载下来的image通过   UIImagePNGRepresentation(image)转为NSData存储到本地的，某些处理过的PNG会在该方法后，大小会放大十倍，SDWebImage中，在存储图片的时候，会对PNG，JPEG进行判断，是否可以在Kingfisher中加入该判断

**Comment by onevcat** [comment]
谢谢提出。之后将会加入存储为 JPG 的特性。

**Comment by onevcat** [comment]
Fixed in #110
