### ISSUE TITLE
Sometime image display distorter or blur when we do pull to refresh 

### ISSUE THREAD

**Issue by imobdevtech** [onevcat/Kingfisher#840]
There are some wired issue in kingfisher library when i pull to refresh in UICollectionView sometime image will be blur or distorted check the image

![img_0386](https://user-images.githubusercontent.com/159933/34863288-9b80f442-f794-11e7-8c28-b531ca2551c3.PNG)
![img_0387](https://user-images.githubusercontent.com/159933/34863289-9bad9420-f794-11e7-9b6e-835fba2d6011.PNG)

**Comment by onevcat** [comment]
Not sure what happened. Are you using any resizing or crop processor to shrink the downloaded images? Can you paste some related code snippet on how did you use Kingfisher? Or even better, build a sample project in which this could be reproduced?

Thanks!

**Comment by imobdevtech** [comment]
@onevcat  here is the code snippet for this cell

 ```
if objChannel.channelImg.imgURL != nil
        {
            let strUrl = objChannel.channelImg.getImageUrl(withSize: CGSize.init(width: cell.imgPlayVideo.frame.height * 2.0, height: cell.imgPlayVideo.frame.height * 2.0))
            if let url = URL(string: strUrl)
            {
                cell.imgvAdver.kf.setImage(with: url, placeholder: #imageLiteral(resourceName: "icon-catch-feed-placeHolder"), options: nil, progressBlock: nil, completionHandler: { (image, error, cacheType, url) in
                    if image != nil
                    {
                        cell.imgvAdver.image = image
                        cell.imgvAdver.contentMode = .scaleToFill
                    }
                })
            }
        }
```

**Comment by imobdevtech** [comment]
@onevcat  okay got the problem it will be at this line           
` let strUrl = objChannel.channelImg.getImageUrl(withSize: CGSize.init(width: cell.imgPlayVideo.frame.height * 2.0, height: cell.imgPlayVideo.frame.height * 2.0))`
Thanks for supports
