### ISSUE TITLE
Tableview problem loading

### ISSUE THREAD

**Issue by lillogoal** [onevcat/Kingfisher#843]
Hi,
i'm trying to use kingfisher with my tableviewcell but image is loaded a random.

this is my code:
internal func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let gruppo = arr_gruppi[indexPath.row]
        
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell_gruppo") as! GruppiViewCell
        cell.mLabelNome.text = gruppo.getName()
        if(gruppo.getPath() != nil){
            if(!Utility.trimIsEmpty(str: gruppo.getPath()!)){
                let modifier = AnyModifier { request in
                    var r = request
                    r.setValue((AppDelegate.user?.getCutkn()), forHTTPHeaderField: "Segreto")
                    r.setValue((gruppo.getPath()), forHTTPHeaderField: "pic")
                    return r
                }
                
                let resource = ImageResource(downloadURL: URL(string: (BackendMethods.URL_BACKEND+"picture"))!, cacheKey: gruppo.getLastModified())
                
                cell.mImageGruppo.kf.indicatorType = .activity
                cell.mImageGruppo.contentMode = .scaleAspectFill
                cell.mImageGruppo.kf.setImage(with: resource,placeholder: nil,options: [.requestModifier(modifier)])
            }else{
               //   cell.mImageGruppo.kf.setImage(with: nil)
             //   cell.mImageGruppo.image = UIImage(named: "PlaceholderProfile")

            }
        }else{
           // cell.mImageGruppo.kf.setImage(with: nil)
         //   cell.mImageGruppo.image = UIImage(named: "PlaceholderProfile")
        }
      
        
        
        return cell
        // cell?.textLabel?.text = arrayTitles[indexPath.row]
        
    }

**Comment by onevcat** [comment]
Hi,

The cells are reusable so you need to make sure all code path would set the image of the cell. Otherwise, the previous images will be kept.

**Comment by lillogoal** [comment]
Sorry i'm not dire that have understand. How do i have to do? Thanks

**Comment by onevcat** [comment]
If there is a chance that your code falls into any `else` clause, the image setting method will not be called and the previous images in the reused cell will be used. So it would seems that your images are in random order.

**Comment by lillogoal** [comment]
I too tryed to uncomment my else instructions but It didn't work.
Can you suggest me?
Thanks

**Comment by fanguohuiruan** [comment]
@onevcat  can you explain the question from me!

**Comment by lillogoal** [comment]
@fanguohuiruan sorry but this is my question

**Comment by onevcat** [comment]
@lillogoal Not sure what happened. It should work fine and show your `PlaceholderProfile` images if you uncomment the code in `else`s.

I noticed that you are using `gruppo.getLastModified()` as your cache key. Kingfisher is using this `cacheKey` to determine whether an image was already in cache or not. If you have multiple images with the same `gruppo.getLastModified()` value, Kingfisher will just use the cached one instead of downloading it again. Maybe it causes your problem?

I suggest you to check it again. It would be also great if you could create a sample project to reproduce it so I could take another look at it.

**Comment by lillogoal** [comment]
@onevcat hi, the problem isn't gruppo.getLastModified().
Because if i scroll ttableview sometimes It Will load correct Image in the correct position.

My Imageview is a circual Imageview... I used swityavatar maybe this problem ?.
If i uncomment else instruction problem persists

**Comment by lillogoal** [comment]
I understand the bug in library and i solved.

In my REquests i Use always the same url, but i change value in header (getPath and Cutkn).
Kingfisher check the url of queue request and don't execute the same or skip the same.

You haven't to check the URL but the request so too header and other value.

Let me if you understand

**Comment by onevcat** [comment]
@lillogoal 

Hi, I could understand your meaning. However, it is the way how Kingfisher works. The images are basically bound to the download urls, the library depends this fact to coordinate its behavior.

For your case, maybe you could try to modify your url by appending some arguments. This will not change the request destination, at the same time, Kingfisher will recognize them as different urls. Like this:

```
https://domain.com/your_path/asset.jpg?path=abc
```

**Comment by lillogoal** [comment]
Yes i solved when i typed last message.
In my opinion this is a bug.
Whay do you think?

**Comment by onevcat** [comment]
The resource is defined by `downloadURL` of resource. Each resource (or say, asset) should have its own URL, this is also what the URI should do. It's really a rare case to use something like header in a request to serve resources dynamically like that. So there is no plan to change current behavior I am afraid.
