### ISSUE TITLE
使用AnimatedImageView.image,没法展示动画呢,使用 animatedImageView.kf.setImage可播放,但控制不了播放次数和代理回调呢

### ISSUE THREAD

**Issue by jyyjkt** [onevcat/Kingfisher#850]
喵神可能我使用有问题,image?.kf.imageSource?.imageRef总是==nil, fileprivate(set) var imageSource: ImageSource?,也不会让我创建,使用setImage无法控制,主要delegate也不走,我看到有人提了,而且解决了,但是我没懂.

**Comment by jyyjkt** [comment]
let path = Bundle.main.path(forResource: "2", ofType: "gif")
        let image  = Image(contentsOfFile: path!);
        let animatedImageView : AnimatedImageView = AnimatedImageView.init(image: image);
        self.view.addSubview(animatedImageView);
        animatedImageView.frame = CGRect(x: (UIScreen.main.bounds.size.width - 100)/2, y: 400, width: 100, height: 100);
        animatedImageView.backgroundColor = UIColor.blue;
        animatedImageView.delegate = self;
        animatedImageView.autoPlayAnimatedImage = true;
        animatedImageView.framePreloadCount = 10;
        animatedImageView.runLoopMode = RunLoopMode.commonModes;
        animatedImageView.repeatCount = .finite(count: 1);

**Comment by onevcat** [comment]
I am not sure what's your problem or issue. Could you describe your question more clear?

**Comment by jyyjkt** [comment]
我传入一个GIF,kf.setImage时候没法播放,正常写成animatateImageView.image = image,gif不会播放且不调用代理,无法控制GIF播放几次,发现问题出在AnimatedImageView.swift文件中,imageSource = image?.kf.imageSource?.imageRef 的imageRef一直是nil,所以不会走:
animator = Animator(imageSource: imageSource,
                                contentMode: contentMode,
                                size: bounds.size,
                                framePreloadCount: framePreloadCount,
                                repeatCount: repeatCount)
            animator?.delegate = self
            animator?.needsPrescaling = needsPrescaling
            animator?.prepareFramesAsynchronously()
我就无法获取代理实现.
想要尝试加入ImageSource,
但.kf.imageSource是个fileprivate(set) var imageSource: ImageSource? { },只能文件内使用.
我无法自己给这个属性赋值.

**Comment by onevcat** [comment]
Basically you need to decode your GIF images. By using `Image(contentsOfFile: path!)`, your GIF file will be just a plain image with first frame (since UIImage does not support GIF format directly). I suggest you could use `DefaultImageProcessor` and decode the GIF file to a valid animated image, then try to set it to the AnimatedImageView.

```swift
let image = DefaultImageProcessor.default.process(.data(yourGifData), options:[])
```

Now you should have an image source.

**Comment by jyyjkt** [comment]
好的明白了 谢谢喵神
