### ISSUE TITLE
How to display the placeholder image before loading??

### ISSUE THREAD

**Issue by harifsp** [onevcat/Kingfisher#859]
am using the below code,

let url = URL(string: data.imageUrl)!
self.dataImage.kf.setImage(with: url,
placeholder: UIImage(named:"placeholderImg"),
options: [.transition(ImageTransition.fade(1))],
progressBlock: { receivedSize, totalSize in },
completionHandler: { image, error, cacheType, imageURL in})

In here blank white space was displayed at very first time

**Comment by onevcat** [comment]
@harifsp Your code seems to be fine to me. The image with name of "placeholderImg" should be displayed while loading. 

If it shows a blank one, I suggest to check whether you have a valid image under that name. (Make sure ` UIImage(named:"placeholderImg")` is not `nil`).
