### ISSUE TITLE
Kingfisher does not support Arabic string in URL

### ISSUE THREAD

**Issue by mca-shahabuddin** [onevcat/Kingfisher#863]
#### What

Kingfisher Library does not support that URL which contains Arabic name in the URL. Please check URL "/image/cache/catalog/NEE/150ذهبي%20جديدة-500x500.jpg".

I have tried to debug in the library, It will returns resources empty and redirect to the below code.

 `
guard let resource = resource else {
            self.placeholder = placeholder
            setWebURL(nil)
            completionHandler?(nil, nil, .none, nil)
            return .empty
        }
`

How can I prevent this issue?

**Comment by onevcat** [comment]
You need a valid `URL` to set it as the resource of Kingfisher. For `URL(string:)` method, it only accept a string with acsii characters, so you need to encode your url string first, create the valid `URL` instance (make sure it is not `nil`), then send it to Kingfisher.

**Comment by mca-shahabuddin** [comment]
I have resolved it after encoding URL.

Thanks
