### ISSUE TITLE
Remove Cache of before given time limit.

### ISSUE THREAD

**Issue by gurjitdhiman** [onevcat/Kingfisher#870]
### Remove cache of before particular time limit.

I am creating an app where images are shown for 24 hours and I am using Kingfisher to show these images to better load in the table view. There is a script in the backend which is deleting add images published before 24 hours. So I just want to delete the cache added before 24 hours. 

Thanks.

**Comment by onevcat** [comment]
I believe you could just set the `maxCachePeriodInSecond` https://github.com/onevcat/Kingfisher/blob/master/Sources/ImageCache.swift#L104 to a proper duration and then let Kingfisher handle the cache period for you.
