### ISSUE TITLE
How to Apply signed Cookies in kingfisher request.

### ISSUE THREAD

**Issue by shailyglobal83** [onevcat/Kingfisher#877]
hi, How to apply Signed cookies in Kingfisher, I have tried but unable to download image getting "Forbidden" error. That is what I am doing

    let kingfisherManagerSession = KingfisherManager.shared.downloader.sessionConfiguration
    kingfisherManagerSession.httpCookieStorage = HTTPCookieStorage.shared
    KingfisherManager.shared.downloader.sessionConfiguration = kingfisherManagerSession

    self.kf.setImage(with: _url, placeholder: #imageLiteral(resourceName: "placeholder"), options: [.requestModifier(modifier)], progressBlock: { (receivedSize, totalSize) in
        let percentage = (Float(receivedSize) / Float(totalSize)) * 100.0
        self.kf.indicatorType = .activity
        print(percentage)
    }) { (image, error, cacheType, url) in
        print(error?.localizedDescription)
    }
Can you please help me what am I doing wrong?

**Comment by onevcat** [comment]
Kingfisher is using an ephemeral session to download images, so you may need to set your cookie manually. Maybe you can try to modify the request as you need, mentioned [here](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending).
