### ISSUE TITLE
this image can not loaded

### ISSUE THREAD

**Issue by lizizi** [onevcat/Kingfisher#892]
Hi,The image url cannot be loaded.
http://119.27.160.213:8087/ipms/file/1/richtext-file/15228037486282/IMG20“磁爆步兵”180326083020.jpg

**Comment by jzau** [comment]
This is probably because you have included special characters in your URL. Please try to encode your URL before `setImage(with: url)`. It works.

**Comment by onevcat** [comment]
@lizizi 

Yes. As @jzau said, you need to encode your url string before you create a valid `URL`, otherwise, it will be `nil` when you creating URL from string and the image will not be loaded.

**Comment by lizizi** [comment]
ok
