### ISSUE TITLE
Building with Xcode 6.3 using cocoa pods give me a libtool linker error

### ISSUE THREAD

**Issue by jerometonnelier** [onevcat/Kingfisher#9]
I added Kingfisher in my existing project (which uses some objectiveC pods as well) and I get this error : 

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

Any idea?
Thanks.

**Comment by onevcat** [comment]
No idea about it currently. May I know your CocoaPods version and the content of your Podfile? Maybe I can reproduce it in my Mac.

**Comment by jerometonnelier** [comment]
Sure,here it is. Thx.

pod 'Reachability'
pod 'KVNProgress'
pod 'AcknowledgementsBundle'
pod 'JDStatusBarNotification'
pod 'HACLocationManager'
pod 'SWBufferedToast'
pod 'BBBadgeBarButtonItem'
pod 'Onboard'
pod 'IAPHelper'
pod 'NYTPhotoViewer'
pod 'FSDDropdownPicker'
pod 'DMRNotificationView'

**Comment by alexdd55** [comment]
Version is missing ;)

**Comment by onevcat** [comment]
Hi, @jerometonnelier 

It compiled without error for me (except a plist file missing for `AcknowledgementsBundle `).

Would you please update to the latest CocoaPods and try again. I am using version 0.36.3 and it works well.

**Comment by jerometonnelier** [comment]
Hi,
I'm using 0.35 indeed,but I can't upgrade to the latest since a whole team uses cocoa pods :-/
Thanks anyway ;)

**Comment by onevcat** [comment]
Hi, CocoaPods supports Swift framework from 0.36, so you cannot use Kingfisher from CocoaPods if it is 0.35.

**Comment by sealedace** [comment]
CocoaPods supports Swift framework from 0.36. That helps me!
