### ISSUE TITLE
A question about the diskTaskCompletionHandler in tryToRetrieveImageFromCache function of KingfisherManager.swift

### ISSUE THREAD

**Issue by guoyingtao** [onevcat/Kingfisher#911]
I don't get why there is a diskTaskCompletionHandler there.
It seems that it is only a simple wrapper of completionHandler.
Is it equivalent if I just replace diskTaskCompletionHandler with completionHandler?

Thanks for any hint!

**Comment by onevcat** [comment]
Yes, it is now just a wrapper for it. It was used to prevent rewriting some logic other than invoking completionHandler. But that code had already gone now. See [this](https://github.com/onevcat/Kingfisher/pull/578/files#diff-002f8b26539a770bf0cfe68cc82f9a86R181)
