### ISSUE TITLE
加载大图奔溃

### ISSUE THREAD

**Issue by ya-eternity** [onevcat/Kingfisher#912]
加载一个4M左右的图片控制台输出 Message from debugger: Terminated due to memory 直接闪退

**Comment by VermouthC** [comment]
@ya-eternity  kingfisher在处理图片的时候,要加载到内存里,iOS设备内存肯定吃紧,当超过阈值肯定会崩溃
所以大图的处理,上传的时候就要进行质量压缩和宽高的等比缩放

**Comment by Songkunda** [comment]
如果必要高质量的图 可以分阶段读取上传 不过4m加到内存里也就10m左右 应该不会出现这个问题 是不是你一次性加载了过多的图片到内存里了？

**Comment by onevcat** [comment]
From version 5.0 (not released yet now), we use a better memory management strategy with the max limit of memory cache, so memory related issues should be much less now.

And for huge images, you can now use `DownsamplingImageProcessor` first to downsample it before showing (in a list, eg). A demo for using it is also contained in the repo sample app.
