### ISSUE TITLE
Resizing strategy

### ISSUE THREAD

**Issue by RuiAAPeres** [onevcat/Kingfisher#92]
After downloading an image, I would like to cache a resized version of it (thumbnail). Am I right to assume the best approach for this would be to:

1- Not use the `KingfisherManager.swift`
2- Create my own Manager that uses `ImageCache.swift` and `ImageDownloader.swift` and inject this logic in a method ["similar to this"](https://github.com/onevcat/Kingfisher/blob/2cc88a011a82fe8254bd5fac3571961304830e95/Kingfisher/KingfisherManager.swift#L112#L180).

**Comment by onevcat** [comment]
There is no need to do so. You can just use `ImageCache` separately. You could just throw your thumbnail to the default cache (KingfisherManager.sharedManager.cache) by calling [`storeImage:forKey:`](https://github.com/onevcat/Kingfisher/blob/2cc88a011a82fe8254bd5fac3571961304830e95/Kingfisher/ImageCache.swift#L142) with a key different from your original file. Of course, you can create a new cache object to store these thumbnail if you do not want to mess it up with the default cache. It depends on you.

When you need to access these thumbnails, you could use `retrieveImageForKey:options:completionHandler:`. If there is no such cached image there, you will get `nil` and then you know you should download it from web.

**Comment by RuiAAPeres** [comment]
Thanks for the feedback @onevcat
