### ISSUE TITLE
gif 播放的时候不能控制重复次数吗？

### ISSUE THREAD

**Issue by yuchenH** [onevcat/Kingfisher#924]
有重复次数的gif图，使用Kingfisher加载后就成了无限重复的了

**Comment by onevcat** [comment]
I didn't see something like loop count or repeat count in GIF data specification. Not quite sure about it.

But you can set the loop count manually. For `UIImageView`, it is [`animationRepeatCount`](https://developer.apple.com/documentation/uikit/uiimageview/1621070-animationrepeatcount). And for the `AnimatedImageView`, it is `repeatCount`.
