### ISSUE TITLE
Terminated due to memory issue

### ISSUE THREAD

**Issue by yanganggithub** [onevcat/Kingfisher#925]
<img width="396" alt="screen shot 2018-05-25 at 5 01 50 pm" src="https://user-images.githubusercontent.com/13554921/40536058-8110546a-603d-11e8-881d-2e540abb741f.png">
use imgOne.kf.setImage(with: URL.init(string:itemOne.image_url)) in the UICollectionViewCell

when the cell disappear ,use code like this 
 func collectionView(_ collectionView: UICollectionView, didEndDisplaying cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
 cell.imgOne.kf.cancelDownloadTask()
}
is there something wrong with use it ,why load some 10kb's Image data ，always receive a memory warning,when I receive memory warning I use the code :   
 let cache = KingfisherManager.shared.cache
        cache.clearMemoryCache()
but the application still crash with terminated due to memory issue after  receiving memory warnings multiple times. How big the kingfisher bears image data size,my image size is like this picture

**Comment by onevcat** [comment]
I don't think loading this image would ever cause a memory issue. This 1024*768 image at RGB would take 18MB~ memory, it should be far away from receiving a memory warning. 

So maybe you need to profile your app in a more detail way with Instrument to find what's taking your memory.

**Comment by onevcat** [comment]
Version 5 (not released yet now) will ship a better memory management with upper limitation. The memory related problem should be solved at a higher level. If you are trying to load huge images, I suggest to use `DownsamplingImageProcessor` to downsample the image before show it. Some demo for handling huge images are also contained.
