### ISSUE TITLE
加载图片 url 相同 后台可能会一段时间内只替换图片不跟换URL 

### ISSUE THREAD

**Issue by sinorychan** [onevcat/Kingfisher#930]
请问下如何根据 设置header 来检图片 Last-Modified信息  做更新

**Comment by zengyuanchen** [comment]
imageView.kf.setImage(with: url, placeholder: nil, options: [.fromMemoryCacheOrRefresh], progressBlock: nil, completionHandler: nil)

**Comment by wudijimao** [comment]
You had better let your server not do this!!!    You at lest get the header from server to know if it been updated!!  It will be a big waste!!

**Comment by onevcat** [comment]
Kingfisher uses URL string as the cache key. So a better approach is adding a suffix or query to your image URL, say like "https://domain.com/image.png?time=12345".
