### ISSUE TITLE
时间戳图片地址的缓存问题

### ISSUE THREAD

**Issue by LvJianfeng** [onevcat/Kingfisher#933]
你好，喵神。
我们应用图片返回地址是这样
```swift
http://******/448add18-0e68-4a2b-8b94-d673ad440afa.jpg?Key=TlfVIS&Expires=1528206436
```

请教下，图片地址上有时间戳，我如何去控制图片缓存呢？因为图片数量较多呢。

**Comment by onevcat** [comment]
How do you want to "control" the cache? Kingfisher provides a max duration for a cached image and it will purge that image if it is not accessed for a while. However, there is no such control in a per image duration to determine its lifetime in the cache.

**Comment by LvJianfeng** [comment]
我想控制cachekey，昨晚看了下，我想我找到方法了```ImageCache```，来设置key为url的某个固定的部分，retrieveImage去取回。
