### ISSUE TITLE
collectionview嵌套collectionview ，使用kingfinisher加载webp滚到下屏回来会暂停，使用YYImage加载没问题

### ISSUE THREAD

**Issue by Juefeiye** [onevcat/Kingfisher#934]
您好喵神，collectionview嵌套collectionview，使用kingfinisher加载webp滚到下屏回来会暂停，使用YYImage加载没问题

**Comment by onevcat** [comment]
看描述是 runloop mode 的问题，可以试着改改？
另外 Kingfisher 内置并没有 webp 支持，所以可能最好问一下用的具体是哪个 processor。

**Comment by onevcat** [comment]
@Juefeiye 

Try to change this: https://github.com/onevcat/Kingfisher/blob/master/Sources/AnimatedImageView.swift#L107-L119 on the `AnimatedImageView`, if you are using it to show the animation.
