### ISSUE TITLE
Receiving negative numbers in downloading progress block

### ISSUE THREAD

**Issue by Shagans982** [onevcat/Kingfisher#935]
I seem to be getting negative numbers sent to me as progress during the download of an image on the first fetch. Every subsequent one seems to show correctly. Any idea why this is? I looked around but can't seem to locate anything in this regard. 

  ImageDownloader.default.downloadImage(with: URL(string: self.imageUrlToView!)!, retrieveImageTask: nil, options: nil, progressBlock: {
            receivedSize, totalSize in
            let percentage = (Float(receivedSize) / Float(totalSize)) * 100.0
            print("downloading progress: \(percentage)%")
            self.updateProgressBar(progress: percentage)
     ...

Console - print("downloading progress: \(percentage)%")
downloading progress: -1330700.0%

downloading progress: -1605700.0%

downloading progress: -2922600.0%

downloading progress: -3067400.0%

downloading progress: -3936200.0%

**Comment by onevcat** [comment]
It might be an internal problem in URLSession, which gives you the "totalSize" as `-1` to indicate it is not available (unknown) for the request, so maybe you need to ignore that case. :(

**Comment by onevcat** [comment]
From version 5.0, the progress block will not be called anymore when the "totalSize" as -1 (the server does not returning the expected size info in response header).
