### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by daodaidao** [onevcat/Kingfisher#936]
大神们我在使用的时候发现 如果我的图片链接  http://image.cnpp.cn/upload/images/20160905/09380421552_400x300.jpg  后面有一个空格的话，就加载不出来了，能否加个容错性

**Comment by onevcat** [comment]
This is the `URL` struct to recognize your string with trailing space to `nil`. Then `nil` URL is sent to Kingfisher which makes it unloadable. You could just add your own extension on `URL` to trim your URL string before creating a URL, and it should not be an issue in Kingfisher (and we can do little for it I guess).
