### ISSUE TITLE
图片无法加载

### ISSUE THREAD

**Issue by CxDtreeg** [onevcat/Kingfisher#946]
https://mmbiz.qpic.cn/mmbiz_jpg/zHhwFqhGzAgBEmHqE0WJ0F7wfqjBtYBNYz3jld5s2nD0NIE9b6sGwGjGs5qotD2ZkB1Xozyy6EePRZXxnYx5rA/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1

在加载如上URL的图片的时候不能进行加载

**Comment by onevcat** [comment]
It's a webp file and not natively supported in Kingfisher and iOS. Read this: https://github.com/onevcat/Kingfisher/wiki/FAQ#can-i-load-some-special-image-format-like-webp
