### ISSUE TITLE
Show Placeholder image as same image Thumbnail(/blurred) until actual image downloaded

### ISSUE THREAD

**Issue by KarthikaReddy** [onevcat/Kingfisher#953]
I have below code for showing full screen image once User selects it.

fullImage.kf.setImage(with: url)

During the time the actual image downloads, I wanted to show a place holder as the same image but thumbnail size stretched out(same thumbnail with blurred or so). This thumbnail was cached by Kingfisher library while showing thumbnails previously.

When I show the image with out KF library, by using regular iOS UIImage downloader it shows a blurred preview of thumbnail stretched until it downloads actual image - then it shows actual image. How can this be achieved with KF library?

**Comment by nooralam6** [comment]
I am having the same issue, please let us know a way for this.

**Comment by KarthikaReddy** [comment]
You have to do it manually - I have changed my logic to below.
First fetch the thumbnail by querying Kingfisher and then set this thumbnail image as a placeholder image while the library actually fetches for full size image.
ImageCache.default.retrieveImage(forKey: **thumbnailURL**, options: nil) { image, _ in
self. fullImage.kf.setImage(with: url, placeholder: **image**, options: [.requestModifier(header)],
            self.showImage(url, image, header, ID)
}

**Comment by nooralam6** [comment]
i hve done it this way, 
```
let cacheImage = ImageCache.default.retrieveImageInMemoryCache(forKey: "cache")

let resource = ImageResource(downloadURL: imageURL, cacheKey: "cache")

imageView.kf.setImage(with: resource, placeholder: cacheImage, options: [.forceRefresh, .cacheOriginalImage], progressBlock: nil, completionHandler: nil)
```

and whenever the image is being updated I store the image with:

`ImageCache.default.store(image, forKey: "cache")`
