### ISSUE TITLE
ImageCache.default.maxMemoryCost issue

### ISSUE THREAD

**Issue by alexanderkhitev** [onevcat/Kingfisher#955]
Hello! I have a question, I did `maxMemoryCost == 100`, but the limit is exceeded more than 4 times (454 megabytes). Is this the correct behavior? Thanks.

```
        let maxMemoryCostMegabytes: UInt = 100
        ImageCache.default.maxMemoryCost = maxMemoryCostMegabytes * 1024 * 1024
```
![cashe](https://user-images.githubusercontent.com/12511909/42155620-effa4a46-7df9-11e8-96b9-d8edad90eeaf.png)

**Comment by onevcat** [comment]
Memory cache does not mean the memory usage your images may take. It is the cached images in memory for loading again quickly, instead of the memory used for displaying or referred by your own variables.
