### ISSUE TITLE
在setImage之前，没有主动调用cancel

### ISSUE THREAD

**Issue by Beyond-Chao** [onevcat/Kingfisher#958]
SDWebImage 里面在sd_internalSetImageWithURL之前会先
 [self sd_cancelImageLoadOperationWithKey:validOperationKey]; 取消之前的加载任务，一般为**SDWebImageDownloaderOperation**。**Kingfisher** 的**Demo**里面在**tableView**的这个代理方法中调用了**cancel**，

`
override func collectionView(_ collectionView: UICollectionView, didEndDisplaying cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {        
        // This will cancel all unfinished downloading task when the cell disappearing.
        (cell as! CollectionViewCell).cellImageView.kf.cancelDownloadTask()
        print("cell didEndDisplaying: \(indexPath.row)")
    }
`
如果开发者在用使用**tableView** 加载图片的时候，忘了写**cancel**，会不会出现加载错乱的现象？

**Comment by lxzzzzzz** [comment]
看看文档。。。 [cancel-a-downloading-or-retriving-task]((https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#cancel-a-downloading-or-retriving-task))

**Comment by Beyond-Chao** [comment]
// In table view delegate
func tableView(_ tableView: UITableView, didEndDisplaying cell: UITableViewCell, forRowAt indexPath: IndexPath) {
	//...
	cell.imageView.kf.cancelDownloadTask()
}

还是需要手动去调用cancel 当 cell endDisplaying 的时候。我意思是说能不能直接写在setImage里面，像SD一样。

**Comment by onevcat** [comment]
The downloading will continue (with the consideration that you might need that image anyway later). However, the image setting will check current (the latest set) URL so it will only show the latest one you need.

**Comment by tzongw** [comment]
1. let url = URL.init(string: "https://test.com/remote_image")
    imageView.kf.setImage(with: url)
2. imageView.kf.cancelDownloadTask()
    imageView.image = UIImage.init(named: "local_image")

I have a similar situation，sample code is like above(in reality, code 1 and 2 may be called in different time).
When `remote_image` is `never cached` before or `remote_image` is in `memory cache`, I got `local_image` in the end; but when `remote_image` is in `disk cache`(can happen in app relaunch),` remote_image` is finally showing.
Any suggestions to avoid this?

**Comment by onevcat** [comment]
@tzongw The `cancelDownloadTask`, as its name indicates, only works for downloading tasks. If the image is from disk cache, it is not the scope which that method can handle. Kingfisher load image disk asynchronously by default for non-blocking UI, which causes your issue. The easiest way might be add `.loadDiskFileSynchronously` to the setting option so all the operation would happens in the same runloop.
