### ISSUE TITLE
How to clear image cache?

### ISSUE THREAD

**Issue by PulkitAppz** [onevcat/Kingfisher#960]
I am using Kingfisher library to set image from url but on scrolling my table I am getting memory leakage error issue. I want to clear my image cache so that I can overcome this issue of memory leakage. How can I clear cache to load more images.

**Comment by onevcat** [comment]
Basically Kingfisher will clean its memory cache automatically when receiving a memory warning, however, you could still trigger it manually. Please read this: https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#clear-cache-manually
