### ISSUE TITLE
swift 4.1 can't  pod install successful.

### ISSUE THREAD

**Issue by Mornin5** [onevcat/Kingfisher#964]
swift 4.1 can't  pod install successful.
dur  s.swift_version = "4.0"
would you update Kingfisher.podspec:28

![_472d4e4f-64f4-4c2c-a955-c628e831aeb0](https://user-images.githubusercontent.com/13310462/43308117-045cc71c-91b3-11e8-85da-bdb1435eb1e4.png)

**Comment by onevcat** [comment]
This kind of Swift version support wasn't added until CocoaPods 1.1.0. So I guess you could solve it by just upgrading you CocoaPods version.
