### ISSUE TITLE
Getting image with ImageCache from disk is 3x bigger

### ISSUE THREAD

**Issue by balanegrero** [onevcat/Kingfisher#969]
I store the image using:
            ImageCache.default.store(image, forKey: "key")
when I close the app and I enter again, I get the image using:
             ImageCache.default.retrieveImage(forKey: "key", options: nil)

but the image is 3x bigger, it doesn't happens when the image is coming from memory.

**Comment by onevcat** [comment]
Hi,

If your image scale does not match your screen scale, it might happen. You may need to specify the image scale yourself if you are trying to load it from disk manually, like this:

```swift
// For your case, it seems you are trying to load a 3x image.
ImageCache.default.retrieveImage(forKey: "key", options: [.scaleFactor(3.0)])
```

**Comment by vijaysharm** [comment]
I know this ticket is pretty old, but in case someone else has this issue, I ran into this issue because the UIImage i was storing had a `.scale` equal to 3.0. For me, that value was exactly equal to the main screen's scale size. I use the solution that @onevcat suggested by modified such that

```
ImageCache.default.retrieveImage(forKey: "key", options: [.scaleFactor(UIScreen.main.scale)])
```
