### ISSUE TITLE
Passing in a NSURLSession

### ISSUE THREAD

**Issue by RuiAAPeres** [onevcat/Kingfisher#97]
I would be great if the `ImageDownloader` would have a constructor that would receive a `NSURLSession` as a parameter. This way we could make use of something like [DVR](https://github.com/venmo/DVR) for stub images downloads. :+1:

**Comment by dmcrodrigues** [comment]
Yeah that flexibility would be great for testing but also to provide a customised `NSURLSessionConfiguration`, e.g. request timeout interval, maximum connections per host, shared container identifier. :+1:

**Comment by onevcat** [comment]
Yeah, that's cool. I will add it later.

**Comment by RuiAAPeres** [comment]
Awesome @onevcat ✨

**Comment by RafaelPlantard** [comment]
Nowadays, is it possible? Stub of images?

**Comment by onevcat** [comment]
Please check [this](http://onevcat.github.io/Kingfisher/Classes/ImageDownloader.html#/s:10Kingfisher15ImageDownloaderC20sessionConfigurationSo012NSURLSessionE0Cvp).

And according to your use case, you may also want to use a customized `ImageProcessor` or an `ImageDataProvider` to do similar things. But it depends on your needs to find the best approach.

**Comment by RafaelPlantard** [comment]
Thanks, I want just use this stub for my instrumented tests with KIF, I want all my tests have no limitation such need to be internet connection (for downloading an image, for example).

**Comment by onevcat** [comment]
So I guess you can just use the `LocalFileImageDataProvider`.

```swift
var testing = true
let source: Source
let remoteImageURL: URL

func getLocalURL(remote: URL) -> URL {
    return remoteToDiskMap[remote]
}

if testing {
    let localImageURL = getLocalURL(remote: remoteImageURL)
    source = .provider(LocalFileImageDataProvider(fileURL: localImageURL))
} else {
    source = .network(remoteImageURL)
}
imageView.kf.setImage(with: source)
```

**Comment by RafaelPlantard** [comment]
Thank you @onevcat I will try
