### ISSUE TITLE
ImageDownloader.swift line 504 Crash

### ISSUE THREAD

**Issue by CivelXu** [onevcat/Kingfisher#974]
Fatal Exception: NSMallocException*** -[NSConcreteMutableData appendBytes:length:]: unable to allocate memory for length (343619) Raw Text
--
0 | CoreFoundation | __exceptionPreprocess
9 | Foundation | -[NSConcreteMutableData appendData:]
10 | Kingfisher | ImageDownloader.swift line 504specialized ImageDownloaderSessionHandler.urlSession(URLSession, dataTask : URLSessionDataTask, didReceive : Data) -> ()
11 | Kingfisher | ImageDownloader.swift line 0@objc ImageDownloaderSessionHandler.urlSession(URLSession, dataTask : URLSessionDataTask, didReceive : Data) -> ()
12 | CFNetwork | __67-[NSURLSession delegate_dataTask:didReceiveData:completionHandler:]_block_invoke220
23 | UIKit | UIApplicationMain
24 | Primas | AppDelegate.swift line 14main
25 | (Missing) | (Missing)

**Comment by laus102** [comment]
bump

**Comment by onevcat** [comment]
As mentioned in #1001 . This issue should be already resolved in Kingfisher version 5. I quote the comment here:

> Kingfisher v4 (and any of an earlier version) is using an aggressive strategy to cache images in memory. It relies on the system memory warning notification to free up cache in memory. However, it seems that recently the system sometimes fails to fire this notification to the app.
> 
> This behavior is changed in Kingfisher version 5. Now we are using a better approach to cache images. At most, a maximum 25% of your memory will be used for caching images in memory. Version 5 will be released in a few days (currently it is in beta and I am writing migration guide and document for it). If you'd like to try it now, just use the [beta versions like this](https://github.com/onevcat/Kingfisher/releases/tag/5.0.0-beta.3).
> 
> If this issue bothers you a lot, and you have no chance to upgrade to version 5, you can set the [`maxMemoryCost`](https://github.com/onevcat/Kingfisher/blob/8b91f9e225cca6dd043aa8cd5bc564ca5842bedb/Sources/ImageCache.swift#L85) to a reasonable value:
> 
> ```swift
> // It means disabling memory cache.
> KingfisherManager.default.cache.maxMemoryCost = 1
> ```
