### ISSUE TITLE
Filter 里的tint: (Color) -> Filter 有个小错误

### ISSUE THREAD

**Issue by zgjff** [onevcat/Kingfisher#977]
let filter = CIFilter(name: "CISourceOverCompositing")!
这里的filter应该用CIMultiplyCompositing滤镜来改变image的tintColor

**Comment by onevcat** [comment]
There isn't a definite definition of what is a tint for. And it's not possible for Kingfisher to provide all the filters. So if that one is not for you, you could easily create your own by conforming the `CIImageProcessor`.
