### ISSUE TITLE
High res images “Terminated due to memory issue”

### ISSUE THREAD

**Issue by akashpopat** [onevcat/Kingfisher#979]
So my app only displays images in a CollectionView and it crashes because of memory issues. This is the memory graph 

![](https://i.stack.imgur.com/9Gmfx.png)

This is the sample project you can check. [https://github.com/akashpopat/ImageTest](url)

I've tried this same project with Kingfisher Library and AlamofireImage Library and it crashes on both.

**Comment by linqingmo** [comment]
try this
```swift
KingfisherManager.shared.cache.maxMemoryCost = 30 * 1024
```
Kingfisher's memory cache is unlimited by default, it should be a limited size 30mb or other.

**Comment by onevcat** [comment]
Duplicated to #1001 

This issue should be resolved from Kingfisher version 5.

Particularly for the high-resolution images, we also have a `DownsamplingImageProcessor` now to downsample the original image to smaller one before loading it in memory. It is useful if you want to show a bunch of high-res images in a list. A demoscene to show the best practice (with caching the original high-res images to disk, to prevent downloading it again) is also contained in the demo app for Kingfisher version 5. Check it when you want to upgrade!

I also paste my comment in #1001 below for reference.

> Kingfisher v4 (and any of an earlier version) is using an aggressive strategy to cache images in memory. It relies on the system memory warning notification to free up cache in memory. However, it seems that recently the system sometimes fails to fire this notification to the app.
> 
> This behavior is changed in Kingfisher version 5. Now we are using a better approach to cache images. At most, a maximum 25% of your memory will be used for caching images in memory. Version 5 will be released in a few days (currently it is in beta and I am writing migration guide and document for it). If you'd like to try it now, just use the [beta versions like this](https://github.com/onevcat/Kingfisher/releases/tag/5.0.0-beta.3).
> 
> If this issue bothers you a lot, and you have no chance to upgrade to version 5, you can set the [`maxMemoryCost`](https://github.com/onevcat/Kingfisher/blob/8b91f9e225cca6dd043aa8cd5bc564ca5842bedb/Sources/ImageCache.swift#L85) to a reasonable value:
> 
> ```swift
> // It means disabling memory cache.
> KingfisherManager.default.cache.maxMemoryCost = 1
> ```
