### ISSUE TITLE
forSecurityApplicationGroupIdentifier kingfisher

### ISSUE THREAD

**Issue by codebendr-product-designer** [onevcat/Kingfisher#981]
Am building a sticker app where images are cached in the main app and can also be accessed in the keyboard and iMessage extension. 

I want to be able to access those images from kingfisher cache using grouped app feature. 

Is this possible?

**Comment by ludriv** [comment]
I have the same question but with Share extension.

**Comment by ludriv** [comment]
You can do it your own by using the same container url in the main app and extensions.
```
let containerURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "foo.bar.shared")!

KingfisherManager.shared.cache = ImageCache(name: "shared", path: containerURL.path)
```

**Comment by onevcat** [comment]
👍
