### ISSUE TITLE
maxCachePeriodInSecond not working

### ISSUE THREAD

**Issue by c0dehunter** [onevcat/Kingfisher#988]
#### What

KF does not honor maxCachePeriodInSecond when setting cache. Expected result is that KF downloads image from URL when maxCachePeriodInSecond expires. Instead, it always loads image from cache. 

#### Reproduce

This happens always with any URL. Here is our code:

```
case fiveMinutes = 5

...

iconImageView.kf.setImage(with: urlValue, options: [.transition(.fade(0.25))], cachePeriod: .fiveMinutes )

...

extension Kingfisher where Base: ImageView {
    func setImage(with resource: Resource?, options: KingfisherOptionsInfo? = nil, cachePeriod: KingfisherImageCachePeriodType?, completionHandler: CompletionHandler? = nil) {
        var newOptions: KingfisherOptionsInfo? = options
        if let cacheType = cachePeriod {
            let cache = ImageCache(name: cacheType.getChacheName)
            cache.maxCachePeriodInSecond = 60 * cacheType.rawValue
            if newOptions != nil {
                newOptions!.append(.targetCache(cache))
            } else {
                newOptions = [.targetCache(cache)]
            }
        }
        self.setImage(with: resource, options: newOptions, completionHandler: completionHandler)
    }
}
```

**Comment by onevcat** [comment]
`maxCachePeriodInSecond` is a "suggestion" of longest cache duration. It is not an aggressive way to control and clean the cache when any access happens. Basically, Kingfisher will check and clear the expired cached images when user tap Home button to send your app to background. If you need such an aggressive cleaning behavior, you may need to call [`cleanExpiredDiskCache(completion:)`](http://onevcat.github.io/Kingfisher/Classes/ImageCache.html#/s:10Kingfisher10ImageCacheC016cleanExpiredDiskC0yyycSg10completion_tF) every time you try to access the images yourself, and do image retrieving in the completion handler.

**Comment by c0dehunter** [comment]
Thank you for this guideline. It seems we were mis interpreting this value and will fix our code accordingly.
