### ISSUE TITLE
[!] Failed to load 'Kingfisher' podspec:  [!] Invalid `Kingfisher.podspec` file: undefined method `swift_version=' for #<Pod::Specification name="Kingfisher">.

### ISSUE THREAD

**Issue by shadyk** [onevcat/Kingfisher#994]
When will Kingfisher support 4.1 ?

**Comment by shadyk** [comment]
I forked Kingfisher 4.8.1. 
Changed something in Xcode 9.4.1 (swift 4.1)
then i tried to to install the pod from my github 
 pod 'Kingfisher', :git => 'https://github.com/shadyk/Kingfisher.git', :branch => "master".
it is giving the following errors: 

Pre-downloading: `Kingfisher` from `https://github.com/shadyk/Kingfisher.git`, branch `master`
[!] Failed to load 'Kingfisher' podspec: 
[!] Invalid `Kingfisher.podspec` file: undefined method `swift_version=' for #<Pod::Specification name="Kingfisher">.

 #  from /var/folders/44/vdkn4f6951n4bjnhf71dcp5c0000gn/T/d20180903-13628-1aen4yy/Kingfisher.podspec:28
 #  -------------------------------------------
 #  
 >    s.swift_version = "4.1"
 #  
 #  -

Is it something from my side? or Kingfisher?

**Comment by onevcat** [comment]
You may need to upgrade your CocoaPods to the latest version.
