### ISSUE TITLE
同一URL下，服务器更换图片，移动端清理缓存甚至卸载应用后重新安装后仍无法正确刷新图片，已确认非服务端问题

### ISSUE THREAD

**Issue by DreamParagon** [onevcat/Kingfisher#995]
如题，我尝试卸载应用(包括重启机器)，重新下载安装或xcode运行后，图片仍然是之前的旧图片；我只有用一台新设备，才能看到这个URL下的正确图片，请问这个该怎样解决？谢谢(除了设备恢复出厂设置没有尝试过之外，其他我能想到方法都试了，目前看上去缓存貌似以某种方式跟设备绑定在一起，无法通过卸载，重启，重新安装等常规方式清除URL的旧数据，安卓端和网页均可以正确显示，所以应该不是服务器缓存的问题)

**Comment by onevcat** [comment]
iOS cache folder is used for caching images. So uninstall the app will not purge it. Try calling cache clear method explicitly if you want to remove them:

```swift
ImageCache.default.clearMemoryCache()
ImageCache.default.cache.clearDiskCache() //This is an async operation and you may want it finishes before you reload.
```

See [the wiki](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#clear-cache-manually) for more.

**Comment by DreamParagon** [comment]
谢谢喵大，问题已解决~只是还有一个问题不解，卸载了应用，对应的沙盒跟着被清除，那么沙盒内cache文件夹下的kingfisher文件夹下的缓存图像怎么还存在呢？

**Comment by DreamParagon** [comment]
刚刚发现模拟器是好了，但是真机上还是不行ImageCache.default.clearMemoryCache()
ImageCache.default.cache.clearDiskCache()，这些加上后还是没法改变旧图片

**Comment by DreamParagon** [comment]
另外，我修改maxCachePeriodInSecond = 60，过了5分钟，我重新运行xcode启动我的app，发现也并没有重新刷新图片。。。用了几台真机设备，均是此问题，模拟器运行，ImageCache.default.clearMemoryCache()
ImageCache.default.cache.clearDiskCache()
这俩行代码可以保证重新启动后，缓存是被清掉了的，能够看到新图片

**Comment by onevcat** [comment]
`maxCachePeriodInSecond` is a "suggestion" for clear cache when your app SWITCHED to the background. It is not an aggressive way to clear your cache. See https://github.com/onevcat/Kingfisher/issues/988

For the cache not being cleared in real device, we didn't receive any report on it before. And now I am not sure what happens. I'll check it later to see if I could reproduce it.

**Comment by DreamParagon** [comment]
<img width="642" alt="2018-09-05 11 49 24" src="https://user-images.githubusercontent.com/5466178/45070016-f21ef980-b101-11e8-8ba9-014dddedd126.png">
实际上，如图，在我清除掉缓存后，我看到kingfisher的缓存文件夹内已经空了。。。所以我很困惑，不知道旧的图片是哪里来的，感谢喵大重开这个issue~

**Comment by onevcat** [comment]
Could you try to print the cache type in the setting image completion handler to see where is it from. Like this:

```swift
imageView.kf.setImage(with: url, completionHandler: { 
    (image, error, cacheType, imageUrl) in
    print(cacheType)
})
```

**Comment by DreamParagon** [comment]
<img width="1148" alt="2018-09-05 12 05 54" src="https://user-images.githubusercontent.com/5466178/45070514-272c4b80-b104-11e8-957d-5cd87d4f9e88.png">
你好，喵大，这是我在清除缓存后未经任何与app交互，直接杀掉程序再进来之后的断点截图。
<img width="1139" alt="2018-09-05 12 08 07" src="https://user-images.githubusercontent.com/5466178/45070590-8a1de280-b104-11e8-948c-0980b86619d8.png">
这是我在上次测试后留下来的缓存未被清除，杀掉程序后再进来的断点截图

**Comment by DreamParagon** [comment]
另外，在App运行中，我也看到type打印出来的是memory，这些打印看上去都是正确的

**Comment by onevcat** [comment]
So it seems fine and everything is correct to me...Do you have any cache policy header in the response? Or did you changed the image downloader session of Kingfisher?

Maybe it would help to use a proxy to check the response to see what does your server return to you.

**Comment by DreamParagon** [comment]
感谢喵大的耐心，我先去问问服务端
