### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Z-JaDe** [onevcat/Kingfisher#997]
刚大概拜读了作者的代码，就是我想要的那种感觉。
很Swift，相比之下SD太陈旧了。不过还是有一些粗浅的见识想说下：
项目里面下载前下载后可以添加很多处理，比如图片处理，动画，加载进度显示，缓存，回调线程，占位图，可以说是很完美了。
但是我看使用方法的时候这些额外的处理都是用Option的方式来传的，从这个层面来说，我没有感受到加kf属性的好处，要是能搞成Rx那种感觉链式处理。
self.imageView.kf.filter(cor:5).placeholder(R.image.icon()).setImage(url)

**Comment by Z-JaDe** [comment]
这种写法感觉很爽，也很舒服

**Comment by Z-JaDe** [comment]
现在options是枚举的方式来写的，如果按照rx那种思想写的话，假设我集成项目后有什么其他的扩展，只要项目中添加一个生产者，遵循下载状态的协议，然后就能和现有的Kingfisher完美兼容

**Comment by onevcat** [comment]
`kf` is mainly for avoiding namespace conflicting. Kingfisher itself is an aged project, which could be retroacted to Swift 1. So some APIs are not so Swifty in current days.

I have a plan to rewrite most code in Swift 5, but it might not happen until 2019.

So I will keep your suggestion in mind to see what we could do to make it better!

Thanks.
